### ISSUE TITLE
Re-introduce middle-click to open in new space

### ISSUE THREAD

**Issue by ryanzabcik** [micheleg/dash-to-dock#100]
Gnome 3.12 removed this feature, I think. It was very useful. I would like it so that when an application is middle-clicked on the dock, it spawns the new application window in a new workspace.

**Comment by burashka** [comment]
Sorry. I updated from 3.10 to 3.14 and click middle button doesn't work. Ctrl+Clk open new app window on current workspace and I don't see setting in extension settings. Should I change any settings (extension/Gnome?) or open in new workspace doesn't work?

**Comment by micheleg** [comment]
It's not an extension settings, that's part of the default behaviour since 3.12. Can you confirm the behaviour is the same disabling the extension? Also, have you tried using the above mentioned extension?

**Comment by burashka** [comment]
Without extension - analogue behaviour: open in current workspace. Problem in GNOME(

**Comment by micheleg** [comment]
Yes, that's the default behaviour now (https://git.gnome.org/browse/gnome-shell/commit/?id=620e3cef20710ef29996bbe13f0f66a09fa97c6f). As you see it's not difficult to reimplement the previous behaviour, it's only a few lines difference. When I'll work on #148, this will be definitely considered.

**Comment by burashka** [comment]
Thanks!
