### ISSUE TITLE
[Feature Request] Show shortcut numbers on left nav icons

### ISSUE THREAD

**Issue by Bernmeister** [micheleg/dash-to-dock#1000]
In Unity if I hold down the SUPER key, the left nav places numbers above each icon and so it reminds me what to press as a shortcut.

In GNOME Shell, the numbers appear after you select a shortcut. I found that SUPER Q will show the numbers, but was hoping that you could put in the numbers immediately upon holding down the SUPER key and then I can just hit the number key for the shortcut I want.

**Comment by hackel** [comment]
Dupe of #469, #684.  Next time search first.
