### ISSUE TITLE
Dash to dock not working after recent update

### ISSUE THREAD

**Issue by Burday** [micheleg/dash-to-dock#1001]
Hey. I recently upgraded to GNOME 3.34.0 and the extension now displays an error and, obviously, doesn't work. I'm on arch (btw) if that should matter, i assume its more of a gnome issue.

**Comment by iguntur** [comment]
Hi @Burday, did you try [installation from source](https://github.com/micheleg/dash-to-dock#installation-from-source)?

If reloading shell `Alt + F2` -> `r [Enter]` not working, just restart your machine.

It works for me on GNOME version 3.34.0 on Arch.

**Comment by Burday** [comment]
Hey, I attempted installing from source and the issue still remained. After general messing around with gnome and the extension it is seemingly fixed. I tried reproducing it but failed. I'd assume it was a local problem.
