### ISSUE TITLE
Dash no longer hidden by xscreensaver screen locking

### ISSUE THREAD

**Issue by inthreedee** [micheleg/dash-to-dock#1002]
### Current behavior
Since the Gnome 3.34 update, dash-to-dock is showing up on the screen when it's locked by xscreensaver.  The dock appears overlayed on top of the blanked screen/running screensaver.

### Expected behavior
Prior to this update, the dock was hidden along with the rest of the screen whenever xscreensaver locks the screen.

### Version info
OS: Arch

Dash-to-dock: ~~Installed via the aur package, which is basing off of this commit for gnome 3.34 compatibilty: https://github.com/micheleg/dash-to-dock/commit/908a05022a1ce2565d56af4c762fe95c5fb6b39c~~
v67 release installed via extensions.gnome.org

xscreensaver: Version 5.43

### Other
Nothing else appears to have broken in this way after the Gnome 3.34 update.
Some info on how xscreensaver works:
https://www.jwz.org/xscreensaver/man1.html
> When it is time to activate the screensaver, a full-screen black window is created on each screen of the display. Each window is created in such a way that, to any subsequently-created programs, it will appear to be a "virtual root" window. Because of this, any program which draws on the root window (and which understands virtual roots) can be used as a screensaver.

**Comment by AlexWayfer** [comment]
The same.

The photo (sorry, I don't know how to make a screenshot at lock screen):

![image](https://user-images.githubusercontent.com/6510020/66393065-40c05680-e9da-11e9-8b04-77466857943e.png)

**Comment by inthreedee** [comment]
Some additional info that might be relevant is provided in the xscreensaver faq:

> Programs sometimes pop up dialog boxes over the screen saver while my display is locked, and I wish they didn't.
https://www.jwz.org/xscreensaver/faq.html#popup-windows

**Comment by micheleg** [comment]
I'm not sure xscreensaver is in any way supported in Gnome nowdays. The extension is disabled when the gnome lock screen is triggered, but I suspect the it is completely unaware of what the xscreensaver window. Indeed I'm surprised it were working before.

**Comment by inthreedee** [comment]
@micheleg I appreciate your response.  For clarification, it seems you're implying that you've done nothing on your end to cause this behavior and that something has changed in the way Gnome itself displays extensions?  If that's the case, I will report it upstream to the xscreensaver dev.

For completeness, I want to point out that xscreensaver does continue to work fine in Gnome.  I'm aware that Gnome itself moved away from xscreensaver a long time ago, but this extension is the only thing that shows on a locked screen when it shouldn't.  On stock Gnome without dash-to-dock, everything continues to be properly hidden behind xscreensaver.

(I know @AlexWayfer's screenshot shows the top bar in addition to the dock, but that doesn't look like a normal xscreensaver lock screen to me so I think something else is going on there.)

**Comment by inthreedee** [comment]
I reported the issue to the xscreensaver developer and here's the insights he had:

> The only way this is possible is if this dock window is an override-redirect window which is forcing itself to the top of the stacking list. There is nothing that xscreensaver can do to detect or prevent that. The bug report you mentioned points to https://www.jwz.org/xscreensaver/faq.html#popup-windows which is right. It must be that the way this dock program is managing its windows is at fault here.

In reference to https://github.com/micheleg/dash-to-dock/pull/975/commits/8a17d436cd6715ddc4b577e2af69b1322444cbba, he also had this to say:

> However it's noteworthy that the "dock" seems to think of itself as a "pop up menu" because those tend to approach things with the attitude of "I am only temporary so I must be atop everything else always", which is clearly not the case with a dock.

**Comment by micheleg** [comment]
Yes, I position the dock on top of all other windows because... well, it needs to be placed there in respect to all windows:
 
https://github.com/micheleg/dash-to-dock/blob/4fd2776643c505859f28907e3f6fa75776ee19b4/docking.js#L1086

In particular with a scren grab we heve:

https://github.com/micheleg/dash-to-dock/blob/4fd2776643c505859f28907e3f6fa75776ee19b4/docking.js#L1107

The latter could be not necessary any more. I can also confirm that there is not problem in gnome 3.30, so there must have been some change upstream, potentially this:https://gitlab.gnome.org/GNOME/gnome-shell/commit/2bd80579eddba9804871ce6c8de742bdf9b1d800

**Comment by micheleg** [comment]
Have a look at this branch: https://github.com/micheleg/dash-to-dock/tree/fix/xscreensaver and let me know if it fix your problem as well as if it break something else (concerns are about dragging items in the docks in particular).

**Comment by inthreedee** [comment]
@micheleg Yes, that branch does fix the problem!  I can drag application icons to reposition them, the right click menu works, and autohide seems to work fine.  I will use it for a few days and report back if I notice anything acting strange.

Thank you very much for taking the time to look into this.  I appreciate it!

**Comment by AlexWayfer** [comment]
> I know @AlexWayfer's screenshot shows the top bar in addition to the dock

This is usual top bar for lock screen as I remember. You can see the lock icon on the right.

**Comment by inthreedee** [comment]
So far so good; no unusual behavior on my end the past few days.

**Comment by AlexWayfer** [comment]
1. I don't know why the `invalid` label is here.
2. Also I count this issue as security (not a large, but a small).
3. Also looks like this overlaying breaks password input sometimes (just can't set focus to the field, but visible Dash-to-Dock works).

**Comment by raginggoblin** [comment]
> The same.
> 
> The photo (sorry, I don't know how to make a screenshot at lock screen):
> 
> ![image](https://user-images.githubusercontent.com/6510020/66393065-40c05680-e9da-11e9-8b04-77466857943e.png)

How did you manage that nice login box, I have been looking for a decent looking XScreensaver dialog for ages (And I am not the only one according to Google...)

**Comment by AlexWayfer** [comment]
> How did you manage that nice login box, I have been looking for a decent looking XScreensaver dialog for ages (And I am not the only one according to Google...)

Sorry, I don't remember. I'm currently using GDM (and, probably, `gnome-screensaver`), so this is not an issue for me now.
