### ISSUE TITLE
Unable to remove mounted drives

### ISSUE THREAD

**Issue by elgs** [micheleg/dash-to-dock#1005]
After the most recent upgrade, some mounted drives are shown in the panel, and there is no way to remove them. They are annoying. I want to keep my panel absolutely simple. I wonder if there is any way to turn off this feature. Thanks.

**Comment by dvorapa** [comment]
Of course, in the dash-to-dock prefferences

**Comment by elgs** [comment]
Oh, thank. But I was not able to find it. I'm using Arch Linux.

**Comment by dvorapa** [comment]
Either visit this page: https://extensions.gnome.org/local/ or install gnome-tweaks and find it in the "Extensions" tab

**Comment by elgs** [comment]
Thanks you! That worked!
