### ISSUE TITLE
Activities overview doesn't shrink some windows adequately and they are partially off screen

### ISSUE THREAD

**Issue by memeplex** [micheleg/dash-to-dock#1007]
In gnome 3.34 / ubuntu 19.10 beta (both yaru + ubuntu-desktop and adwaita + gnome-session) the following problem arises when vertically expanding dash-to-dock to fit the screen: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1834967

**Comment by jessedubord** [comment]
I'm also experiencing this in the default Ubuntu 19.10 fresh install. It also seems to be elongating the bottom border of the Workspace Switcher on the right side (see attached screenshot):

![Screenshot from 2019-12-09 20-23-45](https://user-images.githubusercontent.com/11955519/70494944-02bade00-1ac2-11ea-8fcb-8b6df0164ef2.png)
