### ISSUE TITLE
Currently focused app is poorly highlighted on 100 % opacity

### ISSUE THREAD

**Issue by dvorapa** [micheleg/dash-to-dock#1008]
On 100 % opacity, currently focused app is not highlighted enough to be recognized, see:
![Snímek z 2019-10-08 13-25-17](https://user-images.githubusercontent.com/5113916/66392060-1ae18480-e9cf-11e9-845c-7b38b31bf4fb.png)

**Comment by dvorapa** [comment]
The same with the default Adwaita theme

**Comment by dvorapa** [comment]
The same with the default Adwaita theme:
![Snímek z 2019-10-08 13-27-46](https://user-images.githubusercontent.com/5113916/66392219-7ad82b00-e9cf-11e9-9cf5-ef34f4cd10b2.png)

**Comment by micheleg** [comment]
Not really a use case I intend to support directly. I think this should bedone at the theme level. The opacity tweaking historicall mainly exists as way to tweak the transparency in the opposite direction.
