### ISSUE TITLE
top right and bottom right corners only are always rounded

### ISSUE THREAD

**Issue by luca-viggiani** [micheleg/dash-to-dock#1010]
Regardless the dock position chosen, top right and bottom right corners only are always rounded.
This is ok when the dock position is set to left. It is not for all other positions.
This is happening on GS 3.34 on Arch and Dash to Dock v67.
See attachment
![dash-to-dock](https://user-images.githubusercontent.com/25035914/66407529-a702a480-e9ed-11e9-8eeb-7a820908c664.png)

**Comment by micheleg** [comment]
This seems to have been introduced in 5075934a5788e27cede7a67fbf568680775ec642.
