### ISSUE TITLE
Disabling "Show mounted volumes and devices" hides all icons on second monitor

### ISSUE THREAD

**Issue by darkdragon-001** [micheleg/dash-to-dock#1025]
Disabling _Show mounted volumes and devices_ hides all icons on second monitor. Dash to Dock version 67 on Ubuntu 19.10.

**Comment by ramesh45345** [comment]
I can confirm this as well. When "Show mounted volumes and devices" is enabled, the 2nd monitor's dock icons show, and when disabled, they disappear, showing only the "Show Applications" icon. Primary monitor's icons are unchanged and show correctly.

Using Fedora 31, Gnome Shell 3.34.1, Dash to Dock v67. Enabled "Show on all monitors" option in Dash to Dock.

**Comment by valerauko** [comment]
https://github.com/micheleg/dash-to-dock/blob/4fd2776643c505859f28907e3f6fa75776ee19b4/locations.js#L141

`this._monitor.run_dispose()` for some reason erases the other app icons from the dock on that monitor as well. commenting that out made only the drives disappear, but i suspect that's not ideal

**Comment by siegfriedhuber** [comment]
Same here. v67 on Ubuntu 19.10 Eoan Ermine Gnome 3.34.1

**Comment by valerauko** [comment]
Rebooting (or just reloading the shell) after changing the setting makes the dash work as expected though.

**Comment by darkdragon-001** [comment]
> https://github.com/micheleg/dash-to-dock/blob/4fd2776643c505859f28907e3f6fa75776ee19b4/locations.js#L141
> 
> `this._monitor.run_dispose()` for some reason erases the other app icons from the dock on that monitor as well. commenting that out made only the drives disappear, but i suspect that's not ideal

Every screen/display/monitor aka display has its own instance of `Locations.Removables`/`DashToDock_Removables`. They both run `this._monitor = Gio.VolumeMonitor.get();` in
https://github.com/micheleg/dash-to-dock/blob/4fd2776643c505859f28907e3f6fa75776ee19b4/locations.js#L104
Therefore the object for each display references the _same_ `GVolumeMonitor`. When the first display runs `this._monitor.run_dispose()`, it destroys this object. When the second display run this code again, it fails since `null.run_dispose()` doesn't work.

**Comment by TheAifam5** [comment]
Same thing on ArchLinux but much weird is, that the dash is there if you have following options:
- [x] Show Applications icon
- [ ] Show mounted volumes and devices

**Comment by darkdragon-001** [comment]
Reading [Common Question 1.4](https://developer.gnome.org/gtk3/stable/gtk-question-index.html) in combination with the [Documentation for `GVolumeMonitor.get()`](https://developer.gnome.org/gio/stable/GVolumeMonitor.html#g-volume-monitor-get) told me how to handle GTK `GObject`s correctly. Surprised that nobody spotted this...
