### ISSUE TITLE
Turning off "use keyboard shortcuts to activate apps"

### ISSUE THREAD

**Issue by xircon** [micheleg/dash-to-dock#1036]
Doesn't work, I have defined super+num to switch workspaces,  but it always launches an app from dash to dock.
Manjaro Unstable, gnome 3.34

**Comment by marcinn** [comment]
They're conflicting with default and hidden shortcuts provided by Gnome.
To disable default shourtcuts you must redefine them via gsettings or dconf.
Handy loop in terminal looks like:
```
for i in {1..9}; do gsettings set "org.gnome.shell.keybindings" "switch-to-application-$i" "[]"; done
```
That's a Gnome's huge UX mistake.

**Comment by xircon** [comment]
Thanks, works and completely agree.
