### ISSUE TITLE
"Show Applications" popover is not hidden when it should be

### ISSUE THREAD

**Issue by xordspar0** [micheleg/dash-to-dock#1038]
If you hover over any icon in the dock, a popover message appears that explains what the button is. For most of these icons, if you right click, the popover disappears and is replaced by a menu. This is not the case for the Show Applications button. The menu is simply drawn on top of the popover.

![popover](https://user-images.githubusercontent.com/2390950/67907703-d9b04080-fb46-11e9-9473-cb485d0e59c2.gif)

I'm running Gnome Shell 3.32 with dash-to-dock 66.

**Comment by acerspyro** [comment]
This appears to no longer be an issue on Gnome 3.34 with dash-to-dock 67.

**Comment by micheleg** [comment]
Yes, this is bothering me every time I open that menu... but I have always been to lazy to try to fix it. As @acerspyro points out, it is indeed already solved in master. 

Here (https://github.com/micheleg/dash-to-dock/tree/fix/showappstooltip-3.32) is an attempt of a quick fix for 3.32.

**Comment by xordspar0** [comment]
That does the trick! Thanks.
