### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by mone27** [micheleg/dash-to-dock#1041]
There is an extra space after the backslash, that makes impossible to copy and paste the command a terminal. The issue is in https://micheleg.github.io/dash-to-dock/download.html under Installation under manual Installation.
Where can I make a PR for the website?

**Comment by micheleg** [comment]
Thanks. The website is here, in the gh-pages branch https://github.com/micheleg/dash-to-dock/tree/gh-pages.You can open a PR against that.

**Comment by libreajans** [comment]
+ There is also an extra space before the git clone command.

` git clone https://github.com/micheleg/dash-to-dock.git`

Would you like to fix both of them?
