### ISSUE TITLE
"Show applications" shows the app grid in place before the animation starts

### ISSUE THREAD

**Issue by axelmeunier** [micheleg/dash-to-dock#1043]
When exiting the application overview (by hot corner of super key) without any action in the overview, the next time I click on "show application", the app grid is shown in place before the spring animation starts again. Not really easy to explain, here is a screen recording of the issue:
https://raw.githubusercontent.com/axelmeunier/personal/master/Capture%20d%E2%80%99%C3%A9cran%20vid%C3%A9o%20de%2003-11-2019%2022%3A59%3A52.webm
It happens only when the dock is at the bottom or on top, not when on the left or right side.
I am not sure it is a dash-to-dock bug though.
FWIW it's on Ubuntu 19.10 with a vanilla gnome session and dash-to-dock v67 installed.

EDIT : link

**Comment by Valleriite** [comment]
I am experiencing the same result,here is what I noticed:
when I open the activities menu and click the "Show Applications" button the animation works correctly,
but when I click "Show Applications" from dash to dock the issue is present.
I am on gnome 3.38.2

**Comment by Valleriite** [comment]
I guess this issue and https://github.com/micheleg/dash-to-dock/issues/1359 are the same but https://github.com/micheleg/dash-to-dock/issues/1359 got more replies,
so maybe this should be closed even thought it was posted before the other.

**Comment by axelmeunier** [comment]
Ok I am going to close it then.
