### ISSUE TITLE
No "show-mount" option on dash-to-dock v67 on Pop_OS

### ISSUE THREAD

**Issue by Aisyk** [micheleg/dash-to-dock#1057]
I want to try this : http://ubuntuhandbook.org/index.php/2019/11/hide-mounted-drives-left-dock-ubuntu-19-10/

But i don't have the option on my configuration...
https://ibb.co/QQYXs26

**Comment by 3v1n0** [comment]
You must use the configuration for the dock (can open right-clicking the show-apps button or from gnome-extensions tool)
