### ISSUE TITLE
Add a feature to show full-length top panel when dock expanded

### ISSUE THREAD

**Issue by LouisDK1** [micheleg/dash-to-dock#106]
This is how my desktop look when the dock is expanded. The top panel does not have full length which bugs me.

![skrmbillede fra 2014-06-09 02 43 57](https://cloud.githubusercontent.com/assets/4969294/3212719/a5eeed34-ef6f-11e3-8f84-28ac0be69f7e.png)

If you could add a feature to get the dock expanded while the top panel has full length it would be very nice.

![skrmbillede fra 2014-06-09 02 45 20](https://cloud.githubusercontent.com/assets/4969294/3212722/c9cdfec0-ef6f-11e3-8214-6391dbecd5b6.png)

**Comment by micheleg** [comment]
The behaviour is now the one you were suggesting (02b0f67aeddcd5337f3482815dbc2083ad73e8eb). I decided to stick with one rather than having two options and this is easier to maintain.
