### ISSUE TITLE
Dock doesn't hide in fullscreen mode 

### ISSUE THREAD

**Issue by dvivanov00** [micheleg/dash-to-dock#1062]
I'm running Pop_OS with gnome-shell v.3.34.1. While having intelligent auto-hide on with the dodge windows option set to only maximized windows, it keeps the dock while playing YouTube videos fullscreen but the actual browser window is windowed. This but also occurs when the browser is in fullscreen mode (F11) or viewing an image/video on Telegram.
![image](https://user-images.githubusercontent.com/58141819/69496841-2802f600-0edf-11ea-903a-f84c3dc72e82.png)
![image](https://user-images.githubusercontent.com/58141819/69496865-7617f980-0edf-11ea-9916-97569f845d7c.png)
![image](https://user-images.githubusercontent.com/58141819/69499066-0e6da880-0ef7-11ea-8546-1626f3b67573.png)

**Comment by biji** [comment]
Same issue here, in fedora 35 wayland

Probably there should be new option, Dodge windows: 

- [ ]  Only maximized windows and fullscreen windows

**Comment by biji** [comment]
sorry, there's actually new option in master branch 

![image](https://user-images.githubusercontent.com/665559/156693983-33e45e87-453c-44a7-8260-b808a1fb47cf.png)

should be closed

**Comment by vanvugt** [comment]
Indeed it sounds like that setting. The second option is the default. If you still have problems after changing that setting then please open a new issue.
