### ISSUE TITLE
Media Icon of Partition Mounted Automatically at Boot won't Disapear After Umount

### ISSUE THREAD

**Issue by thiggy01** [micheleg/dash-to-dock#1074]
I have an external hard drive that has two partitions that ubuntu 19.10 automatically mounts after boot and their icon appear on dash-to-dock side bar as it should.

After I right click to umount the first partition, its icon disappears normally. However, when I click to umount the second partition, the partition gets umounted, but the icon stays there.

Two Icons | Umount Last Media Icon | Persisting Icon
------------ | ------------- | -------------
![Screenshot from 2020-01-02 22-20-27](https://user-images.githubusercontent.com/20028082/71702913-cb81d900-2db0-11ea-8108-f48fb5146868.png) | ![Screenshot from 2020-01-02 22-29-25](https://user-images.githubusercontent.com/20028082/71702962-0421b280-2db1-11ea-909d-9fa31ab0c7de.png) | ![Screenshot from 2020-01-02 22-22-38](https://user-images.githubusercontent.com/20028082/71702994-2b787f80-2db1-11ea-9696-de9b504a322e.png)

When I plug my external HDD after Ubuntu has booted, the partition umounts and their icons are removed normally. This bug happens when my HDD drive is already plugged in during the boot process.

**Comment by philipl** [comment]
So, the logic here is that if we know _where_ the partition will be mounted, we'll keep showing an icon and let you mount from the icon. If we don't know where the partition will be mounted, the icon will disappear when unmounted.

In your scenario, my guess would be that if he device is plugged in at boot time, the mount point is calculated and remembered in a different way than when you plug it in after boot.

(This assumes that if you right click on the icon after un-mount, it offers a working Mount action).

**Comment by thiggy01** [comment]
Thanks for answering. That seems to be the case here.
