### ISSUE TITLE
Right click option: 'run on dedicated graphic card' doesn't do what expected

### ISSUE THREAD

**Issue by spiderdab** [micheleg/dash-to-dock#1102]
Hi, I'm running latest PopOs on a dell with dual graphic card, and I've recently seen that clicking with the right mouse button on a app in the dock you can  'run on dedicated graphic card', which I understand it make it run on the Nvidia, instead of the Intel.
I'm running in Hybrid mode, and I can run apps on the Nvidia using the '__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia APPNAME' method.
is the dock 'run on dedicated graphic card' meant to do the same?

thanks, Davide.

**Comment by spiderdab** [comment]
Hi, I've Just Installed Pop!_OS 20.04 and just tried to run an app on the dedicated graphic card, clicking on the right click-context menu. If done in the gnome app drawer it works, but if it is done in the app inside dash to dock it doesn't work, simply it does anything.
Any suggestion?

thanks, dab.

**Comment by jw-maynard** [comment]
This is the error in the logs:

`May  4 17:02:28 by1903a54302643 gnome-shell[1616]: JS ERROR: Error: Expected type enum for Argument 'discrete_gpu' but got type 'boolean'#012_rebuildMenu/<@/home/jmaynard/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:828:42#012activate@resource:///org/gnome/shell/ui/popupMenu.js:191:14#012vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14`

**Comment by roboknight5** [comment]
I have the same issue as well with the same error as @jw-maynard

**Comment by roboknight5** [comment]
i think i found a fix in appIcons.js line 828 ` this._source.app.launch(0, -1, true);` change true to 1 ` this._source.app.launch(0, -1, 1);` i am not sure if this a proper fix but it worked for me

**Comment by mentos1386** [comment]
@roboknight5 willing to make a PR? I'm also encountering this issue.
