### ISSUE TITLE
Badge Counts / Progress Bars? Are they still working?

### ISSUE THREAD

**Issue by Jonchun** [micheleg/dash-to-dock#1110]
I've found several articles like https://www.omgubuntu.co.uk/2017/09/ubuntu-dock-now-supports-progress-bars-badge-counts from a long time ago telling me that ubuntu-dock now supports badge icons. However, I can't for the life of me figure out what ubuntu-dock is and what dash-to-dock is and why this repository contains both.

I am currently on a fresh install of Ubuntu 19.10 and have tried many combinations of downloads from the releases page and from the https://extensions.gnome.org/extension/307/dash-to-dock/ page and was unable to get badge counts working the way it showed in the first article.

gnome-shell-extension-ubuntu-dock is already the newest version (67ubuntu19.10.1).

Searching the repo gives me issue #872 and PR #1054 which makes me think these badge counts are supposed to be available, but I'm not seeing them

Here's an example of what my dock looks like: I've included several apps such as Mailspring/Telegram/Discord that I would expect SOME sort of badge for.
![image](https://user-images.githubusercontent.com/5800539/76162988-ce82a800-6118-11ea-88fc-66a5c9d21cb0.png)

Here is the top-right tray, where I do seem to be getting badges:
![image](https://user-images.githubusercontent.com/5800539/76163006-f245ee00-6118-11ea-9336-18171e329e6c.png)

Did I accidentally install something that might disable the badges, or am I just completely missing something here?

**Comment by LuFlo** [comment]
You should get the notification badges on Telegram when the window is actually open (in your Screenshot it's not). Since my PR is not merged to master yet it is unlikely that you accidentally installed the version where badges are disabled.
Also progress bars should appear as soon as you zip something in nautilus. I realized though that discord doesn't have notification badges anymore (or maybe it is a setting inside discord). Be aware that applications may not support this feature.
Also try to uninstall the ubuntu-dock just to be sure there is no interference.

**Comment by Jonchun** [comment]
Thank you for responding @LuFlo .

I realized that only after my screenshot was uploaded. However, I am sure that it does not work whether it is open or not. Here is a new screenshot where you can see Telegram is open, but no badge counter in the dock (only in the top right tray):

![image](https://user-images.githubusercontent.com/5800539/76169302-30f59b80-614d-11ea-97c2-427cba0c459a.png)

**Comment by LuFlo** [comment]
Can you show a screenshot of the appearance tab? Also can you show us the content of "~/.local/share/gnome-shell/extensions" and "/usr/share/gnome-shell/extensions"?

**Comment by Jonchun** [comment]
```
jchun@jonathan-aspire5:~$ ls -lah ~/.local/share/gnome-shell/extensions
total 12K
drwxr-xr-x 3 jchun jchun 4.0K Mar  8 10:12 .
drwx------ 3 jchun jchun 4.0K Mar  8 15:05 ..
drwxr-xr-x 5 jchun jchun 4.0K Mar  8 10:12 dash-to-dock@micxgx.gmail.com
jchun@jonathan-aspire5:~$ ls -lah /usr/share/gnome-shell/extensions
total 68K
drwxr-xr-x 17 root root 4.0K Mar  8 10:07 .
drwxr-xr-x  6 root root 4.0K Mar  8 10:02 ..
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 apps-menu@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 auto-move-windows@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Oct 17 08:27 desktop-icons@csoriano
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 drive-menu@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 horizontal-workspaces@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 launch-new-instance@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 native-window-placement@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 places-menu@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  3 root root 4.0K Oct 17 08:27 ubuntu-appindicators@ubuntu.com
drwxr-xr-x  3 root root 4.0K Oct 17 08:27 ubuntu-dock@ubuntu.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 user-theme@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 window-list@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 windowsNavigator@gnome-shell-extensions.gcampax.github.com
drwxr-xr-x  2 root root 4.0K Mar  8 10:07 workspace-indicator@gnome-shell-extensions.gcampax.github.com
```
![image](https://user-images.githubusercontent.com/5800539/76171868-50e58900-6166-11ea-9d70-42d2eddf77a1.png)

**Comment by LuFlo** [comment]
Can you remove the "ubuntu-dock@ubuntu.com" folder (and backup it ;) ), restart the shell and see if the problem still exists? I remember I had some issues because it was installed and I think you can't remove it via the extension homepage.

**Comment by Jonchun** [comment]
No dice. Just tested Telegram again. 

![image](https://user-images.githubusercontent.com/5800539/76172642-5a72ef00-616e-11ea-942b-0411866316c2.png)

I restarted shell with ```
killall -3 gnome-shell
``` so hopefully that wasn't wrong.

**Comment by LuFlo** [comment]
I usually restart the shell with ALT-F2, type "r" and hit enter, but killing it should do the same... Also you might have to reopen the Apps after a shell restart in order to see the badges but I assume you already tried this^^

**Comment by Jonchun** [comment]
I just did a full restart just to be 100% sure and same thing. (Opened the apps again and everything). I'm still not 100% sure Telegram even supports it, so I tried compressing something from the file manager to see if I get a progress bar like you mentioned should happen, and I don't get one of those either.

I was able to reproduce this consistently 4 times. 2 times on 2 different computers. Once on 18.04 which I tried first, then read stuff about how I needed to update gnome-shell for the latest ubuntu-dock, so I moved to 19.10. Both computers do not have the badge count notifications working.

**Comment by LuFlo** [comment]
ok that is interesting, I will try with a fresh install in a VM. Telegram supports this, you may have to go to Settings -> Notifications -> Badge Counter (in Telegram) but it should have the right settings by default.

**Comment by Jonchun** [comment]
Just checked my Telegram settings. Badge counter was enabled. (I suspect proof of that is the counter working in the tray). However, there was a checkmark called "native notifications" that was unchecked. I tried checking it and restarting telegram/gnome but same result

**Comment by Jonchun** [comment]
I've changed absolutely nothing (intentionally) and it suddenly started working on one of my computers. I'll do some more digging/test on my other computer to see what it was.

![image](https://user-images.githubusercontent.com/5800539/77147653-21872400-6a64-11ea-99fe-f2f717ee81bb.png)

Currently I suspect some library auto-updated and fixed it. It is now working with discord as well.

**Comment by Jonchun** [comment]
I have no clue what's going on. It is extremely inconsistent. I've tried multiple reboots/apt-get upgrades and both of my computers should be on the latest version of everything.

They both have the same dash-to-dock version as well. 

However, on one computer:
![image](https://user-images.githubusercontent.com/5800539/77168962-185f7c80-6a8f-11ea-8b47-e8d87655b8c6.png)

On the other:
![image](https://user-images.githubusercontent.com/5800539/77168996-290ff280-6a8f-11ea-930a-ec010e5024be.png)

Both screenshots were taken at the same time. For some reason, Telegram started working on both but Discord only works on one. I read somewhere that I should try
```apt-get install libindictor7 libindicator3-7```
but that didn't seem to do anything either.

**Comment by Jiia** [comment]
I think this should be re-opened. There's an [AskUbuntu thread](https://askubuntu.com/questions/1041232/no-badge-notification-in-ubuntu-18-04) without any replies about this same issue.

I have a freshly installed Ubuntu 18.04. The badges didn't work with ubuntu-dock so I removed it and installed dash-to-dock instead. Same issue.

This doesn't seem to have anything to do with Snap store because native apps such as Firefox and Thunderbird fail to show badges and progress bars too.

**Comment by Jonchun** [comment]
> because native apps such as Firefox and Thunderbird fail to show badges and progress bars too.

Don't make the same mistake I did and assume a specific app will work. That was the big problem I ran into when troubleshooting. Check against an app that 100% works on a different OS/dock. For example, try to see if Telegram notifications (which I have proven with screenshots) works in 18.04 work. If you can get even one application working, chances are the Unity Launcher API portion of the dock is working fine and the apps that are NOT working are the problem.

I did a lot of testing with the dbus API as well before finally concluding that a bunch of apps that supposedly have this working don't actually have it fully working, and it definitely depends on whether you installed from .deb/apt or flatpak/snap store because your .desktop file needs to be named correctly as well.

If you're handy with Python at all, you can also try running this code to try forcing a badge count onto an arbitrary .desktop file:

**Comment by Jiia** [comment]
> If you're handy with Python at all, you can also try running this code to try forcing a badge count onto an arbitrary .desktop file: https://wiki.ubuntu.com/Unity/LauncherAPI#Python_Example

Thank you, it indeed does appear that the dock and the API seem to work fine as the badge notification and progress bar worked with the script you linked.

It appears there's an open bug about this for [Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1482674). Such a shame but thanks for letting me know so I don't have to keep banging my head against the wall any longer.
