### ISSUE TITLE
vfunc_get_preferred_width JS ERROR: InternalError: too much recursion

### ISSUE THREAD

**Issue by gnloch** [micheleg/dash-to-dock#1117]
I am getting this message while using the version from branch `tmp/gnome-3.36`, commit `253fb3e45e838af2f3886abf5143886957aa34c9`.
OS: Archlinux

Using Xserver
```
JS ERROR: InternalError: too much recursion
vfunc_get_preferred_width@/home/gloch/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:128:47
```
Using Wayland
```
JS ERROR: InternalError: too much recursion
vfunc_get_preferred_height@/home/gloch/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:140:49
```

**Comment by hrdwrrsk** [comment]
Not sure but this issue seems crash my shell when clicking "Show Applications" :\

Using dash-to-panel again, temporarily until it's fixed :\

**Comment by gnloch** [comment]
I've been using this last commit for the last 4 hours and it seems that the issue was fixed. Closing it.
Thanks @3v1n0 for solving it.
