### ISSUE TITLE
Dock is not centered when aligned to bottom

### ISSUE THREAD

**Issue by SparK-Cruz** [micheleg/dash-to-dock#1120]
![image](https://user-images.githubusercontent.com/1179000/76478845-b34dbc00-63e8-11ea-8b48-e34fe47394f1.png)

**Comment by PizzaLovingNerd** [comment]
I having the same issue. I'm running Dash to Dock from git on Arch with GNOME 3.36.

![image](https://user-images.githubusercontent.com/13041099/76548003-559e8b80-644b-11ea-8316-3d8355c8b8eb.png)

**Comment by dvorapa** [comment]
Perhaps a duplicate of #1113 ?

**Comment by nboughton** [comment]
Same issue here, also on Arch with 3.36
![Screenshot from 2020-03-12 23-12-11](https://user-images.githubusercontent.com/8879583/76575430-fece9b80-64b6-11ea-988c-0289b19e705d.png)

**Comment by SparK-Cruz** [comment]
> Perhaps a duplicate of #1113 ?

Yes, despite the other issue's title being not what users will search for...

**Comment by dvorapa** [comment]
> > Perhaps a duplicate of #1113 ?
> 
> Yes, despite the other issue's title being not what users will search for...

I did 🤷‍♂️ the other issue's title is quite good to me

**Comment by Alexander-Huang** [comment]
Yeah,I have the same issue.And the dock is not centered at the left and right either.But it looks less strange at the left so I put it there.
Also Arch ,Gnome3.36.0

**Comment by KingCartman** [comment]
I have the same Issue.
I am using GNOME 3.36.0 on Manjaro Linux (unstable branch)

**Comment by lucenera** [comment]
I have the same problem about centering. Arch and Gnome 3.36. I have use the repository tmp/gnome-3.36. The problem is on all position (top/bottom/left/right).
![Schermata del 2020-03-15 20-06-26](https://user-images.githubusercontent.com/35407790/76708613-7b9c8800-66f8-11ea-81b6-c5db035daf65.png)

**Comment by Alexander-Huang** [comment]
> I have the same problem about centering. Arch and Gnome 3.36. I have use the repository tmp/gnome-3.36. The problem is on all position (top/bottom/left/right).
> ![Schermata del 2020-03-15 20-06-26](https://user-images.githubusercontent.com/35407790/76708613-7b9c8800-66f8-11ea-81b6-c5db035daf65.png)

Use gnome-3-36 branch and everything turns fine >_<

**Comment by lucenera** [comment]
> > I have the same problem about centering. Arch and Gnome 3.36. I have use the repository tmp/gnome-3.36. The problem is on all position (top/bottom/left/right).
> > ![Schermata del 2020-03-15 20-06-26](https://user-images.githubusercontent.com/35407790/76708613-7b9c8800-66f8-11ea-81b6-c5db035daf65.png)
> 
> Use gnome-3-36 branch and everything turns fine >_<
> ![2020-03-16 09-07-23 的屏幕截图](https://user-images.githubusercontent.com/42209822/76715039-79244780-6765-11ea-9b66-e1758c2f4e1b.png)

Thanks, now it's perfect!

**Comment by lucenera** [comment]
@Alexander-Huang thanks, now it's perfect!

**Comment by SparK-Cruz** [comment]
I've updated through AUR and it's fine now, thank you!
