### ISSUE TITLE
Scrolling behaviours don't work

### ISSUE THREAD

**Issue by dawkot** [micheleg/dash-to-dock#1122]
Switching between windows/workspaces by scrolling doesn't work anymore.

Dash-to-dock 67, Gnome-shell 3.34.4, Manjaro stable.

**Comment by IIIProphetIII** [comment]
for me, switching between windows is ok,but switching between workspaces does not seem to work.
Here is log.
`gnome-shell[11158]: JS ERROR: TypeError: Utils.DisplayWrapper is undefined                                     
                                                 onScrollEvent@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1274:1`
Something broke when i upgrade manjaro on 3.14,this probably is one.

**Comment by 3v1n0** [comment]
This has been fixed by commit 3219295ca49d7fbae005532d21c10c96f4146886
