### ISSUE TITLE
Don't Work In gnome3.36!!!

### ISSUE THREAD

**Issue by KyleJKC** [micheleg/dash-to-dock#1123]
Hello! I hope you can see this issue, **dash-to-dock don't work at gnome3.36**. I hope you can **update it soon**! thank you so much!!!

_OS: Archlinux
Kernel: 5.5.9-arch1-2
DE: GNOME3.36_

**Comment by svbergerem** [comment]
I guess this is a duplicate of some of these issues:
https://github.com/micheleg/dash-to-dock/issues?q=is%3Aissue+is%3Aopen+3.36

And here is a PR that fixes this issue: #1097

**Comment by KyleJKC** [comment]
OK, I solve that problem, I use the branch: gnome-3-36, It works!

**Comment by EdoardoLaGreca** [comment]
May someone (the author) fix it at https://extensions.gnome.org so that all the users can update to the fixed version?

**Comment by Razer0123** [comment]
I cannot seem to be able to rearrange icons, not sure if this has to do with 3.36 or has always been the case
