### ISSUE TITLE
issue when ordening dock-items (icons)

### ISSUE THREAD

**Issue by tvercruysse** [micheleg/dash-to-dock#1124]
Rearranging applications (drag and dropping) is nearly impossible, the X coordinate is calculated wrongly ( whenever i drag a dock-item over its sibling it tries to place it two positions to its right or left.

When i set the dock to position left or right, it works as expected.

branch: `gnome-3-36`
dock position: `bottom`
screen resolution: `3440x1440`

**Comment by KMPR** [comment]
I suffer from the same issue. It's not that big of deal but still quite annoying.

branch:   gnome-3-36
dock position:   bottom
screen resolution:   1920x1080

**Comment by owlJaeger** [comment]
I also suffer from this issue.
branch: gnome-3-36
dock position: bottom

If you really have to reorder some stuff, switching the dock position to left, reordering and switching it back works for me everytime.

**Comment by lucenera** [comment]
Same here, same solution. The problem was in previous versions too.

**Comment by patrickaldis** [comment]
I can second this. On gnome 3.34, latest version of ext

**Comment by wiuribecomodisimos** [comment]
I also suffer from this issue.

**Comment by hrozan** [comment]
Same problem here

- Gnome 3.36.1
- Manjaro Linux
- 1280 x 720

**Comment by patrykbajos** [comment]
The same issue on:
GNOME: 3.36.1
distro: Manjaro Linux
resolution:1920x1080 100% scalling
dock position: bottom
dash-to-dock Version: 67
It was not present on 3.34
[Nagranie ekranu z 09.04.2020 21:45:00.zip](https://github.com/micheleg/dash-to-dock/files/4458584/Nagranie.ekranu.z.09.04.2020.21.45.00.zip)

**Comment by genericusername3** [comment]
Yup. Same here with Manjaro and Gnome 3.36.1.
My guess is that the item position is calculated from the relative Y position of the cursor in the dock which fails on horizontal docks.

**Comment by MitaiGit** [comment]
решения проблемы нет?

**Comment by lucenera** [comment]
> решения проблемы нет?

With the latest version 3.36 the problem is completely solved. For me it can be closed.

**Comment by MitaiGit** [comment]
> > решения проблемы нет?
> 
> С последней версией 3.36 проблема полностью решена. Для меня это может быть закрыто.

after restarting it worked

**Comment by tvercruysse** [comment]
After building straight from master this issue seems to be fixed.

Closing this issue.
