### ISSUE TITLE
Two windows open at the same time(only for gnome-web)

### ISSUE THREAD

**Issue by demolg** [micheleg/dash-to-dock#1129]
After enable extension, when I launch gnome-web(epipany) from dock or appmenu, it appears two windows.

**Comment by omicron-b** [comment]
Can confirm, Debian Testing
I use c58004802b2eedfde96966a4ec0151fea2a1bd98 (latest in gnome-3-36) but it is also reproduced with 226b7ed8a4cef1ab48acb5db89761a40ad863ca8, so there is no particular commit in gnome-3-36 to blame

**Comment by omicron-b** [comment]
This is upstream issue, dash-to-panel guys reported it here: https://gitlab.gnome.org/GNOME/epiphany/-/issues/1152

**Comment by omicron-b** [comment]
Fixed in Gnome Web 3.36.2
https://gitlab.gnome.org/GNOME/epiphany/-/blob/gnome-3-36/NEWS
