### ISSUE TITLE
No dconf scheme available

### ISSUE THREAD

**Issue by bmarien** [micheleg/dash-to-dock#114]
There doesn't seem to be a dconf scheme for this extensions at boot/load time. 
settings only become available via the dconf editor or gsettings cli tool, after the tweaktool has been used to change settings for the dash-to-dock extension. Only the settings changed via the above tool are visible in the sheme org.gnome.shell.extensions.dash-to-dock

Any idea's on this?
Thanks
Bart

**Comment by micheleg** [comment]
Sorry for the late reply. This appears to be the behaviour of all extensions apart from the system installed ones. I'm not sure if anything can be done in this respect. If you need to see the source of the schema with all possible options available it is in ```~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml```
