### ISSUE TITLE
Error with Gnome 3.36 on Manjaro (X11)

### ISSUE THREAD

**Issue by henrik-wittenberg** [micheleg/dash-to-dock#1140]
This extension stopped working on my Manjaro installation (Gnome 3.36/X11).

Looking Glass shows the following:

TypeError: appIconPrototype._onLeaveEvent is undefinded

**Comment by Atyk-oO** [comment]
I had the same issue on Manjaro 19.0.2, [this is how i fixed it](https://github.com/micheleg/dash-to-dock/issues/1141#issuecomment-604949793).

**Comment by henrik-wittenberg** [comment]
> I had the same issue on Manjaro 19.0.2, [this is how i fixed it](https://github.com/micheleg/dash-to-dock/issues/1141#issuecomment-604949793).

Thanks, that worked for me. :-)

**Comment by battlezone** [comment]
> I had the same issue on Manjaro 19.0.2, [this is how i fixed it](https://github.com/micheleg/dash-to-dock/issues/1141#issuecomment-604949793).

This issue has been deleted for some reason. Also, it didn't solve the issue in my case

**Comment by Atyk-oO** [comment]
The content of the post was the following:

Clone the git repo with gnome 3.36 branch
`git clone -b gnome-3-36 https://github.com/micheleg/dash-to-dock.git`

Then cd to directory:
`cd dash-to-dock/`

Make & Make install:
`make`
`make install`

Restart gnome-shell
`alt+f2` type `r` press `enter`

The dock should be now activated, if not, activate it in gnome-tweaks or use the following command:
`gnome-extensions enable dash-to-dock@micxgx.gmail.com`

If you are using another dock you have to quit it first (plank can inhibit dash-to-dock to show for example).

**Comment by battlezone** [comment]
Correct, thanks for sharing it here. I have followed those steps but Dash-to-dock still fails to load. I do not have any other docks installed or enabled. It was working fine with Ubuntu 18.04 but after I updated to 19.04 it no longer works.

**Comment by Atyk-oO** [comment]
If the version output in this command `gnome-extensions info dash-to-dock@micxgx.gmail.com`
is <67 or if the path is not in your `/home` directory try to delete the extension using the following command `gnome-extensions uninstall dash-to-dock@micxgx.gmail.com` also delete any dash-to-dock download/clone you have done before and follow again every step in my previous post.

are you using gnome with wayland ?

**Comment by battlezone** [comment]
The output of `gnome-extensions info dash-to-dock@micxgx.gmail.com` is 67 and the path is /home. I tried deleting it and redid the steps. It sadly did not work.

I am using Gnome with Wayland with Gnome 3.34 (so not really the right issue to report this to, sorry)

**Comment by Atyk-oO** [comment]
oh you're using gnome 3.34, try to clone the master branch then `git clone https://github.com/micheleg/dash-to-dock.git`

**Comment by battlezone** [comment]
Thanks, that did the trick. I don't know how I thought installing the 3.36 branch was going to work.
