### ISSUE TITLE
Application menu/grid acts weird.

### ISSUE THREAD

**Issue by AtifChy** [micheleg/dash-to-dock#1142]
Application menu acts weird when I enter it from activities, only when panel mode:extend to screen mode is enabled.

**Comment by Schlaumra** [comment]
> Application menu acts weird when I enter it from activities, only when panel mode:extend to screen mode is enabled.
I have the same issue

**Comment by vanvugt** [comment]
Is this still a bug? If so then please clarify what "acts weird" means.
