### ISSUE TITLE
3.36 empty space on dynamic size

### ISSUE THREAD

**Issue by jtagcat** [micheleg/dash-to-dock#1147]
F32, `gnome-shell-extension-dash-to-dock-67-5.20200224git5658b5c.fc32.src.rpm`
![image](https://user-images.githubusercontent.com/38327267/77916114-14e6a500-7288-11ea-8fec-21b612ba192a.png)
Empty space is added before everything for no apparent reason, making the extension unusable in non-panel mode.

**Comment by JorgeHerreraU** [comment]
I'm also having the same problema on Fedora 32

**Comment by martinRenou** [comment]
How did you actually install it on Fedora 32? Did you install it from sources?

**Comment by jtagcat** [comment]
I was installing from dnf, since installing from ext.gnome did not work as well.

From dnf is now fixed, I uninstalled and installed from ext.gnome again. It worked as well. It seems that this has been fixed.
