### ISSUE TITLE
Have "Customize the dock background opacity" disabled by default.

### ISSUE THREAD

**Issue by lassekongo83** [micheleg/dash-to-dock#115]
I'm a developer of some 3rd party themes and this extension seems to interfere with any CSS rules I apply to the dash causing unnecessary bug reports that's not an issue with my themes. 

It would be great if you could disable "Customize the dock background opacity" by default as I don't see it to be a needed feature to have enabled by default, especially if you use 3rd party gnome-shell themes.

**Comment by micheleg** [comment]
Background opacity customization is now disabled by default. 89e36e07fb839d94af2687ce437bea9d2874a319.
