### ISSUE TITLE
show-mounts false hides all items on the dock on non primary monitors.

### ISSUE THREAD

**Issue by Nigh7Stalk3r** [micheleg/dash-to-dock#1156]
Using 3 monitors when i set org.gnome.shell.extensions.dash-to-dock show-mounts false it removes the mounted drives from the primary monitor dash but removes all items from the dash on my other 2 monitors.

Ubuntu 19.10
https://i.imgur.com/2is4JL5.png

**Comment by Nigh7Stalk3r** [comment]
Okay found a fix, moving the dock to another position then moving it back again fixes it.

**Comment by darkdragon-001** [comment]
Duplicate of #1025

**Comment by 3v1n0** [comment]
Duplicate of #1025
