### ISSUE TITLE
Error loading extension on Ubuntu 20.04 beta

### ISSUE THREAD

**Issue by aplab** [micheleg/dash-to-dock#1158]
![2020-04-08_11-51](https://user-images.githubusercontent.com/4007240/78753647-97a9e700-798f-11ea-81c6-d69e0be7b510.png)

I use installation from source

**Comment by legluondunet** [comment]
Same issue here for I upgraded my Ubuntu to 20.04.

**Comment by advaithm** [comment]
yeah same here

**Comment by totof1169** [comment]
same here

**Comment by jsco2t** [comment]
I'm having the same issue - and I have installed the `extension` from source.

I'm not sure if this is the issue - but when I check `journalctl` I see the following errors:

```
sudo journalctl /usr/bin/gnome-shell | grep 'dash-to-dock'

gnome-shell[1872]: JS WARNING: [/home/jason/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js 1051]: reference to undefined property "_onLeaveEvent"

gnome-shell[1872]: JS ERROR: Extension dash-to-dock@micxgx.gmail.com: TypeError: appIconPrototype._onLeaveEvent is undefined
```
Unfortunately I don't know enough about `gnome extensions` to tell if this is actually what's breaking the extension. I'd be happy to try out a bug fix if you come up with one though.

**Comment by aplab** [comment]
I'm trying to next steps

```
git clone https://github.com/micheleg/dash-to-dock.git
git fetch --all
git checkout origin/gnome-3-36
make
make install

```

then press <alt>+<f2> r to restart, and it works!

**Comment by yoshieki1992** [comment]
thank you

**Comment by advaithm** [comment]
I think that the branch temp/gnome3.36 needs to be removed

**Comment by aplab** [comment]
> I think that the branch temp/gnome3.36 needs to be removed

I used branch origin/gnome-3-36 but not tmp/gnome-3-36

**Comment by advaithm** [comment]
I have used origin/gnome-3-36. it works well. occasionally it does crash but reloding the  gnome shell does fix it.

**Comment by quique-rgb** [comment]
> I'm trying to make next steps:
> 
> create empty catalog and enter it
> 
> ```
> git clone https://github.com/micheleg/dash-to-dock.git
> cd dash-to-dock
> git fetch --all
> git checkout origin/gnome-3-36
> make
> make install
> ```
> 
> then press
> 
> ```
> <alt>+<f2> r 
> ```
> 
> to restart, and it works fine!
> 
> ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)

Didn't work for me, it doesn't appear in gnome-tweaks, thanks.

**Comment by quique-rgb** [comment]
Well, finally made it to work, many thanks, I put the folder inside /.local/share/gnome-shell/extensions, many thanks

**Comment by HenglyEver** [comment]
> I'm trying to make next steps:
> 
> create empty catalog and enter it
> 
> ```
> git clone https://github.com/micheleg/dash-to-dock.git
> cd dash-to-dock
> git fetch --all
> git checkout origin/gnome-3-36
> make
> make install
> ```
> 
> then press
> 
> ```
> <alt>+<f2> r 
> ```
> 
> to restart, and it works fine!
> 
> ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)

It does work for me, thank you :D

**Comment by micheleg** [comment]
Closed by #1097.

**Comment by PratikGandole** [comment]
its work for me.

**Comment by moghaazi** [comment]
> I'm trying to make next steps:
> 
> create empty catalog and enter it
> 
> ```
> git clone https://github.com/micheleg/dash-to-dock.git
> cd dash-to-dock
> git fetch --all
> git checkout origin/gnome-3-36
> make
> make install
> ```
> 
> then press
> 
> ```
> <alt>+<f2> r 
> ```
> 
> to restart, and it works fine!
> 
> ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)

When i type `git checkout origin/gnome-3-36` It's show me this message
 `error: pathspec 'origin/gnome-3-36' did not match any file(s) known to git
`

**Comment by aplab** [comment]
> > I'm trying to make next steps:
> > create empty catalog and enter it
> > ```
> > git clone https://github.com/micheleg/dash-to-dock.git
> > cd dash-to-dock
> > git fetch --all
> > git checkout origin/gnome-3-36
> > make
> > make install
> > ```
> > 
> > 
> > then press
> > ```
> > <alt>+<f2> r 
> > ```
> > 
> > 
> > to restart, and it works fine!
> > ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)
> 
> When i type `git checkout origin/gnome-3-36` It's show me this message
> `error: pathspec 'origin/gnome-3-36' did not match any file(s) known to git `

Branch "origin/gnome-3-36" was removed. Try "git checkout master"

**Comment by moghaazi** [comment]
@aplab  Can you type the full line of code

**Comment by aplab** [comment]
> @aplab Can you type the full line of code

git checkout master

**Comment by moghaazi** [comment]
ok but i've got another error when i type `make` it show me this message 
`msgfmt -c po/hu.po -o po/hu.mo
make: msgfmt: Command not found
make: *** [Makefile:54: po/hu.mo] Error 127`

**Comment by aplab** [comment]
> ok but i've got another error when i type `make` it show me this message
> `msgfmt -c po/hu.po -o po/hu.mo make: msgfmt: Command not found make: *** [Makefile:54: po/hu.mo] Error 127` @aplab

Try it

sudo apt-get install build-essential
sudo apt-get install make

**Comment by DandelionFs** [comment]
its "git clone" works, first i try download then it doesn't work...

**Comment by aplab** [comment]
What are you trying to download?

> its "git clone" works, first i try download then it doesn't work...

**Comment by moghaazi** [comment]
I restart the PC, and everything returned to normal.

**Comment by xi2oh2co3** [comment]
> > ok but i've got another error when i type `make` it show me this message
> > `msgfmt -c po/hu.po -o po/hu.mo make: msgfmt: Command not found make: *** [Makefile:54: po/hu.mo] Error 127` @aplab
> 
> Try it
> 
> sudo apt-get install build-essential
> sudo apt-get install make

I have tried it, but it did not work.

**Comment by nesso99** [comment]
> > > ok but i've got another error when i type `make` it show me this message
> > > `msgfmt -c po/hu.po -o po/hu.mo make: msgfmt: Command not found make: *** [Makefile:54: po/hu.mo] Error 127` @aplab
> > 
> > 
> > Try it
> > sudo apt-get install build-essential
> > sudo apt-get install make
> 
> I have tried it, but it did not work.

Try it

sudo apt-get install gettext

**Comment by blankah2** [comment]
> > I'm trying to make next steps:
> > create empty catalog and enter it
> > ```
> > git clone https://github.com/micheleg/dash-to-dock.git
> > cd dash-to-dock
> > git fetch --all
> > git checkout origin/gnome-3-36
> > make
> > make install
> > ```
> > 
> > 
> > then press
> > ```
> > <alt>+<f2> r 
> > ```
> > 
> > 
> > to restart, and it works fine!
> > ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)
> 
> When i type `git checkout origin/gnome-3-36` It's show me this message
> `error: pathspec 'origin/gnome-3-36' did not match any file(s) known to git `

Thanks for this, all the above commands work in terminal but when I do 'Alt+F2 then r' I get an error 'Restart is not available on Wayland' 
Basically I've still got the initial issue in Extensions 'Error Loading Extension' 

Any help would be grateful on this.

Thanks
![image](https://user-images.githubusercontent.com/77338984/104331587-259a9b80-54e7-11eb-8889-e35d8a6d5da5.png)

**Comment by pranay-sama** [comment]
I Had a double dock problem and used Hide dash X to hide the dock in Overview but now after following @aplab 's solution i was able to install properly but now i cannot see the application dock at all. If i disable Hidedash X then i can see the dock in overview.
Any help would be appreciated. Thankyou

> > @aplab Can you type the full line of code
> 
> git clone https://github.com/micheleg/dash-to-dock.git
> cd dash-to-dock
> git checkout master
> make
> make install

**Comment by youssefshehab73** [comment]
> > > I'm trying to make next steps:
> > > create empty catalog and enter it
> > > ```
> > > git clone https://github.com/micheleg/dash-to-dock.git
> > > cd dash-to-dock
> > > git fetch --all
> > > git checkout origin/gnome-3-36
> > > make
> > > make install
> > > ```
> > > 
> > > 
> > > then press
> > > ```
> > > <alt>+<f2> r 
> > > ```
> > > 
> > > 
> > > to restart, and it works fine!
> > > ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)
> > 
> > When i type `git checkout origin/gnome-3-36` It's show me this message
> > `error: pathspec 'origin/gnome-3-36' did not match any file(s) known to git `
> 
> Thanks for this, all the above commands work in terminal but when I do 'Alt+F2 then r' I get an error 'Restart is not available on Wayland' 
> Basically I've still got the initial issue in Extensions 'Error Loading Extension' 
> 
> Any help would be grateful on this.
> 
> Thanks
> ![image](https://user-images.githubusercontent.com/77338984/104331587-259a9b80-54e7-11eb-8889-e35d8a6d5da5.png)
> 

Same man

**Comment by Muhammed-Rahif** [comment]
> I'm trying to make next steps:
> 
> create empty catalog and enter it
> 
> ```
> git clone https://github.com/micheleg/dash-to-dock.git
> cd dash-to-dock
> git fetch --all
> git checkout origin/gnome-3-36
> make
> make install
> ```
> 
> then press
> 
> ```
> <alt>+<f2> r 
> ```
> 
> to restart, and it works fine!
> 
> ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)

**Worked Fine... Thanks... 👍️**

**Comment by noyidoit** [comment]
> I'm trying to make next steps:
> 
> create empty catalog and enter it
> 
> ```
> git clone https://github.com/micheleg/dash-to-dock.git
> cd dash-to-dock
> git fetch --all
> git checkout origin/gnome-3-36
> make
> make install
> ```
> 
> then press
> 
> ```
> <alt>+<f2> r 
> ```
> 
> to restart, and it works fine!
> 
> ![dtd](https://user-images.githubusercontent.com/4007240/79062204-714abb00-7cb1-11ea-8b16-2cc26698d19a.png)

It works fine for me when I just run `<alt>+<F2> r`, thanks

**Comment by mikufu** [comment]
I try this branch, gnome-3.38, it works fine, thanks!
![Uploading Screenshot from 2023-12-10 15-11-42.png…]()

**Comment by mikufu** [comment]
I try this branch, gnome-3.38, it works fine, thanks!
![Screenshot from 2023-12-10 15-11-42](https://github.com/micheleg/dash-to-dock/assets/116622424/d4b98a6c-a24e-4f2e-a76d-d18f16e28f51)
