### ISSUE TITLE
Window counter indicator bug

### ISSUE THREAD

**Issue by zloymalefic** [micheleg/dash-to-dock#1159]
On Manjaro 19.0.2 (Dash to dock 67) when you changing the of the Window counter indicator the default once stays visible.
![Screenshot from 2020-04-08 12-18-50](https://user-images.githubusercontent.com/5164061/78767330-22d8ac00-7993-11ea-8c17-059bd6fbdf43.png)

**Comment by Sn3ipen** [comment]
It's because of the default theme in Manjaro Gnome. To fix it you need to change the theme.
