### ISSUE TITLE
can not open Dash to dock Settings from dock

### ISSUE THREAD

**Issue by neptu39701** [micheleg/dash-to-dock#1164]
Hi i am using arch and gnome 3.36.1-1 when i try to open dash to dock settings with right click from "show applications" button, nothing happens

**Comment by SaucySauce** [comment]
This isn't just with D2D, I've had the same thing happen with other extensions with easy to reach settings menu. Even Tweaks tool is locked out, only way of reaching the settings menu on 3.36 seems to be through the new Extensions app.

**Comment by 3v1n0** [comment]
New code is updated to support the proper tool for opening the settings, so use that.

Also make sure you've that installed (it's not by default in debian/ubuntu)
