### ISSUE TITLE
The Show Applications button is unclickable in the corner and along its bottom edge in Ubuntu 20.04

### ISSUE THREAD

**Issue by DoctorRover** [micheleg/dash-to-dock#1167]
Clicking the Show Applications button in the very corner of the screen and at its bottom edge doesn't work. This bug applies in the cases of left and right positions of the dock and there is no this bug in the case of bottom position. There was no this bug a couple of ubuntu-dock versions before.

This issue is very annoying since the mouse pointer runs at the very corner of the screen in vast majority of cases as you intent to press the Show Apps button.

gnome-shell-extension-ubuntu-dock version 67ubuntu20.04.4

**Comment by DoctorRover** [comment]
Here is the downstream Ubuntu bug report on Launchpad:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1873321

**Comment by ducvuongpham** [comment]
Exactly the bug report I'm looking for. It's really annoying

**Comment by DoctorRover** [comment]
Thank you for fixing the issue so quickly.
Is there a chance that the fix will land in the upcoming Ubuntu 20.04?

**Comment by imchau** [comment]
There seems to be a regression and this issue has resurfaced on Ubuntu 21.10 impish (daily build) with the baked-in version 70~ubuntu2 of gnome-shell-extension-ubuntu-dock.

See here for a video demonstration: https://launchpadlibrarian.net/556946811/Show_Applications_Fitts.gif

Reported downstream at https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1942702

**Comment by vanvugt** [comment]
@imchau, since this bug is closed you should open a new one instead.
