### ISSUE TITLE
Minimum icons size

### ISSUE THREAD

**Issue by didierga** [micheleg/dash-to-dock#1169]
Hi,
I just updated to Fedora 32 Beta with gnome-shell-3.36.1-4.fc32.x86_64 then I installed gnome-shell-extension-dash-to-dock-67-8.20200415git9c13203.fc32.noarch
Icon size is very small compared to icon size I had with Fedora 31 and gnome-shell-3.34
Is there a way to specify minimum icon size as it is possible to specify the maximum one ?
Thanks for your help.

**Comment by micheleg** [comment]
I believe this is related to this: https://github.com/micheleg/dash-to-dock/pull/1097#issuecomment-615003951

**Comment by didierga** [comment]
Problem is fixed after upgrade to gnome-shell-extension-dash-to-dock-68-1.fc32.noarch
Thanks for your work.
