### ISSUE TITLE
Ubuntu 20.04 auto-hide dash overlaps with dock

### ISSUE THREAD

**Issue by gnobre** [micheleg/dash-to-dock#1195]
I have auto-hide on and sometimes when I hover over the bottom, both the dash and the dock appears. Usually it's fixed when I restart gnome with alt+f2 + r

**Comment by xpt1x** [comment]
I added a workaround for this issue: https://github.com/micheleg/dash-to-dock/issues/1185

**Comment by gnobre** [comment]
ha, thanks @xpt1x
