### ISSUE TITLE
Transparent column of space between dock and windows

### ISSUE THREAD

**Issue by mostly-hrmless** [micheleg/dash-to-dock#1218]
When placing a window next to the dock or viewing a window in full screen mode a column of blank space is visible between the dock and the window.

![image](https://user-images.githubusercontent.com/1943899/81738216-5bbee180-9467-11ea-9bf0-0713a1f48c7a.png)

OS: Pop_OS 20.04
Dash to Dock version: 68

**Comment by jlocash** [comment]
Had this same issue, and it seems that installing from source fixed it.

**Comment by mostly-hrmless** [comment]
I just tried installing from source and the problem persists.  The installed version is 68, which looks like the same version that's available on extensions.gnome.org.

**Comment by jlocash** [comment]
my mistake. it did originally appear to be fixed, but upon rebooting it came back. I don't see this with the stock adwaita theme, perhaps its a theme issue?

**Comment by mostly-hrmless** [comment]
Ah, I think you're right.  The issue appeared using the Pop_OS and matcha gtk themes.  I switched to adwaita and the gap is gone.  I'm not sure this is something that can be fixed by the extension developer.  Once that's confirmed I'll go ahead and close this issue.

**Comment by jlocash** [comment]
what's more interesting is that the issue also goes away if 'Shrink the dash' is disabled, at least for me

**Comment by jlocash** [comment]
The issue is in stylesheet.css:
```
/* Shrink the dash by reducing padding */
#dashtodockContainer.shrink #dash,
#dashtodockContainer.dashtodock #dash {
    border:1px;
    padding:0px;
}
```
I removed `border:1px` and reinstalled from source and the gap is gone. No idea why it was there in the first place

**Comment by mostly-hrmless** [comment]
jlocash's fix worked for me.  Here is the fix on Pop_OS:

Uninstall the extension from extensions.gnome.org

`sudo apt install gettext`
`git clone https://github.com/micheleg/dash-to-dock.git`
`cd dash-to-dock`
`vim stylesheet.css`
Remove the following on line 4: `border:1px;`
`make`
`make install`

Alt+F2 r Enter and re-enable the extension in gnome tweaks.
