### ISSUE TITLE
Dash to dock displays twice with autohide when logging back from lock screen on Ubuntu 20

### ISSUE THREAD

**Issue by dominikduda** [micheleg/dash-to-dock#1223]
Steps to reproduce:

1. Scroll to a workspace without any windows
![image](https://user-images.githubusercontent.com/14922999/81843682-3ce74a80-954e-11ea-8e03-0f01db1f3306.png)
2. Lock screen (ctrl + l). Notice the dash is still displayed on the locked screen.
3. Log back in and notice the dash is displayed twice.
![image](https://user-images.githubusercontent.com/14922999/81843860-859f0380-954e-11ea-938e-ffcc62002a27.png)

Steps 2 and 3 sometimes need to be repeated more than 1 time.

My settings: 
![image](https://user-images.githubusercontent.com/14922999/81843915-9cddf100-954e-11ea-8220-a075caadf1e3.png)
![image](https://user-images.githubusercontent.com/14922999/81843936-a5362c00-954e-11ea-9d5b-d96cea8f8663.png)
![image](https://user-images.githubusercontent.com/14922999/81843950-a9624980-954e-11ea-9a89-1c3b0ce78b67.png)
![image](https://user-images.githubusercontent.com/14922999/81843967-ad8e6700-954e-11ea-8ed4-d46d95dc7b5a.png)
![image](https://user-images.githubusercontent.com/14922999/81843976-b121ee00-954e-11ea-989a-bdd0d1f29537.png)

It's critical since after duplication sometimes it causes the system to freeze.

**Comment by SiddharthVarshney** [comment]
Having something similar issue : (
#1215

**Comment by WadeShadow** [comment]
Pleased to see somebody who did all the job of describing the problem in detail for me. Thank you.
By the way, experiencing the same issue on latest Ubuntu 20.

**Comment by dominikduda** [comment]
The following commands fixed the issue for me:
```
cd /usr/share/gnome-shell/extensions
sudo mv ubuntu-dock@ubuntu.com ubuntu-dock@ubuntu.com.bkp
```

**Comment by generalov** [comment]
I had installed the Dash to Dock extension from https://extensions.gnome.org/local/ and and ran into the problem after updating Ubuntu.

Ubuntu 20.04 installs another version of the extenstion in the `gnome-shell-extension-ubuntu-dock` package as a dependency of `ubuntu-desktop`.

Uninstalling 'Dash to Dock' from https://extensions.gnome.org/local/ solves the problem.

**Comment by ambigus9** [comment]
> The following commands fixed the issue for me:
> 
> ```
> cd /usr/share/gnome-shell/extensions
> sudo mv ubuntu-dock@ubuntu.com ubuntu-dock@ubuntu.com.bkp
> ```

Thanks. Works. But i'm seeing that the reaction after suspend is really slow, and some times my system gets all black screen. Any idea?
