### ISSUE TITLE
Error after Suspend

### ISSUE THREAD

**Issue by heliommsfilho** [micheleg/dash-to-dock#1231]
After hit GNOME's Suspend button, when I log into the session again the extension is in a error state.

**Before suspension (everything OK):**
![Screenshot from 2020-05-18 10-59-09](https://user-images.githubusercontent.com/10871439/82202322-3f9cc380-98f1-11ea-9b25-e5cafe0e5d85.png)

**After suspension (error in Dash To Dock):**
![Screenshot from 2020-05-18 11-15-13](https://user-images.githubusercontent.com/10871439/82202369-52af9380-98f1-11ea-90e7-cb5e066bcda8.png)

This causes Ubuntu's default panel do overlay Dash To Dock:
![Screenshot from 2020-05-18 11-14-57](https://user-images.githubusercontent.com/10871439/82202437-6f4bcb80-98f1-11ea-94b3-2cadaa645865.png)

**Info:**
Extension version: 68
Gnome Shell version: 3.36.1
Linux distribution and version: Ubuntu 20.04 LTS
Whether you have a multi-monitor configuration: No
Dconf dump:
`[/]
apply-custom-theme=false
click-action='skip'
custom-background-color=false
custom-theme-shrink=false
customize-alphas=true
dash-max-icon-size=48
dock-fixed=false
dock-position='BOTTOM'
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
isolate-workspaces=true
max-alpha=0.80000000000000004
min-alpha=0.0
multi-monitor=false
pressure-threshold=50.0
running-indicator-style='DEFAULT'
scroll-action='cycle-windows'
show-apps-at-top=true
show-mounts=true
transparency-mode='DYNAMIC'`

**Comment by heliommsfilho** [comment]
I found the fix for this problem in [dominikduda's comment.](https://github.com/micheleg/dash-to-dock/issues/1223#issuecomment-629264180)

**Comment by ambigus9** [comment]
> I found the fix for this problem in [dominikduda's comment.](https://github.com/micheleg/dash-to-dock/issues/1223#issuecomment-629264180)

Thanks, Works. But i'm seeing that the reaction after suspend is really slow, and some times my system gets all black screen. Any idea?

**Comment by emmenlau** [comment]
The answer from @ambigus9 helped me too.
