### ISSUE TITLE
dash-to-dock glitches while in auto-hide setting

### ISSUE THREAD

**Issue by georkapetanos** [micheleg/dash-to-dock#1232]
When "Auto-hide the Dock" is enabled and there is a maximized window, so that the dock is hidden, upon moving the mouse to the bottom of the screen, sometimes the dock glitches and initiates a hide-show animation without stopping instead from showing up until the cursor moves away from the dock.

https://youtu.be/Lw2HBmLhd6w

This bug was first noticed after upgrading to ubuntu 20.04 from 19.10

Description: Ubuntu 20.04 LTS
Release: 20.04

gnome-shell-extension-ubuntu-dock:
  Installed: 67ubuntu20.04.5
  Candidate: 67ubuntu20.04.5
  Version table:
  67ubuntu20.04.5 500
        500 http://gr.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        500 http://gr.archive.ubuntu.com/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

ProblemType: Bug
ApportVersion: 2.20.11-0ubuntu27
Architecture: amd64
CasperMD5CheckResult: skip
CurrentDesktop: ubuntu:GNOME
DistroRelease: Ubuntu 20.04
InstallationDate: Installed on 2019-10-27 (204 days ago)
InstallationMedia: Ubuntu 19.10 "Eoan Ermine" - Release amd64 (20191017)
NonfreeKernelModules: nvidia_modeset nvidia
Package: gnome-shell-extension-ubuntu-dock 67ubuntu20.04.5
PackageArchitecture: all
ProcVersionSignature: Ubuntu 5.4.0-29.33-generic 5.4.30
Tags: focal
Uname: Linux 5.4.0-29-generic x86_64
UpgradeStatus: Upgraded to focal on 2020-05-09 (9 days ago)
UserGroups: adm cdrom dip lpadmin lxd plugdev sambashare sudo
_MarkForUpload: True

**Comment by zebest-potato** [comment]
OS: Pop_OS! 20.04
DE: Gnome 3.36.2
extension version: 68 (from gnome extension site)

same here the dock jumps up and down when moving the cursor to where the dock is. this doesn't happen all the time but often enough and happens only when you place the dock on the bottom

**how to reproduce:**
1-place dock on the bottom
2-toggle on intelligent autohide 
3-open maximized window
4-show and hide the dock multiple times  (some times happens from the first time)
5-dock jumps up and down

![simplescreenrecorder-2020-05-19_22 52 59](https://user-images.githubusercontent.com/51344986/82367343-50962380-9a1c-11ea-8872-2facb64e31f7.gif)

**other notes**
happens with plank dock too when placed on the bottom if that matter

**Comment by jscombs91** [comment]
Having the same issue with mine. Running the same versions as zebest-potato on a fresh install. I've noticed it only does it using Xorg. Running in Wayland it doesn't appear to do it from what I've seen.

**Comment by 161355** [comment]
Same problem on arch.

OS: Arch Linux
Gnome version: 3.36.2
Windowing system: X11
Extension version: 68

**Comment by 0xearl** [comment]
i have the same problem on my Ubuntu 19.04 and this bug only appears when my mozilla firefox is on full screen i have tested it with chromium if the bug appears but it seems like (in my case) it only appears on mozilla being full screen
Gnome-version: 3.34.2
Extension-version: 37

**Comment by manuel-uberti** [comment]
It's happening for me too:

Ubuntu 20.04 LTS
GNOME Shell 3.36.1 (x11)
GTK+ Version 3.24.18
Extension version: 68

**Comment by JensVanhooydonck** [comment]
Same problem as #1207

**Comment by manuel-uberti** [comment]
To which `Gap` option are you referring to in #1207?

**Comment by JensVanhooydonck** [comment]
That's the gap which is added by the Pop Is shell (tiling manager extension for gnome).

**Comment by manuel-uberti** [comment]
OK, thank you, but I'm not using either Pop nor the the tiling manager extension.

**Comment by JensVanhooydonck** [comment]
If you move to the side of where the dock would open. Does your mouse change to the resize icon if you are at the bottom of the page? It looks like that when my mouse is resizing the window, it doesn't seem te be registered by Dash-to-Dock, and thus it thinks it's not on the dock itself..

**Comment by manuel-uberti** [comment]
No, the mouse cursor doesn't change.

**Comment by JensVanhooydonck** [comment]
Okey, Than that path is probably not the issue.

**Comment by ceiphr** [comment]
Same issue. Ubuntu 20.04 LTS. GNOME version 3.36.2. Extension version 68.

**Comment by TC68** [comment]
I've been having the same on Pop!_OS 20.04 and suspected the window tilling. It seems to be an issue when a window is close to the edge of the screen. I raised an issue over there:
https://github.com/pop-os/shell/issues/402#issue-628135373

**Comment by Barazok** [comment]
This issue seems to come from the "pressure push to show" feature, I have it only if I enable this feature. I'm unable to reproduce it without this feature enabled. I'm on Fedora 32, Gnome 3.36, Dash-to-Dock v68 RPM.

**Comment by Barazok** [comment]
Nevermind. The issue is still here even without pressure push.

**Comment by harunyasar** [comment]
I believe that this problem is solved by making the `animation duration` to `0`.

**Comment by Barazok** [comment]
Indeed, I'm unable to reproduce the issue with `animation duration` set to `0` for both display and hide settings.

**Comment by TC68** [comment]
This is a good workaround and seems to help for me too.

**Comment by manuel-uberti** [comment]
Thanks for the workaround, although the animation effect makes it look better IMHO.

**Comment by harunyasar** [comment]
@TC68 @manuel-uberti I'm very glad to hear that the solution above also works for you.

**Comment by sedighi66** [comment]
Same bug.

ubuntu 20.04 upgraded from 19.10.
GNOME Shell 3.36.2
GTK+ Version 3.24.32
Extension version: 68

**Comment by ectogon** [comment]
Setting `animation duration` to `.075` with the other 2 settings at default seems to fix this for me. Going up to `.099` triggered the bug again.

**Comment by code-10** [comment]
the issue of dash to dock glitching is due to error in hide top bar extension for me, i deleted hide top bar extension and now dash to dock is working fine

**Comment by speakradmin** [comment]
Still getting this on my second monitor when Show on all monitors is enabled. Lowering Animation Duration, Hide Timeout or Pressure Threshold seems to have no effect like it did before.

Interestingly, it only does this when the window on the second monitor is maximised and focused. Unmaximised windows do not seem to trigger the glitching. It's also very reproducible for me at least whereas in the past I only sometimes got the glitch.

**Comment by Offroaders123** [comment]
> the issue of dash to dock glitching is due to error in hide top bar extension for me, i deleted hide top bar extension and now dash to dock is working fine

I can confirm that this removes the issue for me also.

Ubuntu 22.04 LTS
GNOME Shell 42.0

**Comment by Victorhtf** [comment]
@speakradmin I have been facing this trouble exactly the same way. Dock just glitching in my second monitor, just in certain  windows and when its maximized. Have you manage this issue? These recommendations doesn't seem to have effect.

Debian 12
GNOME 43.6

**Comment by purvaldur** [comment]
If anyone else finds this thread at the top of their google results, disabling unredirection is a solid workaround that fixed it for me. Keep in mind it *may* affect game performance. More information here:

https://github.com/micheleg/dash-to-dock/issues/1813

**Comment by Victorhtf** [comment]
> If anyone else finds this thread at the top of their google results, disabling unredirection is a solid workaround that fixed it for me. Keep in mind it _may_ affect game performance. More information here:
> 
> #1813



> If anyone else finds this thread at the top of their google results, disabling unredirection is a solid workaround that fixed it for me. Keep in mind it _may_ affect game performance. More information here:
> 
> #1813

Hello Purvaldur, I would try it.
How can I disable unredirection?

**Comment by alexander-m-92** [comment]
"Hide top bar" and "dash to dock" are definitely in conflict while auto-hide and "mouse hover/pressure to show" are enabled. While one of them is disabled(not completely, just "hover/pressure to show" setting), the other one works fine with any settings.

Animation settings make no difference for me.

Are there any solutions to make both work together?

Debian 12, systemd
GNOME v: 43.9

**Comment by glaucusec** [comment]
I have a similar issue

> "Hide top bar" and "dash to dock" are definitely in conflict while auto-hide enabled. While one of them is disabled, the other one works fine with any settings.
> 
> Animation settings make no difference for me.
> 
> Same issue while using both dash to dock and dash to panel (while "hover to show" is enabled for dash to dock).
> 
> Are there any solutions to make both work together?
> 
> Debian 12, wayland GNOME v: 43.9

I have somewhat similar issue in ubuntu 22.04. I don't have dash to dock extension enabled. When I disable the "Hide Top Bar" extension the left side application menu and top bar has no glitches. but when it is enabled. the top bar and application menu glitches. tried installing different versions of the extension, but it doesn't fixes the issue.

**Comment by rossparachute** [comment]
Ubuntu 22.04.3 LTS, 64-bit
GNOME v42.9
Wayland

Only an issue on my second monitor strangely.

Hover over the dock, even with animation delay 0 if you aren't constantly moving the mouse over the dock it'll flicker and disappear until you move the mouse again. Not got the auto-hide top bar extension installed. Does not occur when auto-hide dock disabled.

Seems to be apps like Firefox, Chrome and VS Code that are the worst offenders. Nautilus has no issue.

Tried monkeying around in dconf-editor as [here](https://askubuntu.com/a/1313434) but no joy.

Will try the XOrg window and disabling unredirection stuff and see if that sorts anything.

**Comment by delki8** [comment]
disabling unredirect worked for me: https://extensions.gnome.org/extension/1873/disable-unredirect-fullscreen-windows/

**Comment by MasterFru** [comment]
I fixed the bug by making pressure threshold -> 0 & its working fine for me
