### ISSUE TITLE
How can I remove this extension on Ubuntu 20.04?

### ISSUE THREAD

**Issue by aethletic** [micheleg/dash-to-dock#1241]
When I install, I get an ERPOR message, but the extension installs and my dock doubles.
When you try to delete, the extension is not deleted, but writes that it is as if it was deleted.

How do u manually remove it?

**Comment by aethletic** [comment]
1. Open the console.
2. Go to the extensions directory: `cd ~/.local/share/gnome-shell/extensions`
3. List the extensions and get the name of the unwanted extension: `ls -l`
4. Delete the extension directory: `rm -r extension@author`
5. Reload gnome-shell. Press `ALT + F2,` type `r` and press `ENTER`.

So will it be right?

**Comment by AsciiWolf** [comment]
I think that you can actually disable this extension in the [Extensions app](https://www.omgubuntu.co.uk/2020/02/gnome-3-36-features#extensions-app).
