### ISSUE TITLE
Not working with gnome-desktop 3.36.5

### ISSUE THREAD

**Issue by gilvbp** [micheleg/dash-to-dock#1292]
Hi, not working anymore with new gnome-desktop 3.36.5, here the Stack trace:

 dconf dump /org/gnome/shell/extensions/dash-to-dock/  output:

[/]
background-opacity=0.11
dash-max-icon-size=77
dock-position='BOTTOM'
icon-size-fixed=true
transparency-mode='FIXED'

/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled (dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled)”: open() falhou: Arquivo ou diretório inexistente

getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:142:31
DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:86:41 (dash-to-dock@micxgx.gmail.com/prefs.js:86:41)
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20 (dash-to-dock@micxgx.gmail.com/prefs.js:869:20)
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by gilvbp** [comment]
its was a local problem

**Comment by gombosg** [comment]
@gilvbp 
What was the problem? Looks like it's broken for me since 3.36.5 but it may be something else.
