### ISSUE TITLE
bottom-dock results in improper overview display

### ISSUE THREAD

**Issue by PatrickTrentin88** [micheleg/dash-to-dock#130]
hi, 
when the dash-to-dock is set to be on the bottom of the screen, and I activate the overview (WIN or top-left hand corner), the opened windows are not placed properly.

I did not yet investigate deeply in this issue (e.g. by disabling all other extensions to see if something changes), but I can do that upon request.

EDIT: i checked, this bug can be reproduced by activating the Workspace-To-Dock in combination with Dash-To-Dock.

![schermata da 2015-01-07 14 29 39](https://cloud.githubusercontent.com/assets/6245704/5646243/2bfe5002-967a-11e4-8045-4e79f8ed897e.png)

As a side note, I would like to take advantage of this issue to propose a feature: would it be possible to decouple the positioning of the dock-bar from 'switch workspace when scrolling over the dock'? I like to scroll on the left/right borders of my screen to switch workspace, as if there was a scrolling bar there. Scrolling on the bottom of the screen to change workspace (which are organized in a vertical stack) feels quite unnatural. :-)

**Comment by micheleg** [comment]
Hi, thank's for the bug report.
I think the problem is due to an incompatibility with the workspace-to-dock extension by @passingthru67 and the bottom option. 

I've uploaded a simple workaround in https://github.com/micheleg/workspaces-to-dock/tree/dashtodock_bottom_support.

**Comment by micheleg** [comment]
Regarding your feature suggestion, I agree scrolling on the bottom dock is quite unnatural. There use to be an extension providing that functionality, which I had to include into my extension as the two extensions couldn't easily coexist at the same time

* https://extensions.gnome.org/extension/136/desktop-scroller/
* https://extensions.gnome.org/extension/235/desktop-scroller-left-and-overview-version/
* https://extensions.gnome.org/extension/561/desktop-scroller-all-sides-for-gnome-36/

None of them seems to be working on my setup

I will consider decoupling the two features, or maybe moving  the scrolling one back to a separate extension as I might have found a way to avoid incompatibilities.

**Comment by PatrickTrentin88** [comment]
I merged the patch, and it solves the issue.
I'll look into the suggested extensions.

Many Thanks :)
