### ISSUE TITLE
suggestion: export the settings

### ISSUE THREAD

**Issue by furkanunluturkk** [micheleg/dash-to-dock#1302]
I think it would be great to have an option to export the current settings of the extension. So that user can share it with others or may be use it for self later on.

**Comment by micheleg** [comment]
Hi, there a way to export the settings from dconf: 
```
dconf dump /org/gnome/shell/extensions/dash-to-dock/
```
There's a hint here https://micheleg.github.io/dash-to-dock/development.html#bugreporting, as I sometimes use it to reproduce bugs in the exact user settings. The settings can be loaded with `dconf load ...`. Honestly, I don't believe dash-to-dock has such a huge number of settings with requires tedious manual entries, so I do not see much value in inplementing such feature.
