### ISSUE TITLE
Dock (bottom position) is "jumping" when autohide is on

### ISSUE THREAD

**Issue by k0lourful** [micheleg/dash-to-dock#1304]
Summary: dock keeps repeatedly hiding and opening when mouse cursor is hovered in the bottom edge of the screen. You can observe this behaviour in [the screencast on imgur](https://imgur.com/a/67MYbry).

System info:
Fedora 32 x86_64, Linux 5.8.4
Gnome 3.36.5, X11
Dash to Dock 68 from the Fedora repository.

**Comment by UA27** [comment]
Check out #1296, should fix the issue.

**Comment by k0lourful** [comment]
Thank you for the request! Since it's merged, the issue is no more.
