### ISSUE TITLE
Dash to dock twitches when cursor is at very low.

### ISSUE THREAD

**Issue by rela589n** [micheleg/dash-to-dock#1310]
`lsb_release -a`:
Description:     Ubuntu 20.04.1 LTS
Release:          20.04
Codename:      focal

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41589422/92935632-b5550e00-f451-11ea-82dc-7680b2b9e301.gif)

**Comment by AdoniasAlcantara** [comment]
Same to me! It also happens with default ubuntu dock. I noticed that the bug is only reproduced when the dock is positioned at the bottom.

**Comment by micheleg** [comment]
I believe this is a duplicated of #1234 and was solved in https://github.com/micheleg/dash-to-dock/pull/1296.

**Comment by rela589n** [comment]
> I believe this is a duplicated of #1234 and was solved in #1296.

Probably you mistyped #1232
