### ISSUE TITLE
Clock not centered in topbar

### ISSUE THREAD

**Issue by lepa22** [micheleg/dash-to-dock#1312]
When using the extension with the default settings, the clock is not centered. It looks like this:

![Screenshot from 2020-09-20 13-47-35](https://user-images.githubusercontent.com/16370046/93709607-2da18a80-fb48-11ea-8722-719c47d2601d.png)

However, when enabling the _Intelligent autohide_ option, the clock moves a bit to the left, along with the rest of the desktop, and is now properly centered:

![Screenshot from 2020-09-20 13-47-18](https://user-images.githubusercontent.com/16370046/93709603-24b0b900-fb48-11ea-95ff-f16a18625219.png)

Here are the the above screenshots stacked to make the problem more obvious:

![d2d-topbar-stacked](https://user-images.githubusercontent.com/16370046/93709953-6b53e280-fb4b-11ea-8386-197397435031.png)

What should happen is that the clock shouldn't move upon enabling/disabling the _Intelligent autohide_ option and should  always be centered as in the second screenshot.

**Comment by micheleg** [comment]
Is this a new behaviour? This seems to have been the bevariour for a few years and the desired behaviour https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/cd0af33947f8eb73a163ecef975728988ab51549
