### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by R2D2Hud** [micheleg/dash-to-dock#1316]
I have Installed dash to dock but when I go into gnome tweaks there is a error symbol and I can't turn it on.

**Comment by baldpale** [comment]
You haven't provide any information on what version of Gnome you tried to use that with. I can confirm it doesn't work on fresh 3.38

**Comment by R2D2Hud** [comment]
I was using gnome 3.38

**Comment by baldpale** [comment]
This may be already fixed. It worked for me when I:

1. Uninstalled the extension I tried to install from extensions.gnome.org
2. Cloned the repository
3. make && make install
4. Relogin

**Comment by hsehdar** [comment]
> This may be already fixed. It worked for me when I:
> 
> 1. Uninstalled the extension I tried to install from extensions.gnome.org
> 2. Cloned the repository
> 3. make && make install
> 4. Relogin

Thank you @baldpale as this helped me to solve the issue on ClearLinux with Gnome 3.38.

**Comment by R2D2Hud** [comment]
Now it does not show up a all

**Comment by HadetTheUndying** [comment]
> Now it does not show up at all

I fixed the issue by following the buildig/installing from source guide in the readme and relogging. I recommend you try the same.

**Comment by survivor303** [comment]
@HadetTheUndying that isnt solve the primary, most users install this from gnome extension website or from gnome software.
Issue is that 3.38 isnt supported yet, https://extensions.gnome.org/extension/307/dash-to-dock/ dosnt give option to choose 3.38 shell. latest shell what it offer is 3.36.

**Comment by Morteza-Rastgoo** [comment]
Same issue here

**Comment by R2D2Hud** [comment]
I am going to close this.
