### ISSUE TITLE
Error after most recent update, using Pop!_OS 20.04 with Gnome 3.36.3

### ISSUE THREAD

**Issue by A-Random-Lantern** [micheleg/dash-to-dock#1321]
The version that errored out is v69, it seems like I'm not the only one having this problem currently.

**Comment by scottdiemer** [comment]
I also received an error installing the update. I'm running Manjaro with Gnome version 3.36.6

**Comment by RedGradient** [comment]
The same issue. Ubuntu 20.04, Gnome 3.36.3
