### ISSUE TITLE
There was an error loading thr prefernces dialog for Dash to Dock

### ISSUE THREAD

**Issue by JKingRolling** [micheleg/dash-to-dock#1327]
TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/jack/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:865:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
![Screenshot from 2020-10-08 03-22-13](https://user-images.githubusercontent.com/46061424/95377731-8d07e480-0915-11eb-9cb3-d557dd66be82.png)

**Comment by JKingRolling** [comment]
> TypeError: ExtensionUtils.initTranslations is not a function
> 
> Stack trace:
> init@/home/jack/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:865:5
> _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
> wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
> _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
> wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
> _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
> wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
> main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
> @
> 
> :1:43
> ![Screenshot from 2020-10-08 03-22-13](https://user-images.githubusercontent.com/46061424/95377731-8d07e480-0915-11eb-9cb3-d557dd66be82.png)

**Comment by HoanKy** [comment]
This is [solution](https://github.com/micheleg/dash-to-dock/issues/902#issuecomment-473720166) !
