### ISSUE TITLE
Disable notification badge in do-not-disturb mode

### ISSUE THREAD

**Issue by jtojnar** [micheleg/dash-to-dock#1329]
When I enable GNOME Shell’s Do Not Disturb mode, I would like to avoid all distractions. Notification badges are bright red on the dash so they are pretty distracting. I would like to hide them in do-not-disturb mode.

**Comment by ckotte** [comment]
@jtojnar Can you add a screenshot?

**Comment by jtojnar** [comment]
![New mail](https://user-images.githubusercontent.com/705123/96282159-9dd1ed80-0fda-11eb-80da-6e4b4aef8255.png)
