### ISSUE TITLE
Windows in overview are not centered

### ISSUE THREAD

**Issue by x1b6e6** [micheleg/dash-to-dock#1330]
![image](https://user-images.githubusercontent.com/28683836/96082021-ab0cb080-0ee4-11eb-942c-eb72c5543b46.png)
![Screenshot from 2020-10-15 12-28-17](https://user-images.githubusercontent.com/28683836/96080729-f40f3580-0ee1-11eb-99c7-e4798e6552d4.png)

Archlinux
gnome-shell 3.38
dash-to-dock 69

**Comment by davidbepo** [comment]
same issue here, this extension is the cause

**Comment by TechnologyMan101** [comment]
This is caused by commit 3610a0882f41276c1e4c41c107ef21d4d4122df1.

**Comment by Crucizer** [comment]
I have issue way too similar to this. Applications don't align properly.

![Screenshot from 2020-11-10 22-13-45](https://user-images.githubusercontent.com/34895065/98703902-0b86f480-23a2-11eb-9682-b80b426ebc9b.png)

**Comment by isness** [comment]
> This is caused by commit [3610a08](https://github.com/micheleg/dash-to-dock/commit/3610a0882f41276c1e4c41c107ef21d4d4122df1).

I commented it out and still have the same issue.

**Comment by JLTastet** [comment]
Seems related to #1323.

Downstream Gnome issues:
* https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3378
* https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3286

**Comment by x1b6e6** [comment]
> Seems related to #1323.

Yes (why haven't I seen this before?)
I'm closing issue as duplicate.
