### ISSUE TITLE
dash-to-dock is not showing mounted network volumes and devices

### ISSUE THREAD

**Issue by lmachegger** [micheleg/dash-to-dock#1338]
Mounted network-volumes and devices are not showing in the dock although the option "Show mounted volumes and devices" is enabled.  

Here is a screenshot: https://imgur.com/a/PzcD3nb

I have my NAS mounted at `/media/nas` and my google-drive is also mounted. Both are showing correctly in gnome-files, but not in the dock.

I tested with all extensions except dash-to-dock disabled.

- Single-monitor setup
- OS: Manjaro-GNOME
- Kernel: 5.8.16-2-MANJARO
- Dash to Dock version: 68
- Dash to Dock settings:
```
dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
apply-custom-theme=false
background-opacity=0.14999999999999999
dash-max-icon-size=36
force-straight-corner=false
height-fraction=0.84999999999999998
hot-keys=false
hotkeys-overlay=false
hotkeys-show-dock=false
icon-size-fixed=false
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
max-alpha=1.0
preferred-monitor=0
shortcut=@as []
shortcut-text=''
show-mounts=true
show-trash=true
transparency-mode='DYNAMIC'
```
- Gnome-version: 
```
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>36</minor>
 <micro>6</micro>
 <distributor>Arch Linux®</distributor>
 <!--<date></date>-->
</gnome-version>%  
```

**Comment by grolongo** [comment]
@micheleg @3v1n0
on a fresh Ubuntu 22.10 with default settings (showing network drives in the dock is enabled by default) this doesn't work.
same as OP, we can see the mounted network share in Nautilus but it doesn't show an icon in the dock.
external devices like a USB key show properly though.
