### ISSUE TITLE
Error Loading Extension

### ISSUE THREAD

**Issue by kakosf** [micheleg/dash-to-dock#1340]
I've searched for similar issues and all are closed and claimed to be fixed.
I am on a fresh install Fedora 33. The extension installed from the official repositories.
I can go to extension's settings through Tweaks, however the extension has never worked since its installation.

**Comment by dunxiii** [comment]
I am also on Fedora 33 and experience the same, I think this is a problem with gnome 3.38 rather than Fedora.

**Comment by kakosf** [comment]
@dunxiii Yes, you are right. I found that the issue is related to bug [1884795](https://bugzilla.redhat.com/show_bug.cgi?id=1884795). The solution is there to the comment 4. Briefly, the problem is solved if you install:
`sudo dnf install libdbusmenu-gtk3`
I can close the issue.

**Comment by youssefshehab73** [comment]
> @dunxiii Yes, you are right. I found that the issue is related to bug [1884795](https://bugzilla.redhat.com/show_bug.cgi?id=1884795). The solution is there to the comment 4. Briefly, the problem is solved if you install:
> `sudo dnf install libdbusmenu-gtk3`
> I can close the issue.

When I run that command on Kali Linux
Sudo: dnf : command not found what can I do?

**Comment by kakosf** [comment]
> > @dunxiii Yes, you are right. I found that the issue is related to bug [1884795](https://bugzilla.redhat.com/show_bug.cgi?id=1884795). The solution is there to the comment 4. Briefly, the problem is solved if you install:
> > `sudo dnf install libdbusmenu-gtk3`
> > I can close the issue.
> 
> When I run that command on Kali Linux
> Sudo: dnf : command not found what can I do?

I believe that in Kali Linux the package manager is `apt`, instead of `dnf`, so I recommend you try to install the package with that.
