### ISSUE TITLE
Minimize toward dock

### ISSUE THREAD

**Issue by d-kaylor** [micheleg/dash-to-dock#135]
This extension is great! I have one aesthetic feature request though. When a window is minimized, the animation moves toward the upper left corner. I place my dock at the bottom and this animation feels wrong to me. I think it would be better if it showed the window moving towards the icon in the dock itself.

**Comment by micheleg** [comment]
This would make sense, I agree.

**Comment by region51** [comment]
Да согласен, минимизироваться должно в иконку.

**Comment by micheleg** [comment]
@region51 !? Google helped me.

**Comment by sryze** [comment]
:+1:

**Comment by demetrislambrou123** [comment]
yeah this feature and a show to desktop icon would make this extension awesome

**Comment by micheleg** [comment]
There are two experimental branches, minimize_animation and minimize_animation-3.14 for 3.16 and 3.14 respectively, with a tentative implementation of this feature. I would appreciate if you could test it and provide feedback.

**Comment by region51** [comment]
@micheleg ,minimize_animation-3.14 normal, no problem
![test](https://cloud.githubusercontent.com/assets/11947263/7239368/13b63d5a-e7b2-11e4-9c1b-436ce2c9fc9a.gif)

**Comment by bendem** [comment]
Can confirm `minimize_animation-3.14` works fine. Even with 2 screens.

**Comment by micheleg** [comment]
Merged into master (be8e9412fd4ce65c610770354bfe377954e7c365) and into the gnome-3.4 branch (ccdf1a873d733ee7ba89232c8aab104b4dd9a595).
