### ISSUE TITLE
dash to dock flickering gnome 3.38

### ISSUE THREAD

**Issue by Tuxino88** [micheleg/dash-to-dock#1359]
**Gnome-Shell** 3.38.2 , **Mutter** version 3.38.2 , running on Wayland.

![WhatsApp-Video-2020-12-08-at-15 48 19](https://user-images.githubusercontent.com/75674245/101499115-2e8ad100-396d-11eb-87d4-9754af0ab096.gif)

**Comment by moshiur-raj** [comment]
facing the same problem. I'm on gnome 3.38.2 in archlinux.

**Comment by tetsuo76** [comment]
Same issue on Fedora 33 + GNOME 3.38.2 + X11

**Comment by chenhongqiao** [comment]
Also facing the same issue, running GNOME 3.38.2 on X11.

**Comment by svenoaks** [comment]
Same on Fedora 33 with Wayland

**Comment by GaVenga** [comment]
Not on manjaro gnome 3.38.2 / HDR-screen

**Comment by skaldek** [comment]
Same issue. Arch + gnome 3.38.2 on X11

**Comment by MaxBMic** [comment]
I confirm the bug with Fedora 33 - Gnome 3.38.2 - Wayland or X11

**Comment by desdevol** [comment]
Same issue on Manjaro Gnome 3.38.2 Wayland

**Comment by ismaail** [comment]
@skaldek thanks for the [workaround](https://github.com/skaldek/dash-to-dock/commit/f50d3d88beeb635be08751d0b555231e4ecb4d0f)

**Comment by moshiur-raj** [comment]
@skaldek thanks.

**Comment by DenDeline** [comment]
@skaldek thank you

**Comment by pixel1138** [comment]
@skaldek Thank you! [Workaround](https://github.com/skaldek/dash-to-dock/commit/f50d3d88beeb635be08751d0b555231e4ecb4d0f) confirmed fixes the issue on Manjaro 20.2.1 with Gnome 3.38.2.

**Comment by raffaem** [comment]
Confirm that PR #1361 fixes the issue on Ubuntu 20.10 with GNOME 3.38.3

**Comment by vanvugt** [comment]
Downstream Ubuntu bug: https://launchpad.net/bugs/1919972

**Comment by samueluy** [comment]
working with 20.10

**Comment by newinnov** [comment]
Hi, Same issue on Fedora 33 (Wayland) Gnome 3.38.5, 
but above comments says it was working with ubuntu, may be not in fedora...

**Comment by sergiotca** [comment]
Hi guys, reading through the comments I see this issue has apparently already been fixed downstream and I assume it was (or will be) merge in new versions of the Dash to dock extension (#1361).

Unfortunately I am still experiencing this issue under v69 of the extension. 
Has a new version already been release with this fix or how can I get it? 

I am sorry if this is a dumb question, I'm kind of a newbie.
BTW, I'm using Ubuntu 21.04, Gnome 3.38.5 and X11.

**Comment by vanvugt** [comment]
This bug was fixed *upstream* fixed in #1361 but I have seen it happen a couple of times since then. So not fully fixed. Please open a new bug to track the issue with details of the affected package versions.

An alternate fix #1369 was also proposed but never landed so maybe that will be useful.
