### ISSUE TITLE
Show Applications animations issue

### ISSUE THREAD

**Issue by demetrislambrou123** [micheleg/dash-to-dock#136]
It seems that when having the workspaces to static and only 1 (in essence disabling the workspaces) dash to dock does not show any animations either when toggling on or off the "Show Applications" button.

Furthermore when enabling workspaces only when toggling on the "Show Applications" animations appears. The off animation does not appear.

Might not be a priority or an issue but thought of mentioning it.

**Comment by micheleg** [comment]
Yes. I can reproduce it. Quite a strange effect, I will investigate. Sometimes minor annoyances hide bigger problem... Thanks for the info.

**Comment by demetrislambrou123** [comment]
A great. Thanks for the quick response. Awesome extension just donated keep up the good work :)

**Comment by micheleg** [comment]
I think I solved the issue in the bug_singleworkspace. Could you confirm it works now?

**Comment by demetrislambrou123** [comment]
yes now it works but the show applications "off" animation is not working even with static or dynamic workspaces. Of course both animations works if you toggle on and off the show applications button from activities overview but toggling off the show applications button outside the activities overview is not. I hope you understand what I mean ;p

**Comment by micheleg** [comment]
If I correctly undestand: 
1. With 1 static workspace, i.e. no workspaces, the on animation was never shown, non even from inside the overview (apart for the first time in a session maybe)
2. With any configurations, the off animation is not shown when exiting directly to the desktop view.
This was before these patches. These patches should have put the 1 static workspace on par with the multiple workspace situations, solving problem 1,

What's still missing  - I didn't get this - is a solution  for problem 2. Did I understand correctly?

**Comment by demetrislambrou123** [comment]
yes exactly solution for problem 2. Problem 1 is solved although now that I notice before the patch 1 static workspace (no workspaces) inside activities overview animation off was working (animation on was not).

**Comment by micheleg** [comment]
problem 2 should be solved too now in the same branch

**Comment by demetrislambrou123** [comment]
aye sir it works perfectly know. Thanks a lot now it is perfect :)

**Comment by micheleg** [comment]
Merged into master. Closed by 9e4353bd7..f39ed32.
