### ISSUE TITLE
Bug: dock no longer shows on mouse hover

### ISSUE THREAD

**Issue by stderr-to-devnull** [micheleg/dash-to-dock#1382]
Distro: POP_#$*(@#*#$!OS 20.10
Gnome: 3.38.2

I had a Volume Mixer Gnome extension update and, as always with any other Gnme extension, after installing, it showed with error. The fix is to restart with ALT+F2 and type r because Gnome and generally because Linux Desktop.

After I did that, the dock refuses to show on mouse hover, I quadruple-checked the extension settings (not normal but this is Linux Desktop magic experience we are talking about), all settings are as I left them.

As this is an ACTUAL PRODUCTION LAPTOP, not a Linux enthusiast/hobbyist/experimentalist/distro hopper's machine, I actually TRY to do my work (as in MY ACTUAL JOB) on it. So just rebooting it is not a solution.

Not sure if it's the extension's fault, Gnome's fault, the distro's fault, the kernel's fault or our lord and savior's Jesus fault. Maybe it's my fault for insisting on using any Linux Desktop distro that actually works (tried them all at this point to different degrees of facepalm inducing and crippling bugs).

**Comment by tocomo** [comment]
Please open a terminal and run `journalctl -f`  while restarting gnome-shell with. A lot of errors will show up to support us with fixing issues.

**Comment by ewlsh** [comment]
Please try to be respectful in your bug reports, we're all volunteers here. Extension upgrades require at least a Shell restart because of the way they are structured/modify the Shell.
