### ISSUE TITLE
Add translation.

### ISSUE THREAD

**Issue by region51** [micheleg/dash-to-dock#140]
Add  Russian translation.
Добавьте Русский перевод.

**Comment by micheleg** [comment]
You can help providing russian translaton , few instructions here:
http://micheleg.github.io/dash-to-dock/localization.html
I can't really do it by myself.

**Comment by vantu5z** [comment]
Instruction links to "pot" file in "po" dir, but it missing. I use another translation to make Russian "po" file. And make a pull request #139 .

**Comment by region51** [comment]
Thank you very much, screenshot http://i.imgur.com/vxf96Mk.png

**Comment by vantu5z** [comment]
Look fine, i think.

**Comment by region51** [comment]
@vantu5z , A good translation, can use it.
@micheleg, When to add?

Forgive me for my bad English.  Google Translate helped me.

**Comment by micheleg** [comment]
Pull request #140 has been merged.  @vantu5z: regarding the missing  .pot file, it get generated by running <code>make potfile</code>, as per linked instructions. If not, some dependencies are missing (gettext).

**Comment by vantu5z** [comment]
Figured out how to make .pot file (command must be run at 'dash-to-dock' dir, and not in 'po' dir) and update some strings. #145

**Comment by region51** [comment]
@vantu5z " command must be run at 'dash-to-dock' dir "
Yes, that is correct.

**Comment by region51** [comment]
add in ru.po
```
#: prefs.js:636
msgid "About"
msgstr "О программе"
```

![2015-03-13 15 18 19](https://cloud.githubusercontent.com/assets/10940138/6638198/725dc742-c994-11e4-840f-ce403de5bf35.png)

**Comment by micheleg** [comment]
Thanks, marged.  3ed890cf22d
