### ISSUE TITLE
dash stoped exentending to top of display

### ISSUE THREAD

**Issue by Jhackler** [micheleg/dash-to-dock#1403]
On arch linux today the dash suddenly added a gap to top of screen (toggling extend to entire screen on and off does nothing)  
![Screenshot from 2021-03-29 11-24-51](https://user-images.githubusercontent.com/7755152/112868967-443e1680-9082-11eb-9e37-64c26b7b6aef.png)

**Comment by Jhackler** [comment]
ignore gap above the panel failed to crop out top monitor

**Comment by vanvugt** [comment]
It looks like you might have received a buggy mutter update.

**Comment by Jhackler** [comment]
The top panel is fine I just screen caped part of my third monitor above it well panel is still usable guess I'll just wait for problem to either get worse or go away lol

**Comment by Jhackler** [comment]
seems to have been related to gnome 40 bits as arch was rolling different parts out piece by piece lol.
