### ISSUE TITLE
Workspaces are shown briefly when opening the app drawer

### ISSUE THREAD

**Issue by ampetrosillo** [micheleg/dash-to-dock#141]
Even when not in the Overview, if you open the app drawer you'll see the workspaces showing up on the right for a split second and then disappearing again. If the app drawer is opened in the normal view (ie. not in the overview) the workspace display should be entirely bypassed.

**Comment by micheleg** [comment]
This might have been already fixed in current master. I reworked the way I trigger animations. Would you mind testing it?

**Comment by ampetrosillo** [comment]
I've tried installing the current master. I've had a few errors though.

$ make
glib-compile-schemas ./schemas/
msgfmt -c po/de.po -o po/de.mo
msgfmt -c po/ja.po -o po/ja.mo
msgfmt -c po/hu.po -o po/hu.mo
msgfmt -c po/pl.po -o po/pl.mo
msgfmt -c po/fr.po -o po/fr.mo
po/fr.po:7: warning: header field 'PO-Revision-Date' still has the initial default value
po/fr.po:7: warning: header field 'Language-Team' still has the initial default value
msgfmt -c po/cs.po -o po/cs.mo
msgfmt -c po/pt_BR.po -o po/pt_BR.mo
po/pt_BR.po:7: warning: header field 'PO-Revision-Date' still has the initial default value
po/pt_BR.po:7: warning: header field 'Language-Team' still has the initial default value
msgfmt -c po/pt.po -o po/pt.mo
po/pt.po:7: warning: header field 'PO-Revision-Date' still has the initial default value
po/pt.po:7: warning: header field 'Language-Team' still has the initial default value
msgfmt -c po/zh_CN.po -o po/zh_CN.mo

Then, after restarting the Shell, I get an "Error loading extension", and the following when I try opening the preferences window:

GLib.FileError: Failed to open file '/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  getSettings@/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/convenience.js:66
  WorkspaceSettingsWidget<._init@/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:27
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  buildPrefsWidget@/home/adriano/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:655
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:96
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1

**Comment by ampetrosillo** [comment]
Oh, I've done ```make && make install``` again and now everything's fine. The animation is fixed. Thank you.

**Comment by micheleg** [comment]
Perfect.
