### ISSUE TITLE
empty space in panel mode

### ISSUE THREAD

**Issue by muhajirmuhajir** [micheleg/dash-to-dock#1411]
When switching to panel mode and dock position in the right, the dock does not fully extend to the screen edge.
![Screenshot-2021-04-11-07:09:21](https://user-images.githubusercontent.com/44341915/114287188-9d04aa80-9a97-11eb-8121-a204ec02c017.png)

**Comment by kerhong** [comment]
I have the same issue and #1412 fixes it for me

**Comment by raknos13** [comment]
Yes #1412 fixes it for me as well.
Adding the line `margin-top: 0px;` in `/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css` fixes this issue.

**Comment by jo3fis** [comment]
#1412  also works for me although I had the edit stylesheet.css in the below location for it to take effect. 

`~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com`

**Comment by TROMsite** [comment]
Same. That fixes it. Will this be pushed upstream?

**Comment by 0MazaHacka0** [comment]
The same. Works for me

**Comment by 3v1n0** [comment]
I think this is fixed in current git, please re-open if needed.
