### ISSUE TITLE
Dash to Dock Error | Gnome 40 | Fedora 34 | Wayland

### ISSUE THREAD

**Issue by ChesterNut999** [micheleg/dash-to-dock#1419]
Hi friends,
Can anyone help? 

That is the error:
------------------------------------------------------------------------------------------

Gtk.BuilderError: /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

------------------------------------------------------------------------------------------
Thanks!

**Comment by ewlsh** [comment]
Dash to Dock doesn't support 40 yet.

See #1358 and #1402.

**Comment by ChesterNut999** [comment]
> Dash to Dock doesn't support 40 yet.
> 
> See #1358 and #1402.

Hi @ewlsh . Thanks for the answer! I'm from Brazil.

Oww ... It's sad, but I see a lot of fork from the original project and I'm in doubt which one should work better.
I installed your version and it worked. It has some bugs but it is still excellent.

Att,
ChesterNut999

**Comment by didierga** [comment]
To have a temporary solution for gnome 40 see https://github.com/micheleg/dash-to-dock/pull/1402#issuecomment-814937395

**Comment by ChesterNut999** [comment]
> As Fedora 34 is now release candidate, to have a temporary solution for gnome 40 I followed this tip: [#1402 (comment)](https://github.com/micheleg/dash-to-dock/pull/1402#issuecomment-814937395)
> 
> It works but we have to wait for an official release for gnome 40.

@didierga ,

You're right! 
I'm following the tip! Thanks.

Att,
ChesterNut999

**Comment by ChesterNut999** [comment]
Follow the tip [#1402 ](url).
