### ISSUE TITLE
Label text alignment for app folders is buggy when changing dock position

### ISSUE THREAD

**Issue by ampetrosillo** [micheleg/dash-to-dock#142]
Moving the dock to the bottom or to the right "confuses" the Shell, and causes the label text for app folders to be left aligned instead of centered. Restoring the dock on the left doesn't fix the issue, requiring an X (or a Shell) reboot to fix.

**Comment by micheleg** [comment]
I can't reproduce the problem. 'm not sure I understood. Could you provide a screenshot?

**Comment by ampetrosillo** [comment]
After installing the latest master the issue doesn't arise anymore. I was using the version provided on [extensions.gnome.org].

**Comment by micheleg** [comment]
Perfect, I still haven't released a new version with the fix. It's not clear to me which commit fixed the issue...
