### ISSUE TITLE
Bug: The dock is shown outside of the activities view even when "Intelligent Autohide" enabled and "Intelligent Autohide->Autohide" disabled.

### ISSUE THREAD

**Issue by LorienLV** [micheleg/dash-to-dock#1421]
If you enable **Intelligent Autohide** but disable **Intelligent Autohide-> Autohide** (inside the **Intelligent Autohide** settings), the dock is shown when hovering the mouse over the edge of the screen.

![Intelligent Autohide enabled](https://user-images.githubusercontent.com/31626586/115531291-e5407b80-a294-11eb-8009-87b5f841b4e5.png)
![Autohide disabled dock shown](https://user-images.githubusercontent.com/31626586/115531436-11f49300-a295-11eb-85b2-873e2edd3be4.png)

**Comment by micheleg** [comment]
Which shell version is this? Is is an existing bug or a regression in the port to gnome-40? I don't seem to be able to reproduce the problem in GNOME 40.

**Comment by LorienLV** [comment]
I am using GNOME Shell 3.36.9, so this is an existing bug.
