### ISSUE TITLE
"This extension is incompatible with this GNOME-Version"

### ISSUE THREAD

**Issue by matteodev8** [micheleg/dash-to-dock#1422]
Hi! After installing dash-to-dock on GNOME 40.1, I still get the Error message in the extensions program.

**Comment by ewlsh** [comment]
Dash to Dock doesn't support 40 yet.

See #1358 and #1402.

**Comment by scva39** [comment]
> Dash to Dock doesn't support 40 yet.
> 
> See #1358 and #1402.

Thank U for trying to add support for latest gnome with GTK4. Gnome Dock still unuseful for me.
