### ISSUE TITLE
Merge "quit" option in dash with Dash-to-Dock

### ISSUE THREAD

**Issue by ampetrosillo** [micheleg/dash-to-dock#143]
I've seen you have another extension adding the "Quit" option for Dash icons. It would seem nice to have it included in the Dash-to-Dock extension. I'd install it separately but it only supports up to GNOME 3.10. It would be nice to add a "Force Quit" option too, as sometimes GNOME doesn't notice application locks for some reason.

**Comment by micheleg** [comment]
I have a fork of that extension, running correctly on my 3.14 system: https://github.com/micheleg/shell-extension-quitfromdash.

Merging it has been in my todo list for a while, I'll think of it.

**Comment by gevera** [comment]
I second ampetrosillo. It is the only "killer" feature that is missing in Dash-to-Dock

**Comment by micheleg** [comment]
Have a look at the quitfromdash branch, I tried to merge the quitfromdash functionality. Please let me know if it's working as expected.

**Comment by ampetrosillo** [comment]
It's working perfectly. Thumbs up!

**Comment by micheleg** [comment]
Merged into master: 2833fce53af458ee13c1b4593305262e5b698dda
