### ISSUE TITLE
Minimize from dock icon

### ISSUE THREAD

**Issue by apicgg** [micheleg/dash-to-dock#1439]
The dock works great with pop os. But users should be able to minimize the opened windows from the dock icons by clicking on the icons just like in windows. Guess it adds more functionality to the users users.

**Comment by linoshkm** [comment]
![Screenshot from 2021-05-29 11-38-11](https://user-images.githubusercontent.com/67228783/120059958-651aec00-c072-11eb-8832-489fb62f0966.png)

None of these options help?
