### ISSUE TITLE
all of the apps disapper when i turn on disks

### ISSUE THREAD

**Issue by rx10** [micheleg/dash-to-dock#1441]
when i turn on the show mounted drives option, the applications disappear. i am running gnome 40 on fedora.
i have previously used this extension on the same configuration and it worked perfectly. i don't understand why this happened.

**Comment by linoshkm** [comment]
Duplicate of #1239
Try this solution  #1239 (comment)

**Comment by 3v1n0** [comment]
Duplicate of #1239
