### ISSUE TITLE
Dock shows up even when screen is locked

### ISSUE THREAD

**Issue by erlisdhima** [micheleg/dash-to-dock#1451]
This is happening on Ubuntu 20.04. When the screen is locked after some time of inactivity, the dock still appears.
I can click on it, but nothing happens until I unlock my screen.

Hope this makes sense!

**Comment by DuttaAB-dev** [comment]
Happens inn ubuntu 21.04 aswell

**Comment by yinzixie** [comment]
Same issue on 20.04, and after unlocking the screen you will get two dockers on your screen.

**Comment by focamacho** [comment]
Can confirm this is happening in 20.04 when you lock the screen while hovering the dock.
After unlocking the screen, the dock is duplicated.

**Comment by vanvugt** [comment]
I haven't seen this reported in any recent versions of Ubuntu so let's assume it's fixed. If you still have issues then please run:
```
ubuntu-bug gnome-shell-extension-ubuntu-dock
```

**Comment by vanvugt** [comment]
It was also previously tracked in:
 * https://github.com/micheleg/dash-to-dock/issues/649
 * https://github.com/micheleg/dash-to-dock/issues/641
 * https://launchpad.net/bugs/1769383
 * https://launchpad.net/bugs/1716982
