### ISSUE TITLE
Bug on Gnome 40 (Fedora 34): grey square gap

### ISSUE THREAD

**Issue by Altonss** [micheleg/dash-to-dock#1453]
![image](https://user-images.githubusercontent.com/66519591/120517852-303fc980-c3d1-11eb-8189-7d6cd5b77050.png)

**Comment by dbasinge** [comment]
Noticing the same.

**Comment by Altonss** [comment]
@dbasinge Are you also on Fedora 34?

**Comment by dbasinge** [comment]
Yes, Fedora 34 using Wayland,

**Comment by theEndurance-del** [comment]
Using this on ArchLinux and a similar behavior is present when applying any shell theme(Using GNOME on X.org)

**Comment by ewlsh** [comment]
This should be fixed now.
