### ISSUE TITLE
Description of the application close to the dock

### ISSUE THREAD

**Issue by Linuxoid85** [micheleg/dash-to-dock#1456]
The name of the app next to the dock. Without dash to dock, there is no.
[Dash To Dock](https://sun9-69.userapi.com/impg/W7pb_QbJ79960F9bhCju0KaUS3azNQ3U0-Cl2A/AclucnZvah8.jpg?size=140x77&quality=96&sign=3a23016e7aa26de1dd27c950fcc843be&type=album).
[Without this](https://sun9-19.userapi.com/impg/4f3xwg1wb3GU-UCf8YpPEvMk2czWAwtYOlyJ8w/ysJno30hGVY.jpg?size=109x128&quality=96&sign=83722fca65d47d6fdf44fca5f4b7e3a5&type=album)

**Comment by ewlsh** [comment]
Include photos within the issue itself, I don't view unknown links.
