### ISSUE TITLE
Problem with Installation when attempting to make

### ISSUE THREAD

**Issue by santaman217** [micheleg/dash-to-dock#1457]
Below is the error I keeo getting:

msgfmt -c po/ar.po -o po/ar.mo
make: msgfmt: No such file or directory
make: *** [Makefile:54: po/ar.mo] Error 127

I may just be extremely silly as I am struggling to find anyone with the same problem.

Thanks!!!

**Comment by Avii3301** [comment]
How'd you resolve this? I'm getting the same error

**Comment by gupta-shrinath** [comment]
sudo apt install gettext
Type this in the terminal and you are good to go
