### ISSUE TITLE
dash to dock (red button) not able to turn on !

### ISSUE THREAD

**Issue by thalalmlp** [micheleg/dash-to-dock#1459]
Gtk.BuilderError: /home/tkadmin/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/home/tkadmin/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/home/tkadmin/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:878:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by LlamaSauce** [comment]
Download this zip : https://github.com/ewlsh/dash-to-dock/tree/ewlsh/gnome-40
Extract the zip and cd into the dash-to-dock directory

_Make sure you have sassc installed, if on Fedora you can use_ **sudo dnf install sassc**

run these after sassc is installed

make
make install

Alt+F2
type r and hit enter

You should be able to enable the extension

**Comment by micheleg** [comment]
Will be fixed once #1402 is merged and release.
