### ISSUE TITLE
Which exec does dash to dack use to open apps?

### ISSUE THREAD

**Issue by SanpuiRonak** [micheleg/dash-to-dock#1464]
I wanted to know which exec does dash to dock use for opening apps
I use a custom exec for google chrome
![image](https://user-images.githubusercontent.com/54654681/123384518-21a09880-d5b2-11eb-883b-50230397f366.png)

which makes chrome use dark mode[when opened form app drawer]

![image](https://user-images.githubusercontent.com/54654681/123384998-b3100a80-d5b2-11eb-8100-460e1ed16674.png)

but on starting from dash it just "ignores" all of my flags

![image](https://user-images.githubusercontent.com/54654681/123384794-72b08c80-d5b2-11eb-8c1c-0376f854ee67.png)

**Comment by ewlsh** [comment]
Dash to Dock uses the same logic here as GNOME Shell. It should use the default `exec`, generally.
