### ISSUE TITLE
Error when trying to update environment items

### ISSUE THREAD

**Issue by KulkovN** [micheleg/dash-to-dock#1467]
Error when trying to update environment items: "The following packages have unmet dependencies:
gnome-shell-extension-cosmic-dock: Breaks: gnome-shell-extension-ubuntu-dock but 69ubuntu1pop0 ~ 1624393749 ~ 21.04 ~ 00aed10 is to be installed " 
(OS - Pop_OS 21.04)

**Comment by ewlsh** [comment]
Consult your distro packagers.
