### ISSUE TITLE
intellihide is crashing other extension

### ISSUE THREAD

**Issue by rudrab** [micheleg/dash-to-dock#1470]
Hi,
The latest  gnome 40 branch is causing error to other extension like hide-top-bar.
I have made hard reset to `Mon May 3 01:09:51 2021 -0700    Initial fix for dynamic icon sizing...`  commit and all is working fine. Without that reset(I havnt checed later commits),  hide-top-bar is crashing, 

Please ask me if you need some log (tell me how to produce that).

**Comment by ewlsh** [comment]
It is entirely possible we'll conflict with another extension making large changes, you'd need to provide logs of the crash for us to start investigating.

```
journalctl --since "X seconds ago"
```

will produce basic logs when it happens.

Feel free to open with more information...

* Logs
* Distro/GNOME Shell version
* Dash to Dock version
