### ISSUE TITLE
When would D2D extension for Gnome 40 arrive in extensions.gnome.org?

### ISSUE THREAD

**Issue by chdslv** [micheleg/dash-to-dock#1472]
When would D2D extension for Gnome 40 arrive in extensions.gnome.org?
Using[ this](https://github.com/ewlsh/dash-to-dock/tree/ewlsh/gnome-40) branch atm.
@ewlsh

**Comment by ewlsh** [comment]
Soon-ish. Currently pruning the issue tracker.
