### ISSUE TITLE
Manjaro gnome 40.2.0 on wayland --- error on open settings dash-to-dock

### ISSUE THREAD

**Issue by BoogerMan2103** [micheleg/dash-to-dock#1475]
After packages update starts to popup this error
__________________________________________

The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock
```

Stack trace:
```
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
_bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by salazarbarrera** [comment]
Did you compile it from the [ewlsh-ewlsh/gnome-40](https://github.com/micheleg/dash-to-dock/tree/ewlsh-ewlsh/gnome-40) branch? I use Manjaro with X11, so I can't test it myself, but compiling it (using sassc) from that branch, made it usable for me.

[The extension directory I built](https://drive.google.com/file/d/1PXv4h1PqHKm_llKqIWlnSR5RaerdiyWi/view?usp=sharing), but I recommend you try compiling it yourself.

**Comment by tomoqv** [comment]
I get the same problem. The key preview-size-scale is found with gsettings in the terminal and returns the following value:
```
~ >>>  gsettings get org.gnome.shell.extensions.dash-to-dock preview-size-scale
0.0
```
I tried to change it to 1.0, but opening the settings still returns the same error. I have no idea which values are accepted by the extension.

**Comment by tomoqv** [comment]
```
<key type="d" name="preview-size-scale">
<default>0</default>
<summary>Preview size scale</summary>
<description>
Set the allowed maximum dash preview size scale. Allowed range: 0,00..1,00.
</description>
</key>
```

**Comment by salazarbarrera** [comment]
I have the same schema with the same value with an updated Manjaro using X11.

**Comment by tomoqv** [comment]
I have 40.3

**Comment by netronicus** [comment]
Same here on manjaro with gnome 40.2.0, updated yesterday ann broken after that
![image](https://user-images.githubusercontent.com/12499556/125638510-5cd0867b-331c-4852-af2f-6fe93e139a02.png)

**Comment by netronicus** [comment]
compiling branch for gnome 40 listed on AUR didn't solve it

**Comment by salazarbarrera** [comment]
You probably already tried this, but just in case, have you tried doing a fresh install? Removing the extension, reloading the shell (either by rebooting or alt+f2 > "r" ), and then building and installing the extension from "ewlsh-ewlsh/gnome-40"?

Apparently there are people using X [who are facing the same problem](https://github.com/micheleg/dash-to-dock/issues/1477), thus I don't know what is different from my machine. Maybe this can help you all to find what is different:

```
$ neofetch // I removed the eye candy

OS: Manjaro Linux x86_64 
Host: Aspire A315-53 V2.02 
Kernel: 5.10.49-1-MANJARO 
Packages: 1846 (pacman), 9 (flatpak), 11 (snap) 
Shell: bash 5.1.8 
Resolution: 1366x768 
DE: GNOME 
WM: Mutter 
WM Theme: Matcha-dark-azul 
Theme: Matcha-dark-azul [GTK2/3] 
Icons: Papirus [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-8250U (8) @ 1.600GHz 
GPU: Intel UHD Graphics 620 
Memory: 5000MiB / 11849MiB
```
```
$ cat /etc/*-release

Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.1.0
DISTRIB_CODENAME=Pahvo
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
```
$ gnome-shell --version
GNOME Shell 40.3
```
```
$ X -version 

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: Linux Manjaro Linux
Current Operating System: Linux T-1000 5.10.49-1-MANJARO #1 SMP PREEMPT Sun Jul 11 12:59:43 UTC 2021 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64 root=UUID=5a67b75c-4761-4ab6-bcab-9c712f0a63ef rw quiet apparmor=1 security=apparmor udev.log_priority=3
Build Date: 13 April 2021  04:11:08PM
 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

![image](https://user-images.githubusercontent.com/68821455/125653014-cc80cd9a-122e-4b43-b657-80cb6e99acc3.png)

**Comment by netronicus** [comment]
> You probably already tried this, but just in case, have you tried doing a fresh install? Removing the extension, reloading the shell (either by rebooting or alt+f2 > "r" ), and then building and installing the extension from "ewlsh-ewlsh/gnome-40"?
> 
> Apparently there are people using X [who are facing the same problem](https://github.com/micheleg/dash-to-dock/issues/1477), thus I don't know what is different from my machine. Maybe this can help you all to find what is different:
> 
> ```
> $ neofetch // I removed the eye candy
> 
> OS: Manjaro Linux x86_64 
> Host: Aspire A315-53 V2.02 
> Kernel: 5.10.49-1-MANJARO 
> Packages: 1846 (pacman), 9 (flatpak), 11 (snap) 
> Shell: bash 5.1.8 
> Resolution: 1366x768 
> DE: GNOME 
> WM: Mutter 
> WM Theme: Matcha-dark-azul 
> Theme: Matcha-dark-azul [GTK2/3] 
> Icons: Papirus [GTK2/3] 
> Terminal: gnome-terminal 
> CPU: Intel i5-8250U (8) @ 1.600GHz 
> GPU: Intel UHD Graphics 620 
> Memory: 5000MiB / 11849MiB
> ```
> 
> ```
> $ cat /etc/*-release
> 
> Manjaro Linux
> DISTRIB_ID=ManjaroLinux
> DISTRIB_RELEASE=21.1.0
> DISTRIB_CODENAME=Pahvo
> DISTRIB_DESCRIPTION="Manjaro Linux"
> Manjaro Linux
> NAME="Manjaro Linux"
> ID=manjaro
> ID_LIKE=arch
> BUILD_ID=rolling
> PRETTY_NAME="Manjaro Linux"
> ANSI_COLOR="32;1;24;144;200"
> HOME_URL="https://manjaro.org/"
> DOCUMENTATION_URL="https://wiki.manjaro.org/"
> SUPPORT_URL="https://manjaro.org/"
> BUG_REPORT_URL="https://bugs.manjaro.org/"
> LOGO=manjarolinux
> ```
> 
> ```
> $ gnome-shell --version
> GNOME Shell 40.3
> ```
> 
> ```
> $ X -version 
> 
> X.Org X Server 1.20.11
> X Protocol Version 11, Revision 0
> Build Operating System: Linux Manjaro Linux
> Current Operating System: Linux T-1000 5.10.49-1-MANJARO #1 SMP PREEMPT Sun Jul 11 12:59:43 UTC 2021 x86_64
> Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64 root=UUID=5a67b75c-4761-4ab6-bcab-9c712f0a63ef rw quiet apparmor=1 security=apparmor udev.log_priority=3
> Build Date: 13 April 2021  04:11:08PM
>  
> Current version of pixman: 0.40.0
> 	Before reporting problems, check http://wiki.x.org
> 	to make sure that you have the latest version.
> ```
> 
> ![image](https://user-images.githubusercontent.com/68821455/125653014-cc80cd9a-122e-4b43-b657-80cb6e99acc3.png)

If i try to uninstall the extension from Software, this request to uninstall manjaro-gnome-assets, I don't want that to happen, also tried to install it manually buen the same issue is present, I think I will wait for an update for dash to dock extension, meanwhile I'm using Dash to panel :cry:

**Comment by BoogerMan2103** [comment]
>  Edit: I accidentally sent the comment before finishing. The last Manjaro update introduced GNOME Shell 40.3, are you sure you have GNOME Shell 40.2.0?

It is strange but at issue start moment gui show me the 40.2.0, but now gui and neofetch give me 40.3. May be affects updates

![Снимок экрана от 2021-07-14 20-45-00](https://user-images.githubusercontent.com/34261046/125668266-41147307-ac46-48a7-800e-ecc18ed3180f.png)

> You probably already tried this, but just in case, have you tried doing a fresh install? Removing the extension, reloading the shell (either by rebooting or alt+f2 > "r" ), and then building and installing the extension from "ewlsh-ewlsh/gnome-40"?

It is clean install for 2 days, I`m not pro at compiling gnome extensions because of I probably will wait for normal update or turn off / delete dash panel, but problem will be in minimized windows)

**Comment by salazarbarrera** [comment]
@BoogerMan2103 @netronicus  In case you change your mind about trying to build it, here are some instructions:

1. Open the application "Extensions" (or run the '`gnome-extensions-app`' command, which will open it too).
2. Locate "Dash to Dock" on the list. It will probably be deactivated and with an exclamation mark.
3. Press the triangle to the right of switch which toggles the extension.
4. Press the button saying "Remove" (or something similar, mine is in Spanish). Confirm.
5. Reboot (probably overkill, but that way we make sure everything is "clean").
6. On your preferred directory, run `$ git clone https://github.com/micheleg/dash-to-dock.git`.
7. `$ cd dash-to-dock`
8. `$ git checkout ewlsh-ewlsh/gnome-40`
9. `$ git pull`
10. On the same terminal, install sassc ( `# pamac install sassc` or `$ sudo pamac install sassc` ).
11. Temporarily set the variable SASS ( `$ export SASS=sassc` ).
12. `$ make`
13. `$ make install`

That will install the extension in your current user in `/home/$USER/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com`

If all of that it doesn't work, sadly I don't know what will.

**Comment by netronicus** [comment]
> @BoogerMan2103 @netronicus In case you change your mind about trying to build it, here are some instructions:
> 
> 1. Open the application "Extensions" (or run the '`gnome-extensions-app`' command, which will open it too).
> 2. Locate "Dash to Dock" on the list. It may appear deactivated and with an exclamation mark (or not, given BoogerMan2103's screenshot).
> 3. Press the triangle to the right of switch which toggles the extension.
> 4. Press the button saying "Remove" (or something similar, mine is in Spanish). Confirm.
> 5. Reboot (probably overkill, but that way we make sure everything is "clean").
> 6. On your preferred directory, run `$ git clone https://github.com/micheleg/dash-to-dock.git`.
> 7. `$ cd dash-to-dock`
> 8. `$ git checkout ewlsh-ewlsh/gnome-40`
> 9. `$ git pull`
> 10. On the same terminal, install sassc ( `# pamac install sassc` or `$ sudo pamac install sassc` ).
> 11. Temporarily set the variable SASS ( `$ export SASS=sassc` ).
> 12. `$ make`
> 13. `$ make install`
> 
> That will install the extension in your current user in `/home/$USER/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com`
> 
> If all of that it doesn't work, sadly I don't know what will.

It can't be disabled that way :cry: 
![image](https://user-images.githubusercontent.com/12499556/125677435-0a31d4cc-c7d6-41c1-88f1-e0bf729270ca.png)

**Comment by netronicus** [comment]
Found a solution

`
cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/
sudo mv schemas schemas-bak
`

**Comment by salazarbarrera** [comment]
> Found a solution
> 
> `cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/`
> `sudo mv schemas schemas-bak`

ooooh, that makes sense. So it was a conflict with the  version included with the system. I'm not sure why my computer successfully ignores the existence of `/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com` and favours the one inside in my user's home, but it does that. I'm glad you found a workaround.

**Comment by TROMsite** [comment]
cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/
sudo mv schemas schemas-bak

Works for me too! Awesome!

**Comment by tomoqv** [comment]
> Found a solution
> 
> `cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/`
> `sudo mv schemas schemas-bak`

Works, thanks!

**Comment by BoogerMan2103** [comment]
> Found a solution
> 
> `cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/`
> `sudo mv schemas schemas-bak`

Amazing solution, works, thanks!
