### ISSUE TITLE
How to pin my folder/file like in windows 10?

### ISSUE THREAD

**Issue by nazar2sfive** [micheleg/dash-to-dock#1479]
![screenshot (1)](https://user-images.githubusercontent.com/12841320/125617901-9cbdcc8c-29db-46b1-98f9-2994c3d5b6cf.jpg)

**Comment by ewlsh** [comment]
You can use a menu modifying extension/app to handle this behavior, but I believe this is out of scope for Dash to Dock (and lacking information)
