### ISSUE TITLE
Expand the 'Customize actions on mouse click' to include middle click to quit and double-click to duplicate (currently undocumented middle click)!!

### ISSUE THREAD

**Issue by yeehaw2015** [micheleg/dash-to-dock#148]
Hi!!

I'm loving and hugely appreciating your awesome dash to dock, thanks for the current active dev't on it! I'm on gnome 3.14 in deb jessie.

A request: I love the 'middle click to close' idea in computing and have used it to close tabs in browsers and as many proggies I can get my hands on, from my early windows days to my OS X transition and now my enlightened times of Linux :). In Windows I would use tools to modify the taskbar (7+ Taskbar tweaker) to bring the 'middle click to close' action to the taskbar too - it was awesome. Of course, windows is different to the gnome/OS X dock, which groups them per application so on windows it would close 'windows' but here clearly it would have to be 'Quit'.

I see the current behavior for middle click (I'm using v40 from e.g.o), is to duplicate the window ('new instance'), not close.

Might you consider expanding the 'Customize actions on mouse click' area to include a drop-down selection of options for middle click (offering the same sort of offering of options as the current single left click one)? [I guess there's no need to introduce code headache in not having any overlap - user can just have one click action mapped to whatever in the list so it can be easy!] 

For me I'd love middle click to close, and I'm using left click to 'Cycle through application windows' (which is AWESOME btw!!!), and yeah as mentioned in title, other cool idea, if it's not too buggy of a hassle to implement: how about double click as a customiazble action too (and in my case, I'd assign the current 'New Window' action to it, where middle click is currently)?

Oh and if we really want to go to town, how about a fourth action to map to the same master list of actions as the three above - to left double click? 

Thanks micheleg, this is the best extension ever!

~

Also, I have another idea - but maybe it should be a separate request thread: with a customizable timeout setting (from 0.whatever seconds to say 10 seconds), it would be awesome to extend the idea of 'middle click to close', to hovering the mouse on an app icon, and having the windows expand out from it as thumbnail previews (exactly like the things on the overview), where, of course, selecting a thumbnail box will open that window, but especially in the case of my idea, middle click also can close that individual window! So that way you can add granularity to the 'middle click to quit' action by hovering a little longer, and do a less violent 'close by window at a time' thing instead.

I guess Gnome Shell overview itself has a full overview of all windows anyway (and there's even extensions for that in overview - https://extensions.gnome.org/extension/352/middle-click-to-close-in-overview/) but I guess this is all about just being nice and mouse-y with dock only, which is and feels quicker. :)

And furthermore, window thumbnail hover would bring general awesomeness to the dock in that for not-so power users the dock is more user-friendly/useful and when they hover on an icon it can automatically remind them of the otherwise 'hidden' windows (if this option is selected, of course), so there's that too. Having hover thumbnails would really bring usability awesomeness to the Dock in general :).

Thanks!

**Comment by micheleg** [comment]
I like the middle-to-close pattern and tend to try to close stuff with it as well. Regarding having a more granular settings for the standard clicks and modifications key, this could be done I think, I don't see real technical problem. A bit diffferent is dealing with the double click. Unless the action on the second click complete the first one - close window -> close all windows, it's difficult to have two different actions. Either one has to react to the first click and then if a second arrives "undo" that action or one have to wait  enough to ensure no double click was performed before triggering the event, which would probably make the extension feel unresponsive.

Regarding the windows overview, they have already be suggested in #144. I'm more towards having an "overview" limited to the windows of that application, to be triggered somehow, also in order to allow a better support of drag and drop. I'll take into account your considerations, I still not have a clear plan.

**Comment by franglais125** [comment]
@micheleg I was thinking of working to implement this.
However, before I start I wanted to know:
 - If you actually would want to review/merge something like this. You might just not want to overpopulate the options (or do it yourself with your own style/take the time to think about it)
 - How to go about it on the GUI settings. At the moment the space is a bit limited already in the _Behavior_ tab.

**Comment by micheleg** [comment]
@franglais125 I'm very happy to accept patches improving of the current settings! However, as you anticipate, we need to be careful to not transform the settings GUI in a nightmare to be used and understood.

The first question is: what do we actually want? Do we want to provide all possible combinations of interaction or do we want  a consistent set? We have few desirable actions:

1.b switch/bring forward all application window (the default behaviour, currently incorrectly labelled do nothing)
1.b switch/bring forward next window of the application (i.e "cycle through windows")
2. launch new instance
3. minimize current window
3.b minimize all windows of the application
4. close current application window
4.b close all windows of the application 

All these actions are somehow implemented in the code, but it might be worth to split the logic from the actions (to be defined in different functions).

We then have multiple possible user interactions:

1. left click
2. right click
3. middle click
3. mouse-wheel scroll

plus modifiers: Alt, Shift, Ctrl. 

However:
* ctrl is already used by the shell for new instance launcher and I would keep it untouched.
* I have no intention to touch right-click behaviour
* dealing with the scroll-wheel imply incompatibilities with the scrolling of the dock

Tentative idea 1:  extend current option with other combinations. In principle only one UI element added to the settings.
* click: 
  - default/new instance/cycle/minimize
*  middle click
  - default/new instance/cycle/minimize
*  shift click
  - default/new instance/cycle/minimize

I would rather find  a more concise way of exposing these settings but this could be a good start. What do you think? Any other idea is welcome.

**Comment by franglais125** [comment]
@micheleg 
Thanks for the quick feedback. All the points you brought up are relevant. I have to say I agree with everything you said.

1) Regarding the various actions/clicks/modifiers, I am fine with your proposal at the end.
However, wouldn't we include an option to "Quit window" or "Quit App"? (Unless that's what it is meant by "default"). Personally I don't use it, but that's what this issue (#148) was requesting. Something like (although it doesn't make much sense to quit with left click):
 - click:
       - default/new instance/cycle/minimize/quit
 - middle click
       - default/new instance/cycle/minimize/quit
 - shift click
       - default/new instance/cycle/minimize/quit

2) Do you think we need a new tab, an "Advanced mode" for clicks, or something else? Adding a new option (namely "Middle click") would take too much vertical space for small screens (or large fonts, etc.). This is how the Behavior tab looks on Gnome-Shell 3.20 1366x768 13.3 screen:
![screenshot from 2016-07-04 18-19-20](https://cloud.githubusercontent.com/assets/19195975/16570543/06100a28-4215-11e6-8035-bfb60c4f125d.png). If using the dock at the bottom, it is already quite difficult to activate the "scrolling on dock" feature. (This is what I get for using a small laptop, heh).

3) I think you might get people asking for "hey, can I have Shift+Middle click for option xyz". I was tentatively thinking (and this might address point 2 as well) that we could have something like:
 - click:
       - default/new instance/cycle/minimize/quit
 - middle click
       - default/new instance/cycle/minimize/quit

Plus: (Advanced mode or something, with a "gear" like the extra options for intellihide):
 - Shift + click:
       - default/new instance/cycle/minimize/quit
 - Shift + middle click
       - default/new instance/cycle/minimize/quit

I have to say I don't "love" this layout, but it would allow for us to use less space (and possibly add Shift+Middle click).

**Comment by micheleg** [comment]
I definitely would not include the close on click. It does not seems a same option at all. 

For point 2: although adding settings inside settings is far from optimal, it's probably the safest option. I would go for keeping only the customization of the left click in the main panel and moving everything else in an additional advanced window, with the reset to default button as the intellihide. Then we will have plenty of space to layout the options.

**Comment by franglais125** [comment]
Hi @micheleg , I have a first version of this work in this branch: https://github.com/franglais125/dash-to-dock/tree/click_options .
It's a single patch for now [bf6f236e8cd3f9b78c5cd8c24b4db6b4d90dd97d].

Essentially I have:
 - Created a Modal dialog for the Middle-Click (and Shift) options
 - I left the regular Click untouched
 - Expanded the options for Shift+Click, Middle-Click and Shift+Middle-Click to:
    - Do nothing
    - Minimize windows
    - Launch new instance
    - Cycle
    - Quit
 - I tested this code on 3.20 as usual

Since we are already looking at this part of the code... we can maybe rename "Do nothing" to something more meaningful :) (https://github.com/micheleg/dash-to-dock/issues/312).
"Focus app"
"Focus window"
"Bring to front"
"Default"
I'll let you know if I come up with a better suggestion... I didn't change anything for now.

**Comment by franglais125** [comment]
@micheleg 
Due to the work I'm doing for this issue, I have been doing a lot of testing of the different click options.
I also looked in other reported issues for problems people already had with the current behavior, to watch out for potential problems/solve issues if possible.

I'll probably leave a few comments in other (click-related) issues as well!

**Comment by micheleg** [comment]
Good work! For #312 I think rather than default its better to try to describe the action.

**Comment by franglais125** [comment]
In the Keyboard shortcuts, Gnome uses the term "Raise window" in some of the options. Maybe we can use something like that?

**Comment by micheleg** [comment]
Improved click settings now available in master [08bc3629dceaa].

**Comment by zapashcanon** [comment]
@micheleg, this can be closed too I guess. :)

**Comment by micheleg** [comment]
yes.
