### ISSUE TITLE
Dash to dock not working with GNOME Shell 40.3

### ISSUE THREAD

**Issue by muellerti** [micheleg/dash-to-dock#1485]
Manually copying the extensions leads to the following error:

Gtk.BuilderError: /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:13:35 Invalid property: GtkBox.margin_left

Stack trace:
  DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:92:23
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:869:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  

I am using Manjaro Gnome Shell 40.3.

Regards

**Comment by muellerti** [comment]
Tested with dash-to-dock Version 69.

**Comment by calexandru2018** [comment]
Same here although Gnome 40.2

**Comment by davidovitch** [comment]
Gnome 40 is not supported yet but there already is an issue for that (see the #1358, it is even pinned at the top of the page). If you read #1358, you'll see that PR #1402 is preparing Gnome 40 compatibility, but the work is not done yet.

**Comment by ewlsh** [comment]
Duplicate of #1358
