### ISSUE TITLE
Destkop autohide function

### ISSUE THREAD

**Issue by dgikiller** [micheleg/dash-to-dock#149]
Hello, I found very useful your extension but I saw that dock partially overlap desktop icons when there are no windows.
It's possible to add an option that pad the desktop icons when dock is visible or to hide dock by default.

**Comment by micheleg** [comment]
For the overlap with desktop: nope, as far as I know. See issue #17.

You can disable intellihide and keep autohide on. In this way the dock will
be shown only by mouse hovering the edge of the screen. Alternatively you
can keep the dock always visible and fixed.

Unfortunately the desktop icons are not expected to be use in GNOME shell.

**Comment by dgikiller** [comment]
Thank you Michele for your answer, I will disable intellihide as suggested.
