### ISSUE TITLE
Change app launcher icon.

### ISSUE THREAD

**Issue by raymerjacque** [micheleg/dash-to-dock#1494]
Can someone please tell me how to change the app launcher icon in dash to dock ? which icon does the extension link to that i can swop out for my own preferred icon ?

**Comment by theEndurance-del** [comment]
I think it is stored in `<path_to_your_icon_theme>/actions/symbolic/view-app-grid-symbolic.svg` as far as I remember.

**Comment by raymerjacque** [comment]
You are right, altho changing that didnt work for me due to the shell theme, some shell themes changing that icon works, some shell themes not. so a solution for me was to simply change to another shell them and then edit that icon. thank you, hopefully this helps others with the same issue :D

**Comment by theEndurance-del** [comment]
> altho changing that didnt work for me due to the shell theme

which theme was it?

**Comment by raymerjacque** [comment]
I think it was a theme from gnome-look website, cant remember the name as i deleted it, I think it may have been called transparent or something...  ( its the Shell Theme, not GTK Theme ).
