### ISSUE TITLE
dash-to-dock glitches while in auto-hide setting

### ISSUE THREAD

**Issue by speakradmin** [micheleg/dash-to-dock#1497]
Possibly related to https://github.com/micheleg/dash-to-dock/issues/1232

Opening a new issue as it seems the behaviour is different enough that it could be caused by something else

Still getting this on my second monitor when Show on all monitors is enabled. Lowering Animation Duration, Hide Timeout or Pressure Threshold seem to have no effect like it did before.

Interestingly, it only does this when the window on the second monitor is maximised and focused. Unmaximised windows do not seem to trigger the glitching nor do maximised but unfocused windows. It's also very reproducible for me at least whereas in the past I only sometimes got the glitch. Even more interesting, it only seems to happen with certain widows. Specifically Chrome and Microsoft Teams that I have found so far. Will update if I find any others

Fresh install of Ubuntu 21.04 Wayland with a minimal set of apps, themes and extensions.

**Comment by speakradmin** [comment]
Apologies, seems to be a duplicate of https://github.com/micheleg/dash-to-dock/issues/1381

**Comment by ewlsh** [comment]
Closing as duplicate.
