### ISSUE TITLE
Still No Update For GNOME40

### ISSUE THREAD

**Issue by ozbrk** [micheleg/dash-to-dock#1506]
People have figured it out how to get the old version run on the Gnome 40 altough it is not perfect but still no update for the current extention over a year. Is this still maintained?

**Comment by validatedev** [comment]
https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock the ubuntu-dock tree is maintained regularly, and works flawlessly for 40.4.0.

**Comment by keilmillerjr** [comment]
> https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock the ubuntu-dock tree is maintained regularly, and works flawlessly for 40.4.0.

Last commit was 6 weeks ago, but it's 332 commits ahead of master. Whats left on the to-do list before merge to master?

**Comment by ewlsh** [comment]
Duplicate of #1358
