### ISSUE TITLE
Use custom icons for mounted devices

### ISSUE THREAD

**Issue by freder** [micheleg/dash-to-dock#1508]
it would be great if `dash-to-dock` could display custom icons set for mounted devices (by honouring the `metadata::custom-icon` attribute).

![image](https://user-images.githubusercontent.com/724844/130210902-8896d4bc-5327-4ca2-a642-7eff5543e310.png)

bonus request: add a divider between mounted devices and applications.

**Comment by 3v1n0** [comment]
I've the feeling that we'd need [GMount support for this](https://gitlab.gnome.org/GNOME/gtk/-/issues/3013#note_882088), so not really an option for now.

**Comment by 3v1n0** [comment]
Ah, no ok.. I was wrong. It's an attribute that can be attached to the mounting folder too.
