### ISSUE TITLE
Dash breaks making Screenshots

### ISSUE THREAD

**Issue by cldx** [micheleg/dash-to-dock#151]
Hey @micheleg i'm in the middle of testing Extensions against 3.16 and i noticed this weird bug where you can't take Screenshots. Or to be more exact, you CAN take screenshots, but the Screenie will only show the Dock. I added two shots for reference.

![bildschirmfoto von 2015-03-27 20-43-16](https://cloud.githubusercontent.com/assets/470526/6875843/999e6d14-d4c2-11e4-8ead-c61f99cb52f6.png)
Dash to Dock Extension

![bildschirmfoto von 2015-03-27 18-49-11](https://cloud.githubusercontent.com/assets/470526/6875849/a87159fa-d4c2-11e4-82f2-32c9fb44a50e.png)
Ozon Atom Dock Extension

Any idea as to how we can tackle this? 

Best regards.

**Comment by micheleg** [comment]
How are you taking the screenshots? I have no problem in both 3.14 and 3.16 on my system with the gnome screenshot tool.

**Comment by cldx** [comment]
It only happened after installing 3.16, i just used the "Print"-Shortcut, but it happens too with gnome-screenshot. In 3.14 it worked like a charm. Maybe this isn't even connected to the Dock but something is wrong on my Machine after all oO'

**Comment by micheleg** [comment]
I run 3.16 from jhbuild on the same system where I run 3.14 (Debian Jessie), so maybe it depends on the the new version of the screenshot tool?  Everything is ok with the extensions disable?

**Comment by cldx** [comment]
Yes, when i disable the Dock everything works as expected.

**Comment by cldx** [comment]
So you gave me an idea there with it being connected to gnome-screenshot.
I found this bug which might be connected https://bugzilla.gnome.org/show_bug.cgi?id=698799 which seems to be around since quite a while.
I can also confirm that taking a screenshot works with xfce4-screenshooter (like mentioned in the bug report).

**Comment by micheleg** [comment]
Any update on this?
