### ISSUE TITLE
something's gone wronge [manjaro x64, gnome 40.3.0]

### ISSUE THREAD

**Issue by CRY-D** [micheleg/dash-to-dock#1513]
when i click on `Dash to Dock settings` i get this message
`
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock

Stack trace:
  _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
  _bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
  _init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
![Screenshot-20210825200002-1366x768](https://user-images.githubusercontent.com/16564491/130849483-6ace0e1b-6fa9-4542-ab01-4dc01eab5f38.png)
`

**Comment by Timelessprod** [comment]
I have the same issue !

The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock
```

Stack trace:
```
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
_bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
_init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by bilyboy785** [comment]
Same issue here : 

- Manjaro Linux Gnome
- Kernel : 5.10.60-1
- Gnome : 40.4

```
Error: GSettings key preview-size-scale not found in schema org.gnome.shell.extensions.dash-to-dock

Stack trace:
  _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:563:23
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:515:30
  _bindSettings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:545:81
  _init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:219:14
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by AlwaysStudent** [comment]
Just try this:
```shell
cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/
sudo mv schemas schemas-bak
```
Then, try to open `Dash to Dock settings` in the extension.
Maybe you can open the setting window without any issues.

**Comment by bilyboy785** [comment]
> Just try this:
> 
> ```shell
> cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/
> sudo mv schemas schemas-bak
> ```
> 
> Then, try to open `Dash to Dock settings` in the extension.
> Maybe you can open the setting window without any issues.

It's Works ! Thanks !

**Comment by CRY-D** [comment]
> Just try this:
> 
> ```shell
> cd /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/
> sudo mv schemas schemas-bak
> ```
> 
> Then, try to open `Dash to Dock settings` in the extension.
> Maybe you can open the setting window without any issues.

It's Works fine Thank you
