### ISSUE TITLE
[ubuntu-dock-70] "Show Applications" button is unclickable in the corner and along its bottom edge in 21.10

### ISSUE THREAD

**Issue by imchau** [micheleg/dash-to-dock#1518]
There seems to be a regression of https://github.com/micheleg/dash-to-dock/issues/1167 because the issue has resurfaced on Ubuntu 21.10 with version 70~ubuntu2 of package gnome-shell-extension-ubuntu-dock 

On Impish daily builds, with the default left-side setup of the dock, swing the mouse pointer to the bottom-leftmost corner of the screen. The "Show Applications" button is not highlighted and cannot be activated. The button is unclickable in the corner and along its bottom edge.

Video demonstration
![Show_Applications_Fitts](https://user-images.githubusercontent.com/14195241/132169635-e3beea5b-c643-4017-8bfa-667e611af151.gif)

Reported downstream at https://bugs.launchpad.net/dash-to-dock/+bug/1942702

@vanvugt

**Comment by dimztimz** [comment]
This bug is still present in Ubuntu 22.04.

```
Package: gnome-shell-extension-ubuntu-dock
Version: 72~ubuntu5.22.04.1
```

[bug show applications.webm](https://user-images.githubusercontent.com/6236568/190298011-fa00140c-ea11-4436-a0fa-6e1feb2ee8d8.webm)
