### ISSUE TITLE
"Expand" adds rounded corner after suspend

### ISSUE THREAD

**Issue by asgerbj** [micheleg/dash-to-dock#152]
When running the extension in "expand" mode, it will remove the rounded corners. However, the rounded corners are added again after the system is recovering from suspend.
![screenshot from 2015-04-04 16 10 21](https://cloud.githubusercontent.com/assets/1816592/6992970/58b9c89c-dae5-11e4-9b59-b7f0a4e00cd2.png)

**Comment by region51** [comment]
@micheleg , hi, I'm using version 40 and mode "Expand (experimental and buggy)"
![2015-04-04 18 28 32](https://cloud.githubusercontent.com/assets/10940138/6993321/4942b14e-daf9-11e4-83b1-59f553ea60d0.png)
mode show applications button first normal
![2015-04-04 18 29 02](https://cloud.githubusercontent.com/assets/10940138/6993356/134dca8c-dafa-11e4-8829-b54c75b0eb07.png)

**Comment by micheleg** [comment]
@asgerbj Which extension version? Does the problem occurs also when locking the screen? Does the problem occurs without any custom theme?

**Comment by asgerbj** [comment]
@micheleg Extension version 38, Gnome-shell version 3.12. Yes, problem also exists on locking the screen, and exists both if dock is set to "fixed" (so it takes the space of the top bar) or is in intellihide.

I do not use any custom GTK+/Window themes, all are set to Adwaita (default) as out of box Ubuntu GNOME 14.04.2 LTS. Other extensions installed are only "transparent top bar" and Moka + Faba icons.

**Comment by micheleg** [comment]
There's also version 41 which is available for Gnome 3.12. Please update to it, it's available in the extension website.

**Comment by asgerbj** [comment]
Updated to version 41 from the extension website and it has corrected the problem. Thanks!
