### ISSUE TITLE
Here is the fix for the 'Show mounted volumes and devices' icon problem.

### ISSUE THREAD

**Issue by Tuxman2** [micheleg/dash-to-dock#1521]
Hello,

I found a 'bug' when the 'Show mounted volumes and devices' option is enabled. The icon who is displayed on the dock when a device is mounted is not correct. It is a white icon with a wheel (in my case) and not an icon from the icon theme.

The issue is in the location.js file of the extension. Precisely in this part:

`
_getWorkingIconName(icon) {
if (icon instanceof Gio.EmblemedIcon) {
icon = icon.get_icon();
}
if (icon instanceof Gio.ThemedIcon) {
return ‘’;
} else {
return icon.to_string();
}
}
`

It is here:

`if (icon instanceof Gio.ThemedIcon) {
return ‘’;
}
`

So it returns nothing.

Here is the fix:

`if (icon instanceof Gio.ThemedIcon) {
    let names = icon.get_names();
    return names[0];
    } `

After that, it's good. 

I don't know how to make a pull request or modify the code in the github. So, can someone here make the change for me ?

Thanks.

**Comment by 3v1n0** [comment]
This was handled via locations refactory.
