### ISSUE TITLE
Icons jump sometimes (with experimental and buggy option)

### ISSUE THREAD

**Issue by bigbn** [micheleg/dash-to-dock#154]
![2](https://cloud.githubusercontent.com/assets/740864/7026563/26f12c5e-dd53-11e4-9fc5-d6e245a4145e.png)
![1](https://cloud.githubusercontent.com/assets/740864/7026562/26ee5254-dd53-11e4-988b-8674528c3583.png)

Gnome 3.16 Arch (with testing repos)

**Comment by micheleg** [comment]
I'd be glad if you could test the current master. I think this problem was solved in 3f81640fced97b5d7d34286a55be865ffe6e3017.

**Comment by bigbn** [comment]
Yes, it seems all right. Thank you!
