### ISSUE TITLE
Expanded dash-to-dock

### ISSUE THREAD

**Issue by evfool** [micheleg/dash-to-dock#155]
Hi,
Since the GNOME 3.16 update + dash-to-dock update after closing an application, the icon spacing gets weird in the dock, see the attached screenshot (there will be a huge gap before and after the icon of the closed application). 
![screenshot from 2015-04-11 05-31-30](https://cloud.githubusercontent.com/assets/443993/7099902/3049e870-e00c-11e4-8a81-25ff6cff9be4.png)

This can be reset by moving any of the application icons by drag and drop, or changing settings  (e.g. toggling the Show applications first) in the extension settings.

My relevant settings: 
Expand (yes, that experimental and buggy option, which used to work fine until now :)) - true
Show favorite apps + running apps + applications first - true
Apply built-in custom theme

**Comment by yuryrodrigues** [comment]
I have the same error.

Expand(experimental and buggy)
Gnome-Shell 3.16
Dash-to-Dock version: 42

**Comment by micheleg** [comment]
That's a known issue #154 that is already fixed in master, but still not released on the extension website. I'll update the extension soon, please use current master in the meantime.

**Comment by evfool** [comment]
Indeed, applying change 3f81640 locally fixes the issue, so closing this.

**Comment by yuryrodrigues** [comment]
Thank you micheleg!
