### ISSUE TITLE
Dash background color inverts green/blue

### ISSUE THREAD

**Issue by drakkar1969** [micheleg/dash-to-dock#1553]
When customizing the dash background color, somehow the green and blue channels appear to be inverted.
E.g. setting the background color to #383c4a results in the dash background color being rendered as #384a3c.

Many thanks for the port to GNOME 40 btw, cannot live without this extension!

**Comment by coreybruce** [comment]
Having the same weird issue, what is going on lol

**Comment by drakkar1969** [comment]
Think this bug was introduced with https://github.com/micheleg/dash-to-dock/commit/c9a83048bb9c5e0e1cce5ac24e602df426f19da0

Line 77 of `theming.js` was changed to:
```js
`rgba(${color.red}, ${color.blue}, ${color.green}, ${newAlpha})`;
```

Which should probably be:
```js
`rgba(${color.red}, ${color.green}, ${color.blue}, ${newAlpha})`;
```
