### ISSUE TITLE
Rounded corners only partially transparent

### ISSUE THREAD

**Issue by Rodancoci** [micheleg/dash-to-dock#1555]
Currently using [Vimix](https://github.com/vinceliuice/vimix-gtk-themes) as the gnome shell theme. I'm experiencing an issue when using anything other than the built-in theme (Adwaita) where enabling rounded corners shows a rounded outline on the corners of the dash, but the square corners don't completely disappear. I think there may be a second layer with a semi-transparent rectangle with square corners under the dock itself, if that makes sense?

The issue is especially apparent against a white background:
![image](https://user-images.githubusercontent.com/11667577/138089664-a52889e9-7a9c-427d-8326-b54004c357d1.png)

System info:
OS: Arch Linux
Kernel: 5.14.12-arch1-1
DE: GNOME 40.5

**Comment by drovrak** [comment]
hey, It can come from your shell theme, try a default one(worked for me)

**Comment by mackdroid** [comment]
Adwaita is the default theme

**Comment by drovrak** [comment]
Well, try an other.

**Comment by mackdroid** [comment]
Same thing

**Comment by Rodancoci** [comment]
The package I use for Vimix on Arch, `vimix-gtk-themes-git`, has been updated and I no longer experience the issue.
