### ISSUE TITLE
Dash To Dock Opacity Bug

### ISSUE THREAD

**Issue by EdgarsFeic69** [micheleg/dash-to-dock#1559]
OS: Manjaro 21.1.6 Pahvo
GNOME 40.0

I don't know why it happens, but I have this bug with Dash To Dock on Gnome 40, the first time I used it it worked, but it has been like this for a long time.

![DashToDockBug](https://user-images.githubusercontent.com/83674207/138395328-58ed8305-1eff-4f19-80a6-57e0065ff484.png)

**Comment by andrewcking** [comment]
This seems to be resolved for me. I think the issue was a conflict with 'blur-my-shell'. After disabling 'dash' blur on blur my shell the issue resolved. Can anyone else confirm?

**Comment by prabh1601** [comment]
> This seems to be resolved for me. I think the issue was a conflict with 'blur-my-shell'. After disabling 'dash' blur on blur my shell the issue resolved. Can anyone else confirm?

Oh Damn ! Thats a great observation, this fixed the thing for me too. Thanks :)
