### ISSUE TITLE
Bug Mode Expand

### ISSUE THREAD

**Issue by ThePierrezou** [micheleg/dash-to-dock#156]
Hello,
I've made a video :
https://www.youtube.com/watch?v=A5aCXoogEPw&feature=youtu.be
I'm using https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock/
Thanks 
ThePierrezou

EDIT= Sorry with the lastest git version i don't have this bug

**Comment by VanCoding** [comment]
I too have this problem on 2 up to date arch linux computers.

**Comment by micheleg** [comment]
It's a known issue (#154). Please update to current master while I prepare a new release for the extension website.

**Comment by VanCoding** [comment]
Wow that was fast :)
Okay, I think I'll wait for the official update then.

Thank you! :+1:
