### ISSUE TITLE
Shaking animation never stops

### ISSUE THREAD

**Issue by BlueManCZ** [micheleg/dash-to-dock#1568]
Whenever an application window is opened without the user clicking on the dock icon or the notification is received, the icon starts shaking. There is nothing wrong with that. But it never stops doing that. Whenever I click on the icon to focus the window, minimize, click again, etc, the icon is still shaking. I have to close the application and open it again to stop the shaking animation.

Version 71, GNOME 40.4.0

https://user-images.githubusercontent.com/17854950/139556297-610ea889-b31c-441d-8e46-d43c838c38e3.mp4

**Comment by BlueManCZ** [comment]
It was Firefox for me as well, but I remember I encountered the same problem with Telegram and Geary in the past. I don't know how to reproduce it. It just happens sometimes and it's hard to say why.

https://user-images.githubusercontent.com/17854950/139500513-71df5eb6-aa6d-4aa8-9800-a12a886af200.mp4

**Comment by BlueManCZ** [comment]
https://user-images.githubusercontent.com/17854950/139528019-f659b22a-4b23-4148-a687-21dfec67d412.mp4

**Comment by BlueManCZ** [comment]
https://user-images.githubusercontent.com/17854950/139556297-610ea889-b31c-441d-8e46-d43c838c38e3.mp4

**Comment by inthreedee** [comment]
I've had this happen with multiple applications, but Firefox is the easiest to reproduce.
@3v1n0 I can reliably reproduce it with these steps:

1. Launch Firefox
2. Minimize Firefox to the dock
3. Click a link in, for example, a chat window
4. Firefox should automatically restore its window and open the link in a new tab.  The dock icon will be wobbling.
5. Unfocus/focus/minimize/restore Firefox at this point has no effect on the wobbling.
6. Additionally, I have my dock configured to minimize/restore a window when I click its icon.  This function no longer works.
7. To fix it, right click the Firefox icon in the dock and select "New Window".  The wobbling stops and the click-to-minimize function now works again.

Step 2 is critical.  I can't reproduce it unless Firefox is minimized.

**Comment by BlueManCZ** [comment]
I can confirm what @3v1n0 says. Clicking a link and opening it in Firefox (for me no matter if minimized or not) starts the dancing animation. And there are two cases:
1. If Firefox was minimized, the opening of a new window is enough to stop dancing animation.
2. If Firefox was not minimized, you have to close the new window in addition for the animation to stop.

**Comment by inthreedee** [comment]
@BlueManCZ It sounds like you have Firefox configured to open links in a new window?

By compaison, I have mine configured to open links in a new tab in the existing window.  This could explain the slightly different behavior we're seeing.

**Comment by BlueManCZ** [comment]
No no, mine Firefox opens links in new tabs as well.

**Comment by markuspfeiffer** [comment]
I can also reproduce it with Firefox like this:
- Open Firefox
- Open some other application on top of Firefox (e.g. terminal)
(does not have to be full screen, just ordered in front of Firefox)
- Ctrl+click a URL in the terminal
- Firefox moves to the front and opens the link in a new tab
- Its icon starts wiggling and never stops

**Workaround**
- Center-click of Firefox icon to open a new window stops the shaking

**Comment by wallon-ines** [comment]
Same problem with Firefox and Evolution mail on Fedora 34 with enabled extensions : 

tray-icons@zhangkaizhao.com
audio-switcher@albertomosconi
just-perfection-desktop@just-perfection
weatherintheclock@JasonLG1979.github.io
gitlab-extension@infinicode.de
dash-to-dock@micxgx.gmail.com
system-monitor@paradoxxx.zero.gmail.com
argos@pew.worldwidemann.com
user-theme@gnome-shell-extensions.gcampax.github.com

**Comment by linuxiorr** [comment]
Is there a way to disable the shaking behaviour? I find no use for it, the only thing it's doing for me is just being an unwelcome distraction.

I would love to be able to disable it.

**Comment by BlueManCZ** [comment]
@linuxiorr Removing or commenting this line in the code should do the trick I guess:

https://github.com/micheleg/dash-to-dock/blob/55e9f07766183ad19668763ce60a8d77eb2ea2a0/appIcons.js#L156

**Comment by inthreedee** [comment]
> Removing or commenting out these two lines in the code should do the trick I guess:

While this does stop the shaking animation, this bug is more than just a cosmetic issue.  If you have a click action configured, for example minimize window, that click action stops working when this bug is triggered.

I've tried commenting out the entire `notify::urgent` block as well, but it still happens.

**Comment by inthreedee** [comment]
Some investigation:  This line is why the click to minimize feature fails to work:
https://github.com/micheleg/dash-to-dock/blob/master/appIcons.js#L483

The hasUrgentWindows flag is failing to be properly cleared when an app is brought to the foreground in this way (ie, clicking a link somewhere else that launches Firefox).  This is also why the animation is never cleared.  Still trying to figure out if this is a bug here or upstream.

**Comment by inthreedee** [comment]
I have found one part of the solution:
https://github.com/micheleg/dash-to-dock/blob/39e5597da42124a23d3f0d5dbca69fea1f3fa96b/appIcons.js#L313-L315

Adding a check so we don't set the urgent flag on focused windows seems to prevent this from happening, like so:
```
    _addUrgentWindow(window) {
        if (this._urgentWindows.has(window) || window.has_focus())
            return;
```

This isn't a complete solution though because it doesn't solve the main bug.  When the bug is triggered for Firefox, for example, you can unfocus and re-focus Firefox and the wobbling never stops, meaning there is another bug somewhere causing the urgent flag to not be cleared correctly when focusing an application.

**Comment by BlueManCZ** [comment]
Nice job @inthreedee. I also got time to analyze this a little and found this workaround.

https://github.com/micheleg/dash-to-dock/blob/39e5597da42124a23d3f0d5dbca69fea1f3fa96b/appIcons.js#L144-L149

To this function append one line so it looks as follows:

```
this.connect('notify::focused', () => {
    this.urgent = false;
    if (this.focused)
        this.add_style_class_name('focused');
    else
        this.remove_style_class_name('focused');
})
```

I guess it's not the cleanest solution but seems to work.

**Comment by inthreedee** [comment]
I've opened a pull request to fix this: https://github.com/micheleg/dash-to-dock/pull/1613

**Comment by inthreedee** [comment]
Heads up for everyone here, some additional debugging help is being requested by @3v1n0 over in the PR. They're having trouble reproducing the problem: https://github.com/micheleg/dash-to-dock/pull/1613#issuecomment-1019027159

**Comment by hmlendea** [comment]
Can we somehow disable the shaking completely in all situations?
I find it incredibly distracting and annoying and at least in my eyes serves no useful purpose. I understand that some might find it useful, but I think for those that do not, there should be a toggle to disable it.

**Comment by frederikheld** [comment]
I absolutely agree to what @hmlendea says. Please allow to disable this feature completely!

More than often I have the scenario that I restore a Firefox session which opens 10+ Windows and I do not want to click each of them individually just to get rid of this annoying animation. If this is supposed to focus my attention, it's doing exactly the opposite: I know that there are tons of new windows, I just made Firefox open them. There is absolutely no need to distract me from what I actually want to do whenever I open the dock!

**Comment by ghabit** [comment]
I think shaking functionality is useful indeed. But, here, on archlinux, telegram is continuously shaking while minimized. Is there a way to stop it doing so? Thank you.

**Comment by ZimbiX** [comment]
@hmlendea @frederikheld @ghabit I've submitted a PR adding a setting to disable icon shaking 🙂 https://github.com/micheleg/dash-to-dock/pull/1896
