### ISSUE TITLE
launcher disaper

### ISSUE THREAD

**Issue by drovrak** [micheleg/dash-to-dock#1573]
Hello there,
I have an issue when I want to set a personalised theme in "appearance", when I do this every launcher, icons, disappear like so :
![Capture d’écran de 2021-10-31 19-18-31](https://user-images.githubusercontent.com/42212416/139594787-c88ca0ef-a7ba-49c7-8d98-bd5dd75e40b6.png)

But in "default" mode icons are here :

![Capture d’écran de 2021-10-31 19-18-29](https://user-images.githubusercontent.com/42212416/139594826-edfe2451-6358-4669-b9f1-eb1ba7897cd3.png)

thanks for helping !
have a good day !

**Comment by 3v1n0** [comment]
If you're using a custom theme, you need your theme provider to adapt the code to support dash-to-dock, by including the `_stylesheet.scss` rules in the custom theme.

**Comment by drovrak** [comment]
I don't understand, can you detail please ?

**Comment by 3v1n0** [comment]
You're using a custom gnome-shell theme from what I see.

And dash-to-dock changed its stylesheet quite a lot recently, so any custom theme need to adapt the code to suport it, or you'll get visual issues. Check reverting to the upstream gnome-shell theme to verify this.

**Comment by drovrak** [comment]
I do use the Nordic-darker theme. But I tried default theme and then every other pre-installed themes but still nothing
