### ISSUE TITLE
Wierd margin around the actual dock 

### ISSUE THREAD

**Issue by LouvAndTech** [micheleg/dash-to-dock#1579]
Since i've update to Ubuntu 21.10 and so, Gnome 40 i've got that litle second shadow dock behind the actual one, which is so unsatisfying to see.

![Capture d’écran de 2021-11-05 15-48-05](https://user-images.githubusercontent.com/68016832/140529702-b8f3c9ee-0123-46c0-a6ee-b7a977359345.png)

Anyone as an idea where it come from ?

**Comment by 3v1n0** [comment]
Using any custom theme?

You can use the shell inspector to understand what's that area though (`Alt+f2` -> `lg` -> Enter key)

**Comment by LouvAndTech** [comment]
I do use a custom theme, but it stay even when i disable it.
here what I've found on the inspector :

![Capture d’écran de 2021-11-05 16-31-17](https://user-images.githubusercontent.com/68016832/140536515-85376d1c-8d97-4cea-9846-c29836944c4a.png)

The second one (the longest one) is the shadow behind

**Comment by 3v1n0** [comment]
I mean, using gnome-shell stock theme you get the same?

**Comment by LouvAndTech** [comment]
After testing the issue happen with every theme, except the default one and Yaru....

**Comment by 3v1n0** [comment]
So please, ask your theme developers to update the code to support dash-to-dock by syncing with our stylesheet, otherwise we can't fix it from the extension side.
