### ISSUE TITLE
wrong translation or ... bug

### ISSUE THREAD

**Issue by region51** [micheleg/dash-to-dock#160]
i use version 43 
Where's Show favorite applications?
![2015-04-18 17 21 14](https://cloud.githubusercontent.com/assets/11947263/7215864/7e24195e-e5f1-11e4-89c1-6d9b43f57036.png)

Where's  Show running applications?
![2015-04-18 17 21 09](https://cloud.githubusercontent.com/assets/11947263/7215866/8c0633f4-e5f1-11e4-9129-8914c7b6e28b.png)

**Comment by micheleg** [comment]
People already pointed it out, it's already fixed in master 3816b49876016b1958d69a990be5c5e5bb2a4cf0
