### ISSUE TITLE
Gnome 41: Buggy favorite app handling.

### ISSUE THREAD

**Issue by Bananaman** [micheleg/dash-to-dock#1605]
# Method 1: Works

I have these applications open:

![image](https://user-images.githubusercontent.com/38923130/144631692-9216af6b-4a51-405a-b5e1-9671aaf8de9b.png)

I right click on Extensions (the app) and add it to favorites:

![image](https://user-images.githubusercontent.com/38923130/144631632-a18a4633-56b8-4672-b072-d96faa68f0db.png)

It works perfectly. Now Extensions has moved to the left side of the divider bar to prove that it's a favorite:

![image](https://user-images.githubusercontent.com/38923130/144631865-62b9a924-efc8-4840-a062-f8ea7cfe0f6d.png)

# Method 2: Bugged

I remove Extensions from my favorites, so that it's at the normal non-favorite location again:

![image](https://user-images.githubusercontent.com/38923130/144631692-9216af6b-4a51-405a-b5e1-9671aaf8de9b.png)

**THIS IS THE BUG! Now I click and DRAG Extensions to the left side to make it a favorite. Look what happens if I drop it to the left of the "Software" app. As you can see, Software gets pushed to the right into the non-favorite area. This fixes itself next time the dock refreshes though, but it's weird:**

![image](https://user-images.githubusercontent.com/38923130/144632224-f2c39a49-b2a9-42a5-9946-5049c8881817.png)

**ANOTHER VARIATION OF THE BUG! If I click and DRAG Extensions to the RIGHT side of the "Software" app, Extensions becomes a favorite but still sits in the non-favorite area:**

![image](https://user-images.githubusercontent.com/38923130/144631692-9216af6b-4a51-405a-b5e1-9671aaf8de9b.png)

These bugs don't happen when Dash to Dock is disabled. :)

**Comment by 3v1n0** [comment]
Thanks for the detailed report, will check on that

**Comment by Bananaman** [comment]
@3v1n0 It's late but I just want to say thank you very much for solving the issue. It works beautifully now. :)
