### ISSUE TITLE
Gnome 41: Icon highlight freezes when right-click menu is used.

### ISSUE THREAD

**Issue by Bananaman** [micheleg/dash-to-dock#1606]
This is a very simple, short and sweet bug report.

Works properly: If you hover over an icon and left click it to launch the app, the highlight vanishes properly:

![image](https://user-images.githubusercontent.com/38923130/144632822-becdebae-a6e9-46ec-9ab8-2ca607328532.png)

Bugged: If you right-click on an application (such as Files, or Text Editor), to get the app actions menu, and choose something (such as "New Window"), the Dash to Dock highlight of the icon still stays afterwards, like this:

![image](https://user-images.githubusercontent.com/38923130/144632970-62621d5b-146f-4826-af97-1fd59260b452.png)

The highlight stays until the user manually uses the mouse to highlight and then remove highlight from the icon again.

**Comment by 3v1n0** [comment]
Mmhmh, I've been testing this on 40 and 41 but I don't get it, what I actually do get instead is that the highlighting isn't happening on 41 at all, while it should be the case for applications that are currently focused.

**Comment by Bananaman** [comment]
@3v1n0 Strange. I use Fedora 35 fully updated, so I'm on GNOME 41.1.

**Comment by somepaulo** [comment]
For me the highlight stays on right after opening a new window through the right-click menu, which is expected as the newly opened window is actually in focus. Switching to a different application switches focus as expected. Showing the overview also keeps the focus indicator on the last focused app before opening the overview. All these seem pretty normal to me.

**Comment by Bananaman** [comment]
@3v1n0 @somepaulo  It doesn't happen for me anymore. Could be an update of GNOME or dash to dock that has fixed it.
