### ISSUE TITLE
Can't install Dash to Dock

### ISSUE THREAD

**Issue by PhantomLel** [micheleg/dash-to-dock#1611]
I tried a few different ways of installing. First, I tried using the gnome extensions website to download it, but when I click the 'on' switch, it does nothing and doesn't show up in gnome tweaks. This is on Firefox by the way, but it doesn't work on Chrome either

Next, I ran the commands under Installation from source. at https://micheleg.github.io/dash-to-dock/download.html. I made the files using the provided commands, then rebooted. Looked in gnome tweaks under extensions, nothing was there. 
Thanks for you help in advanced.

**Comment by PhantomLel** [comment]
Ok so update. I got it to show up in gnome tweaks, but now there is an issue saying that it can't open the settings for the extension. 
![image](https://user-images.githubusercontent.com/84487477/144753008-a067f3fe-0502-4730-ac60-fc3be871f850.png)

then when i click on it, it shows this:
![image](https://user-images.githubusercontent.com/84487477/144753031-954484c6-c914-4aca-ad58-ea2b078761bd.png)

**Comment by gatsby0203** [comment]
Check your gnome-shell version.
gnome-shell 3.65 support was branched out. You need to clone and install from that branch. 
`cd /tmp
git clone -b tmp/gnome-3.36 https://github.com/micheleg/dash-to-dock.git
cd dash-to-dock
make
make install`

**Comment by 3v1n0** [comment]
Please show the technical details.

And indeed, what's your shell version?

**Comment by PhantomLel** [comment]
> Check your gnome-shell version. gnome-shell 3.65 support was branched out. You need to clone and install from that branch. `cd /tmp` `git clone -b tmp/gnome-3.36 https://github.com/micheleg/dash-to-dock.git` `cd dash-to-dock` `make` `make install`
Thanks, this worked for me!
