### ISSUE TITLE
Dash to dock not working on first install

### ISSUE THREAD

**Issue by axkibe** [micheleg/dash-to-dock#1619]
This is also something I now watched several times, on a fresh install (debian bullseye) installing Dash to Dock pretty much as the first thing after logging into the system (yes it's that important to me). It will not reliable work. Sometimes it crashes right away, sometimes it's just awkward. After the first install removing the extension, logging out, logging back in and reinstalling it works normally from then on.

**Comment by 3v1n0** [comment]
Sadly it's hard to understand without screenshots and logs.

**Comment by 3v1n0** [comment]
Feel free to reopen once you've a clearer description
