### ISSUE TITLE
Artifact of rouded corners

### ISSUE THREAD

**Issue by vantu5z** [micheleg/dash-to-dock#162]
When dock covered by window, corners have some artifacts:
![2015-04-19 19-36-54](https://cloud.githubusercontent.com/assets/8698003/7219130/1f5b977a-e6c4-11e4-8926-bb09efc997dc.png)
Use last git version.

**Comment by region51** [comment]
v43 normal
![2015-04-19 15 30 10](https://cloud.githubusercontent.com/assets/11947263/7219446/4bf73b74-e6a9-11e4-8b36-391280ef7844.png)

**Comment by micheleg** [comment]
Pretty strange. Are you using a custom theme? It might be a graphic driver bug, which drivers are you using?

**Comment by vantu5z** [comment]
I use catalyst-test-pxp 14.12-3 driver. Try to switch from amd to intel driver, that not helped. Maybe I use not last update of gnome(3.16) or some lib, but now can't update system.

**Comment by vantu5z** [comment]
Use Vertex-theme, try switch to adwaita, don't help.

**Comment by ainola** [comment]
I get no such behavior on nvidia (arch+gnome 3.16)

**Comment by vantu5z** [comment]
I think problem is in gnome-shell-theme-elegance-colors (use git version)
(arch+gnome 3.16)

**Comment by micheleg** [comment]
@vantu5z You previously claimed the problem was occurring even with the default theme. Can you confirm if the error is actually limited to that specific custom theme?

**Comment by vantu5z** [comment]
@micheleg Sorry, I don't know how it work's (elegance-colors theme), because it doesn't support gnome-shell 3.16. May be configure files stay from previous version of gnome.
With other themes, looks fine. Think issue may be closed.
