### ISSUE TITLE
Remove dash-to-dock because it does not work properly

### ISSUE THREAD

**Issue by alexmro** [micheleg/dash-to-dock#1626]
I have installed it by cloning the repository and running `make` but I have problems on Ubuntu 21.10.

The dock disappears if the system logs out, when I login back. Only the small button for showing all the apps is shown but even that does not work. When I click it, the applications are not shown, just a big grey window with an inactive search bar at the top.

I also get system errors related to GNOME so I want to remove it but I don't know how. I basically want my old dock back

**Comment by AnAlligatorPear** [comment]
Having the same issue as above ^

**Comment by inthreedee** [comment]
You can try running `make uninstall` from the same directory.  If the dock that ships with Ubuntu was removed, I believe the package is `gnome-shell-extension-ubuntu-dock`, which you can reinstall with your package manager of choice.  Ubuntu-dock is just a modified version of dash-to-dock.

**Comment by AnAlligatorPear** [comment]
Hey @alexmro , 

I found a solution to the initial problem (dock disappears on login). If you turn off the original ubuntu dock in gnome tweaks (eave dask to dock on) and then restart, you should have no problems locking your desktop and then logging back in with the dock still functional
