### ISSUE TITLE
Feature Request: Hide "Applications Icon"

### ISSUE THREAD

**Issue by x11tete11x** [micheleg/dash-to-dock#164]
For example for people (like me xD) that use "Applications Menu" to not have "dual launchers" it will be intresting if we can hide the "Applications icon" thx!

**Comment by micheleg** [comment]
I'm not sure it makes sense. The application icons is also used to remove favorites app, and give access to the extension settings. Whant would be the real benefit of removing it? The visual simmetry of the dock (I like asimmetries....)? The 50px space saved?

**Comment by x11tete11x** [comment]
sorry for late answer i was busy :) it's not for "save space" it's for not have redundant app menus (if that option can be implemented) will looks like this: http://i.imgur.com/sQbCTjD.jpg

actually looks like this: http://i.imgur.com/WuoPjco.jpg 

as you can see there are redundant ways to invoque an app menu :)

thx!

**Comment by k0377** [comment]
:+1: I never use the applications icon and start all my apps with super key and search.

**Comment by micheleg** [comment]
The feature is  implemented in master and in the gnome-3.14 branch. Please check it out and report any bug.
