### ISSUE TITLE
Can't enable the extension from the Gnome Extensions 

### ISSUE THREAD

**Issue by ryukamish** [micheleg/dash-to-dock#1642]
So here's the thing I have gnome extension and i did the installation but am not able to toggle the button for the extension. The toggle which has on and off is showing an error button and I when went to the Extensions app the toggle was not working and showed this message : 

```
The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
SyntaxError: fields are not currently supported
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
```

**Comment by 3v1n0** [comment]
What versions are you using?

Do you have some more detailed error in the journalctl?

**Comment by ryukamish** [comment]
> What versions are you using?
> 
> Do you have some more detailed error in the journalctl?

It got fixed.. the problem seemed to be have been the shell option which I tweaked. Something happened and it let me restart the whole process again and it works.

Sorry for the inconvenience and thank you for *dash-to-dock*.
