### ISSUE TITLE
New problem to dock - The dock disappears when the PC is in sleep mode and you reopen it.

### ISSUE THREAD

**Issue by Leonardo425874** [micheleg/dash-to-dock#1645]
Good morning, there is a new problem, when the computer goes into standby and I open it the dock is no longer there. Unless they end the session and reopen a new session.
This problem occurred to me on Debian.
Thank you very much for your work.

**Comment by GeoffreyCoulaud** [comment]
Hello, thanks for reporting this. 
You may want to have a more descriptive title for easier bug triaging and give more info about your system to help reproduce.

**Comment by Leonardo425874** [comment]
Okay, no problem.
Let me know at the resolution of the problem.
Have a nice day.

**Comment by 3v1n0** [comment]
Please provide logs or more information, at the current state is impossible to help with this.

I'm closing it, feel free to reopen adding more infos.

**Comment by linus-jansson** [comment]
What logs should I provide as I experience the same issue? Is there any stored logs from gnome extensions or any theme logs? 

In that case where is the logs located?

**Comment by Leonardo425874** [comment]
Good morning, the bug I had encountered has been fixed. Thank you very
much, Leonardo.

Il giorno ven 21 gen 2022 alle ore 02:00 Marco Trevisan <
***@***.***> ha scritto:

**Comment by Leonardo425874** [comment]
Good morning, I apologize but the bug is still there. I report it again
with the screenshot. Thank you and have a good day.

Il giorno ven 21 gen 2022 alle ore 01:59 Marco Trevisan <
***@***.***> ha scritto:

**Comment by GeoffreyCoulaud** [comment]
Please take a short video of the problem and provide these informations :

- Distro (and version)
- GPU
- Display server (Xorg or Wayland)
- Version of Gnome
- Version of dash-to-dock

As of now, we literally have no path to search into from the info you provided, that's why this issue was closed.

**Comment by linus-jansson** [comment]
-Display server - xorg
```
❯ ps -e | grep tty
   1830 tty2     00:00:00 gdm-x-session
   1832 tty2     00:00:10 Xorg
   1994 tty2     00:00:00 gnome-session-b
```

-Version of Gnome-shell - 40.5
-Version of dash-to-dock - I am unsure where to locate that but there is no new updates on gnome extensions

![Screenshot from 2022-01-25 23-07-06](https://user-images.githubusercontent.com/30862662/151068440-0feca7b1-b3d6-40d5-9699-61745f157ca1.png)
![Screenshot from 2022-01-25 23-07-49](https://user-images.githubusercontent.com/30862662/151068451-820ffd35-3e2e-4ee0-84ee-d28f7a71d0c5.png)
![Screenshot from 2022-01-25 23-10-38](https://user-images.githubusercontent.com/30862662/151068469-fa9050b0-4983-4263-99f1-894e13abf35f.png)


This is the wanted result
![Screenshot from 2022-01-25 23-18-06](https://user-images.githubusercontent.com/30862662/151069168-9613a80b-68f3-4b71-bb2a-2a9b2340e4d0.png)

I hope images are ok

**Comment by Leonardo425874** [comment]
Thank you very much, I have already made the report with the screenshot.

Il giorno mar 25 gen 2022 alle ore 23:21 Linus J ***@***.***>
ha scritto:

**Comment by linus-jansson** [comment]
You have not attached any screenshots.
