### ISSUE TITLE
Dock colors and transparency broken

### ISSUE THREAD

**Issue by GarrettBlackmon** [micheleg/dash-to-dock#1646]
![Peek 2022-01-19 00-49](https://user-images.githubusercontent.com/5715535/150080222-7380872a-eb3c-41bf-aaa7-72eb05a4c7fd.gif)

After an update to Pop!_Os 21.10 I begrudgingly went through the slog of restoring my gnome shell extensions and making my DE function as I'd like. When I first disabled everything COSMIC from gnome extensions and installed dash-to-dock everything was fine and the transparency appeared to be as I left it.

But shortly after I changed a GTK theme and the dock lost transparency.

I've tried:
* Changing the theme back
* Rebooting
* Uninstalling and re-installing dash-to-dock

You can see by the very strange behavior in the screen capture above something appears to be very wrong.

**Comment by 3v1n0** [comment]
This should be fixed by commit c9a83048bb9c5e0e1cce5ac24e602df426f19da0

**Comment by GarrettBlackmon** [comment]
I may lack some understanding here but from what I can see c9a8304 went into version 70 while I have 71 on gnome 40.4.0.

![image](https://user-images.githubusercontent.com/5715535/150448186-3dea01cf-dafc-4c47-9ad9-cc16253928bc.png)

I just installed it from the gnome extensions page, nothing special about my install.

**Comment by 3v1n0** [comment]
Ok, sorry... Colors are indeed swapped, but that should have been fixed by commit f9fc5c4ae4143e1441c15dff848582820403bb94

**Comment by 3v1n0** [comment]
As per transparency, are you using a custom shell theme?

**Comment by hmlendea** [comment]
For me there's a semi-transparent dark background whenever I try to use transparency, no matter the opacity level.

![image](https://user-images.githubusercontent.com/10261133/151036795-88115b5f-5f73-492e-9364-e5b8fa2a6d57.png)

Oh and the corners are straight on the left side and rounded on the right side.

This happens only when I have the `user-theme` extension enabled as well. My shell theme is ZorinGray-Dark from ZorinOS

**Comment by 3v1n0** [comment]
So... Sadly that's not our bug.

You need to ensure that the theme handles d2d properly.

**Comment by GarrettBlackmon** [comment]
> This happens only when I have the `user-theme` extension enabled as well. My shell theme is ZorinGray-Dark from ZorinOS

This seemed to solve my issue. I'm using https://github.com/Jannomag/Yaru-Colors just to change some accent colors, I just disabled user themes which allowed me to keep my very minimal theming while fixing the dock.

Thanks so much @hmlendea
