### ISSUE TITLE
spanish translation duplicate message definition

### ISSUE THREAD

**Issue by doppelhelix** [micheleg/dash-to-dock#1647]
```
po/es.po:519: duplicate message definition...
po/es.po:102: ...this is the location of the first definition
msgfmt: found 1 fatal error
```

**Comment by aminvakil** [comment]
This is causing my AUR package to fail: https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock-git/

https://github.com/aminvakil/aur/runs/4904194617?check_suite_focus=true#step:11:961
