### ISSUE TITLE
Isolate workspaces started showing some apps from other workspaces.

### ISSUE THREAD

**Issue by JustCryen** [micheleg/dash-to-dock#1651]
Previously the dock worked flawlessly but recently it started to show some programs from other workspaces even though I have the option "Isolate workspaces" checked.

And they're not always the same type of windows, now it's a web browser and later it can be something entirely different.
Also sometimes it's just one program that shows on all workspaces and sometimes it's multiple programs doing that. 

If I have to guess when it started doing that I'd say around monday, so January 17th.

One last thing, I noticed that right now it only happens on Gnome Web / Epiphany. If one window is open it shows as two instances on the dock, If two are open, four indicators show and so on.
When I move to another workspace I just see half of the indicators on the dock. Maybe browsers started spawning some processes which count as extra instances on the dock.
I'm sure It happened before with Chromium and Thunderbird but now only Epiphany does that.

And also I just noticed that when I close a window in Epiphany, dock doesn't free up the indicator, it just keeps the space of the closed window (and perhaps processes that launched at startup of each web window). It does that until I quit all usable instances of the program.
This way I was able to have 10 web "processes" on the dock but  only one of them is actually an epiphany window. 

That's a view from the workspace the program is on:
![image](https://user-images.githubusercontent.com/41633661/150635072-99ffce1f-5b88-4bde-a760-50ecf646d5b1.png)

That's from another workspace:
![image](https://user-images.githubusercontent.com/41633661/150635310-475109b4-8a60-4666-9452-7c95838326b5.png)

### Other Info: ###
**OS:** Archlinux
**Kernel version:** *5.16.2-zen1-1-zen*
**Gnome-shell version:** *1:41.3-1*
**DashToDock version:** *71* (downloaded from extensions.gnome.org)
**xorg-server version:** *21.1.3-1*
**Epiphany version:** *41.3-2*

**Comment by 3v1n0** [comment]
have you tried git version?

**Comment by JustCryen** [comment]
Not yet.
I noticed another thing.
Today I was able to connect secondary display and all mentioned issues just affect the integrated one even if the problematic programs are on the external display.

**Comment by JustCryen** [comment]
Ok, it's is actually fixed in the git version.
I guess I can close the issue now.

**Comment by peterlobster** [comment]
I'm having this issue as well with the extensio installed from extensions.gnome.org, the latest version of 41

**Comment by stereomato** [comment]
Same here, latest version
