### ISSUE TITLE
Simple CI trying to build package

### ISSUE THREAD

**Issue by aminvakil** [micheleg/dash-to-dock#1654]
What do you think about a CI which just tests if `make` and `make install` works correctly in order to prevent something like https://github.com/micheleg/dash-to-dock/issues/1647 happen.

It would be nice and I can help with that if that's acceptable.

**Comment by 3v1n0** [comment]
Yeah, I was thinking about that...

Indeed it would be welcome! Also doing some eslint would be nice to have a basic JS syntax validator, sadly we're not at the point of having full eslint, but wouldn't be bad to use it (probably can be done by [disabling all the rules](https://eslint.org/docs/user-guide/configuring/) though).
