### ISSUE TITLE
Animation duration of 0.000(s) makes autohide not work

### ISSUE THREAD

**Issue by gfekw** [micheleg/dash-to-dock#166]
Hello, fantastic Dash to Dock developer!

A bug: I updated from v40 to v43, and had animation set to 0. (all three timeouts to 0 in fact.) Autohide suddenly did not work! It made me think Dash to Dock had some HUGE bug as it simply would not show until I kept on tweaking with the settings... :)

It seems I have to set animation to *something* for Autohide to work again.

So, just a bug, kindly passing on to you.

Thanks for the awesome ongoing work!

**Comment by micheleg** [comment]
Thank you for the bug report. I see the problem. I reworked the machinery triggering the dash showing in those versions and I might not have considered this edge case.

**Comment by micheleg** [comment]
This should have been fixed by fe038b33235407fde5e23205e20e5bbf13fb5dbb.
