### ISSUE TITLE
cant uninstall

### ISSUE THREAD

**Issue by pnv28** [micheleg/dash-to-dock#1665]
I tried the extension and it's great, but after installing I can't uninstall it. Am using Ubuntu 20.04 LTS. I have tried restarting, Restoring Timeshift backup, reloading the gnome shell. Idk what else to do

**Comment by GeoffreyCoulaud** [comment]
Where did you install the extension from ? 
If it was from extensions.gnome.org, you could try removing the extension in `~/.local/share/gnome-shell/extensions`.

**Comment by Tim024** [comment]
Had the same issue, this worked for me:
`killall -3 gnome-shell`
from 
https://askubuntu.com/questions/1235881/cant-uninstall-dash-to-dock
https://askubuntu.com/questions/100226/how-to-restart-gnome-shell-from-command-line

**Comment by pnv28** [comment]
It got fixed, thx for advice
