### ISSUE TITLE
Icon badges cannot be turned off

### ISSUE THREAD

**Issue by brennmat** [micheleg/dash-to-dock#1672]
For reasons I don't understand, the dock recently started showing icon badges (like the number of unread emails in Geary). The badges may be useful to some, but I feel they are very distracting. I would like to turn this feature off. If I can't do this, I will have to stop using dash-to-dock, because it tends to kill the focus on my work.

(I know there are a bunch of similar reports, but they seem to be old and have gone stale. I hope someone can pick this up!)

**Comment by vanvugt** [comment]
Duplicate of #872
