### ISSUE TITLE
Updated French Translations

### ISSUE THREAD

**Issue by ghost** [micheleg/dash-to-dock#1674]
I noticed the French translations were outdated so I followed the guide to generate a .POT and updated them so I could add them to my own install of Dash to Dock. I sent you the files by email back in January but never got an answer and they were't added to the git so just in case you didn't get my message, here are the .po and .mo files so you can eventually add them to the repo.

Thank you for this great extension and ongoing support! Without it, I couldn't use Gnome! :D

[fr_FR.zip](https://github.com/micheleg/dash-to-dock/files/8120732/fr_FR.zip)
!

**Comment by 3v1n0** [comment]
Closed via #1823
