### ISSUE TITLE
Error: Type name Gjs_DashToDock_Settings is already registered

### ISSUE THREAD

**Issue by SumNeuron** [micheleg/dash-to-dock#1676]
Error: Type name Gjs_DashToDock_Settings is already registered

Stack trace:
  _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:444:27
  registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
  @/home/solstice/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:180:24
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by jpjarnoux** [comment]
Same problem here.

**Comment by 3v1n0** [comment]
It's normally fixed by a reboot.

Let us know if it's not the case.
