### ISSUE TITLE
Issues under GNOME 42 beta.

### ISSUE THREAD

**Issue by weimzh** [micheleg/dash-to-dock#1679]
dash-to-dock has some issues under GNOME 42 beta:

1) the 'dots' under program icons are not correctly shown:
![image](https://user-images.githubusercontent.com/1220443/156689279-9c8f7404-263c-4761-b059-87398002869c.png)

(Issues below are fixed by PR #1656)

2) original dash overlaps with dock in activities screen:
![image](https://user-images.githubusercontent.com/1220443/156689399-e61bbadc-157b-40ee-a402-53c7f8452a82.png)

3) there are errors in gnome extensions app:
![image](https://user-images.githubusercontent.com/1220443/156689441-0d3fd997-a991-4ce7-a4c2-bab596a05d06.png)

GNOME version:
![image](https://user-images.githubusercontent.com/1220443/156689531-6d652483-9127-4403-8347-a0156f63397b.png)

EDIT:

I tested PR #1656 which fixes most of the issues.  Only issue 1 still exists.

**Comment by timocapa** [comment]
> 1. the 'dots' under program icons are not correctly shown:

Current easy workaround is setting "Customize windows counter indicators" under Appreance to Dots instead of Default

My only two problems are that the app name when you move your mouse over things likes to stay and not disappear, and that the dock hiding automatically feels.. unreliable

**Comment by scottbeamer** [comment]
How are you even able to install in GNOME 42 at this point?  I'm running it on openSUSE Tumbleweed and it's showing not compatible

**Comment by timocapa** [comment]
> How are you even able to install in GNOME 42 at this point? I'm running it on openSUSE Tumbleweed and it's showing not compatible

Merge https://github.com/micheleg/dash-to-dock/pull/1656 and build.

**Comment by arkonbob** [comment]
> How are you even able to install in GNOME 42 at this point? I'm running it on openSUSE Tumbleweed and it's showing not compatible

I'm running TW and got it some time ago, Friday eve IIRC.

**Comment by KushagraKarira** [comment]
> How are you even able to install in GNOME 42 at this point? I'm running it on openSUSE Tumbleweed and it's showing not compatible

`gsettings set org.gnome.shell disable-extension-version-validation true`

This disables the version check for extensions in gnome.

**Comment by KushagraKarira** [comment]
> > How are you even able to install in GNOME 42 at this point? I'm running it on openSUSE Tumbleweed and it's showing not compatible
> 
> Merge #1656 and build.

Working perfectly in Shell 42 running on Debian

**Comment by MrMan314** [comment]
The extension no longer works in the latest version of gnome.

**Comment by vanvugt** [comment]
#1656 was merged and version 72 is now tagged.

Could someone please open separate issues for whatever the remaining issues are? I can see the indicator dot is still a problem in version 72 at least.

**Comment by vanvugt** [comment]
Answering the original issues here:

> 1. the 'dots' under program icons are not correctly shown:

Now tracking in #1757.

> 2. original dash overlaps with dock in activities screen:

That's either fixed already or user error (having two dock extensions loaded).

> 3. there are errors in gnome extensions app:

Also fixed already.
