### ISSUE TITLE
Dock conflicts with 3.16 slide-out system tray

### ISSUE THREAD

**Issue by a-m-s** [micheleg/dash-to-dock#168]
If I set the dock to the bottom of the screen, and there are a lot of icons in both the dock and the new Gnome 3.16 slide-out system tray, then the two will overlap. This makes the right-most part of the system tray inaccessible.

One possible solution might be to move the dash behind the system tray, since that is usually hidden.

Another possibility is to have the intellihide feature dodge the tray, the same as it does windows. If the dock is hidden then there's no problem. However, that doesn't help those who prefer a fixed dock (but would fix it for me!)

**Comment by micheleg** [comment]
Thanks for your considerations and suggestions. I see the problem, I thought a bit to a solution but I didn't come out with something totally satisfactory. Unless you have a a lot of items in the tray  you can keep the dock slightly smaller to avoid interference. Moving the dock behind the legacyTray is not something straightforward as it would break other functionalities (drag and drop). I like the idea of hiding the dock when the tray is shown (and overlap the dock) instead. I'll think of it. 

One option in the meantime in case you didn't consider it is installing the topicons extension (https://extensions.gnome.org/extension/495/topicons/).

**Comment by a-m-s** [comment]
I switched from intelihide to plain autohide, for now. It's mostly the same effect anyway, and avoids this problem as long as there's at least one window open. The top icons thing doesn't sit well with my other extensions.

**Comment by micheleg** [comment]
Would having the legacyTray above (as in the elelements stack) fix the issue (experimental branch: https://github.com/micheleg/dash-to-dock/tree/test_below_legacytray)?

**Comment by anassahmed** [comment]
I don't understand what happened in this experimental branch, but I switched to it and restarted my shell and I can't notice any difference in the behavior (I'm using fixed size, intelli-hide, bottom bar right now). Is there a new setting to switch to the new behavior?

![screenshot from 2017-03-21 20-35-27](https://cloud.githubusercontent.com/assets/928614/24164323/f5c2e1f8-0e75-11e7-9ce0-fa0b32083640.png)

**Comment by franglais125** [comment]
@anassahmed Perhaps @micheleg forgot to commit something? That branch seems to be even with master, i.e. no new commits.

**Comment by anassahmed** [comment]
@franglais125 Yeah, I noticed that too. I thought maybe he sneaked the commit to the `master` branch. 😂

**Comment by micheleg** [comment]
You see nothing because I forgot to commit the changes! I have updated the branch.

**Comment by anassahmed** [comment]
OK, looks like it's working until I drag an app to it, then the dash returns back on top of _LegacyTray_. I've to disable the extension and enable it again to get it back on top of it.  
But at least it's working now better than before, and I don't keep the legacy tray open all day, just when I need to open it.

**Comment by micheleg** [comment]
@anassahmed Thanks for the feedback. I have updated the branch, now it should not fail after  drag and drop.

**Comment by micheleg** [comment]
I've merge the branch into master [b96491370ca0e6d].
