### ISSUE TITLE
Slow updating when windows are opened/closed

### ISSUE THREAD

**Issue by Gerlesh** [micheleg/dash-to-dock#1682]
When a window is opened (doesn't matter what program), the dock does not show the new apps for a long while (ranges from seconds to minutes). A similar issue occurs when closing, where instead of the icon disappearing, only the indicator dot disappears. The icon stays on for roughly the same amount of time as the opening takes to load.

```
$ dconf dump /org/gnome/shell/extensions/dash-to-dock/

[/]
animate-show-apps=true
background-opacity=0.80000000000000004
click-action='cycle-windows'
dash-max-icon-size=48
dock-fixed=false
dock-position='LEFT'
extend-height=false
height-fraction=0.90000000000000002
hide-delay=0.0
hot-keys=false
intellihide=false
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
isolate-workspaces=true
manualhide=false
multi-monitor=true
require-pressure-to-show=false
show-delay=0.0
show-favorites=false
show-mounts=false
show-running=true
show-show-apps-button=false
show-trash=false
```
Using Gnome 40.4.0 on Pop!_OS 21.10

**Comment by Jrfarl** [comment]
Experiencing a very similar issue. When I switch to x11 it stops happening, and switching back to wayland causes it to happen again.

`animate-show-apps=false
apply-custom-theme=true
autohide-in-fullscreen=true
background-opacity=0.80000000000000004
border-radius=30
click-action='minimize'
custom-theme-shrink=false
dash-max-icon-size=48
dock-position='BOTTOM'
extend-height=false
floating-margin=4
force-straight-corner=false
height-fraction=0.90000000000000002
hot-keys=true
icon-size-fixed=false
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
isolate-locations=false
isolate-workspaces=true
middle-click-action='previews'
preferred-monitor=0
preview-size-scale=0.0
scroll-action='cycle-windows'
scroll-to-focused-application=true
shift-click-action='minimize'
shift-middle-click-action='launch'
show-apps-at-top=false
show-favorites=true
show-mounts=false
show-running=true
show-show-apps-button=false
show-trash=false
show-windows-preview=false
transparency-mode='DEFAULT'
`
Using Gnome 41.3 on Fedora 35

**Comment by Microwave-WYB** [comment]
Same problem but happens to both X11 and Wayland when opening certain apps, like OBS and Typora.

**Comment by 3v1n0** [comment]
Is this handled by #1677 ?

**Comment by franciskafieh** [comment]
https://github.com/micheleg/dash-to-dock/pull/1677#issuecomment-1101931794 this fixed it for me!
