### ISSUE TITLE
[Regression] Isolate Workspace bug in both dash-to-dock (Fedora 35, Gnome 41) and ubuntu-dock (22.04 daily build, Gnome 42)

### ISSUE THREAD

**Issue by MrSnugglesGH** [micheleg/dash-to-dock#1685]
[Isolate workspace is on + static workspaces + No. of workspaces: 4]

1. Start Fedora or Ubuntu in Desktop view (If I remember correctly there was a problem in Gnome 41 so you can try it in Fedora 35 and in Ubuntu 22.04 daily build which uses Gnome 42)
2. Open any program. 
3. Go to overview. 
4. Use your mouse to drag the opened program from the workspace that program was in to another workspace in workspace switcher, but STAY IN THE SAME WORKSPACE IN THE OVERVIEW. 
5. Notice (while still in the overview and still in the workspace you started in) there are no opened windows, however there is a dot below the application in the dash, indicating that there is an application opened even though there should be no such indicator, since the application window is in another workspace (you moved it yourself in step 4.) ~~Clicking on that application does nothing if i remember correctly.~~ EDIT1: Clicking on that application opens new window.
6. Close the overview (get back to the desktop view) and you will still see the dot in the dock as if there was an application opened. If you try clicking on it, nothing happens. No new instance of the application opens, and neither do you get switched to the workspace where you moved the application to in step 4.

If you move to another workspace and then back to the same workspace, the dot will be gone in both dash (overview) and dock (desktop). This is how it should behave, since isolate workspace is on.

EDIT 2: in Ubuntu 20.04 (Gnome 3.36.8) this problem does not exist and therefore this could be counted as a regression.

**Comment by MrSnugglesGH** [comment]
Dash-to-panel extension for gnome 42 also had this bug, but now it's solved.

Here is the link for more info:
https://github.com/home-sweet-gnome/dash-to-panel/issues/1610

**Comment by 3v1n0** [comment]
Do you still have this issue?
