### ISSUE TITLE
Autohide sometimes does not works correctly when hovering over the dock and leaving it

### ISSUE THREAD

**Issue by rivetchip** [micheleg/dash-to-dock#1689]
Hello,

The 'autohide' functionality does not always works correctly when we hover over the dock and then leaving it.

As you can see in the screenshot below, the cursor was outside the dock, but the dock is still visible :  

It seems the dock thinks I'm still hovering an icon (you can see the hover effect on the "Transmission" application) but the cursor is outside of the dock.

![2022-03-28 00-27-40](https://user-images.githubusercontent.com/7000625/160304016-f2965edb-a989-4731-b3ed-0ea80742425d.png)

System information : 
- Dash to dock version : latest master commit https://github.com/micheleg/dash-to-dock/commit/6f717302747931de6bf35bc9839fb3bd946e2c2f
- Fedora 35
- Gnome Shell 41.5
- Display : X11
- Extensions : only Dash to dock used

Just in case : I have basic knowledge in GTK and Gnome Shell extensions development, so I can try and tests if needed! :) 

Dconf dump : 

```
dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
animation-time=0.20000000000000001
apply-custom-theme=false
autohide=true
autohide-in-fullscreen=false
background-opacity=0.80000000000000004
click-action='minimize'
custom-background-color=false
custom-theme-shrink=false
dash-max-icon-size=48
dock-position='BOTTOM'
extend-height=false
force-straight-corner=false
height-fraction=0.90000000000000002
hide-delay=1.3877787807814457e-17
icon-size-fixed=false
intellihide=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
multi-monitor=true
preferred-monitor=-2
preferred-monitor-by-connector='DP-4'
pressure-threshold=100.0
require-pressure-to-show=false
scroll-action='cycle-windows'
show-apps-at-top=false
show-delay=1.3877787807814457e-17
show-mounts=false
show-show-apps-button=true
show-trash=false
show-windows-preview=false
transparency-mode='DEFAULT'
```

**Comment by ZZYSonny** [comment]
Same issue on GNOME 42.

**Comment by pukmajster** [comment]
Same issue on Fedora 35, Gnome41 and X11 aswell

**Comment by k1gen** [comment]
Same issue on GNOME 42 (Arch Linux, Wayland).

**Comment by RedCommand** [comment]
Same issue on Fedora 36 wayland

**Comment by rivetchip** [comment]
I experienced the same issue on the "Dock to dash" extension, it seems they had the same issue : https://github.com/fthx/dock-from-dash/issues/22 

Maybe it's related to the "Dash" object or Gnome Shell itself.

![Capture d’écran de 2022-04-08 18-47-16](https://user-images.githubusercontent.com/7000625/162486968-dc4ca013-4732-4193-933a-5b073f04e711.png)

**Comment by 3v1n0** [comment]
It looks like this is upstream by https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321/diffs?commit_id=0280b0aaa563db65bf79a3643f6a9e8e76bfe458

Please reopen if it's not the case.
