### ISSUE TITLE
Bar doesn't auto hide after draging icon out

### ISSUE THREAD

**Issue by Shihira** [micheleg/dash-to-dock#169]
Hello. (I incautiously pressed Enter while editing title so a litter old issue is out there. Feeling sorry.)
Sometimes I accidentally drag an icon out of the dock, and drop down, and then the icon went back the dock as usual. Now the dock cannot hide by itself. I have to call the activity screen and go back to hide the dock or it will disturb me. Looking forward to a fix.

**Comment by micheleg** [comment]
I can't reproduce the problem on my system. Which  extension /GNOME version are you using?

**Comment by Shihira** [comment]
I was using version 39. The latest version has fixed this problem. Sorry for disturbing.
