### ISSUE TITLE
Error "Main.panel._leftCorner" on Gnome 42 and gjs 1.72.0 (Debian sid)

### ISSUE THREAD

**Issue by palWorx** [micheleg/dash-to-dock#1691]
Following this https://github.com/kgshank/gse-sound-output-device-chooser/pull/230 it looks like the constructors in dash-to-dock are the problem.

"Main.panel._leftCorner" is found  in docking.js, along with constructors - just as a hint, because i know nothing about JS.

**Comment by BubbyNX** [comment]
Also experiencing this issue on Fedora 36!

**Comment by brainstormtrooper** [comment]
Could be because the rounded corners are no longer present in Gnome 42?
