### ISSUE TITLE
Two docks after lock screen

### ISSUE THREAD

**Issue by g0J0na** [micheleg/dash-to-dock#1700]
Ubuntu 20.04.4 LTS
After lock screen , it create a new dock in left side
![image](https://user-images.githubusercontent.com/90030004/162222184-211663e7-16d9-4a7c-89dd-693f6f810409.png)

**Comment by emansom** [comment]
Get a new eyeglass prescription, it shows in the extensions tab of GNOME Tweaks that both Ubuntu dock (Dash to Dock fork) and Dash to Dock itself are enabled. Thus, yes, two instances are running.

**Comment by g0J0na** [comment]
thanks
