### ISSUE TITLE
Show mounted volumes and devices crashes GNOME

### ISSUE THREAD

**Issue by obitsudog** [micheleg/dash-to-dock#1701]
For the past week or so, I've been experiencing an issue with the GNOME Shell Extension, Dash to Dock.  Specifically, the issue is with Dash to Dock's Show mounted volumes and devices component.

If Show mounted volumes and devices is enabled, and I click on an external USB hard disk in the dock, then GNOME Shell crashes, with the following message:

"Oh no! Something has gone wrong.  A problem has occurred and the system can't recover.  Please log out and try again."

Once logged back in, GNOME Shell extensions are disabled and must be toggled back to the on position.

Disabling Show mounted volumes and devices is a work-around.  I can still access external disks via Files.  Re-enabling Show mounted volumes and devices causes the issue described, once again.

System:
$ uname -a
Linux kali 5.16.0-kali6-amd64 #1 SMP PREEMPT Debian 5.16.14-1kali2 (2022-03-23) x86_64 GNU/Linux

$ gnome-shell --version
GNOME Shell 41.4

$ apt-cache show gnome-shell-extensions
Version: 41.1-2kali1

$ apt-cache show gnome-shell-extension-dashtodock
Version: 71-1

$ echo $XDG_SESSION_TYPE
x11

**Comment by 3v1n0** [comment]
See #1656

**Comment by obitsudog** [comment]
The issue has been fixed with an update from Kali.

`$ apt-cache show gnome-shell-extension-dashtodock`
`Version: 72~ubuntu5-0kali1`
