### ISSUE TITLE
"Main.panel._rightCorner is undefined" on Gnome 42

### ISSUE THREAD

**Issue by Superangers** [micheleg/dash-to-dock#1702]
I modified the metadata.json file to install it on Gnome 42 but I get an error in the extensions manager: "Main.panel._rightCorner is undefined".

**Comment by Superangers** [comment]
And it's broken when I check the "extend to the screen edge" option

**Comment by ugjka** [comment]
I just use the "ubuntu-dock" branch for time being

**Comment by 3v1n0** [comment]
It's handled by https://github.com/micheleg/dash-to-dock/pull/1656/commits/52d983fc7cb9b1cd8f30f2d9e25577cadff8f8ed

**Comment by rayshabh** [comment]
> It's handled by [52d983f](https://github.com/micheleg/dash-to-dock/commit/52d983fc7cb9b1cd8f30f2d9e25577cadff8f8ed)

Was facing an error “Main.panel._leftCorner is undefined”; made some changes in docking.js according to https://github.com/micheleg/dash-to-dock/commit/52d983fc7cb9b1cd8f30f2d9e25577cadff8f8ed but still the error persists.
![Screenshot from 2022-04-19 23-42-49](https://user-images.githubusercontent.com/43938393/164071462-45033c19-c194-466a-ae45-c2eef6d49b54.png)

Please help!

**Comment by rayshabh** [comment]
Also, cannot view the dash to dock setting properly.
![Screenshot from 2022-04-20 00-02-11](https://user-images.githubusercontent.com/43938393/164071825-99d0b8fe-6327-4138-9d8a-5acee31899be.png)

**Comment by rayshabh** [comment]
> Also, cannot view the dash to dock setting properly. ![Screenshot from 2022-04-20 00-02-11](https://user-images.githubusercontent.com/43938393/164071825-99d0b8fe-6327-4138-9d8a-5acee31899be.png)

**UPDATE**
This issue got fixed by installing Ubuntu-dock from https://github.com/micheleg/dash-to-dock.git -b ubuntu-dock

![Screenshot from 2022-04-21 11-57-42](https://user-images.githubusercontent.com/43938393/164388204-a4dfdfd9-e249-47c0-9d5b-8b035703690f.png)
Now, I'm able to view the setting properly!

**Comment by rayshabh** [comment]
> > It's handled by [52d983f](https://github.com/micheleg/dash-to-dock/commit/52d983fc7cb9b1cd8f30f2d9e25577cadff8f8ed)
> 
> Was facing an error “Main.panel._leftCorner is undefined”; made some changes in docking.js according to [52d983f](https://github.com/micheleg/dash-to-dock/commit/52d983fc7cb9b1cd8f30f2d9e25577cadff8f8ed) but still the error persists. ![Screenshot from 2022-04-19 23-42-49](https://user-images.githubusercontent.com/43938393/164071462-45033c19-c194-466a-ae45-c2eef6d49b54.png)
> 
> Please help!

**UPDATE**
Finally, I found the reason behind the strange rectangle box issue!

![Screenshot from 2022-04-21 11-51-05](https://user-images.githubusercontent.com/43938393/164388443-b473814e-22b6-4552-8dcb-cea48995e31e.png)

The issue got fixed when I disabled the “Dash to Dock Blur effect” in Blur my Shell extension settings.


![Screenshot from 2022-04-21 11-51-19](https://user-images.githubusercontent.com/43938393/164388523-74436784-4950-4733-95ba-8117b92beea9.png)

Ubuntu-Dock branch works well in my system.
