### ISSUE TITLE
Gnome 42 Support

### ISSUE THREAD

**Issue by dmike3** [micheleg/dash-to-dock#1704]
Can't wait for gnome 42 support.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, please !

**Comment by ugjka** [comment]
I just use the "ubuntu-dock" branch for time being

**Comment by codevski** [comment]
> I just use the "ubuntu-dock" branch for time being

When having the extension enabled the overview workspace screen is missing...

![image](https://user-images.githubusercontent.com/1435321/162653181-444080e2-88ba-4858-a5f6-5e50565dfca5.png)
