### ISSUE TITLE
ubuntu-dock branch

### ISSUE THREAD

**Issue by starsareintherose** [micheleg/dash-to-dock#1712]
- OS: archlinux
 - commit: b695cee218444eb733372903b02a5966e0318c79

![截图 2022-04-11 22-02-35](https://user-images.githubusercontent.com/37733075/162831827-8b1f7f1b-6d85-4932-9b97-cee2c0eaef9b.png)

Issue1: I choose auto transparent, it shows like this in nautilus, it should be darker, but so white

Issue2: when I right-click the left icon, I can't set the extension

**Comment by 3v1n0** [comment]
1 is due to theme, 2 is fixed.
