### ISSUE TITLE
Dock shrinks when window is open (ubuntu-dock)

### ISSUE THREAD

**Issue by loulou921222** [micheleg/dash-to-dock#1714]
Arch Linux
GNOME 42
X11

When selecting windows, the dock shrinks down. If I scroll with the scroll wheel, it drops down.

https://user-images.githubusercontent.com/39203111/163567286-8d48974b-3fce-468c-860c-bec098c3627c.mp4

**Comment by loulou921222** [comment]
Settings: (sorry I can't easily get it to display in a different language)
![image](https://user-images.githubusercontent.com/39203111/163567440-09fbae01-13a7-4742-b803-51f16d8404d5.png)
![image](https://user-images.githubusercontent.com/39203111/163567487-6bbc5de1-37ce-48ce-b2ab-feed39d9b90b.png)
![image](https://user-images.githubusercontent.com/39203111/163567492-abf79af3-345c-4d91-a3e2-14e79cf86e36.png)
![image](https://user-images.githubusercontent.com/39203111/163567506-0dbc085f-cb00-4964-8d5e-76dc83e84ffc.png)

**Comment by loulou921222** [comment]
with the menu on my second monitor, scrolling drops it to the main monitor

**Comment by vanvugt** [comment]
Resolved in #1739.

For information about when the fix will be released however see https://bugs.launchpad.net/bugs/1967121
