### ISSUE TITLE
Secondary monitor dock flashing over discord

### ISSUE THREAD

**Issue by CoreyTV** [micheleg/dash-to-dock#1716]
When I am using intelligent hide and have dash to dock enabled on all monitors at the bottom of the screen, when my focused window is Discord and maximized, only on my second monitor, the dock flashes/flickers at the bottom of my screen. I'm on fedora 35 GNOME version 41.5 I have tried changing animation time and auto hide time, pressure threshold, and disabled hardware acceleration in discord. reinstalled dash to dock etc. I'm using version 41.71. Love this extension and cant live without it. I hope it is a simple solution or easy patch. It seems to work with 99% of applications, but it is very noticeable on discord specifically, not doing it on most other applications, so it may be something to open with discord. Dash to Panel does it as well with discord, so it may be on their end. Thanks if it helps replicate the issue, my secondary monitor is my left monitor. both monitors are 1080p, left is 23 inches and 60 hz, right (main) is 27 inches and 144 hz

**Comment by CoreyTV** [comment]
> When I am using intelligent hide and have dash to dock enabled on all monitors at the bottom of the screen, when my focused window is Discord and maximized, only on my second monitor, the dock flashes/flickers at the bottom of my screen. I'm on fedora 35 GNOME version 41.5 I have tried changing animation time and auto hide time, pressure threshold, and disabled hardware acceleration in discord. reinstalled dash to dock etc. I'm using version 41.71. Love this extension and cant live without it. I hope it is a simple solution or easy patch. It seems to work with 99% of applications, but it is very noticeable on discord specifically, not doing it on most other applications, so it may be something to open with discord. Dash to Panel does it as well with discord, so it may be on their end. Thanks if it helps replicate the issue, my secondary monitor is my left monitor. both monitors are 1080p, left is 23 inches and 60 hz, right (main) is 27 inches and 144 hz

Turns out wayland was the issue. I'm using fedora 35 that defaults to wayland. Hope this helps people in the future

**Comment by gbegkas** [comment]
I have the same issue. I am using Arch with Nvidia and this started to happen when I changed to Wayland. The dock is flashing only on the second monitor and only when a window is maximized. The dock is fine when no window on the second screen is maximized.
