### ISSUE TITLE
Strange Square cut corners and incomplete settings view page!

### ISSUE THREAD

**Issue by rayshabh** [micheleg/dash-to-dock#1719]
How do I fix these issues?
![Screenshot from 2022-04-19 23-42-49](https://user-images.githubusercontent.com/43938393/164091713-93984366-487d-46a6-95a8-1274021a4e86.png)
Strange black rectangle box behind the dock; made some changes in docking.js according to https://github.com/micheleg/dash-to-dock/commit/52d983fc7cb9b1cd8f30f2d9e25577cadff8f8ed but still the error persists.

![Screenshot from 2022-04-20 00-02-11](https://user-images.githubusercontent.com/43938393/164091718-8f75e102-666a-452e-bd38-8b712e58c18a.png)
Issue with the extension setting view!!

Please help!!

# Details:
Arch Linux
Gnome 42

**Comment by 3v1n0** [comment]
Use the ubuntu-dock branch, it should handle both these issues.

**Comment by rayshabh** [comment]
> > Use the ubuntu-dock branch, it should handle both these issues.
> 
> Here's the result after installing ubuntu-dock branch - ![Screenshot from 2022-04-20 19-44-28](https://user-images.githubusercontent.com/43938393/164251487-8526149b-8238-4cd8-818b-cad9efedc308.png) The extension setting view is now restored.
> 
> ![Screenshot from 2022-04-20 19-44-54](https://user-images.githubusercontent.com/43938393/164251625-de5656e1-721b-4f57-be49-20182796aa27.png) But the strange rectangle box issues still persist.
> 
> Please help!

**UPDATE**
Finally, I found the reason behind the strange rectangle box issue!
![Screenshot from 2022-04-21 11-51-05](https://user-images.githubusercontent.com/43938393/164387323-4cf8487f-9dbd-4982-a19a-23c007314083.png)
The issue got fixed when I disabled the “Dash to Dock Blur effect” in Blur my Shell extension settings. 

![Screenshot from 2022-04-21 11-51-19](https://user-images.githubusercontent.com/43938393/164387391-646221e3-7692-48e9-ab83-08dcb5fc83bb.png)
Ubuntu-Dock branch works well in my system.
