### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by Vistaus** [micheleg/dash-to-dock#172]
Hello,

I've translated Dash-To-Dock to Dutch based on the current Git version :-) Thanks for making this great extension!
https://onedrive.live.com/redir?resid=7a03150cc9bee130!22479&authkey=!ALAKS-N59u7x9-Q&ithint=file%2cpo

**Comment by micheleg** [comment]
Thank you. I merged it into master and in the gnome-3.14 branch and will be available in the next release which I'm going to prepare.
