### ISSUE TITLE
Weird display dock after upgrading Debian 10

### ISSUE THREAD

**Issue by shakai1** [micheleg/dash-to-dock#1723]
I am using Debian 10. After upgrading my packages today using apt upgrade this happened to the dock. Dash-to-dock-settings stopped working.

![gnome-bug](https://user-images.githubusercontent.com/98556687/164952074-ed9268af-898b-4519-b968-b138ca3beff6.png)

**Comment by shakai1** [comment]
I have rolled back a snapshot, and upgraded my system again and happened exactly same thing. This time I have the error message of dash-to-dock setting

`GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui”: No such file or directory

Stack trace:
  _init@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:198:27
  DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:182:4
  buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:1013:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:219:40
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:175:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:128:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by shakai1** [comment]
Dash-To-Dock for COSMIC extension fixed the issue completely.

**Comment by 3v1n0** [comment]
Are you using ubuntu-dock branch? If not, master will be fixed soon.
