### ISSUE TITLE
Trash on the Dash

### ISSUE THREAD

**Issue by luigidr** [micheleg/dash-to-dock#173]
Hi,

first of all, thanks for your amazing and useful extension. I'm using it daily on Fedora 21 (and soon on Fedora 22).

I was wondering if you plan to add a trash/recycle bin option for showing the trash in the dock, like in Unity or in this [derivative](https://github.com/itprojects/gnome-dock) of your extension (that doesn't work, at the moment).

What do you think? Could it be a useful feature (not only for me)?

**Comment by micheleg** [comment]
This would be a nice optional addition, I agree. I'm aware of that derivative of my extension. However, I find a trash icon not that useful if one can't drag an drop things on it. Unfortunately, this is not possible right now due to lack of upstream support as explained in issue #49.

**Comment by luigidr** [comment]
Thanks for the quick reply!
Personally, I drag things on the trash very rarely, but I get the point. :-)

**Comment by micheleg** [comment]
So what would you do with the trash icon on the dock? Just empty it?

**Comment by bulletmark** [comment]
Having a Trash icon anywhere specially convenient is an archaic idea which desktops blindly mimicked from the original 1980's Mac. Should the other "special" directories like Documents, Downloads, Pictures, etc be added to the dock also? Modern desktops, particularly GNOME, have depreciated the Trash desktop icon metaphor. I scoff whenever I see a Trash icon on anyone's Desktop so if this idea gets implemented, please ensure it can be configured off! :)

**Comment by luigidr** [comment]
@micheleg Basically, yes: see the trash status (empty/not empty), open it directly, and empty it.

@bulletmark I agree on the configuration option, to turn the functionality on or off (if it will be implemented). Then, I see a difference between the trash and other "standard" directories (Documents, Downloads, etc.): they don't have a "binary state" (i.e., empty/non empty) nor any "special" action associated (i.e., "empty the trash"). Moreover, I think that "on the dock" is different from "on the Desktop": for me, it could be convenient to have the trash on the dock, but I don't have the trash on the Desktop. ;)

**Comment by ainola** [comment]
From a design paradigm, the dock is supposed to be an 'Application Switcher' for managing your windows and application workflow. Trash (and other file-related activities) are best left to the file manager itself: Indeed, all the file managers have an easily-found trash icon in which a user can drag if need be. There's no reason to make the two interact from both a design perspective and code-maintenance perspective.

Just my two cents.

**Comment by rickhall** [comment]
Just my $0.02, I would love to have the trash icon on the dash bar. I have grown use to this on my macbook as well as having the downloads folder. However, I agree that it doesn't make much sense if you can drag stuff onto it. Here's to hoping that is a possibility in the future.

**Comment by lordadamson** [comment]
I would love to see this (with drag and drop support). I'm ready to contribute code but the documentations are really scarce. Would love some guidance if you will.

**Comment by rickhall** [comment]
Regarding "design" arguments about this topic, I think it is not so clear cut. At a minimum, it is not just an "app switcher", but an "an app launcher shortcut mechanism and an app switcher", so at its most basic it already serves multiple purposes. Whereas something like "alt-tab" is purely an "app switcher".

Accepting that it is a shortcut mechanism, then it is also easy to understand why it makes sense from a design perspective to make it a slightly more general shortcut mechanism for things like [standard] folders. So, I'm definitely +1 for this.

**Comment by dan** [comment]
+1

**Comment by highvoltage** [comment]
I had this request from a few of my users too. I installed the 'trash' shell extension which puts a trash icon in the panel only when they have files in trash, and the feedback so far has been good.

**Comment by lordadamson** [comment]
@highvoltage are you the developer of dash-to-panel?

**Comment by corebots** [comment]
I’d like to have a trash icon in the dock for the reasons of having an always visible and fast accessible trash can to drop files and folders onto it. having a trash can on the desktop seems less helpful as it often gets hidden below windows; whereas on the dock it would be always accessible.

I think it comes down to having shortcuts for commonly accessed places at hand with drag&drop functionality; trash on dock would be just a folder - you can drop/move files into it - they’re just being stored there until you empty it(with the addition of indicating the empty/full status)…. just like having a videos folder on the dock, you drop files on it from everywhere, and later watch them.

**Comment by highvoltage** [comment]
@lordadamson I'm not, but I package it for Debian.

**Comment by dvorapa** [comment]
This seems to be solved since the last release!

**Comment by micheleg** [comment]
Closed by 80928137b61ca94ed
