### ISSUE TITLE
Gnome 42 - What is happening with Dash to Dock?

### ISSUE THREAD

**Issue by damienbutt** [micheleg/dash-to-dock#1730]
Hi all,

This is by far the most important extension to me and sadly since Gnome 42 on Arch Linux, it just hasn't worked for me. 

I am a little confused with what's going on with regards to the whole dash-to-dock/ubuntu-dock thing. Is anyone able to clarify? The website calls it dash-to-dock, the repo calls it dash-to-dock, but after a recent update shortly after Gnome 42 landed, suddenly it is showing up in my extensions list as ubuntu-dock. 

I have always had this extension installed using the gnome-shell-extension-dash-to-dock package from the AUR. Not had any issues until Gnome 42. 
<img width="933" alt="Screenshot 2022-05-03 at 22 25 25" src="https://user-images.githubusercontent.com/22627489/166569173-5f4ceaee-4c2c-438c-918e-397038152642.png">
<img width="606" alt="Screenshot 2022-05-03 at 22 25 00" src="https://user-images.githubusercontent.com/22627489/166569256-a1333957-c765-4955-9e2e-483455811208.png">
<img width="650" alt="Screenshot 2022-05-03 at 22 26 00" src="https://user-images.githubusercontent.com/22627489/166569304-dc1996eb-4dc1-4adf-8db2-9d7cd00783bc.png">
<img width="2560" alt="Screenshot 2022-05-03 at 22 30 01" src="https://user-images.githubusercontent.com/22627489/166569725-8ac416d0-9469-4ab8-b07c-51d73232bec3.png">

It has those black bits around the edges, the opacity is not working at all, and the app indicators are incorrectly placed.

I have also tried cloning the repo and building from the source. The extension shows up as incompatible with Gnome 42.

Is there something I am missing? Is there a specific version I need to use?

Thanks,
D

**Comment by ajoy39** [comment]
Also experiencing issues on Gnome 42, Ubuntu 22.04 for me. The dock is there, I can see it if I hit the super key, but I can't get it to show any other way. In the Gnome extensions menu it says the package is incompatible with the current Gnome version and it shows as disabled, even though I can still see it sometimes. The settings menu is also no longer accessible, the content seems to be there but it's pushed up so far in the container you can't see it. I also see the ubuntu dock extension option , but turning it on yields something that is definitely not the dock I have setup and that I can't make any changes too seemingly

**Comment by damienbutt** [comment]
> If you got it from AUR, then you need to read the comments on AUR — you'll usually find your answers there. They've switched to using the [ubuntu dock branch](https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock) for the AUR package, probably because the main branch still isn't compatible with Gnome 42. They've indicated that they'll switch back to the main branch once it becomes compatible with Gnome 42.

My bad. Completely forgot to check on the AUR.

**Comment by zhangtianze1997** [comment]
> Also experiencing issues on Gnome 42, Ubuntu 22.04 for me. The dock is there, I can see it if I hit the super key, but I can't get it to show any other way. In the Gnome extensions menu it says the package is incompatible with the current Gnome version and it shows as disabled, even though I can still see it sometimes. The settings menu is also no longer accessible, the content seems to be there but it's pushed up so far in the container you can't see it. I also see the ubuntu dock extension option , but turning it on yields something that is definitely not the dock I have setup and that I can't make any changes too seemingly

Same issue after updating to Ubuntu 22.04

**Comment by Dorro101** [comment]
Fedora 36 is now available. Dash-to-dock is a must have extension for me, before I can install the new version. Any idea when it will be available for Gnome 42? I installed PopOS's version in the Live Install Image for Fedora 36, it seems to work fine... I would prefer to install the original, as I prefer to support the creator rather than a fork. A shout out and many thanks to micheleg for for his work and supporting this fantastic extension!

**Comment by gcbishal** [comment]
@Dorro101 yeah. as an alternative i am using 'Dock from dash' extension. It works fine, misses few features though. You can try it. Waiting for the gnome 42 compatibility update....

**Comment by mimminou** [comment]
You can switch to Dash to dock for cosmic, at least for now, it's a fork of this repo.

**Comment by gcbishal** [comment]
@mimminou works, but the dock appears to have black border around the rounded edge.

**Comment by dnut** [comment]
This project has been abandoned. Gnome 42 support has existed for a long time in other forks. The community needs to identify the best fork.

The cosmic fork seems best for now: https://extensions.gnome.org/extension/5004/dash-to-dock-for-cosmic/

**Comment by mimminou** [comment]
> @mimminou works, but the dock appears to have black border around the rounded edge.

Use the default theme in it's settings, there is a switch that disables gnome shell theming or something similar to this.

**Comment by gcbishal** [comment]
> > @mimminou works, but the dock appears to have black border around the rounded edge.
> 
> Use the default theme in it's settings, there is a switch that disables gnome shell theming or something similar to this.

I fixed it, I disabled the dash section from 'blur my shell'.

**Comment by rugk** [comment]
Yeah, also on Fedora 36 and unfortunately dash-to-dock does not work/is not compatible…
![grafik](https://user-images.githubusercontent.com/11966684/168245731-085b5bed-fd7a-4367-af0d-9ae52fc319cb.png)

**Comment by dschemp** [comment]
> > > @mimminou works, but the dock appears to have black border around the rounded edge.
> > 
> > 
> > Use the default theme in it's settings, there is a switch that disables gnome shell theming or something similar to this.
> 
> I fixed it, I disabled the dash section from 'blur my shell'.

Oh. Yeah that's seems to be fix my issue aswell.
But that does not change the fact that I am sad about the Dash to Dock not being available for Gnome 42 :(

**Comment by damienbutt** [comment]
> > > @mimminou works, but the dock appears to have black border around the rounded edge.
> > 
> > 
> > Use the default theme in it's settings, there is a switch that disables gnome shell theming or something similar to this.
> 
> I fixed it, I disabled the dash section from 'blur my shell'.

Thank you! Moved over to the Cosmic fork and then disabled that setting in "Blur my Shell". Now working great again.

Also, found I had to explicitly set the window counter indicators to be "Dots" to fix the alignment issue.

**Comment by gcbishal** [comment]
There just one issue, I just want blur in my dock. hope the cosmic will  be updated with blur option feature.

**Comment by LoneFenris** [comment]
With #1656 now having been merged for a while, should we be expecting to see an e.g.o update in the near future?

**Comment by RyzenDew** [comment]
> This project has been abandoned. Gnome 42 support has existed for a long time in other forks. The community needs to identify the best fork.
> 
> The cosmic fork seems best for now: https://extensions.gnome.org/extension/5004/dash-to-dock-for-cosmic/

This project is not abandoned and never was and works fine on gnome 42 no issues bugs or glitches from my experience

**Comment by deoxyseia** [comment]
For me, it appears as disabled and unsupported for Fedora 36 after upgrade.

**Comment by LoneFenris** [comment]
> > 
> > 
> > This project is not abandoned and never was and works fine on gnome 42 no issues bugs or glitches from my experience
> 
> @RyzenDew you mean that dash to dock works on Gnome 42? It's not selectable as @deoxyseia said

At the moment, it still appears to need to be released to e.g.o for it to auto-update. But if you manually install from the master repo, it looks like it should work on Gnome 42 (or at least it is now marked as supported in metadata.json since #1656 was merged).

**Comment by loxK** [comment]
> > > This project is not abandoned and never was and works fine on gnome 42 no issues bugs or glitches from my experience
> > 
> > 
> > @RyzenDew you mean that dash to dock works on Gnome 42? It's not selectable as @deoxyseia said
> 
> At the moment, it still appears to need to be released to e.g.o for it to auto-update. But if you manually install from the master repo, it looks like it should work on Gnome 42 (or at least it is now marked as supported in metadata.json since #1656 was merged).

I installed it from source, it works and has a few quirks. But, it gets automatically downgraded from https://extensions.gnome.org. (Ubuntu 22.04)

**Comment by maop** [comment]
> I installed it from source, it works and has a few quirks. But, it gets automatically downgraded from https://extensions.gnome.org. (Ubuntu 22.04)

Im having this issue too, does anyone know how to block the downgrade?

**Comment by LoneFenris** [comment]
@maop @loxK 

Some methods to prevent downgrade from Git version are discussed in #1745 , the quickest and dirtiest way is probably https://github.com/micheleg/dash-to-dock/issues/1745#issuecomment-1145876461

The reason for delay is also cited on that issue (e.g.o review was failed, there are further changes needed to pass)
