### ISSUE TITLE
sassc: no such file or directory

### ISSUE THREAD

**Issue by dikshantdk** [micheleg/dash-to-dock#1734]
make -C dash-to-dock install
make: Entering directory '/home/brainiac/dash-to-dock'
sassc --omit-map-comment _stylesheet.scss stylesheet.css
make: sassc: No such file or directory
make: *** [Makefile:66: stylesheet.css] Error 127
make: Leaving directory '/home/brainiac/dash-to-dock'

**Comment by olivierb2** [comment]
This is nothing to do with dash-to-dock, but you have to install sassc command.

On ubuntu, do

    sudo apt install sassc

**Comment by zyhusesit** [comment]
I stuck in this too

**Comment by zyhusesit** [comment]
> 
thanks

**Comment by ran-dall** [comment]
I would recommend you install [the `dart-sass` package](https://www.npmjs.com/package/sass), directly with NPM. Then you should be able to make it with `SASS=dart make **`

**Comment by asynchroza** [comment]
on arch `yay -S sassc`
