### ISSUE TITLE
Ubuntu 22.04: non-interactive pixels at the edge of the screen

### ISSUE THREAD

**Issue by arty-name** [micheleg/dash-to-dock#1736]
I am using vanilla Ubuntu with its version of Dash to dock. After the upgrade to 22.04 I have noticed that sometimes I cannot focus an application by clicking its icon in the dock. 

The dock is on the left side of the screen. There’s a two pixels margin between the app icon and the edge of the screen. If I move my mouse pointer all the way to the left, it will be over those two pixels, and not over the app icon. Clicking there will have no effect, the app will not come into focus. 

I think it was the outcome of the classical UX research that the elements should extend all the way to the very edge of the screen so that it is almost impossible to miss them. This is how Dash to dock behaved in Ubuntu until 22.04.

**Comment by vanvugt** [comment]
Downstream Ubuntu bug: https://launchpad.net/bugs/1966167

**Comment by arty-name** [comment]
Thank you! I failed to find it on LaunchPad. I don’t have the knowledge to decide what to do now with this issue on GitHub.

**Comment by cemerick** [comment]
Yes, just upgraded to 22.04, and this change/regression is incredibly painful. Would love to know of an alternative to use until this is resolved, though I haven't found one after trying a half-dozen gnome extensions.

**Comment by faveoled** [comment]
Still present on Ubuntu 22.04.1 LTS
