### ISSUE TITLE
Workspace switching by scrolling does not work

### ISSUE THREAD

**Issue by Arcoth** [micheleg/dash-to-dock#174]
It simply... doesn't, while it certainly did with earlier versions of Gnome/Dash-to-Dock.
Tested with Gnome 3.16 on Arch. It doesn't work regardless of whether Intelligent Autohide is activated.

**Comment by micheleg** [comment]
Not a real bug, but a result of the introduction of the scrollable dock as explained in this commit message https://github.com/micheleg/dash-to-dock/commit/b13eb499c0dda7b6af56c67b474b164d5e0f43e0

The very edge of the dock close to the screen border should still be active, if the theme you are using has some padding.

**Comment by prdiewelt** [comment]
First of all: Thank you for your great work. Honestly speaking, I think this specific change is a regression. Using the theme Vertex not even the very edge of the screen is scrollable. In my opinion it is more convenient if you do not have to look for the “Show applications” button before being able to change the desktop. I am also on Arch and Gnome 3.16 and use version 46 of the extension.

**Comment by micheleg** [comment]
You might call it regression. If the feature is really import for you, I suggest to temporary downgrade to version 42 that can be downloaded here https://micheleg.github.io/dash-to-dock/releases.html

I decided to drop that option because it looked a bit weird on a horizontal dock and because of the incompatibility with the scrolling option, and I was trying to clean up a bit the extension. I might consider reintroducing it, but I have to find out a consistent way to present the option to the users.

**Comment by prdiewelt** [comment]
Very strange! Suddenly it works when I scroll at the pixel on the screen edge. No idea what changed.

**Comment by Arcoth** [comment]
> If the feature is really import for you, I suggest to temporary downgrade to version 42 that can be downloaded here https://micheleg.github.io/dash-to-dock/releases.html

This option is vital for me, and surely is for other people as well. It provides an incredibly comfortable way of switching workplaces.

> I might consider reintroducing it, but I have to find out a consistent way to present the option to the users.

Please reintroduce it.

**Comment by Tadly** [comment]
Upvote from my site

As said by Arcoth it really is incredibly comfortable to use this feature.
Further I can confirm that scrolling only works when hovering the "Show Applications" icon (and the edge beside it) which I tested with the stock-theme and Arc (gnome 3.16). However using the built-in theme will allow scrolling on the very edge as well.

Still, would be great to see this getting reintroduced :)

**Comment by CarlosManuelRodr** [comment]
Please, put this feature back! I think it's one of the best things of this extensions.
And thanks, this extensions it's so good that I can't use Gnome without it.

**Comment by micheleg** [comment]
There is an experimental branch trying to bring back the old behaviour (https://github.com/micheleg/dash-to-dock/tree/restore_scrollworkspace). Please check if it is working properly. 

The whole dock is sensitive the scroll events again, apart from when the case scrolling of the dock launchers is required. In this case,  the sensitive area is the show apps icons only (the current behaviour).

**Comment by micheleg** [comment]
The feature is back in current master 64b30ca76.
