### ISSUE TITLE
Buggy after Latest Manjaro Updates

### ISSUE THREAD

**Issue by pesfahanian** [micheleg/dash-to-dock#1742]
I had the extension installed and working properly.
After the latest updates, it works OK, but gives the following error on the extension app:
![image](https://user-images.githubusercontent.com/48320537/168423569-29e8c665-ad8d-46c0-877e-aee2d1d85445.png)
Error message is:
`Main.panel._leftCorner is undefined`

My `Extensions (gnome-shell)` version is `42.1`

**Comment by fuale** [comment]
```
/**
 * Adjust Panel corners, remove this when 41 won't be supported anymore
 */
_adjustPanelCorners() {
    if (!Main.panel._rightCorner || !Main.panel._leftCorner)
        return;
```
The time has come 🤔🤔.
Just need to add check: `"_rightCorner" in Main.panel` or smth

**Comment by javadr** [comment]
Same issue with Majaro update to Gnome 42.1

**Comment by pesfahanian** [comment]
> ```
> /**
>  * Adjust Panel corners, remove this when 41 won't be supported anymore
>  */
> _adjustPanelCorners() {
>     if (!Main.panel._rightCorner || !Main.panel._leftCorner)
>         return;
> ```
> 
> The time has come thinkingthinking. Just need to add check: `"_rightCorner" in Main.panel` or smth

Where should I add this piece of code?

**Comment by calexandru2018** [comment]
> There is a file called 'docking.js', on my system it is in the path (/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js)
> 
> There is a method called like this '_adjustPanelCorners' (near the end of the code), just add the if statement.
> 
> ![image](https://user-images.githubusercontent.com/19317011/173378491-6f1d9e7f-2039-4886-bd8a-52334761c7da.png)
> 
> Remember reboot or log out!


I would say that if statement is a bit incorrect, mostly because if one of them does not exist the code below will crash regardless, my suggestion is to slightly modify it and ensure consistency:
![image](https://user-images.githubusercontent.com/31934100/178928168-2efec415-0aca-421c-9103-d651e28bcf4d.png)
```
if (!Main.panel._rightCorner && !Main.panel._leftCorner) {
    return;
}
```
