### ISSUE TITLE
Git vs Extensions.Gnome.Org?

### ISSUE THREAD

**Issue by Bananaman** [micheleg/dash-to-dock#1745]
Hi! I've noticed that the [latest Git code](https://github.com/micheleg/dash-to-dock/commits/master) is always a lot newer than the [published extension](https://extensions.gnome.org/extension/307/dash-to-dock/), with a lot more fixes here on Git that aren't published on the extension.

If I'm not mistaken, the current Gnome Extensions version is v71 from October 2021, so about 7 months old? At least that's what my `metadata.json` says (`"version": 71`) which I guess corresponds to [this commit](https://github.com/micheleg/dash-to-dock/commit/a23f0c5efa82d8dca767dd323436c5998373f139).

I'm thinking of uninstalling it from extensions.gnome.org and manually installing the Git version instead.

It seems like your code/commits on Git are mostly working as-is already without requiring further changes, so the risk of a broken Git version seems low. I also assume that many developers use the Git version?

What do you think, is it wise to switch?

**Comment by Bananaman** [comment]
Hmm, I tried it. I uninstalled the extensions.gnome.org version and installed the Git version, but ran into a problem:

GNOME Extensions (the app) automatically "upgraded" the locally installed git Dash to Dock back to the outdated extensions.gnome.org version. Wtf.

I assume that developers here use the Git version? Have you figured out a way to prevent Extensions app from overwriting Git with the old version?

**Comment by Bananaman** [comment]
Alright, thanks to [@SomeGenericUsername](https://www.reddit.com/user/SomeGenericUsername/), the exact cause has been found:

1. The version 72 of the extension was rejected: https://extensions.gnome.org/review/32340 (Reasons are explained there.)
2. When an extension is marked as rejected, extensions.gnome.org enforces downgrade to the previous version (71), as seen in the source:

https://gitlab.gnome.org/Infrastructure/extensions-web/-/blob/master/sweettooth/extensions/views.py#L173

Relevant lines:

```js
        if proper_version is not None:
            if version < proper_version.version:
                operations[uuid] = "upgrade"
            elif version_obj.status == models.STATUS_REJECTED: // <----- This!
                operations[uuid] = "downgrade" // <----- This!
        else:
            operations[uuid] = "blacklist"
```

So that solves the reason why it was constantly downgrading itself from 72-local to 71-online.

I am not concerned about the issues in the rejection, and I'm proceeding with my two scripts above to automatically mark a very high version number so that I never have this issue again.

So far, the Git version hasn't given me any issues and all the fixes that have happened since v71 are noticeable as a noticeably less glitchy experience.

My original question was "is it a good idea to use the Git version?" and I think it seems to be a good idea. Feel free to close this if there's nothing else to add to this topic. :) Thank you for creating Dash to Dock! <3

**Comment by Bananaman** [comment]
@psychonaut That's an interesting trick. So `chattr +i` marks a file as "immutable" (not allowed to be renamed or deleted).

But you can also just use my scripts/aliases above instead. They ensure that your extension version is labeled as the date you last built/downloaded it, which helps with keeping track of when you need to update it. And the high version number means it will never be downgraded.

**Comment by ascopes** [comment]
> @Bananaman `... sudo dnf install ...`

If you are on Fedora, it looks like they maintain a mirror of this project on their official repos. If you don't mind installing it via the system package manager (which will result in it being provided on a system level rather than per user in `~/.local/share/gnome-shell/extensions`), you can install it via DNF.

```sh
$ sudo dnf install gnome-shell-extension-dash-to-dock
$ sudo pkill gnome-shell  # restart the shell (will force a log out)
```

Just tested this on GNOME 42 and Fedora 36 and it seems to have worked. Will keep an eye out to see if GNOME Extensions then does the revert on this as well but I assume it won't as it will lack root permissions to change the extension when running in userland. If anything breaks, I will update my comment!

**Comment by Bananaman** [comment]
@ascopes Thanks! I always assumed that the Fedora package version was outdated, but I see now that they base it on git and a bunch of their own patches:

https://src.fedoraproject.org/rpms/gnome-shell-extension-dash-to-dock/tree/f36

This file is the most interesting. It shows the nice patches they apply. Mainly a bunch of pull requests that they merge sooner than the official dash-to-dock.

https://src.fedoraproject.org/rpms/gnome-shell-extension-dash-to-dock/blob/f36/f/gnome-shell-extension-dash-to-dock.spec

It could be worth switching to that. I can't remember if GNOME Extensions will offer user-level updates for the system-level extensions. I think it does, from vague memory. But I really don't remember for sure.

**Comment by Bananaman** [comment]
@ascopes Thanks again. I have a little more insight now for you and anyone else:

There are 3 ways to install this extension on Fedora:

1. Via extensions.gnome.org. Frequently has issues due to GNOME's slow review process and demands that extensions follow every guideline. This means that updates can take half a year, during which the extension is broken.
2. Alternatively install it directly from Git, such as via my one-liner scripts posted earlier in this ticket. Those are good but have pros and cons: You get the latest features and bugfixes. But sometimes you get buggy, unfinished features. And you have to do manual updates.
3. The Fedora package you found.

Now a bit more details about the Fedora package:

1. It is mainly maintained by František Zatloukal, who is a RedHat employee, which is very good news. It isn't some random person.
2. There are also a handful of other people helping out, one of whom is a Fedora engineer, as can be seen in the [commit log](https://src.fedoraproject.org/rpms/gnome-shell-extension-dash-to-dock/commits/f36) and [spec file changelog](https://src.fedoraproject.org/rpms/gnome-shell-extension-dash-to-dock/blob/f36/f/gnome-shell-extension-dash-to-dock.spec).
3. So they have a professional RedHat employee as the primary maintainer and several other people help out too.
4. The commit log and spec file shows that they take good care to ensure that Dash to Dock works well with the latest version of RHEL and Fedora.
5. They use a mixture of approaches, such as grabbing a specific git commit if necessary, or the latest GNOME Extensions website version/tag, depending on what is the best starting point. They prefer using the extensions website version.
6. They manually add patches, such as doing early merges for good pull requests that are not merged in this repo yet, or backporting git fixes onto the GNOME Extensions website version of D2D. And also manually tweak anything needed to make it work well on Fedora and RHEL.
7. This means that it is a kind of Frankenstein release with many combined parts. But since the maintainers know what they are doing, it seems to be a very good way to install Dash to Dock on Fedora and RHEL.

I am going to switch to their package now, and will stop doing manual updates.

Thanks again for letting me know about it!

**Comment by ascopes** [comment]
@Bananaman thanks for taking the time to look into this and letting us know of that info. Good to know RedHat are supporting this plugin.

I wonder if there is a way to raise these issues around review times with GNOME themselves? If it is a case of manpower, people like myself would always be interested in helping out with the review process, so it might be interesting to hear what they havet to say!

**Comment by Bananaman** [comment]
@ascopes Happy to help, and I am grateful that you showed me the Fedora package. It's a relief to know that my most important GNOME extension is auto-updating and well maintained.

> I wonder if there is a way to raise these issues around review times with GNOME themselves? If it is a case of manpower, people like myself would always be interested in helping out with the review process, so it might be interesting to hear what they have to say!

I am sure they'd appreciate more manpower (reviewers). But it requires deep understanding of GNOME's internal functions. [You can see what the process looks like here.](https://extensions.gnome.org/review/34780) Basically extensions are submitted and the reviewers job is to look for bad uses of APIs which could cause crashes, and to look for malicious code. I guess most extensions will be hard to review unless you have deep understanding of GNOME's code, since most extensions use a lot of internal Shell functions.

The problem isn't just due to slow reviews from GNOME Extensions. It's also that Dash to Dock has gone through many long periods where all development happens in Git without submitting anything to the Extensions website.

Either way, the last two release reviews (73 and 74) have gone quickly, which is nice to see! :)

**Comment by Bananaman** [comment]
@ascopes Sorry that was the wrong link. Here's the link I meant to post. It shows an example of a rejected version of Dash to Dock. Scrolling down shows you the kind of comments the reviewers provided and what they asked D2D to change/fix:

https://extensions.gnome.org/review/32340
