### ISSUE TITLE
Update dash-to-dock on extensions.gnome.org to version >= 72 for GNOME 42

### ISSUE THREAD

**Issue by theblobscp** [micheleg/dash-to-dock#1750]
While you guys updated the verison to 42 on here, the extension download through EGO doesn't work.

**Comment by theblobscp** [comment]
Should I close this then?

**Comment by vanvugt** [comment]
Yes it sounds like 72 will never be on extensions.gnome.org because I expect a new version 73 would be required to fix [those issues](https://extensions.gnome.org/review/32340).

**Comment by vanvugt** [comment]
Issue reopened now mentioning that GNOME 42 needs version 72 *or later*...

There was no sense in keeping this closed on a technicality when it's such a visible problem.

**Comment by theblobscp** [comment]
Ironically, I don't even use GNOME anymore. I'll be happy to help though.
