### ISSUE TITLE
glitches in fullscreen auto hide feature in full screen 

### ISSUE THREAD

**Issue by SarikAnwar01** [micheleg/dash-to-dock#1760]
whenever i am using any full-screen app the intelligent autohide glitches when move my cursor to dock or to top bar it even prevents me from changing tabs or switching to other app , i have to use my super key to switch apps plz help its very  disturbing and annoying

**Comment by vanvugt** [comment]
This sounds like a duplicate of #1755 which will be fixed in the next release.

**Comment by vanvugt** [comment]
Duplicate of #1755
