### ISSUE TITLE
moving right-click menus

### ISSUE THREAD

**Issue by melmi** [micheleg/dash-to-dock#1766]
Consider the following situation:

I set auto-hide of the dock to on, then I right click on an icon on the duck, a menu appears, I try to click one of the items of that menu, suddenly the duck hides and the menu moves accordingly and my click on the item happens to be on a wrong item.

I suggest to not hiding the duck when a context menu related to duck is showing.

**Comment by vanvugt** [comment]
Duplicate of #1755
