### ISSUE TITLE
Crashing gnome-shell on notification

### ISSUE THREAD

**Issue by horga83** [micheleg/dash-to-dock#177]
I'm seeing this error when used in conjunction with Workspaces to Dock.  It always seems to happen when a notification comes in.  Workspaces to Dock then crashes and has to be restarted but the error seems to be in Dash to Dock.

(gnome-shell:20278): Gjs-WARNING **: JS ERROR: Error: can't convert "x" to an integer
myAppIcon<.updateIconGeometry@/home/george/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1358
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
myAppIcon<.onWindowsChanged@/home/george/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1349
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:188

**Comment by micheleg** [comment]
Hi. Thanks for the bug report. Which shell/extension version? Does the
problem occurs with only dash to dock enabled? Is the notification the
default one or is it a custom application notification?

**Comment by horga83** [comment]
It's gnome-shell 3.16.2 and Dash to Dock 46
The problem so I don'rt see the problem if Workspaces to Dock is not
running, which is odd because I don't see any error with workspaces to
dock.
George

**Comment by micheleg** [comment]
Just to be sure, does the  error in the terminal appears even without Workspace to Dock? I'm wondering if the error itself is related to having workspace to dock and dash to dockrunning at the same time or not.

**Comment by horga83** [comment]
Not sure I'll have to try that.  I suspect it does, just as your email
came in DashtoDock seemed to restart itself, at least it flickered when
the notification came it.
There seems to be some kind of bad juju with GNOME notifications and
extensions that sit on the desktop like the docks.
I'll run the shell in a terminal again and see what happens, sometimes
it takes awhile.
George

**Comment by micheleg** [comment]
You can force a notification with ```notify-send "test"````, if you want to try to reproduce the bug without waiting for somebody writing to you :)

**Comment by horga83** [comment]
I tried that but it seems to be intermittent on the notification, I
wonder if it's tied to Evolution somehow.  Anyway It should happen
eventually.  Probably have to wait until tomorrow now but I'll keep you
updated.
Many thanks
George

**Comment by micheleg** [comment]
Any update on this?

**Comment by micheleg** [comment]
I believe this issue has been solved  by 8d54154a828d64c0 time ago.
