### ISSUE TITLE
If 'Show overview on startup' is disabled, dock "jumps up" onсe during GNOME Shell launch

### ISSUE THREAD

**Issue by maxborowsky** [micheleg/dash-to-dock#1770]
After disabling the 'Show overview on startup' option, overview on startup is really disabled, but the dock "jumps up" once. This happens with both version 72 of Fedora's 36 official repo and the version maked from git sources.

But if you leave the 'Show overview on startup' option enabled and at the same time use the [No overview at start-up by fthx](https://extensions.gnome.org/extension/4099/no-overview/) extension, when starting the GNOME Shell, the desktop and dock are simply shown without any unnecessary animations.

**Comment by 3v1n0** [comment]
By jumps up you meant that it animates moving up?

If that, well that's expected.

**Comment by maxborowsky** [comment]
@[3v1n0](https://github.com/3v1n0)

Yes, that's what I meant. One of the attractive features of DtD is the ability to get rid of unnecessary animations of the default GNOME Shell and the lack of upward (or sideways) movement when starting the desktop would be logical - and the animation is relevant if the user has chosen not to show the dock until the cursor is on the edge of the screen. It is not very convenient to have two extensions instead of one just because the option of one extension in theory should do the same as the second extension, but does it differently.

**Comment by vanvugt** [comment]
Is this the same [issue we see in Ubuntu](https://launchpad.net/bugs/1965208)?

**Comment by maxborowsky** [comment]
[vanvugt](https://github.com/vanvugt)
Yes, this is similar to what was described by your link for Ubuntu. I now disabled _No overview at start-up_, turned on a similar option in DtD and loaded the Wayland session - you can also see the movement of the dock in it, only it does not "jump," but smoothly leaves from the edge of the screen. But - it still moves, and not just arises with the desktop.

**Comment by 3v1n0** [comment]
Please check https://github.com/micheleg/dash-to-dock/pull/1846
