### ISSUE TITLE
Broken alpha transparency behind the "Full Trash" icon on Adwaita [NOT A DASH-TO-DOCK BUG]

### ISSUE THREAD

**Issue by Bananaman** [micheleg/dash-to-dock#1772]
This is a problem that I have observed "forever" across multiple distros. I took these screenshots and was about to report it here. But I made a last-minute disccovery which means that this report is not Dash-to-Dock's fault.

## The Issue:

![d2d-normal-fine](https://user-images.githubusercontent.com/38923130/178160986-88a6bcb6-a044-4f22-ad03-9ce01914f877.jpg)

![d2d-icon-alpha](https://user-images.githubusercontent.com/38923130/178160988-32d3501d-6af4-40fc-af32-b7e5332475c5.jpg)

## The Reason:

- `/usr/share/icons/Adwaita/256x256/places/user-trash.png`:

![user-trash](https://user-images.githubusercontent.com/38923130/178161029-5e287150-9c26-48b0-a1a2-8fdd43c18b92.png)

- `/usr/share/icons/Adwaita/256x256/status/user-trash-full.png`:

![user-trash-full](https://user-images.githubusercontent.com/38923130/178161049-0bce8ee9-0ada-4bbe-a3dd-226864d8fd4c.png)

## Yep, that's right. The Adwaita theme's "full trash" icon simply lacks alpha transparency. I'll be reporting it on the official Adwaita icon theme repo, and am just creating this ticket here to guide other people who see the same issue (which is everyone who uses the Adwaita icons).

**Comment by Bananaman** [comment]
Oh wow, just as I was about to create the bug report on their GitLab, I found this wonderful commit:

[fullcolor: trash-full with alpha. render fullcolor version properly](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/e4f56bd0fd2108318ff61ba35ab69311bed42779)

Turns out they've already fixed it! So, I decided to install the updated icon theme locally, with these commands. The first line is unique for Fedora and gets the dependencies. The `--prefix=/usr` is important too, and makes it overwrite the systemwide icon location. Otherwise we'd end up with `/usr/local/share/icons/Adwaita/...` which would sit as a permanent override for the system theme and we'd miss out on future system theme package updates whenever Fedora catches up to these fixes.

```bash
sudo dnf in autoconf automake git make
git clone --depth=1 https://gitlab.gnome.org/GNOME/adwaita-icon-theme.git ~/Downloads/adwaita-icon-theme
cd ~/Downloads/adwaita-icon-theme
./autogen.sh --prefix=/usr
make
sudo make install
gsettings set org.gnome.desktop.interface icon-theme Adwaita
```

The result is that I now have the latest version of Adwaita icons. Instantly, the "full trash" icon looks beautiful!

![d2d-fixed](https://user-images.githubusercontent.com/38923130/178161736-55862ef6-6877-4dd4-b99b-bae32c3ae273.jpg)

![user-trash-full](https://user-images.githubusercontent.com/38923130/178161765-469175e5-3e65-4fff-b867-da6599b6cbd7.png)

## This is the solution for people who don't want to wait for their distros to update the icon theme.

**Comment by vanvugt** [comment]
Closed because it's not a bug in dash-to-dock.

**Comment by Bananaman** [comment]
@vanvugt Yeah, it should be closed. I only filed it here so that people who have the unfixed icon theme (lots of distros) will see the solution. Thanks and take care! :smile_cat:

**Comment by derhelge** [comment]
I had to switch to a different tag:

```shell
sudo dnf in autoconf automake git make
git clone --depth=1 https://gitlab.gnome.org/GNOME/adwaita-icon-theme.git ~/Downloads/adwaita-icon-theme
cd ~/Downloads/adwaita-icon-theme
git fetch origin tag 43 --no-tags
git checkout tags/43
./autogen.sh --prefix=/usr
make
sudo make install
gsettings set org.gnome.desktop.interface icon-theme Adwaita
```
