### ISSUE TITLE
fullscreen windows breaking autohide functionality

### ISSUE THREAD

**Issue by kppmsd** [micheleg/dash-to-dock#178]
This bug appeared after upgrade to gnome 3.16.
Looks like it also only happens if you have 'Push to show' enabled in intelligent autohide settings.

Any fullscreen window (like mpv or youtube in fullscreen) prevents the autohidden dash from reappearing. The dash reappears when you enter overview mode, and autohide works fine after that until there's another fullscreen window.

Thanks for all of your work with this extension :)

**Comment by micheleg** [comment]
Hi. Could you please describe the previous behaviour, that you consider correct, and the current one, that you consider wrong?

**Comment by kppmsd** [comment]
Hi,

Yes, sorry that my last message was a bit hastily written

Expected behaviour:
1. start application in fullscreen (not maximized, but 100% fullscreen like mpv or youtube video)
2. exit fullscreen application
3. autohidden docked dash reappears when you move mouse cursor to the edge of the screen

Current behaviour:
1.-2. same as above
3. autohidden dash doesn't reappear no matter how much you push your mouse cursor to the screen edge.
4. if you enter overview mode in shell, autohide starts to work again as expected

Again, this only seems to happen with 'Push to show' option enabled, and disabling it corrects the behavior.

**Comment by micheleg** [comment]
I can reproduce the bug. Apparently the problem was introduced by ad5c50a6dbfeb.

**Comment by micheleg** [comment]
It should be fixed in master now 91e7913649c15592a9c54b277f8056d8cd9bd786.

**Comment by kppmsd** [comment]
Just updated to latest master, and the bug is gone.
thanks for the quick fix :)
