### ISSUE TITLE
Dash to Dock not showing up

### ISSUE THREAD

**Issue by badde-media** [micheleg/dash-to-dock#1783]
I have Dash to Dock & Dash to Panel running. Whenever I boot the computer and login to Zorin Pro OS, only Dash to Panel is running. I always have to go to the extensions settings, turn off Dash to Dock and turn it on again to make it appear.

Expected behaviour: Dash to Dock and Dash to Panel should both be shown after system startup

Recreate behaviour: Start computer with Dash to Dock and Dash to Panel both installed (I don't know whether this is a conflict between these two, or whether there's another reason for DtD not running).

**Comment by vanvugt** [comment]
It's possible Dash to Panel in trying to hide the GNOME dash is actually hiding Dash to Dock. If true then the bug and the fix would be in Dash to Panel, so I'm not sure it's helpful logging the bug here.

**Comment by badde-media** [comment]
Thanks for the reply. I'll open the issue at the Dtp github.
