### ISSUE TITLE
Fedora: spacing broken when in panel mode 

### ISSUE THREAD

**Issue by Vittelius** [micheleg/dash-to-dock#1786]
This might be a fedora specific version as it affects the version shipped by fedora in their repo and not the "dash to dock for cosmic" version from the gnome extension repo. basically the show apps button is in the wrong place while in panel mode. It is where it should be if I hadn't activated said option. If I try put the button at the start of the list it will do so, but all the actual app shortcuts will appear centred with an awkward gap between the icon and the app grid button.
![Bildschirmfoto vom 2022-08-13 23-07-01](https://user-images.githubusercontent.com/3718818/184510880-853006dc-8cb3-4824-8d13-5e64629d7149.png)

**Comment by silviucc** [comment]
Hello,

There's something definitely wrong with spacing and maybe padding with the latest package shipped by Fedora for Dash to Dock.

In dock mode, the icons are not centered. But they are correctly centered when in panel mode. I'll attach screenshots below:


![dock mode](https://user-images.githubusercontent.com/3889481/184602830-1f008d5b-fc02-49ec-b8f8-07ff46eda7ac.png)

![panel mode](https://user-images.githubusercontent.com/3889481/184602861-897e7725-9d82-4984-811f-f7ae8caae880.png)

**Comment by silviucc** [comment]
Created bug report on RedHat's bugzilla and added a link to this issue.

https://bugzilla.redhat.com/show_bug.cgi?id=2118255

**Comment by cynchronos** [comment]
Yeah, I had the same issue with the new version of Fedora 36.  but in my case, dash to dock won't give space below apps, it's still filled with black color

**Comment by Altonss** [comment]
> This might be a fedora specific version as it affects the version shipped by fedora in their repo and not the "dash to dock for cosmic" version from the gnome extension repo. basically the show apps button is in the wrong place while in panel mode. It is where it should be if I hadn't activated said option. If I try put the button at the start of the list it will do so, but all the actual app shortcuts will appear centred with an awkward gap between the icon and the app grid button. ![Bildschirmfoto vom 2022-08-13 23-07-01](https://user-images.githubusercontent.com/3718818/184510880-853006dc-8cb3-4824-8d13-5e64629d7149.png)

+1 I have exactly the same issue with the latest update on Fedora 36

**Comment by fbruetting** [comment]
This by the way is not the case in horizontal mode, maybe this helps.

**Comment by 3v1n0** [comment]
I feel this is a distro issue, let's close this for now.

**Comment by RyzenDew** [comment]
Use extension manager on fedora 36 it grabs the good version. Not all good things come in repos
