### ISSUE TITLE
Ghosting and stuttering of moving window of MInecraft

### ISSUE THREAD

**Issue by fansuregrin** [micheleg/dash-to-dock#1789]
When I launched Minecraft (a game written in Java) and move its window, I got the result below. However, other Apps' windows are normal. Before, I thought the problem is caused by Mutter the window manager. However, after I turned off `dash to dock`, the strange behavior of `Minecraft` back to normal. When I turn on `dash to dock`, the problem back. So now I think this problem may be caused by `dash to dock`.

screenshot:  
![](https://gitlab.gnome.org/GNOME/mutter/uploads/781bf65d0dbd5621d4c6277ff2a25bb4/2022-08-18_10-34.png)
![](https://i.imgur.com/4dx4mFI.png)

[screencast here](https://gitlab.gnome.org/GNOME/mutter/uploads/672593c82046cf2ccaea3468bf47d710/2022-08-18_12-37-12.mp4)

My system information is below.
```
OS: Arch Linux x86_64
Kernel: 5.19.1-arch2-1
DE: GNOME 42.4 
WM: Mutter 42.4
SESSION_TYPE: X11
CPU: Intel i5-8250U (8) @ 3.400GHz
GPU: NVIDIA GeForce MX110
GPU: Intel UHD Graphics 620```

**Comment by vanvugt** [comment]
Looks like the shadow has not been included in the known damage region so it doesn't get removed when the window moves. I'm not sure how dash-to-dock could cause that.

**Comment by emansom** [comment]
It may be related to a X11 bug inside Mutter/GNOME components. Those don't get the testing they used to and have been half broken for a while now.

Clapper experienced something similar in the past as well:
https://github.com/Rafostar/clapper/issues/212

A possible workaround may be switching to the Wayland session.

**Comment by fansuregrin** [comment]
This problem has been fixed in new version GNOME.
