### ISSUE TITLE
Your local host connector does not support the following APIs: V6

### ISSUE THREAD

**Issue by xdu-chenrj** [micheleg/dash-to-dock#1792]
My Gnome version is 42.2.
Please help me.

**Comment by 3v1n0** [comment]
How do you get this error?

**Comment by MopsTMC** [comment]
It's a known issue with the [extensions.gnome.org](https://extensions.gnome.org) website. 
[https://askubuntu.com/questions/1418937/your-native-host-connector-do-not-support-following-apis-v6](https://askubuntu.com/questions/1418937/your-native-host-connector-do-not-support-following-apis-v6)

**Comment by 3v1n0** [comment]
Not a bug of the exension.
