### ISSUE TITLE
Automatic Downgrade Issue

### ISSUE THREAD

**Issue by MopsTMC** [micheleg/dash-to-dock#1796]
The extension is perfectly functional when building from source but Gnome automatically downgrades it from version 72 to version 71 which is available on extensions.gnome.org for absolutely no reason. After a log out it refuses to load it because version 71 is incompatible with Gnome 42.  How can I prevent it from getting updated upon every login?

**Comment by vanvugt** [comment]
Please reproduce the downgrade again and then run this command to collect the log from when it happened:
```
journalctl -b0 /usr/bin/gnome-shell > journal.txt
```
and attach the resulting text file here.

**Comment by MopsTMC** [comment]
Because I disabled extension version validation dash to dock loads now even with version 71 and is fully functional even though it appears disabled and it downgraded
![image](https://user-images.githubusercontent.com/74558936/186866150-2cc5abed-6f71-497f-9752-babc4f603667.png)
[journal.txt](https://github.com/micheleg/dash-to-dock/files/9431433/journal.txt)

**Comment by vanvugt** [comment]
Confirmed `_leftCorner` was removed in gnome-shell 42 so this is a bug in dash-to-dock (and in ubuntu-dock).

I wonder how ubuntu-dock got away with it in Ubuntu 22.04 with gnome-shell 42?

**Comment by MopsTMC** [comment]
What could be triggering the downgrade though? Dash-to-dock version 72 works fine with my setup where the only error I get is #1795. If I have disable-extension-version-validation set to true version 71 works too though so I guess I can live with it

**Comment by emansom** [comment]
> I wonder how ubuntu-dock got away with it in Ubuntu 22.04 with gnome-shell 42?

Canonical's patented policy of never upstreaming patches, if I had to guess.

**Comment by MopsTMC** [comment]
This has been fixed by version 73 becoming available
