### ISSUE TITLE
Issues with Settings menu

### ISSUE THREAD

**Issue by MopsTMC** [micheleg/dash-to-dock#1801]
The settings menu of dash-to-dock is a bit broken in Gnome version 42, using any version from 71 and up. The settings tabs convert into tiny lines after a split second upon entering the menu. Occasionally it closes on its own or refuses to open entirely
[Screencast from 27-08-22 10:50:12.webm](https://user-images.githubusercontent.com/74558936/187021200-556e58f5-497d-4fd8-be12-6803d5304a94.webm)
Here's another recording with the cursor visible

https://user-images.githubusercontent.com/74558936/187021616-02c15deb-2d7b-4d70-ac8a-df52fa3574de.mp4

**Comment by leandrokemp** [comment]
Just scroll up and you'll be able to see the tabs.

**Comment by MopsTMC** [comment]
Oh right, thanks I hadn't noticed that. I was trying to scroll in the central area. It still closes suddenly sometimes for no reason though.

**Comment by jm33-m0** [comment]
I can confirm this, if you don't scroll or resize the window, tabs are hardly visible. I suggest we take a look at the default size of the settings window, see if we can make it larger to display all items.

**Comment by MopsTMC** [comment]
I don't see a reason to change the size of the window as everything fits even when scrolled up so the scrolling isn't really needed either unless new setting are planned to be added. I I remember correctly in versions prior to 70 it never existed.

**Comment by emansom** [comment]
:+1: on this issue.

In a mobile setting (e.g. PinePhone Pro, Librem 5) [running GNOME Shell](https://blogs.gnome.org/shell-dev/2022/05/30/towards-gnome-shell-on-mobile/), the current settings window is rendered completely unusable without triggering other button clicks.

The settings window should become more responsive, not fixed in any size.

**Comment by fabd** [comment]
Noticed that as well. Removing the large amount of extra padding at bottom of the first settings pane "Position and size" could maybe be a simple fix or make the issue less noticable. I am guessing this is why it scrolls down the view when the settings dialog opens, and thus the tabs disappears at the top.
