### ISSUE TITLE
a bug and a request

### ISSUE THREAD

**Issue by nibazshab** [micheleg/dash-to-dock#1807]
__the bug:__ indicator is no longer in the correct position by default

![image](https://user-images.githubusercontent.com/44338441/187642762-01140b04-e98c-4081-8f37-946118fbd606.png)

__the request:__ hope to add background blur, like "Gaussian blur"

**Comment by 3v1n0** [comment]
Bug is a duplicate of #1757.

Blur should be technically possible using other extensions, but we'd prefer to avoid to include natively here not to create a performance issue.

**Comment by vanvugt** [comment]
Duplicate of #1757 and #1146.
