### ISSUE TITLE
No option to move to bottom

### ISSUE THREAD

**Issue by jcvfen** [micheleg/dash-to-dock#181]
I cant see to find any option to move it to bottom.
wihle you have on bottom on your screenshots.

**Comment by micheleg** [comment]
Which GNOME version are you using? Bottom option is available from GNOME 3.12

**Comment by jcvfen** [comment]
GNOME Shell 3.10.4

**Comment by micheleg** [comment]
The bottom option is 'unofficially' available for GNOME 3.10 in the gnome-3.10-experimental branch. You need to install it manually: checkout the branch and run ```make install```. Then restart GNOME Shell

**Comment by jcvfen** [comment]
Weird. I upgraded to 3.12. Git cloned and compiled, wasnt compatible in extensions pane.
Removed it and installed it via extensions.gnome.org and worked now.

**Comment by micheleg** [comment]
You might have cloned master, which is supporting only the latest version. There are gnome-3.xx branches around for specific GNOME versions.  Anyway, the version on the extension website is the latest available for GNOME 3.12, so there's no reason to use the git version. Did you get the bottom option working?

**Comment by micheleg** [comment]
Closing, problem solved.
