### ISSUE TITLE
No app shows "running" indicators, although running

### ISSUE THREAD

**Issue by koplo199** [micheleg/dash-to-dock#1812]
The polar opposite of #1787 : No app shows "running" indicators, although they are running. Changing the style of the indicators has no effect. The default dock do not share the same behavior.

---
OS: Arch Linux x86_64
WM Theme: Adwaita
Theme: Adwaita-dark [GTK2/3]
Icons: Adwaita [GTK2/3]

**Comment by vanvugt** [comment]
Do you mean the indicators are completely missing, or just overdrawn like in #1757 ?

**Comment by 3v1n0** [comment]
What applications are you getting this with? All of them?

**Comment by koplo199** [comment]
Yes, all of them

**Comment by koplo199** [comment]
But Dash to Dock seems to know which applications are running, because those who aren't already in my favorites appears in the dock when running and disappears when stopped, just as expected. There is just no running indicator, no "Quit" button, no windows previews etc

**Comment by koplo199** [comment]
I reinstalled gnome and now it seems to be working again ¯\_(ツ)_/¯
Sorry for the inconvenience
