### ISSUE TITLE
moving the dock to the left causes 4x6 app grid allignment on gnome 43

### ISSUE THREAD

**Issue by cassop** [micheleg/dash-to-dock#1822]
moving the dock to the left causes the normal 3x8 app grid allignment to 4x6 on gnome 43.rc
like in the picture below
![Screenshot from 2022-09-17 16-43-15](https://user-images.githubusercontent.com/92434806/190860385-dd798487-ea7a-43d8-bd2a-7846e177b157.png)

**Comment by vanvugt** [comment]
This is not a dock bug, it's a general gnome-shell bug that arises when the available aspect ratio for the icon grid gets slightly narrower. Tracking in https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5791
