### ISSUE TITLE
ubuntu-dock: Fix max gnome-shell version

### ISSUE THREAD

**Issue by jbicha** [micheleg/dash-to-dock#1834]
Please set the maximum gnome-shell version in ubuntu-dock's debian/control to `<< 44~`. The `~` is important because GNOME Shell pre-releases are packaged in Ubuntu with a `~` suffix. The extension is not currently compatible with a future GNOME Shell 44~alpha so we don't want it installable with that version.

**Comment by 3v1n0** [comment]
I was thinking whether to keep this or not, but I think it's actually better to explicitly check whether the extension will be compatible with GNOME 44 pre-releases before actually be preemptive and enable it early in the 44 cycle.

**Comment by jbicha** [comment]
Having debian/control set to `44` without the `~` doesn't work unless you have metadata.json set to include `44`

**Comment by 3v1n0** [comment]
Indeed, I think it's better to keep them in sync.
