### ISSUE TITLE
Regression: No feedback when app is in the process of launching

### ISSUE THREAD

**Issue by inthreedee** [micheleg/dash-to-dock#1836]
When launching an app that is slow to open on first load, for example Steam, the dock doesn't seem to provide any visual indication that the click was successful and the app is in the process of being launched by the OS. The current behavior on my system is that apps such as Steam get a window counter indicator and background shading after the app's window fully opens, but nothing happens when they are clicked for the first time. I thought the dock used to provide some kind of feedback on first launch of an app, but perhaps my memory is faulty so I'm marking this as a feature request.

Some sort of visual indication that the click was good and the app is launching would be useful. The default Gnome dash plays a quick enlarging animation. For dash-to-dock, it might make sense to briefly play the shaking animation that already gets used for app updates/messages/etc.

System info:
OS: Arch
Extension: v74 from Arch Repos
Gnome: 42

**Comment by vanvugt** [comment]
Confirmed the launch animation seems to be missing in ubuntu-dock too. But if I disable the dock extension then the default gnome-shell dash still has the launch animation.

So we need to:
1. Restore the missing animation.
2. Probably make it a bit longer.
