### ISSUE TITLE
dat&time position is not centered in top-panel

### ISSUE THREAD

**Issue by Muqtxdir** [micheleg/dash-to-dock#1841]
hi,

when the extension is enabled the date&time position in top-panel shifts a bit towards right when dash-to-dock is on left and shifts a bit towards left when dash-to-dock is on right. 

#### screenrecording: 

https://user-images.githubusercontent.com/54065734/193660495-6fa7b79d-e447-4d6a-8414-b84e365a0d45.mp4

**Comment by vanvugt** [comment]
This is a feature of Ubuntu. It's designed that way. I don't like it myself but it's definitely intentional.

**Comment by Muqtxdir** [comment]
ok, sorry my bad
