### ISSUE TITLE
Please add support for GNOME 43.0

### ISSUE THREAD

**Issue by warp10** [micheleg/dash-to-dock#1845]
The latest version of GNOME (43.0) is not supported according to extensions.gnome.org. I'm using Debian Testing updated to the latest released packages.

Please add support for this version too.

**Comment by maxborowsky** [comment]
I'm sorry, but I think you're wrong. The extensions.gnome.org site has a version for GNOME 43 and this is version 74.

**Comment by 3v1n0** [comment]
Hey @warp10, indeed that's supported as e.g.o should show :)
