### ISSUE TITLE
All app icons are missing after computer locked for some time

### ISSUE THREAD

**Issue by renetchi** [micheleg/dash-to-dock#1852]
Happening in Ubuntu 22.04

How to reproduce:
1. Left computer idle and locked for quite some time
2. Unlock the computer
3. Only `Show Applications` icon is shown in dash-to-dock
4. When clicked, blank black screen with no application is shown. And can't return to desktop or do any other navigations.

Log out / restart menu still works so I usually restart my computer to fix this.

**Comment by 3v1n0** [comment]
Do you have anything useful in your `journalctl /usr/bin/gnome-shell '?

**Comment by vanvugt** [comment]
Downstream Ubuntu bug: https://launchpad.net/bugs/1936734

**Comment by vanvugt** [comment]
Do you mean the whole screen is black or just the dock?

If the whole screen is blank then please report a new bug to Ubuntu by running:
```
ubuntu-bug gnome-shell
```

**Comment by eliyaoo32** [comment]
I also have this issue

**Comment by vanvugt** [comment]
See also https://launchpad.net/bugs/1993284

**Comment by bartkoro** [comment]
I'm also having this issue.

**Comment by eduardoc7** [comment]
This solve for me:

https://github.com/micheleg/dash-to-dock/issues/1282#issuecomment-664693977

**Comment by holiq** [comment]
still not fix?

**Comment by vanvugt** [comment]
Duplicate of #1522

**Comment by vanvugt** [comment]
Duplicate of #1522

**Comment by santimoy044** [comment]
Still not fixed?

**Comment by vanvugt** [comment]
> Still not fixed?

Please use #1522 to track this issue.

**Comment by abdasis** [comment]
Still not fixed

**Comment by gen3vra** [comment]
Not fixed

**Comment by Rodmatronic** [comment]
Still not fixed. Happened to me out of the blue

**Comment by vanvugt** [comment]
Please use #1522 to track this issue.

**Comment by sapphicart** [comment]
Just had this issue and followed the [suggestion by monocongo](https://github.com/micheleg/dash-to-dock/issues/1282#issuecomment-664693977) from Issue #1522 
so far so good, I have tried locking thrice and the problem has not re-appeared
