### ISSUE TITLE
Please offer a setting to turn off icon shaking

### ISSUE THREAD

**Issue by hosford42** [micheleg/dash-to-dock#1859]
Please offer a setting under Accessibility to completely turn off the icon shaking feature. Anyone with sensory processing disorder, like myself, is likely to struggle significantly with filtering out motion in their peripheral vision (along with any other sensory stimulus that isn't directly relevant to the current task). This is not a rare condition; it is common for neurodivergent people -- those with ADHD or ASD, for example.

NOTE: I just upgraded to Ubuntu 22.04.01 LTS. I don't have this extension installed, but it appears to be incorporated into the OS now. Apologies if that's not the case and I have the wrong repo.

**Comment by vanvugt** [comment]
Two workaround suggestions:
 * Edit `/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js` and change `ICON_ANIMATOR_DURATION` to zero. At least that looks like the offending code.
 * Disable the dock and use the default GNOME one instead:
   `gnome-extensions disable ubuntu-dock@ubuntu.com`

**Comment by lordspace** [comment]
yeah, that's super annoying. Who came up with that stupid idea and who OK'ed it?!?
Our attention is pulled in so many ways anyways.
