### ISSUE TITLE
Applications menu problem

### ISSUE THREAD

**Issue by Danila-hub** [micheleg/dash-to-dock#1873]
After update to GNOME 43 I have one thing:
The application menu began to display icons with fewer columns. I used to have ~8 columns before, it looked more beautiful..
How can I change it?

Display: 16:10

![image](https://user-images.githubusercontent.com/55277394/201463402-053ea624-280c-43bc-8332-1cf1bbf65c99.png)

**Comment by muznyo** [comment]
Same issue here

**Comment by Danila-hub** [comment]
> Same issue here
> 
> also 16:10 display btw

It happens only for 16:10 displays. I connected 16:9 and it looks good.

**Comment by aralon2843** [comment]
Same problem for 16:10

**Comment by vanvugt** [comment]
This is not really related to dash-to-dock. The icon grid size is chosen by gnome-shell.
