### ISSUE TITLE
Weird minimize animation

### ISSUE THREAD

**Issue by Xyphyn** [micheleg/dash-to-dock#1881]
I noticed that when you minimize an app and it goes to the dock, it doesn't fade out before it hits the dock, meaning you can see it suddenly disappear.

[Screencast from 2022-11-21 11-43-12.webm](https://user-images.githubusercontent.com/80978739/203146313-3903fae9-b724-4566-8393-3ab157e207a4.webm)

If the dock is not visible, the issue becomes even more apparent:

[Screencast from 2022-11-21 11-53-43.webm](https://user-images.githubusercontent.com/80978739/203146516-8907de6d-8f72-47fa-9717-5c7f75a8a88e.webm)

**Comment by vanvugt** [comment]
Confirmed, this has been annoying me for quite a while too... But since it's a gnome-shell bug we shouldn't track it here.
