### ISSUE TITLE
Dock is not hiding when right mouse button menu appears 

### ISSUE THREAD

**Issue by brightkill** [micheleg/dash-to-dock#1887]
![изображение](https://user-images.githubusercontent.com/4520913/206020876-bdf0c623-93c9-4875-ad27-a42cfd1f9cc1.png)

Dock with intellihide option overlaps RMB menu and I cant click it

My settings:
Debian testing
GNOME 43.1

**Comment by vanvugt** [comment]
Downstream Ubuntu bug: https://launchpad.net/bugs/1983456
