### ISSUE TITLE
Icon glitch in focused applications (rounded corners)

### ISSUE THREAD

**Issue by xuedi** [micheleg/dash-to-dock#1894]
On Gnome 43, dash-to-dock 75

The currently active app has on the selection the corners missing

Happens ONLY when using option "build in theme", the theme is default gnome 43

The strange thing is it does work for some like active, not pinned apps and sometimes it workes completely.

![Screenshot from 2022-12-21 15-59-01](https://user-images.githubusercontent.com/2644528/208936200-579a5d04-35f3-4c56-a3e3-9e709bae2a71.png)

**Comment by ZimbiX** [comment]
I see this bug too, but only occasionally. I have "Use built-in theme" disabled. I haven't yet worked out a way to reproduce it. It may only affect icons which don't come from [my icon theme](https://aur.archlinux.org/packages/numix-square-icon-theme).

Gnome 43.2, Dash to Dock 75.

Here's a demo clip:

https://user-images.githubusercontent.com/2916331/209422497-34bb6170-648b-4dc2-81a5-b95521c31d09.mp4

**Comment by ZimbiX** [comment]
Perhaps related: https://github.com/micheleg/dash-to-dock/issues/1817
