### ISSUE TITLE
Fullscreen window conflicts with autohide

### ISSUE THREAD

**Issue by nevesnunes** [micheleg/dash-to-dock#190]
I have the dock set with 'Autohide' (with 'push to show' checked) and 'Dodge windows'.

Suppose you have a maximized window. The dock is hidden, mouse hovering reveals it. If this window becomes fullscreen and goes back to a maximized window, the dock can no longer be shown by mouse hover (maybe it is still considering the window as fullscreen).

Switching workspace, accessing the 'Activities' overview or unmaximizing the window (so that it doesn't overlap dock space) allows the dock to be revealed again.

**Comment by micheleg** [comment]
Did you try current master? This issue might have been already solved by 91e7913649c1. Could you please check?

**Comment by nevesnunes** [comment]
On master the bug is present, but in a more specific situation: It only occurs if the maximized window goes fullscreen while simultaneously having the dock revealed (by mouse hover). Also, when using animation, if we enter fullscreen while the dock is in the middle of the hiding animation, it will also not respond to mouse hover after exiting fullscreen.

As long as the dock is hidden during this process, the bug won't be activated.

**Comment by micheleg** [comment]
Ok, I can now reproduce the bug. Thank you.

**Comment by nevesnunes** [comment]
The bug seems to mess up the _updateBarrier function. In particular, the second 'if':
 ```javascript
if (this._slider.actor.visible && this._canUsePressure && this._autohideIsEnabled && this._settings.get_boolean('require-pressure-to-show')) {
            ...
}
```
returns false, and you never get further calls to _updateBarrier, unless you do one of those tricks I described previously (like activating the 'Activities' overview).

**Comment by micheleg** [comment]
Thanks for the additional information. Unfortunately I haven't had time to look into it yet.

**Comment by micheleg** [comment]
@nevesnunes what about just removing the check for 'this._slider.actor.visible' in that if statement? It seems to solve the issue and I think that check is actually not necessary anymore, but I don't have much time for an extensive testing now.

**Comment by nevesnunes** [comment]
From my testing it's working fine, I believe it's safe to close this issue. Thanks!

**Comment by micheleg** [comment]
Closing (8210bd0).
