### ISSUE TITLE
Window previews are horrible

### ISSUE THREAD

**Issue by pratyush3124** [micheleg/dash-to-dock#1903]
This is how I am seeing Window Preview in the dash-to-dock gnome extension.
Please help.

![image](https://user-images.githubusercontent.com/44525862/213876100-705a19cf-3815-4061-b452-fb53e2d6fdc3.png)

System:
OS: Ubuntu 22.04.1 LTS x86_64
DE: GNOME 42.5
Dash-to-Dock version: 75

**Comment by 3v1n0** [comment]
This should be due to wrong scaling, hopefully this is fixed by #1854

**Comment by vanvugt** [comment]
(which will be in dash-to-dock 76)
