### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Joker701** [micheleg/dash-to-dock#191]
When you click the icon in the doc it either creates a new window or opens the window already created, I suggest that when clicking the icon on a raised window it would lower it.

**Comment by micheleg** [comment]
By "raising" and "lowering" do you mean putting the window on the  bottom or top ( ~ z coordinate) of the windows stack, or minimizing maximizing? The latter is implemented as an option.

**Comment by Joker701** [comment]
Duh, I meant minimizing and I just found it in the options, thanks, BTW, 
I love this extension.
-F
