### ISSUE TITLE
bug when sleep too long

### ISSUE THREAD

**Issue by holiq** [micheleg/dash-to-dock#1910]
if i sleep or suspend my laptop for 20-30minutes and when i open it again the dock has bug like this, it cannot be click so i must logout/restart for fix it
my device: ubuntu 22.10, gnome 43
![gambar](https://user-images.githubusercontent.com/30729921/214723875-7b06a006-b594-4d02-837d-5b29aef29fc2.png)

**Comment by vanvugt** [comment]
Duplicate of #1852
