### ISSUE TITLE
Not compatible with GNOME Shell 44

### ISSUE THREAD

**Issue by jbicha** [micheleg/dash-to-dock#1916]
GNOME Shell 44 Beta was released this week.

When I tried enabling the Ubuntu Dock shell extension with the new GNOME Shell, I got this error:

`Meta.MonitorManager.get is not a function`

**Comment by hehellooedas** [comment]
Yes,you are right.This problem also occurred when I updated GNOME44 yesterday

**Comment by OlegKrikun** [comment]
I have the same issue with Gnome 44 beta.

**Comment by RGarrido03** [comment]
I'm facing the same issue as well with GNOME 44 beta on Arch

**Comment by vanvugt** [comment]
Mutter 44.beta [has retired that function](https://gitlab.gnome.org/GNOME/mutter/-/commit/aa2a663380c6c7b3b0af2269f9713b99d6cace58). But it seems [a replacement was prepared in 42.0](https://gitlab.gnome.org/GNOME/mutter/-/commit/65d8164833e998b35434a70f47808296e131b4a0).

**Comment by vanvugt** [comment]
@jbicha, try releasing https://github.com/micheleg/dash-to-dock/tree/ubuntu-dock which contains the fixes. If it works for you then I'll tag it.

**Comment by jbicha** [comment]
@vanvugt I uploaded [75ubuntu1](https://launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/75ubuntu1) now since it makes it easier for us to work with GNOME Shell 44. But I opened https://github.com/micheleg/dash-to-dock/issues/1919

**Comment by jbicha** [comment]
@vanvugt Please update this line in debian/control so that the extension is installable with any GNOME Shell 44 release but not with the 45 releases, to match the metadata.json file.

```diff
-Depends: gnome-shell (<< 44),
+Depends: gnome-shell (<< 45~),
```

**Comment by vanvugt** [comment]
@jbicha, 60f0c8658802a38162709476c6cbf9df2989a939

**Comment by straurob** [comment]
Building from `master` fixes this issue for me.
