### ISSUE TITLE
[Feature] Make preview close button placement follow system's setting

### ISSUE THREAD

**Issue by hyuri** [micheleg/dash-to-dock#1918]
Hi!

I'd like to suggest making the placement of the preview close button follow the user's chosen window buttons placement.

Right now it doesn't, making it inconsistent and breaking expectations.

You can see that my window buttons are placed on the left, but the preview close button is placed on the right:
![ScreenShot_20230220-132913](https://user-images.githubusercontent.com/18584014/220159352-80e21af3-da95-4566-a4fd-3f37eb96b247.png)

**Comment by hehellooedas** [comment]
![image](https://user-images.githubusercontent.com/96963528/220217082-c69dca9d-dd1f-483f-8459-1af95d5416e0.png)
![image](https://user-images.githubusercontent.com/96963528/220217092-b8b30993-ebc7-4592-a305-8ec818a5b4ed.png)
You may need gnome-tweaks?

**Comment by 3v1n0** [comment]
While I agree that this is not super consistent, also it would imply changing the code of the overview... Which is possible but also increases the complexity and maintainability of the extension.

**Comment by hyuri** [comment]
Is it supposed to follow the close button placement of the overview? The close button is placed left on my overview, it follows my placement setting. Maybe another extension is doing it... so I'm thinking that changing just dash-to-dock might suffice.

**Comment by vanvugt** [comment]
:point_up:
Fixed in future version 79.

**Comment by hyuri** [comment]
Awesome! Thank you @3v1n0 !
