### ISSUE TITLE
Window counter indicators dominant color not working

### ISSUE THREAD

**Issue by esa1975** [micheleg/dash-to-dock#1929]
Hello. I use the dominant color option for window count indicators and I noticed in the latest release that no indicators were showing. I switched off the dominant option and the indicators returned. This is an acceptable workaround but I would like to see the dominant color option fixed if possible. I am providing some basic information but please let me know if there is anything else I can provide. Thank you for the wonderful extension!

Manjaro Gnome
Gnome 43.3
X11
Dell Inc. XPS 15 9570

**Comment by sebadorn** [comment]
I have exactly the same issue. It started right after updating to Dash-to-Dock v77.

Ubuntu 22.04.2
Gnome Shell 42.5
X11, single monitor
[dash-to-dock-config.txt](https://github.com/micheleg/dash-to-dock/files/10837766/dash-to-dock-config.txt)

**Comment by glerroo** [comment]
The problem is at line 940 of appIconIndicators.js
```
const [iconInfo] = themeLoader.lookup_icon(iconTexture.get_names(),
````
with the pre-update version work again
```
const iconInfo = themeLoader.lookup_icon(iconTexture.get_names()[0],
```

`sudo journalctl -f /usr/bin/gnome-shell` return this error:
```
JS ERROR: Error: Expected type string for argument 'icon_name' but got type Array
_getIconPixBuf@/home/glerro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:940:40
_getColorPalette@/home/glerro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:960:29
_computeStyle@/home/glerro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:374:67
_updateIndicator@/home/glerro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:397:14
vfunc_allocate@/home/glerro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:254:22
vfunc_allocate@/home/glerro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:158:20
```

**Comment by Theluga** [comment]
i did what glerroo said.
It's working again! Thank you!

**Comment by vanvugt** [comment]
:point_up:
Fixed in next version 78.
