### ISSUE TITLE
When auto-hide mode, can new window be placed avoiding DtoD?

### ISSUE THREAD

**Issue by HubKing** [micheleg/dash-to-dock#1931]
I am using Wayland. I docked DtoD on the left side, and auto-hide is enabled. A lot of apps (such as Gnome Files) start at the (0,0) coordinate or the top-left corner. This is probably because Wayland does not support setting window location for security or something. The problem is that a new window at (0,0) makes DtoD hide itself. Of course, if auto-hide is not enabled, new app windows appear next to DtoD.

I wonder if it is technically possible to make new app windows appear next to DtoD even when auto-hide is enabled, so that DtoD will remain there until the user moves the window to the left or maximise the window.

**Comment by vanvugt** [comment]
The purpose of autohide is to make the whole desktop available as the workarea. So windows might appear in the top-left corner. If you want to change this behaviour then it is more an enhancement request to pose to mutter and gnome-shell.

Workaround:
```
gsettings set org.gnome.mutter center-new-windows true
```

**Comment by HubKing** [comment]
> The purpose of autohide is to make the whole desktop available

Well, actually, I enabled auto-hide, because application windows (mostly FireFox) go beneath DtD when awaking from sleep.

**Comment by vanvugt** [comment]
That's being tracked in #1370 and https://launchpad.net/bugs/1961508
