### ISSUE TITLE
this._launchMaxWaitIds is undefined

### ISSUE THREAD

**Issue by MisterMountain** [micheleg/dash-to-dock#1935]
Hi,

On my Fedora Linux 37/Gnome 43 i receive this error: `this._launchMaxWaitIds is undefined`
Which results in a not working extension for me.
I dont see an UI Endpoint to set this value.

As far as i see, other people seem to have the same Problem as me: https://extensions.gnome.org/extension/307/dash-to-dock/

**Comment by maniacx** [comment]
I got this too. But after several gnome shell restart it started working. 
@micheleg here are some logs the second time dock would show up

`Some code accessed the property 'State' on the module 'docking'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
JS ERROR: TypeError: Docking.State is undefined
_dockIsNear@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:473:24
_updateSolidStyle@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:440:29
enable@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:392:18
_adjustTheme@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:287:32
updateCustomTheme@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:232:14
`

**Comment by maniacx** [comment]
FYI happened again. this time with "this.LaunchMaxWaitIds" Earlier it was logs were for a different error, "Docking.state is undefined."

Anyways here  are logs for "this.LaunchMaxWaitIds"
`JS ERROR: Extension dash-to-dock@micxgx.gmail.com: TypeError: this._launchMaxWaitIds is undefined
destroy@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:397:9
destroy@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:711:15
wrapWindowsBackedApp/shellApp.destroy@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1007:22
destroy@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1230:32
destroy@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2539:29
disable@/home/maniacx/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js:31:17
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:126:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:541:45
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:541:24
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:685:46
disableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:227:29
DisableExtension@resource:///org/gnome/shell/ui/shellDBus.js:451:38
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:324:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34`

**Comment by maniacx** [comment]
Update. this.LaunchMaxWaitIds error on shows when we disable the extension

**Comment by MaxBro12** [comment]
Manjaro Gnome Min same error. 
In my case, after the computer wakes up from sleep mode, after authorization (( Rebooting computer helpsbut not for long. 
Log:
JS ERROR: Extension dash-to-dock@micxgx.gmail.com: TypeError: this._launchMaxWaitIds is undefined
destroy@/home/maxbro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:397:9
destroy@/home/maxbro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:711:15
wrapWindowsBackedApp/shellApp.destroy@/home/maxbro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1007:22
destroy@/home/maxbro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1230:32
destroy@/home/maxbro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2539:29
disable@/home/maxbro/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js:31:17
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:125:32
_onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:536:45
_onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:536:24
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:658:14
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_sync@resource:///org/gnome/shell/ui/sessionMode.js:204:14
pushMode@resource:///org/gnome/shell/ui/sessionMode.js:163:14
activate@resource:///org/gnome/shell/ui/screenShield.js:620:34
_onLongLightbox@resource:///org/gnome/shell/ui/screenShield.js:339:18
onComplete@resource:///org/gnome/shell/ui/lightbox.js:198:18
_makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:152:13
_easeActor/<@resource:///org/gnome/shell/ui/environment.js:239:64

**Comment by ranton1990** [comment]
Same error on Ubuntu when coming back from sleep. Restarting x11 helps.

**Comment by straurob** [comment]
> Same error on Ubuntu when coming back from sleep. Restarting x11 helps.

Just for those who don't know how: Restarting the session can be easily done by: `Alt + F2`, then `r`, then `Enter`

**Comment by Bllacky** [comment]
I can confirm I have the same issue with what is an almost vanilla installation of Fedora 37.

**Comment by VGerris** [comment]
Same issue for me with Fedora 37 and Gnome 43. Happy to test any patches, thanks

**Comment by xXMRK888YTXx** [comment]
Same issue for me with Fedora 37.It show after unlock screen

**Comment by jkemp814** [comment]
this._launchMaxWaitIds is undefined

Fedora Linux 37 Silverblue
fedora:fedora/37/x86_64/silverblue
Version: 37.20230227.0 (2023-02-27T00:44:34Z)

**Comment by tobiulm** [comment]
Same here. Fedora 37. The last version didn't had this Issue. After the update today it crashes.

**Comment by luca-martino** [comment]
Same here. 
OS: Fedora release 37 (Thirty Seven) x86_64
DE: GNOME 43.3

**Comment by rgpublic** [comment]
Same here on recent Manjaro when unlocking screen. Restarting X11 as a workaround obviously doesn't work under Wayland so I'd say this is pretty major.

**Comment by loulou64490** [comment]
Same on fedora 37...

**Comment by brucej72** [comment]
...and same on Ubuntu 22.04. alt + f2 seems to fix it (temporarily)
Also notice that installing from the GNU extensions site shows an error

**Comment by dav1app** [comment]
Same on Debian Bookworm.

**Comment by flaviojoaofelix** [comment]
Same problem here after update system update today. at the same time the smart hiding is not working properly, causing the bar to be always hidden.

Fedora 37 Workstation + GNOME 43.3 + X11

`this._launchMaxWaitIds is undefined`

**Comment by adelynx** [comment]
Same in Fedora 37

**Comment by maniacx** [comment]
As a temporary workaround I am using Dash2Dock Version76 again.  so far works like before..
If you dont know how, Go to release on D2D github and download the v76. 
Extract zip/tar. 
Copy all files/folder from the extracted folder except for 1 file. **metadata.json** . 
I repeat. Dont copy  **metadata.json** .  
Paste all copied file in the .local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com 
Note: .local is a hidden folder.  if you cannot see ./local folder use ctrl+H for nautilus.
Restart gnome
Use on your own risk. I am not responsible for anything.

**Comment by Opendreas** [comment]
> 
I have the latest Tumbleweed with Gnome 43.3 and X11.
After I open a photo in gThumb from Flatpak and when I close gThumb, Gnome crashes.
I I tried versions 76 from Github, 77 from extensions.gnome.org and fix
https://github.com/micheleg/dash-to-dock/pull/1937
but nothing helps, it works only version 75.

**Comment by cobalt2727** [comment]
> Same here on recent Manjaro when unlocking screen. Restarting X11 as a workaround obviously doesn't work under Wayland so I'd say this is pretty major.

@rgpublic you should be able to do the same thing on Wayland by logging out and logging back in

**Comment by NullCoke** [comment]
Same problem in Fedora 37

**Comment by vanvugt** [comment]
:point_up: 
Fixed in next version 78.
