### ISSUE TITLE
Can't pin to dock any more?

### ISSUE THREAD

**Issue by adeel14553** [micheleg/dash-to-dock#1945]
I have updated to the latest version yesterday, now everything is added to favorite and pin as well but as soon as I close the window, it pops out from the dock as well.

**Comment by 3v1n0** [comment]
I don't get such bug, can you please provide the log?

**Comment by adeel14553** [comment]
animate-show-apps=true
apply-custom-theme=true
background-opacity=0.77000000000000002
click-action='minimize'
custom-background-color=false
custom-theme-shrink=true
dash-max-icon-size=40
disable-overview-on-startup=false
dock-fixed=true
dock-position='LEFT'
extend-height=true
height-fraction=0.90000000000000002
icon-size-fixed=false
isolate-workspaces=false
multi-monitor=false
preferred-monitor=-2
preferred-monitor-by-connector='eDP-1'
preview-size-scale=0.20000000000000001
running-indicator-style='DOTS'
scroll-action='switch-workspace'
scroll-to-focused-application=true
show-apps-at-top=false
show-favorites=false
show-mounts-network=true
show-mounts-only-mounted=true
show-show-apps-button=true
show-trash=true
show-windows-preview=true
transparency-mode='DEFAULT'


The problem is the pin system is not working, if i close the app, it will not be shown in dock even if it is pinned or not.

**Comment by 3v1n0** [comment]
That's not enough, I'd need to get the output of `journalctl /usr/bin/gnome-shell` after the issue happen.

To see if you've log lines involving `dash-to-dock`.

**Comment by adeel14553** [comment]
`Mar 03 12:59:54 latitude-3510 gnome-shell[7362]: Spurious clutter_actor_allocate called for actor 0x56467db536c0/<dashtodockContainer>[<Gjs_dash-to-dock_micxgx_gmail_com_docking_DashToDock>:0x56467db536c0] which isn't a descendent of the stage!
Mar 03 14:59:57 latitude-3510 gnome-shell[7362]: st_widget_get_theme_node called on the widget [0x5646804a3180 Gjs_dash-to-dock_micxgx_gmail_com_docking_DashToDock.left dashtodock shrink running-dots fixed extended:insensitive "dashtodockContainer"] which is not in the stage.
Mar 03 14:59:57 latitude-3510 gnome-shell[7362]: Spurious clutter_actor_allocate called for actor 0x5646804a3180/<dashtodockContainer>[<Gjs_dash-to-dock_micxgx_gmail_com_docking_DashToDock>:0x5646804a3180] which isn't a descendent of the stage!`

**Comment by adeel14553** [comment]
Idk, i have many extension. Maybe i can't find the logs properly.

**Comment by adeel14553** [comment]
It works somehow after the updates. Thanks for the response. Enable and disalbe dash-to-dock and then restarted the gnome by alt+f2 and r.
