### ISSUE TITLE
Gnome crash

### ISSUE THREAD

**Issue by Opendreas** [micheleg/dash-to-dock#1950]
Since version 76, if I open a photo in Natilus using gThumb Flatpak, when I close gThumb, Gnome crashes.
If I open first gThumb and photo in gThumb, then everything works fine.

Steps to reproduce
1. Open nautilus
2. Open photo in nautilus with gThumb Flatpak
3. Close gThumb

System:
openSUSE Tumbleweed 20230227
Gnome 43.3-2
Dash to dock 78

**Comment by vanvugt** [comment]
Please attach the section of your system log showing the crash.

**Comment by Opendreas** [comment]
I also found out that the crash happens when I open and close a photo from an SD card. When it comes from home, then everything is fine.

[log.txt](https://github.com/micheleg/dash-to-dock/files/10857105/log.txt)

**Comment by vanvugt** [comment]
These look like two different bugs:
```
Mär 01 05:09:40 precision kernel: gnome-shell[1962]: segfault at fffffffffffffcc0 ip 00007f4c2a09cf0f sp 00007ffe47f7c850 error 5 in libmutter-11.so.0.0.0[7f4c2a053000+13e000] likely on CPU 8 (core 2, socket 0)
Mär 01 05:09:40 precision kernel: Code: 2e 0f 1f 84 00 00 00 00 00 66 90 41 55 48 89 f7 41 54 55 53 48 83 ec 08 e8 6e 03 fc ff 4c 63 25 2b 23 18 00 48 89 c3 49 01 c4 <4d> 8b 2c 24 4c 89 ef e8 65 c2 fb ff 31 f6 >
```
and
```
Mär 01 05:09:45 precision gnome-shell[4633]: JS ERROR: Exception in callback for signal: hiding: TypeError: Docking.State is undefined
                                              _dockIsNear@/home/andreas/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:473:24
                                              _updateSolidStyle@/home/andreas/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:440:29
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                              _changeShownState@resource:///org/gnome/shell/ui/overview.js:300:14
                                              _animateNotVisible@resource:///org/gnome/shell/ui/overview.js:625:14
                                              hide@resource:///org/gnome/shell/ui/overview.js:609:14
                                              activateWindow@resource:///org/gnome/shell/ui/main.js:740:14
                                              _onCloneSelected@resource:///org/gnome/shell/ui/workspace.js:1399:18
                                              _activate@resource:///org/gnome/shell/ui/windowPreview.js:547:14
                                              _init/<@resource:///org/gnome/shell/ui/windowPreview.js:102:51
```
Was the second one actually a crash? I can't tell because there's not enough log.

**Comment by Opendreas** [comment]
the first error is similar to this one
https://gitlab.gnome.org/GNOME/mutter/-/issues/2552

After the crash when closing gThumb, for example, I open flatseal and when closing, crash happens again. 
Nothing else is written in the log, after the crash, the gnome is restored.
All this repeats until I disable dash to dock or put version 75.

**Comment by 3v1n0** [comment]
That `Docking.State` error was fixed in v79, as per the crash please report a new one if it happens again with dock trace.
