### ISSUE TITLE
[Bug] Failed to launch "Trash" proto[finishFunc] is not a function

### ISSUE THREAD

**Issue by hyuri** [micheleg/dash-to-dock#1952]
Clicking the Trash icon fires the following notification: 'Failed to launch "Trash" proto[finishFunc] is not a function'

![image](https://user-images.githubusercontent.com/18584014/223427460-82bc9bcd-8bf6-436b-a8eb-1d3cbc26e1c6.png)

This seems to have started after I restarted the OS and deleted a picture on the desktop.

- Pop!_OS 21.10
- Gnome 40
- X11

**Comment by 3v1n0** [comment]
Please, provide the whole trace from `journalctl /usr/bin/gnome-shell`

**Comment by hyuri** [comment]
[dash-to-dock_trash-error_trace.txt](https://github.com/micheleg/dash-to-dock/files/10881716/dash-to-dock_trash-error_trace.txt)

**Comment by eriktheswede** [comment]
I am getting the same error while trying to open trash by clicking on the trash icon in the dock.

CentOS 9 Stream, Gnome 40.10.

**Comment by persicsb** [comment]
Getting the same error on Red Hat 9.1.
