### ISSUE TITLE
"Show Applications" Button doesn't work with touchscreen except in overview mode.

### ISSUE THREAD

**Issue by alexskc** [micheleg/dash-to-dock#196]
Pressing the "Show Applications" button from the dock doesn't actually pop up the application launcher. It shows the "swarm" animation, overlaying the current window, and then disappears. If you go into overview mode and then press the button, it behaves as expected. Clicking the button with a mouse also behaves as expected.
- Arch Linux
- Gnome 3.16.2
- Dash-to-dock 46
- Default settings, except dock positioned at bottom and with "Use Built-In Theme" enabled.

**Comment by micheleg** [comment]
This is part of a variety of incompatibilities with touch screen events #128. As stated elsewhere, I can't test thus easily develop any touch related stuff.

**Comment by vladimiroltean** [comment]
As a workaround, I am able to obtain the desired behavior by long-pressing the button.
Tested on Yoga 2 Pro, GNOME 3.18, Arch.

**Comment by micheleg** [comment]
Thanks for the additional information. I might be able to get occasional access to a touchscreen system, so I hope I will be finally able to solve this issue and improve touch interaction.

**Comment by MishkaRogachev** [comment]
Have same trouble on my Lenovo u530 touch GNOME 3.18, Ubuntu

**Comment by Wotanhaecker** [comment]
I have the same problem, closed my dublicate entry here #408

**Comment by swprojects** [comment]
hmm I had this issue years ago... seems like it also affects "Window list" extension where trying to select  a window would not work by touch so I would assume it is the same bug.

Link to extension: https://extensions.gnome.org/extension/602/window-list/

**Comment by staviss** [comment]
The same with Debian Jessie @ ThinkPad S1 Yoga
--
Shell version: 3.14.4
Extension version: 51

**Comment by staviss** [comment]
Shell also becoming unresponsible for touscreen activity after the gesture to call the overview (finger-swipe from left) is used, and I think that is a related thing to this: is also occurs when the dock is visible without overview.

**Comment by alien2003** [comment]
Confirmed

**Comment by bittner** [comment]
Related bug reports in other projects:

- [gnome-shell #1765356](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1765356) (Launchpad)
- [gnome-shell #480](https://gitlab.gnome.org/GNOME/gnome-shell/issues/480) (GNOME project) - _closed_

**Comment by bittner** [comment]
@vladimiroltean 
> As a workaround, I am able to obtain the desired behavior by long-pressing the button.

On myLenovo X1 Carbon it's actually long-pressing (to make the applications grid appear) and then slowly swipe the finger away from the icon-button (so that - seemingly - a release-button event is not triggered).

This behavior is fairly easy and consistent to reproduce, and doesn't seem to be dependent on any specific computer model or brand.

**Comment by PJSingh5000** [comment]
I think this is related as well:
https://github.com/micheleg/dash-to-dock/issues/128

**Comment by 3v1n0** [comment]
Yes these are related, and basically the same issue, and a proposed fix is at https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/272

It can be fixed also at extension level, following more or less what said here: https://github.com/micheleg/dash-to-dock/issues/128#issuecomment-432913072, however in this case the `notify::checked` on `showAppsButton` should be wrapped and everytime we get this signal we should verify the current clutter event that generated it, and in case ignore the change.

**Comment by Tooniis** [comment]
Confirmed on Lenovo Miix 310 with Ubuntu 18.10, GNOME 3.30

**Comment by 3v1n0** [comment]
This is now fixed for latest gnome-shell and cherry-picked to 3.28 and 3.30.

If there's interest we could fix this at extension level either for older shell versions, it can be done as explained in https://github.com/micheleg/dash-to-dock/issues/196#issuecomment-432913465

I think we can close the bug here, unless there's interest in workaround the issue at this level.
