### ISSUE TITLE
Notification badge counter persistant or wrong number displayed

### ISSUE THREAD

**Issue by sekurilabs** [micheleg/dash-to-dock#1964]
After the latest update I have noticed the notification badge count is +1 than the actual number of new notifications. For example I get an email, Geary icon badge shows 2 new emails.
For Teams for Linux for example the number of notification doesn't go away after the message is read, it's persistent and only way to clear the count is to restart the shell. Application restart doesn't reset the counter.

**Comment by 3v1n0** [comment]
Notification badges now also includes the tray notifications you have. This could be probably be re-considered in case an application provides its own counting though.

**Comment by vageliskatsiotis** [comment]
Noticed this today after the last update of D2D in Thunderbird. When I deactivated the extension and the initial dock did not have the notification number. Reactivated and it was there again. Also  does not go away even if I read all of the emails. I have to restart gnome shell for it to go away

**Comment by fabd** [comment]
Why am I seeing a (1) now on the Files icon in the dock? Just rebooted after the extension upgrade.

**Comment by jrom99** [comment]
I have the same problem on Firefox after a recent update (dash-to-dock 79, gnome-shell 43.3, fedora 37).

**Comment by 3v1n0** [comment]
Can you verify whether you've notifications involving these apps in the notifications tray?

The reason why the emblems are added is the fix for #20, they can be disabled from d2d settings or using the do-not-disturb mode.

**Comment by jrom99** [comment]
Yes, I had some Outlook notifications in the calendar top popup, but they had already been addressed within Firefox.

**Comment by 3v1n0** [comment]
Eh, that's not something we can check, the feature here is to show the number of unread notifications in the tray.

In case you don't want this feature, there's an option to disable it.

**Comment by vladamarek** [comment]
I have the same problem and on some launchers I can't get rid of those notifications:

![image](https://user-images.githubusercontent.com/82888469/223994549-ec667432-aee5-4288-8ea2-667ebc9316de.png)

The issue appeared after upgrading gnome-shell-extension-dash-to-dock from 78-1 to 79-1.

**Comment by jrom99** [comment]
In that case, the badge's presence doesn't seem to be consistent, since I can close the terminal to erase its badge, but closing Firefox won't do anything. I'll take a look if a report has been issued about the badge's number's size, since it's too small to be visible.

![image](https://user-images.githubusercontent.com/47498278/224026743-10180e2b-2c3f-4dc1-ab94-dd599517d7e8.png)

Wouldn't it be better if the badge disappeared if the window came into focus or the program closed instead of being dependent on the top calendar popup?

**Comment by 3v1n0** [comment]
@mzryz interesting to hear.

As per settings, it's a bit bad looking because we're still supporting Gtk3 used in some old GNOME versions, so we are a bit limited in how to handle the window.

**Comment by 3v1n0** [comment]
What do you get running this in `alt+f2` -> `lg` (looking glass): `Main.messageTray.getSources().map(s => s.notifications.map(n => n.resident))`

**Comment by jrom99** [comment]
```
>>>Main.messageTray.getSources().map(s => s.notifications.map(n => n.resident))
r(0) = false,false
>>>Main.messageTray.getSources().map(s => s.notifications.map(n => n.source.app || n.source._app.id))
r(1) = [object instance wrapper GIName:Shell.App jsobj@0xhex-number native@0xhex-number], [object instance wr...
```

I can't copy the text in that window, and the buttons don't have tooltips, so I'm not sure if I did everything right.

**Comment by 3v1n0** [comment]
You can get the full text by doing `print(Main.messageTray.getSources().map(s => s.notifications.map(n => n.source.app.id || n.source._app.id)))` and then checking your `journalctl /usr/bin/gnome-shell`

**Comment by jrom99** [comment]
`mar 09 22:19:18 n gnome-shell[1597]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed`

This was the last line (and only in the 22h19 mark).

**Comment by pled** [comment]
So if my understanding is correct, we now have badge counters including tray notifications or we have to disable "show icons emblems" in parameters, and then with don't have the previous behaviour (which was the best to my opinion) ?

**Comment by paroj** [comment]
> Notification badges now also includes the tray notifications you have. This could be probably be re-considered in case an application provides its own counting though.

this is a drastic departure from the previous UnityAPI based behaviour:
https://wiki.ubuntu.com/Unity/LauncherAPI#Count

previously it would display an application-defined "count", while now it *adds* a different quantity (notifications) without considering the applications intention.

This would probably be fine, if you just introduced the count badges, but as they were available previously this is a bug on 2 levels
1. it breaks UX as described above. There are *existing* user expectations that no longer hold
2. it breaks the UnityAPI by adding random numbers on what the application wants to convey

**Comment by mickeyr** [comment]
Anyone know of a good replacement for dash-to-dock that doesn't mess up the notification count?

**Comment by 3v1n0** [comment]
@mickeyr there's an option, just disable that.

**Comment by 3v1n0** [comment]
@paroj fair, I think we can do two things:
 - Show another counter just for notifications
 - Don't bother showing notifications count in apps that provide such data.

In any case this is something we can easily customize in settings, I personally prefer to have a sum of them but it could be not the case for other people.

**Comment by pled** [comment]
> @3v1n0 : "there's an option, just disable that."

The option disable ALL notifications (e.g. new emails) so this is not was we expect (previous behaviour). 

> @mickeyr 

You may try [dock-from-dash](https://github.com/fthx/dock-from-dash), a **simple** dock that does use native GNOME Shell dash.

**Comment by paroj** [comment]
>  I think we can do two things:

@3v1n0 actually, I would suggest a combination of both.

For applications that *do provide* LauncherAPI data, display it as before. Do not display notification counts here as chances are that the application is already doing it in a more sophisticated way.

For applications that *do not* provide LauncherAPI data, display the notification count, but use a different color. This makes clear that this is a different kind of data. This is an important cue for the users to know what the numbers mean that they are looking at.

**Comment by christophlsa** [comment]
> @mickeyr there's an option, just disable that.

But does this disable all the notification icons, as others have said?

I've been really annoyed by this behaviour for weeks now. At least now I know it comes from the notifications and not the applications. I have already checked the settings but have only found the option to disable this notification icon completely.

In my opinion, this is not really good UX. When you see the icon with a number on it, you usually click on the application to see if there is anything new, not on the notifications at the top.

**Comment by paroj** [comment]
> I've been really annoyed by this behaviour for weeks now

to meanwhile get back to a sane behavior you can download the previous release:
https://github.com/micheleg/dash-to-dock/releases/tag/extensions.gnome.org-v78

then change the version to 79 here, so you dont get auto-updated:
https://github.com/micheleg/dash-to-dock/blob/4788aea8d6c27cdbfee09bc73b7fbb89971bdefc/metadata.json#L15

the run `make install` to overwrite the current one.

**Comment by 3v1n0** [comment]
Ok, more options and behaviors are now handled in #1988 pull request, please give it a try, you should get these options:

![image](https://user-images.githubusercontent.com/345675/231561360-2ee7fe59-f72e-48ab-a965-b21906bffa3d.png)

**Comment by binarykitchen** [comment]
OMG this issue has haunted me for many weeks, I even contacted Slack's technical support and they pointed me to this thread.

**Comment by mickeyr** [comment]
Yeah, the new option still doesn’t fix it for me on fedora

**Comment by binarykitchen** [comment]
I do not have this extension installed at all, yet I'm experiencing the same problem. My guess, it's a different extension causing this.

Maybe everyone who's experiencing this problem should share a list of installed extensions and their versions here. This might give us a clue what causes notifications never to go away.

Here's my list: https://gist.github.com/binarykitchen/2f41ac2cff36c82160f5503eac6658f5

**Comment by mickeyr** [comment]
Recheck the last one in your list, it is in fact this extension

**Comment by binarykitchen** [comment]
"Ubuntu Dock"? But this repository is called "Dash to Dock". That's not the same name? This got me misleaded.

**Comment by RossContino1** [comment]
You actually have to clear the notification panel manually and then the badges match.  Press the super key (Windows button) + V and clear list.  All your badges will sync and be correct.  Gnome stores all your notifications until you clear them and all are reflected in the application badges.

**Comment by sallam-dev** [comment]
Coming from Windows and KDE, the notification count badge behavior is surprising.

Typically, opening the application would clear the notification badge from the dock but not clear it from the notification center.

The current behavior is sort of like mobile devices (Android specifically) where one would have to clear the notification from the notification panel so the count decreases or resets.

Is this the intended behavior?

Is there a possibility of a configuration option to handle this?

In my case, it's Slack (electron-based). So I'm not sure if this behavior is the same with other apps

**Comment by gazhay** [comment]
> Coming from Windows and KDE, the notification count badge behavior is surprising.
> 
> Typically, opening the application would clear the notification badge from the dock but not clear it from the notification center.
> 
> The current behavior is sort of like mobile devices (Android specifically) where one would have to clear the notification from the notification center/panel so the count decreases or resets.
> 
> Is this the intended behavior?
> 
> Is there a possibility of a configuration option to handle this?
> 
> In my case, it's Slack (electron-based). So I'm not sure if this behavior is the same with other apps

From a UX/UI perspective, this is a horrendous way for the notifications to be handled. I get that its probably (yet another terrible) Gnome upstream thing, but I'd be keen on having a more sane handling, either in this extension or via another. 

The only real solution is to disable the decorations for the icons at the current time.

**Comment by trane77** [comment]
Hi, I've just installed Fedora 42 (with Gnome 48) and encountered this problem. As far as I can remember, the notification badge was working properly on my previous Linux install (was Ubuntu).

Is there any way to fix it? I've already tried to disable/re-enable slack notifications from Gnome settings, with no luck. 

[This solution](https://askubuntu.com/a/1556131) doesn't work as well (there's no `org.gnome.shell.extensions.dash-to-dock`).

Let me know if I can give you more info, or help to fix it 😃

**Comment by capsudo** [comment]
Confirm that even when using following settings: 
- Launchers > Show icon Emblems = true
- Launchers > Show icon Emblems > "Application-provided counter overrides the notification counter" = true

The app badge icons are not updated when "unity like" messages I received.

When using [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel) it works.

I'm opening a new issue for clarity => https://github.com/micheleg/dash-to-dock/issues/2611
