### ISSUE TITLE
Constant notification badge on GNOME Files

### ISSUE THREAD

**Issue by rogueocelot** [micheleg/dash-to-dock#1965]
After the recent update GNOME Files always has 1 notification badge, with no apparent way to clear it without turning off notification badges.

openSUSE Tumbleweed 20230306
Dash to Dock 79
GNOME 43.3 Wayland

![Screenshot from 2023-03-07 15-29-38](https://user-images.githubusercontent.com/21340618/223557211-855f5877-2733-4958-bbd3-1721ad719285.png)

**Comment by 3v1n0** [comment]
Do you have a notification in the notifications tray related to files?

This is what we show, unless you're in dnd mode or emblems are disabled.

**Comment by rogueocelot** [comment]
Yeah that was the issue, I had to manually dismiss the notification tray notification (and I didn't know they persisted through restarts).
