### ISSUE TITLE
size of notification badge counters

### ISSUE THREAD

**Issue by g1bber1sh** [micheleg/dash-to-dock#1969]
firstly this is a wonderful feature. thanks a lot for implementing them!

but is there a way to tweak them to be bigger? i like size 32 icons and the badges are small and blurry and hard to read. i wouldnt mind if the badges were as big as on 48 size icons on 32 size icons.
is there a way i can tweak this myself, or can it be implemented?

**Comment by 3v1n0** [comment]
IIRC this can be changed from css, using minimum size, but I need to check futher, so we can indeed tweak the badge sizes for not-too-small-icons.
