### ISSUE TITLE
Shrunken dash icons do not touch screen edge

### ISSUE THREAD

**Issue by heftig** [micheleg/dash-to-dock#197]
With the default theme, the clickable area of an icon touches the screen edge, extending the target area for the mouse towards infinity. With the built-in theme, the mouse must be removed from the edge before the icon is clickable.

shell 3.16.3
dtd 46

**Comment by micheleg** [comment]
I might have misunderstood, but it seems to me that with the default theme the clickable area is even smaller, with larger margins from the screen edge. Can you confirm?

**Comment by heftig** [comment]
With the default theme, the clickable area touches the screen edge. With the built-in theme, the clickable area ends one pixel removed from the screen edge.

**Comment by micheleg** [comment]
We are talking about the Adwaita theme, right?

**Comment by heftig** [comment]
We are. Default = Adwaita. Built-in = Adwaita + whatever DtD does.

**Comment by micheleg** [comment]
This should be solved in master (cbcc067c3d221ac). Additional themes might still break the behaviour, but the built-in one is now consistent with the default.
