### ISSUE TITLE
Repeats of system tray after sleep and unlock

### ISSUE THREAD

**Issue by beesyrupfactory** [micheleg/dash-to-dock#1974]
I'm not sure how to reproduce this issue, but I'm using a distro based on Ubuntu 20.04 LTS.

After I my machine goes to sleep and I sign in again the dock shows a repeat of the system tray (non-GNOME default icons).

It didn't happen until the latest update, and the only way to fix it is to restart the X server.

If there are any diagnostics I can provide please let me know

**Comment by vanvugt** [comment]
Sounds like you have two dock extensions. Try opening the Extensions app and disabling Ubuntu Dock. Or try:
```
gnome-extensions disable ubuntu-dock@ubuntu.com
```

**Comment by beesyrupfactory** [comment]
Hi @vanvugt ,

Thank you for your response. This results in:
`Extension “ubuntu-dock@ubuntu.com” does not exist
`

I am using Zorin 16.2 on this machine. I do have a macOS-like dock, and have been using Dash-to-Dock like a macOS topbar.

![Screenshot from 2023-03-20 18-45-42](https://user-images.githubusercontent.com/86087525/226327337-ebb232af-592e-4d60-b1f1-c2305af99823.png)

Do you have any recommended approaches? I'm happy to disable ZorinOS's dock, if there are any alternatives that can work alongside Dash-to-Dock.

Thanks!

**Comment by vanvugt** [comment]
Use `gnome-extensions list` to see what they're called and then `gnome-extensions disable` to disable all but one.

**Comment by beesyrupfactory** [comment]
Found the culprit! It was `zorin-appindicator@zorinos.com`.

After setting `gnome-extensions disable zorin-appindicator@zorinos.com`, I'm no longer seeing the dupes after unlocking my system 👌

Very much appreciated, @vanvugt!
