### ISSUE TITLE
Dash to Dock GUI settings in Extensions is too large for lower-res screens

### ISSUE THREAD

**Issue by Anduril97** [micheleg/dash-to-dock#1975]
Hey! You guys have done great work with this, so thanks! I am stuck using a 720p laptop and I have this issue where the window size of the Settings for Dash to Dock (in Extensions) is way too large for my screen so I can never see the bottom settings as the window is not resizeable. Conversely, if I try to drag the window up to reach the bottom the title bar goes offscreen, again due to the window not being resizable. Could you allow the settings window to be smaller with a scrollbar maybe?
Thank you!

**Comment by Franciel-Victor** [comment]
I run into the same problem!

**Comment by vanvugt** [comment]
The GNOME Extensions GUI does seem to be resizable *and* automatically shrinks to fit small screens. I just tested 800x600 on both GNOME 42 and 44. What GNOME versions are you using?

**Comment by vanvugt** [comment]
Is the window not scrollable, or just not obviously scrollable?

**Comment by Anduril97** [comment]
Although the gnome extensions gui does resize to fit the screen resolution, for some reason the Settings page for Dash to dock still displays full size to the point that I cannot access the lower options without moving the title bar beyond the screen (upwards). I tried scrolling it and it did not work for me.

I'm on Gnome version 43.3 (Manjaro)
