### ISSUE TITLE
[Bug] Gnome crashes when opening a text file from the trash bin in Gedit and quitting it

### ISSUE THREAD

**Issue by hyuri** [micheleg/dash-to-dock#1984]
Hi!

Gnome is crashing whenever I open a deleted text file in the trash bin (with Gedit) and quit Gedit.

**System:**
- Pop!_OS 21.10
- Gnome 40
- Dash-to-Dock v79

**Comment by 3v1n0** [comment]
How is this related to the dock? SInce you're opening the files from nautilus...

Does your journal includes dash-to-dock traces?

**Comment by hyuri** [comment]
Seems related to #1952 and #1949 . Started happening after I stopped being able to empty the trash bin with dash-to-dock.

**Comment by 3v1n0** [comment]
Both those issues are fixed in current code, so it should yours. Let me know if that's not the case!
