### ISSUE TITLE
Dash To Dock ruins Workspaces

### ISSUE THREAD

**Issue by HowToCount** [micheleg/dash-to-dock#1987]
When I'm trying to use Workspaces it takes me to the desktop and makes visual dock bug. 
![CIp3SDgbahw](https://user-images.githubusercontent.com/125271782/231529302-07cd0843-018d-4477-9375-c7ef39cd22d6.jpg)

**Comment by 3v1n0** [comment]
What is the extension?

**Comment by ProgKing** [comment]
> What is the extension?

![image](https://user-images.githubusercontent.com/125271782/231748901-7c81cc94-bcac-4c9d-a870-9373d9363d2d.png)

![image](https://user-images.githubusercontent.com/125271782/231749017-42072cd1-9dbc-4fde-a9d6-1a4ea9a2638a.png)

Oh, man! I just fixed it. Silly me.. I turned off Cosmic Dock Built-In extension and now Dash To Dock working fine
