### ISSUE TITLE
Still Experiencing Issues with Dash To Dock and Workspaces

### ISSUE THREAD

**Issue by ProgKing** [micheleg/dash-to-dock#1990]
Every time I launch the POP!_OS system with the Dash To Dock extension, I must turn off Cosmic Workspaces to make it work properly. Otherwise, it doesn't work, and even if I fix it by turning off and turning on Cosmic Workspaces, it resets completely, making it impossible to work like this.

![image](https://user-images.githubusercontent.com/125271782/231954329-a6f7f96e-2cb3-43e1-8e1d-90ff493c2e72.png)

![image](https://user-images.githubusercontent.com/125271782/231954386-a6c96474-bacf-4a6d-9177-13d7c66bda0c.png)

**Comment by 3v1n0** [comment]
I'm sorry, but dash-to-dock is not meant to support a complex setups like that one, I'd suggest you to ask Pop Shell or Pop Cosmic developers to handle this kind of setup.

We do our best to ensure everything work, but other extensions may break our expected behavior.
