### ISSUE TITLE
Feature request: Add support for showing notification count for applications.

### ISSUE THREAD

**Issue by OlegOAndreev** [micheleg/dash-to-dock#20]
It would be useful to (optionally) show the number of notifications, which were emitted by each application. An example can be seen in the following screenshot: http://cloudfront.omgubuntu.co.uk/wp-content/uploads/2011/04/screenshotae_thumb.png

I'm willing to propose a patch if you like the general idea.

**Comment by zeraien** [comment]
What happened with this? Any plans on implementing, is it worth it taking a crack at the code?

**Comment by micheleg** [comment]
@zeraien This was never finalized and  merged and I don't think I am note personally motivated to work on it, as I don't feel the need to overhaul the default Gnome behaviour. Should someone want to try to improve this feature, i'm open to consider its integration, yet I can't promise much of my attention given the time I can dedicate to this project.

**Comment by gochev** [comment]
so sad I would love such feature :( @OlegOAndreev  is gone :) and I guess this will never be rewritten and merged ? :( This is like the biggest thing I miss from my Mac when using Gnome. Is there any other similar extension or something that supports notification badge counts on apps ?

**Comment by Feichtmeier** [comment]
Awesome extension!
Though I miss this really. Progress bars of downloads and unread mail count from geary. That would make it perfect. @gochev you could use plank, like I do, but it just feels renundant to install another dock when there could be this one

**Comment by micheleg** [comment]
Also, download progressbar and unread messages count (vs unread notifications count) is not a freedesktop standard and is supported by ubuntu/libunity and derivative (elementary) only. This makes the notifications a bit less helpful. I personally don't want to target a specific platforms (which i don't run). I have no idea what will happen to unity support in applications now that the project has been deprecated.

**Comment by Alexander-Wilms** [comment]
I file a bug report here: https://bugzilla.gnome.org/show_bug.cgi?id=781368

If Gnome could reuse the Unity LauncherAPI, that'd be great.

**Comment by k3a** [comment]
Yes, this is probably the feature I miss the most, too. I used Plank on Linux which has some kind of "notification" dot but I can't use Plank when in Wayland. Other than that this extension works perfectly for me.

**Comment by owais** [comment]
I wouldn't hold my breath on Gnome accepting any unity. Unity wouldn't exist if that was possible :)

Anyway, there has been some discussion in Gnome bug tracker around this and it looks like Gnome might be open to accept a NEW API to implement things like these. https://bugzilla.gnome.org/show_bug.cgi?id=701402#c13. 

It would be great if just libunity API was accepted as all existing apps would become so much better inside Gnome Shell but a new API wouldn't be so bad either. May be a linunity shim can b created later to add support for libunity in Gnome shell.

**Comment by micheleg** [comment]
@owais Thanks for the information.

**Comment by krasi-georgiev** [comment]
bump so it doesn't get forgotten :)

**Comment by owais** [comment]
This is already implemented in ubuntu-dock now and I think might be up-streamed but not sure about that.

**Comment by micheleg** [comment]
This is indeed implemented in dash-to-dock (as of version 62, awaiting for review on the extension website but available here: https://micheleg.github.io/dash-to-dock/releases.html) as it is in Ubuntu-dock. The main limitation is that it only  works in Ubuntu (and derivatives)  as it uses Unity own dbus protocol to retrieve the notification information.

**Comment by nkkollaw** [comment]
@micheleg : I've installed X and GNOME on top of Ubuntu Minimal CD (upgraded to Bionic).

Is there a specific package that I can install to enable this functionality? Ubuntu is now a slighly modified GNOME desktop, so it should be possibile..?

Thanks!!

**Comment by nkkollaw** [comment]
@micheleg : I've installed GNOME on Ubuntu Minimal CD (upgraded to Bionic).

Is there a specific package that I can install to enable this very useful functionality?

(on a side note, I'm still confused as to what relationship Ubuntu has with Unity anymore. I guess it's been kept around for all the APIs..?)

**Comment by micheleg** [comment]
@nkkollaw sorry for the late reply. I believe that on Ubuntu (and derivatives) as long as you have version 62 you should get the notification badges without having to install any additional package. Did you manage to get it working?

**Comment by nkkollaw** [comment]
Hi sure--no problem!

I never got it to work, unfortunately. I had installed Ubuntu via the minimal CD install so it's very possible that I was missing some package.

I've since moved back to Xfce though, so that somewhat solved that problem :-)

**Comment by nickbien** [comment]
Bumping thread :)

**Comment by fr3nchalp4a** [comment]
Very interesting feature ! Could be interesting and very useful to certain users @OlegOAndreev @micheleg 
But this issue is a bit old, can't it be added in the README hoping some people passing by may get interested in the feature (and maybe dev a PR?) ?

**Comment by 3v1n0** [comment]
This is supported for long time using libunity APIs, so closing.

**Comment by 3v1n0** [comment]
Sorry, I was thinking about unity emblems, I was wrong.
