### ISSUE TITLE
Option to modify "Show Applications" animation

### ISSUE THREAD

**Issue by vjcagay** [micheleg/dash-to-dock#200]
Hi!

It would be nice if this feature is implemented. If possible the animation could be disabled and be replaced with fade in/out effect instead, such as what was done on Simple Dock extension. Honestly the animation is laggy.

I really appreciate that this feature could be considered.

**Comment by micheleg** [comment]
Hi,
I tried to keep the default behaviour as much as possible. While having a simple fadein/fadeout transition should not be too difficult - I did have it at a certain point because the animation was broken - I'm trying not to implement every possible options. On my system the animation is not laggy most of the time, beside the first time it's rendered in a session.  I will consider this option after I do  some test.

**Comment by vjcagay** [comment]
In my case my laptop's running on Intel 4600 in Linux (disabled the nvidia one). It might be in isolated in my case, but the Show Applications animation most of the time is choppy. So I looked on other dock extensions out there and I saw Simple Dock's fade in/out animation smoother.

Thanks for considering!

**Comment by micheleg** [comment]
Just to be sure: is the animation inside the overview - i.e. disabling the
extension - less laggy? With an hd4000 i have only very occasional problems

**Comment by vjcagay** [comment]
Yes. It might be just in my case. That's why I decided to use another extension called Impatience extension to smooth out the choppy animation.

**Comment by micheleg** [comment]
I briefly tested the impatience extension and it actually makes the show appplication animation a bit laggy to me. Can you confirm if this is the case also for you? If the animation is more fluid without the impatience extension then it might be an incompatibility worth to be investigated.

**Comment by micheleg** [comment]
Sorry, my fault. It was the "isolated workspaces" extension to make the animation laggy.

**Comment by vjcagay** [comment]
In my case I tried setting the Impatience above 1.00, which results for the animation to take a little more time, but at least it smoothens out the choppiness.

**Comment by micheleg** [comment]
Hi, 
an option to disable the spring animation (from outside the overview) has been added to the master branch (ecc0a8ca51afc8ae361d7723f61c27263cb4ebe2). This use the same fade-in animation associated with the ```<Super>+A``` shortcut.

**Comment by vjcagay** [comment]
Thanks!
