### ISSUE TITLE
Dash to Dock causes Activities Menu to freeze on login

### ISSUE THREAD

**Issue by VeldoraTheDragon** [micheleg/dash-to-dock#2000]
Hi there
When running dash-to-dock on an arch machine running Gnome 43 and dash to dock 80 (and prior versions), it causes the activities menu to freeze in place. You can however use the top-bar and open programs. But you can't return to the desktop.

This happens, when the notebook is being turned on or rebooted after login.

Our Specs are:
Distro: Arch Linux
Kernel: 6.2.12-arch1-1
Gnome: 43.4-1
Mutter: 43.4-1
GDM: 44.0-1
Display-Server: Wayland

This issue has been going now for a few months, but since no system-update ever fixed the issue, I'm concerned, that it's an extension issue, rather than an OS issue.

This issue here: https://github.com/micheleg/dash-to-dock/issues/774
is describing the exact same behaviour, but since then, no answer of the OP has been given to the question of @micheleg 

Here are my logs, what happens when the issue occurs:
```
Apr 24 14:21:40 gnome-shell[2494]: Window manager warning: Trying to remove non-existent keybinding "shortcut".
Apr 24 14:21:40 gnome-shell[2494]: JS ERROR: Error: Invalid overview shown transition from SHOWING to HIDDEN
                                                                          _changeShownState@resource:///org/gnome/shell/ui/overview.js:295:19
                                                                          _hideDone@resource:///org/gnome/shell/ui/overview.js:640:18
                                                                          _animateNotVisible/<@resource:///org/gnome/shell/ui/overview.js:626:55
                                                                          onStopped@resource:///org/gnome/shell/ui/overviewControls.js:757:21
                                                                          _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:150:22
                                                                          _easeActorProperty/<@resource:///org/gnome/shell/ui/environment.js:316:60
                                                                          _easeActorProperty@resource:///org/gnome/shell/ui/environment.js:285:11
                                                                          init/St.Adjustment.prototype.ease@resource:///org/gnome/shell/ui/environment.js:372:27
                                                                          runStartupAnimation@resource:///org/gnome/shell/ui/overviewControls.js:813:31
                                                                          _prepareMainDash/<@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2212:54
                                                                          _create/object[name]@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:332:37
                                                                          runStartupAnimation@resource:///org/gnome/shell/ui/overview.js:98:24
                                                                          runStartupAnimation@resource:///org/gnome/shell/ui/overview.js:686:24
                                                                          waitForDocksReady/<@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2092:31
                                                                          _emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
                                                                          _createDocks@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2063:14
                                                                          _toggle/this._toggleLater<@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1877:18

```

I would be very pleased, if the issue could be addressed and fixed in the next release, since we're depending on this extension.

If any more information is needed, feel free to ask.

Cheers
~ Veldora

**Comment by VeldoraTheDragon** [comment]
Okay according to the Gnome-Devs, the problem is, that DtD is starting the startup animation again after it has been started. This means, it's not a Gnome Bug.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6633#note_1730866

So maybe this could help solve the problem.

**Comment by claytonwramsey** [comment]
I'm encountering this issue as well.

**Comment by claytonwramsey** [comment]
I'm not sure why, but updating to Ubuntu 23.04 seems to have fixed this for me.

**Comment by VeldoraTheDragon** [comment]
Hi @claytonwramsey 
Has Ubuntu perhaps announced, which package-version they used for the release, since we're still having issues with DtD 80 on Arch.

And just to be sure. 
Isn't the default panel on the left of Ubuntu not made with Dash to Panel instead of Dash to Dock?

**Comment by VeldoraTheDragon** [comment]
Since @micheleg hasn't had any commits since May 2022 and the last Commit of v80 was made by @3v1n0 I'm tagging you.

Do you have perhaps an idea, how to fix the problem, described above?

**Comment by 3v1n0** [comment]
Please check if https://github.com/micheleg/dash-to-dock/pull/2006 helps you otherwise could also be due to https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2763
