### ISSUE TITLE
Make it work with POPOS cosmic?

### ISSUE THREAD

**Issue by BarbzYHOOL** [micheleg/dash-to-dock#2005]
Hello,

would it be possible to add an option to work with POPOS? there is this archived repo that works fine for 22.04 but no longer updated

https://github.com/micheleg/dash-to-dock/compare/ubuntu-dock...halfmexican:dash-to-dock-pop:ubuntu-dock

**Comment by 3v1n0** [comment]
Sorry, this is out of scope for this project.

Pop-os has too many modifications to be able to track, we do accept contributions from their side to work with it, but it's not something we can maintain.

**Comment by BarbzYHOOL** [comment]
:'(
