### ISSUE TITLE
Icons are moving themselves after update to 81-1

### ISSUE THREAD

**Issue by delthia** [micheleg/dash-to-dock#2012]
Hi,
I'm on manjaro, and after updating dash to dock yesterday, I noticed that it started malfunctioning.
I also have the issues mentioned in issue #2010 , but for me I also works strangely when opening a new app, all the icons start to move around. The following is a clip of how it behaves for me.
[Grabación de pantalla desde 2023-05-17 15-10-23.webm](https://github.com/micheleg/dash-to-dock/assets/101663529/80bf7e34-187b-4083-8b23-43a76ee639b0)
The shown above happens with any application.

Thanks

**Comment by mojo5** [comment]
Hello!
I'm on manjaro too.
The same problem exactly.

**Comment by ArcticDev78** [comment]
I have the same problem as well on Fedora 37 running GNOME 43.5

**Comment by gyan000** [comment]
Just to confirm the same issue on Fedora 38, with GNOME 44.1

**Comment by mstapaj** [comment]
Fedora 38, GNOME 44.1, Xorg same problem

[icons_moving.webm](https://github.com/micheleg/dash-to-dock/assets/94313658/59dc34b8-5ef5-4554-a9af-abbd56eca8f0)

**Comment by SercanDmr** [comment]
Ubuntu 22.04 LTS - Same.

**Comment by coreybruce** [comment]
duplicate issue to mine 

https://github.com/micheleg/dash-to-dock/issues/2010

**Comment by delthia** [comment]
> duplicate issue to mine
> 
> #2010

Oh, I saw the part where you couldn't rearrange the icons, but I didn't think that both issues were the same. In that case, I'll close this issue so discussion can continue in yours.

Thanks

**Comment by coreybruce** [comment]
Yeah that is another simpton of this bug I am also experiencing :)

**Comment by rloporp** [comment]
I worked around it by switching off the "Wiggle urgent applications" toggle (Dash to Dock Settings -> Launcher). Is this the expected behavior?

**Comment by coreybruce** [comment]
> I worked around it by switching off the "Wiggle urgent applications" toggle (Dash to Dock Settings -> Launcher). Is this the expected behavior?

Sadly not, this sounds similar to setting the option to make it a full bar isntead of a dock to make it work again. This update has a lot of issues.
