### ISSUE TITLE
When installing Amberol, Dash-to-Dock recycle bin opens Amberol [SOLVED]

### ISSUE THREAD

**Issue by talesam** [micheleg/dash-to-dock#2016]
Something very strange happens, when I install amberol, it modifies something, I didn't find out what and makes this application open by clicking on the trash can that is in the Dash-to-Dock. See the video.

I built the package from this AUR: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=amberol

https://github.com/micheleg/dash-to-dock/assets/981368/aebec20d-dd59-4c12-8fe3-9fe406bbba13

**Comment by ebassi** [comment]
The problem is caused by Arch not shipping a default list of MIME type handlers; this means that the "default" becomes the first application in lexicographical order—and "io.bassi.Amberol" sorts before "org.gnome.Nautilus".

Use:

    xdg-mime default org.gnome.Nautilus.desktop inode/directory

to set Nautilus as the default handler for folders.

**Comment by 0Raik** [comment]
Thanks a lot for the help! Had the same issue when installing Nemo or Amberol (Flatpak). 

`xdg-mime default org.gnome.Nautilus.desktop inode/directory`

It needs a logout or restart.
