### ISSUE TITLE
Dock sometimes does not show (push to show)

### ISSUE THREAD

**Issue by ainola** [micheleg/dash-to-dock#203]
I've been experiencing this since around the latest upgrade (46) on on both Nvidia and Intel graphics. I've put off reporting because I'm not sure how reliably I can report this.

With push-to-show enabled, sometimes I just can't get the dock to come up, no matter how hard I 'push'. Alt-tabbing to a window doesn't 'reset' it, often it takes a trip to the activities overview to get it working again.

Settings:
```
Animation Duration: 0.100
Hide Timeout: 0.300
Show Timeout: 0.100
Pressure Threshold: 160
```

I don't know what else could be helpful. The only other extensions I have are fairly simple ones like weather and quick-unmount menu items, nothing crazy.

**Comment by micheleg** [comment]
Hi, there's is a known bug (#190) related to fullscreen windows (this bug is solved in master). Does this happen in relation to entering and exiting fullscreen? Can you test latest master?

**Comment by jikamens** [comment]
It is happening to me without fullscreen windows.

I don't know how to install the latest master; I install by browsing to extensions.gnome.org and installing through my browser. If you walk me through installing by hand, I'm happy to try it out.

**Comment by micheleg** [comment]
There are basic instructions here:

https://micheleg.github.io/dash-to-dock/download.html#installfromsource

I you have trouble just ask.

**Comment by micheleg** [comment]
You could also test previous versions to find when the issue appears: you can get those for GNOME 3.16 from https://micheleg.github.io/dash-to-dock/releases.html. There are some instruction on the page I linked above.

**Comment by ainola** [comment]
I will also say that it's happening without fullscreen. It's kinda random and will just refuse to work until a trip to the overview. That's all I can say other than that having push-to-show off does not exhibit any problems.

I'll try my best to give you more information as I can: Please bear with me as I may be a little delayed.

Thanks for all your work.

**Comment by micheleg** [comment]
Thank you for your time. To narrow down the origin of the problem: does it
persistente if you disabile the push to show option in the settings
accessibile through  the gear menu of the intellihde switch? The most
importante thing is finding a reproducible way to trigger the bug di that I
can debug it. If you notice any pattern please let me know.

**Comment by ainola** [comment]
Yes, disabling push to show fixes it. I've been paying attention when this happens and it feels like there's a small chance you can stop trying to push, wait about ten seconds, then try again. Other times it will just never work.

**Comment by ainola** [comment]
I think it might have something to do with maximized (not fullscreen) windows, though. My body can 'sense' that it won't work every once in a while and it appears to be when I'm in Firefox (which is always maximized for me).

I'm still trying to find something reproducible.

**Comment by ainola** [comment]
Oh, my god, I'm such a moron. I think you're right: This is the fullscreen bug you fixed. I just found out that I sometimes fullscreen youtube videos! I can 100% reproduce it now. I updated to the latest git version and I can no longer reproduce it. I think we can safely call this a duplicate, then.

I'm sorry to have wasted your time!

**Comment by micheleg** [comment]
No problem.
