### ISSUE TITLE
dash to dock doesn't open on startup

### ISSUE THREAD

**Issue by shraykumar100** [micheleg/dash-to-dock#2031]
Using fedora 37 and dash to dock does not run itself on startup. I have to disable and re-enable the extension to make it work.

**Comment by idanka** [comment]
On Fedora 38, the application launch sometimes works, sometimes not:(

**Comment by persicsb** [comment]
This is a duplicate of https://github.com/micheleg/dash-to-dock/issues/2029

**Comment by 3v1n0** [comment]
Duplicate of #2029
