### ISSUE TITLE
The extension is no longer working

### ISSUE THREAD

**Issue by LucasFM10** [micheleg/dash-to-dock#2046]
The extension has just vanished from my computer on reboot and i cant install it again via gnome extensions website

**Comment by vanvugt** [comment]
Try deleting the contents of `~/.local/share/gnome-shell/extensions/`. Does it even exist?

**Comment by LucasFM10** [comment]
I solved my problem by adding an older version of the extension, but thanks anyway!

**Comment by vanvugt** [comment]
Closing this issue because there's not enough information here for anything to ever be fixed.
