### ISSUE TITLE
Freezing screen when the extension is loaded after last update of Ubuntu 22.04

### ISSUE THREAD

**Issue by wellrats** [micheleg/dash-to-dock#2051]
After last update of Ubuntu 22.04 when the extension is enabled, it freezes graphical interface on boot for almost two minutes before something appears on screen. If it is disabled at boot time the graphical interface appears very fast but if we go to extension manager and enable it the screen freezes for almost two minutes and then the extension becomes available. 

LSB Version:    core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Linux linwell1 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux

Gnome Shell 42.5

{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "A dock for the Gnome Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and desktops. Side and bottom placement options are available.",
  "gettext-domain": "dashtodock",
  "name": "Dash to Dock",
  "original-author": "micxgx@gmail.com",
  "shell-version": [
    "40",
    "41",
    "42",
    "43",
    "44"
  ],
  "url": "https://micheleg.github.io/dash-to-dock/",
  "uuid": "dash-to-dock@micxgx.gmail.com",
  "version": 84
}

I didn't find any error logs

**Comment by wellrats** [comment]
Wayland or X11 have the same problem

**Comment by vanvugt** [comment]
@wellrats, please attach a system log from immediately after the freeze by running:
```
journalctl -b0 > journal.txt
```

**Comment by wellrats** [comment]
I can send you videos with the extension enabled at boot and disabled at boot for you to see how it works.
Thanks.

**Comment by wellrats** [comment]
![image](https://github.com/micheleg/dash-to-dock/assets/3524744/429c0e1d-c860-44a6-b22d-1e95c089cbea)

Problem solved !!!
FlatPak needs d-bus permissions.
Installed FlatSeal to change permissions
Do not ask me why ...

Tks in advance but is good to know.
