### ISSUE TITLE
Cannot Cycle Through Windows on Super + <Num> unless restarted

### ISSUE THREAD

**Issue by George-Spanos** [micheleg/dash-to-dock#2061]
Issue is straight forward. It seems that there is a glitch with almost every app that I try to open multiple windows and cycle through except Files. It doesn't matter if I have 3-4 windows open, Super + Num does not cycle. Some example apps that I tried to cycle with no luck are Chrome, Firefox, Alacritty, VSCode. It also seems that more keybindings of dash to dock don't work unless restarted. One tested is Super + Ctrl + Num which does open new windows of app on Num. 

Everything works just after disabling and re enabling dash to dock from Extentions.

OS: Fedora 38
Dash to Dock: 84 

Thanks for Dash to Dock, has made my life a ton easier :)

**Comment by vanvugt** [comment]
Duplicate of #1414

**Comment by George-Spanos** [comment]
@vanvugt Could you please help me understand what is happening with this issue? I went through a train of issues related to this behavior. One opened seven years ago and is still open and another one was two years ago. However there is no mention to a bug such as the one I described above. People do mention the cycle behavior but none of them mention a behavioral change in the extension whoever you restart it. So I isn't quite get why this ticket is considered a duplicate. 

Do I miss something? Thank you

**Comment by vanvugt** [comment]
Nothing is happening. This extension doesn't have any full-time developers.

If you don't think it's a duplicate then I will un-duplicate it now.

**Comment by George-Spanos** [comment]
I'll try to take a look and hopefully open a PR.  Thanks

**Comment by George-Spanos** [comment]
I will close this issue for now as I cannot replicate with clear specific steps. Thank you @vanvugt for your immidiate responses.
