### ISSUE TITLE
Choose from Running Apps

### ISSUE THREAD

**Issue by lokimon** [micheleg/dash-to-dock#2079]
In Ubuntu 22.04 with dash to dock, if I had multiple instances of the same apps, I would select the app icon in the dock. Then the running apps preview would hover above the dock and I could choose.

I switched to Ubuntu 23.04 with dash to dock.  Now with multiple instances, if I click the app, it cycles one by one through the running apps. Which isn't nearly as fast.

I also only see 1 dot for apps with multiple instances running.
![Ubuntu 22 04](https://github.com/micheleg/dash-to-dock/assets/1200251/bddf33ba-10cb-4b6e-8610-892a71fd2a63)
![Ubuntu 23 04](https://github.com/micheleg/dash-to-dock/assets/1200251/539bfe51-0d11-4144-8943-afb0a7ed2cf8)

How can I get 22.04 behavior?

I really appreciate the help.

**Comment by 3v1n0** [comment]
`gsettings set org.gnome.shell.extensions.dash-to-dock click-action focus-or-previews`

**Comment by lokimon** [comment]
@3v1n0 Thanks!
