### ISSUE TITLE
Crash when I try to open dash-to-dock

### ISSUE THREAD

**Issue by nonameboyx** [micheleg/dash-to-dock#2097]
Randomly when I press windows button to open dash-to-dock I am getting crash and seeing something like to this error:

![image](https://github.com/micheleg/dash-to-dock/assets/139769974/889ba8ea-a6d0-4d62-900d-b70d3f947ae0)

And It is forcing me to log out and lost my session.

uname -a:
```
Linux kali 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux
```

My extensions are turned off after crash:

![image](https://github.com/micheleg/dash-to-dock/assets/139769974/5ee28662-f483-438f-ae2b-f18268adcbd0)

Probably this dmesg output line belongs to this error:
```
[21766.537433] gnome-shell[82458]: segfault at 28 ip 00007fe61d4f5284 sp 00007fff28cba120 error 4 in libmutter-clutter-12.so.0.0.0[7fe61d488000+8e000] likely on CPU 0 (core 0, socket 0)
```

$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
```
[/]
animate-show-apps=true
application-counter-overrides-notifications=true
apply-custom-theme=false
background-opacity=0.040000000000000001
custom-background-color=true
dance-urgent-applications=true
dash-max-icon-size=51
disable-overview-on-startup=true
dock-position='BOTTOM'
extend-height=false
height-fraction=0.90000000000000002
hide-tooltip=false
icon-size-fixed=true
isolate-locations=true
isolate-monitors=false
preferred-monitor=-2
preferred-monitor-by-connector='HDMI-2'
preview-size-scale=0.0
scroll-to-focused-application=true
show-apps-always-in-the-edge=true
show-favorites=true
show-icons-emblems=true
show-icons-notifications-counter=true
show-mounts-only-mounted=true
show-show-apps-button=true
show-trash=false
show-windows-preview=true
transparency-mode='FIXED'
workspace-agnostic-urgent-windows=true
```

Let me know if I can give you more information about this crash

**Comment by vanvugt** [comment]
What was logged before this?
```
[21766.537433] gnome-shell[82458]: segfault at 28 ip 00007fe61d4f5284 sp 00007fff28cba120 error 4 in libmutter-clutter-12.so.0.0.0[7fe61d488000+8e000] likely on CPU 0 (core 0, socket 0)
```

**Comment by nonameboyx** [comment]
Nothing, I mean some usual dmesg logging stuff. I didn't see any abnormal thing before this. I will try to reproduce and post here

**Comment by vanvugt** [comment]
If we can't see a Javascript stack trace here then the bug needs to be moved to gnome-shell. Because there's nothing we can do with this limited information. Please report the issue to your Linux vendor instead.
