### ISSUE TITLE
Support plural forms for translation ("Quit %d Windows" string)

### ISSUE THREAD

**Issue by xalt7x** [micheleg/dash-to-dock#2100]
In appIcons.js [there's](https://github.com/home-sweet-gnome/dash-to-panel/blob/master/appIcons.js#L1474) a code which adds taskbar action to Quit applications/windows:
```
        if (this._source.windowsCount > 0) {
            if (this._source.windowsCount === 1) {
                this._quitMenuItem.label.set_text(_('Quit'));
            } else {
                this._quitMenuItem.label.set_text(__('Quit %d Windows').format(
                    this._source.windowsCount));
            }
```
Which leaves only one form of plural from translators:
```
msgid "Quit %d Windows"
```

For languages like Ukrainian (which can use 3 plural forms), it's impossible to translate this string correctly, covering all possible numbers of windows.

Please add support for the plural forms of this string.

Thanks.

**Comment by 3v1n0** [comment]
Please check if https://github.com/micheleg/dash-to-dock/pull/2102 helps with this
