### ISSUE TITLE
Window picker/Activities Overview wrong margin

### ISSUE THREAD

**Issue by alfonsocv12** [micheleg/dash-to-dock#2108]
Hello I have been trying to fix this problem with no luck I have tested dash to dock for a long time, and believe that the latest version is great for my use case.

the only last issue that I have is the margin when activities overview is activated.

This is without dash-to-dock

![Screenshot from 2023-10-18 14-52-08](https://github.com/micheleg/dash-to-dock/assets/31135704/cbc2794b-0a46-4c5d-825a-67f6e1c60d1e)

And this is with it

![Screenshot from 2023-10-18 14-49-44](https://github.com/micheleg/dash-to-dock/assets/31135704/7cd5b13f-239c-4dd4-b496-d4b98da4dbc3)

I customize the css with `padding: 5px;` to get closer to the OG dock

**Comment by vanvugt** [comment]
Can you clarify whether the second screenshot is with your custom CSS or without? Also can you circle or highlight what the bug is?

**Comment by alfonsocv12** [comment]
Is with it. But is fixed now, I logout and login and everything aligned properly with the 5px padding-buttom (my bad sorry)
