### ISSUE TITLE
Gap between dock and maximized window

### ISSUE THREAD

**Issue by roworu** [micheleg/dash-to-dock#2109]
There is a small gap between dock and maximized window, that only appears with "Panel mode" Off.
Is that intended behavior? Or is there any way to remove it?
I'm using Ubuntu 23.10. Thank you.
 
![Screenshot from 2023-10-19 13-27-15](https://github.com/micheleg/dash-to-dock/assets/36964755/d3f1cb73-453e-4213-ae32-40599bfe1274)
![Screenshot from 2023-10-19 13-27-24](https://github.com/micheleg/dash-to-dock/assets/36964755/90114bfc-ac17-4689-b766-36a3c3b05741)

**Comment by vanvugt** [comment]
This is expected because the floating panel isn't meant to touch any window. But you should be able to tweak it manually by editing
```
/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/stylesheet.css
```

Also in future please report Ubuntu Dock bugs by running:
```
ubuntu-bug gnome-shell-extension-ubuntu-dock
```
