### ISSUE TITLE
Dash-to-dock crashes gnome-shell after resume from suspend

### ISSUE THREAD

**Issue by SKelem** [micheleg/dash-to-dock#2124]
Gnome-shell 45.0 has been crashing in Ubuntu 23.10 after closing then opening my laptop lid.
Here's a [screenshot](https://imgur.com/i1BezMB) from the crash.

I tried the following experiments:

1. Disable all gnome-extensions and reboot: closing/opening laptop lid does not crash gnome-shell.
2. Re-enable all my gnome-extensions, except dash-to-dock: closing/opening laptop lid does not crash gnome-shell.
3. Re-enable dash-to-dock: closing/opening laptop lid crashes gnome-shell.

I have attached some of the journalctl log:

**Comment by vanvugt** [comment]
Please provide the aforementioned log.

**Comment by vanvugt** [comment]
Also since you are using Ubuntu and this issue needs broader debugging as a gnome-shell bug, I'm going to close this and ask you to report it to Ubuntu by running:
```
ubuntu-bug gnome-shell
```
