### ISSUE TITLE
dash to dock can't display on ubuntu 20.04

### ISSUE THREAD

**Issue by johnxu2013** [micheleg/dash-to-dock#2129]
I manually build dash to dock. When I start it on gnome-extensions, it has error:
SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by vanvugt** [comment]
The git version of dash-to-dock doesn't support Ubuntu 20.04 anymore, sorry. For the supported versions please see https://extensions.gnome.org/
