### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ilkerhk** [micheleg/dash-to-dock#213]
Extension disappears (possibly crashes?) and comes back when I restart the gnome-shell. 
I have the version 48 of the extension. Below are the journalctl entries related to the extension. (Note:  it has lots of those within several seconds, I pasted some of them below which are journaled within the same second) 

Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Clutter-CRITICAL **: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed

Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175
Aug 28 23:59:44 suseT440s gnome-session[1652]: (gnome-shell:1915): Gjs-WARNING **: JS ERROR: Error: can't convert "width" to an integer
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.updateIconGeometry@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1397
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: myAppIcon<.onWindowsChanged@/home/ilker/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/myDash.js:1387
Aug 28 23:59:44 suseT440s gnome-session[1652]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Aug 28 23:59:44 suseT440s gnome-session[1652]: _initializeUI/<@resource:///org/gnome/shell/ui/main.js:175

**Comment by micheleg** [comment]
Thanks for your bug report. Closing as duplicated of #188.
