### ISSUE TITLE
The container with Icon/app options doesn't have padding.

### ISSUE THREAD

**Issue by barbudodev** [micheleg/dash-to-dock#2138]
- GNOME Shell 45.2
- Kernel: 6.6.8-arch1-1
- OS: Arch Linux x86_64
- DE: GNOME 45.2 
- Screenshot:  
![image](https://github.com/micheleg/dash-to-dock/assets/42384773/187d8d4d-5484-4def-9e4d-bf9d4ce8de04)

**Comment by vanvugt** [comment]
Menus belong to gnome-shell, so you should [report it there](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues). But before you do that please also check this isn't caused by your custom theme.
