### ISSUE TITLE
Error: No signal 'maximize' on object 'ShellWM'

### ISSUE THREAD

**Issue by alex285** [micheleg/dash-to-dock#214]
That is on GNOME 318 and affects more extensions too. So I Iet it a bit early here. 

https://github.com/micheleg/dash-to-dock/blob/master/intellihide.js#L75

Gjs-Message: JS LOG: Extension "dash-to-dock@micxgx.gmail.com" had error: Error: No signal 'maximize' on object 'ShellWM'

**Comment by nevesnunes** [comment]
[Relevant commit](https://github.com/GNOME/gnome-shell/commit/7305466765395e555278a3b26e9017387edb3a74)

**Comment by micheleg** [comment]
Hi, thanks for the bug report. I think this is a duplicate of #202. There is already a development branch (gnome-3-17 https://github.com/micheleg/dash-to-dock/tree/gnome-3.17). Unfortunately I haven't had time to do proper testing with the unstable version of GNOME Shell.  Have a look at it, and please report any further issue.

**Comment by alex285** [comment]
@micheleg Yeap 3.17 branch fixed that, but there is another bug now. Intelli-hide overlaps legacy status. In any case I close this, since that's a different bug.
