### ISSUE TITLE
"Shrink the dash" toggle shrinks menu

### ISSUE THREAD

**Issue by berezki** [micheleg/dash-to-dock#2141]
I think there is a bug when enabling dash shrinking Gnome menu shrinks as well. Have this on my PC but on laptop everything seems to work fine. It makes icons in menu smaller and apps grid becomes 6x3 instead of 8x3.
### **Shrink the dash disabled:**
![Screenshot from 2024-01-06 22-31-42](https://github.com/micheleg/dash-to-dock/assets/82938421/01a9152b-66ee-4943-9fb6-bc4146125e57)
### **Shrink the dash enabled:**
![Screenshot from 2024-01-06 22-31-21](https://github.com/micheleg/dash-to-dock/assets/82938421/2bd1e6a5-64f2-48a5-ac87-e01b4f39c892)

**Comment by vanvugt** [comment]
Inconsistent and unpredictable app grid sizing is a known issue (issues?) with gnome-shell. It is affected by the size of the things surrounding the app grid, so shrinking the dash will be a factor.

Trackling in https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2173
