### ISSUE TITLE
Bug on "Focus, minimize or app spread/preview" click action

### ISSUE THREAD

**Issue by coolkys** [micheleg/dash-to-dock#2145]
### Prerequisite
- Behavior > Click action > "Focus, minimize or preview" or "Focus, minimize or app spread" is set
- There is only one window visible and focused on the desktop (either only one window is open, or all other applications/windows are minimized)
- Click on the focused window's dock icon to minimize. Then, click on the icon again to focus the window.

### Expected Behavior
- When the app is minimized, the dock icon's "highlight" state is removed. (App is not focused anymore)
- When the icon is clicked again, the window focuses and becomes visible again.

### Bugged Behavior
- The icon stays in the 'window is focused' state, as made apparent by the icon remaining highlighted.
- When the icon is clicked again, the minimized window is not focused. Window does not become visible.

### What I tried
1. Disabling all other extensions, then restarting computer 
2. Resetting dash to dock settings, only applying the click action behavior

### Any error logs?
- Looking glass: No
- journalctl: No

### What am I running?

- Fedora 39, Kernel 6.6.9
- Gnome 45.3, Wayland
- dash-to-dock v89
- Dual monitors, 4K144 + 4K60
- `dconf dump /org/gnome/shell/extensions/dash-to-dock/`
> background-opacity=0.80000000000000004
> click-action='focus-minimize-or-appspread'
> dash-max-icon-size=48
> dock-position='BOTTOM'
> height-fraction=0.90000000000000002
> preferred-monitor=-2
> preferred-monitor-by-connector='DP-3'

**Comment by vanvugt** [comment]
Sounds like people have been reporting [bugs in that feature for years](https://github.com/micheleg/dash-to-dock/issues?q=is%3Aissue+is%3Aopen+Focus%2C+minimize). I don't think they've been triaged/deduplicated yet.

**Comment by coolkys** [comment]
> Sounds like people have been reporting bugs in that feature for years. I don't think they've been triaged/deduplicated yet.
So... does focus&minimize feature not get full bugfix support? If not, that's pretty disappointing; this is quite useful to me. Oh well.

**Comment by vanvugt** [comment]
This project doesn't have developers working on it full time, or even very often. All contributions are welcome.

**Comment by vanvugt** [comment]
Is this the same as #1972?

**Comment by coolkys** [comment]
Nope, seems different; My issue is that the window(not multiple) does not un-minimize at all. It stays minimized, because the dock thinks the window is currently focused even when minimized.

**Comment by e-rakavest** [comment]
I guess it related with also with that https://github.com/micheleg/dash-to-dock/issues/2235

**Comment by vanvugt** [comment]
Being minimized could still be the same issue as #1972. Please test extension version 93 or later.

**Comment by e-rakavest** [comment]
> Please test extension version 93 or later 

Thanks for answering but how I can install version 93 or later in right way on the Ubuntu 24.04 without breaking update in future

**Comment by coolkys** [comment]
Woah, didn't even know it got fixed! I'm currently on v96, Fedora 40. Can confirm issue is fixed. Thank you!

**Comment by vanvugt** [comment]
@e-rakavest, the official fix for ubuntu-dock in 24.04 isn't done yet. But https://bugs.launchpad.net/bugs/1997550 tracks that fact.

As a workaround you could use the `gnome-extensions` command to disable ubuntu-dock and install a newer version of dash-to-dock (for GNOME 46) from https://extensions.gnome.org/extension/307/dash-to-dock/
