### ISSUE TITLE
Second dock appearing when I click on show applications

### ISSUE THREAD

**Issue by claudemirtech** [micheleg/dash-to-dock#2157]
When i click in show application, a second dock appearing in the back
![Screenshot from 2024-03-09 16-10-41](https://github.com/micheleg/dash-to-dock/assets/5927854/7081b7ff-84bf-43cc-8540-b74fff4c561b)

**Comment by vanvugt** [comment]
Usually this means you have two docks installed/enabled. Please check:
```
gnome-extensions list --enabled
```
