### ISSUE TITLE
extension doesn't work in Gnome 46

### ISSUE THREAD

**Issue by a1ex-ak** [micheleg/dash-to-dock#2161]
Dear developer, your extension has stopped working in Gnome 46. I ask you to update, since I have been using it for a very long time. Thank you.

![Снимок экрана от 2024-03-20 09-03-10](https://github.com/micheleg/dash-to-dock/assets/121604147/f10c8ca8-856b-498e-94e6-026a7152beae)

**Comment by vanvugt** [comment]
Duplicate of #2156.

Support for GNOME 46 was merged only a couple of hours ago and has not been released yet.
