### ISSUE TITLE
Icons are not centred vertically in GNOME 46

### ISSUE THREAD

**Issue by vanvugt** [micheleg/dash-to-dock#2173]
Icons are not centred vertically in GNOME 46:

![Screenshot from 2024-03-25 17-34-08](https://github.com/micheleg/dash-to-dock/assets/11951986/c1bddb5f-0a8c-4549-a125-2d705a20d805)

**Comment by sergio-costas** [comment]
Can you post here the configuration? I tested it in Fedora, and the alignment is perfect... (checked with a screenshot and GIMP).

**Comment by vanvugt** [comment]
I reset all my gsettings to defaults and the bug went away so :man_shrugging: :slightly_smiling_face:

**Comment by sergio-costas** [comment]
Magic!!! :-D
