### ISSUE TITLE
Makefile:101: stylesheet.css Error 127 

### ISSUE THREAD

**Issue by jtome7** [micheleg/dash-to-dock#2176]
INSTALLATION of Dash-to-Dock Failed with stylesheet.css Error 127

[dash-to-dock]$ make
sassc --omit-map-comment _stylesheet.scss stylesheet.css
make: execvp: sassc: Permission denied
make: *** [Makefile:101: stylesheet.css] Error 127
[lbarnes@localhost dash-to-dock]$ make install
sassc --omit-map-comment _stylesheet.scss stylesheet.css
make: execvp: sassc: Permission denied
make: *** [Makefile:101: stylesheet.css] Error 127

**Comment by jtome7** [comment]
dash-to-dock]# make
sassc --omit-map-comment _stylesheet.scss stylesheet.css
Error: Invalid CSS after "$dock_sides:": expected expression (e.g. 1px, bold), was "[bottom, top, left,"
        on line 139 of _stylesheet.scss
>> $dock_sides: [bottom, top, left, right];
   -------------^
make: *** [Makefile:101: stylesheet.css] Error 1

**Comment by vanvugt** [comment]
The first comment is invalid because `make: execvp: sassc: Permission denied` was a problem with your installation.

The second comment `Error: Invalid CSS` I cannot reproduce. What OS are you using, and what branch are you trying to build?

**Comment by jtome7** [comment]
Oracle Linux 8.6  ( RHEL Linux Family )
Is this to be built as "root" or as the "user login account" ?
I have the same branch dash-to-dock v66 for Gnome 3.32 installed on another machine with same O.S. and it did NOT require libsass / sassc which I think is causing my problems on this installation.
THANKS for any ideas!

**Comment by vanvugt** [comment]
Please only build using the user login account, and ensure you are using the master branch (v89 or v90) before reporting build bugs here. That also requires that you have GNOME 45 or 46.

**Comment by jtome7** [comment]
THANKS for all your help!   I'll CLOSE this issue.
