### ISSUE TITLE
Release v90 with latest changes on master to support GNOME 46

### ISSUE THREAD

**Issue by theoludwig** [micheleg/dash-to-dock#2177]
Hello! :wave:

Thank you for making and maintaing this awesome GNOME extension. It's probably the most important extension, I'm using for my GNOME Desktop workflow, and to improve my UX (honestly I don't understand, how it is not integrated in GNOME by default, if anyone has a discussion related to it, I would be curious to read it, if it has already been discussed :eyes:).

I've just upgraded my Arch Linux to use GNOME 46, and found out, that this extension is not working. So I tried to follow the instructions on the README to install it from source: https://github.com/micheleg/dash-to-dock#installation-from-source, and it seems to work quite well.

It seems like there are still issues related to GNOME 46: https://github.com/micheleg/dash-to-dock/issues/2160, but I think, it's still already worth to release a new version, as broken versus, already working, is already an improvement worth a release IMHO.
Is it possible to do pre-releases? Maybe that would be the solution, to release "not 100% ready".

I'm not familiar with the development of GNOME extensions, it's the first time, I installed one from source, If you publish a new update, will I automatically be updated to the newest version?

**Comment by Facni** [comment]
> honestly I don't understand, how it is not integrated in GNOME by default, if anyone has a discussion related to it, I would be curious to read it, if it has already been discussed 👀).

I would like to read it too, if someone knows, please.

**Comment by vanvugt** [comment]
I would like to get #2166 merged too.

**Comment by kernelb00t** [comment]
Hey! So basically when you install a software from source, you'll first download the Git repository (I suggest you to watch videos about how Git works, it will be the absolute and most important thing you'll need to learn and master on Linux). If you pull changes from upstream (the server) to your local repo (your machine), you'll just have to re-execute the command to build the software. You will have immediately the latest changes without waiting for a release. But, the obvious downside is if some dev pushes something bad, not much tested, it has the potential to break something. 

Second, I don't think pre-releases are that useful. It still needs packaging, effort etc... for not much help. You still can build the latest with the git repo, consider this a "pre-release". Even the actual extension isn't a stable release, as it will always contain bugs, break easily when a new GNOME is out, etc...

**Comment by theoludwig** [comment]
Thanks for your responses.

@kernelb00t I'm aware of how Git works and Linux. :laughing:
Being a developer myself (but not a developer of GNOME extensions).
Weird that you thought, I was a beginner, maybe my question was not well formulated.

My question was more related to how GNOME extensions releases are working. How updates are pushed to extensions.gnome.org and how users got the update. Is it automatic? How do users download the update?
As I stopped using the version published on extensions.gnome.org, will I still be able to get updates from the "official" one? Or I first need to uninstall the one I built from source, and then install again, the one on extensions.gnome.org?

I hope my questions are now clearer. :smile:

**Comment by Aqua1ung** [comment]
> As I stopped using the version published on extensions.gnome.org, will I still be able to get updates from the "official" one? Or I first need to uninstall the one I built from source, and then install again, the one on extensions.gnome.org?
This is one of the reasons why I would not bother installing directly from Git: it very likely requires maintenance, and returning to the official, non-Git version might be a hassle.

**Comment by penguin-teal** [comment]
@theoludwig you will not be automatically updated. When a new version comes out, you will have to uninstall the source-built copy you had cloned from GitHub and then download from extensions.gnome.org or Extension Manager or whatever you use.
You could also keep pulling the changes and re-installing from the source repo instead of using the GNOME website but those changes might not be stable.

**Comment by kernelb00t** [comment]
@theoludwig Sorry, I don't even know why I thought you were a newbie with git.

**Comment by assapir** [comment]
It still shows up in `https://extensions.gnome.org/extension/307/dash-to-dock/` as incompatible :(
