### ISSUE TITLE
GNOME shell crashes when dash-to-dock extension is disabled in overview

### ISSUE THREAD

**Issue by taoky** [micheleg/dash-to-dock#2179]
With current code from master (https://github.com/micheleg/dash-to-dock/commit/1053b3e336780d0c9a51cca46034d48463b5c2bf), dash-to-dock would make shell crash in both GNOME 45 and 46. This could be reproduced by:

1. Open Overview (both window picker and app grid could trigger this)
2. Lock the screen, or run `gnome-extensions disable dash-to-dock@micxgx.gmail.com` if `ssh`ing.

My local bisecting result shows that https://github.com/micheleg/dash-to-dock/commit/de35ab608daa8368d73397d52783507fa7edd15b is the first bad commit (weird) when testing with GNOME 45. And this diff patch "workarounds" the crash in both GNOME 45 and 46:

```diff
diff --git a/_stylesheet.scss b/_stylesheet.scss
index b23cc43..adc45af 100644
--- a/_stylesheet.scss
+++ b/_stylesheet.scss
@@ -251,10 +251,6 @@ $dock_style_modes: [null, shrink, extended, extended-shrink];
     }
 }
 
-.dash-item-container .overview-tile .overview-icon,
-.dash-item-container .show-apps .overview-icon {
-    background-color: rgba(255,255,255,0);
-}
 
 .dash-item-container .overview-tile:hover .overview-icon,
 .dash-item-container .overview-tile.focused .overview-icon,
```

This issue looks like https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7339 but it's slightly different (crashing widget is `Gjs_ui_dash_ShowAppsIcon`), and I have tried to find the cause but no clue. And this bug, if exists in shell, could only be triggered by an extension. I have also tried to build a simpler extension example, but it does not crash with a CSS-only extension.

bt full (GNOME 46): 
[bt-full-fedora-gnome46.txt](https://github.com/micheleg/dash-to-dock/files/14772277/bt-full-fedora-gnome46.txt)

**Comment by vanvugt** [comment]
Thanks for the bug report. dash-to-dock shouldn't be able to cause a segfault like that, and particularly not with style changes. It looks like we should track this [upstream](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7339) just keeping in mind the only way to reproduce it is with dash-to-dock.

**Comment by vanvugt** [comment]
I'm working on an upstream fix so let's track this in https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7339 instead.

**Comment by vanvugt** [comment]
The upstream fix is https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252, and it's already fixed in Ubuntu.

**Comment by nleanba** [comment]
Even if this gets fixed in upstream GNOME, it would be nice if you could update the extension to not have the problematic CSS rule -- it might take a while until GNOME is patched _and_ the update reaches e.g. my laptop.

While I agree that this is not "your" bug, but an upstream bug, I still think it would be best to implement a workaround here. I would like to be able to use the extension again before GNOME 49 or even 50 gets released with the fix.

**Comment by bradchristensen** [comment]
In the meantime, you can manually apply the patch mentioned by @taoky on your system by modifying `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx@gmail.com/stylesheet.css` (it's the first few lines at the top of the file), bearing in mind that it might get overwritten if the extension updates itself. For me it seems to make no difference to the dock appearance.

**Comment by vanvugt** [comment]
Since @sergio-costas wrote the "first bad commit" de35ab608daa8368d73397d52783507fa7edd15b he can decide whether modifying that is an acceptable workaround. But I suspect it may not even be a reliable workaround if [any stylesheet changes](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7339) could cause the same crash.

**Comment by vanvugt** [comment]
I guess there's a stochastic benefit to changing the CSS. If it reduces the frequency of the crashes then that reduces the burden of repeated crash reports we get here.

**Comment by vanvugt** [comment]
> I'm unable to reproduce the bug neither with the dash-to-dock from the extensions page, nor with the code from `master`. I've been doing the tests in a VM with Fedora 40 (Gnome Shell 46).

@sergio-costas, using freed memory won't always crash a process. Certainly last time I looked at this it didn't crash, but today it does.

To get a reliable answer I am now running gnome-shell under valgrind to ensure there are no errors matching the function names in https://bugs.launchpad.net/bugs/2069559

**Comment by vanvugt** [comment]
The upstream fix finally landed in gnome-shell version 49.rc

**Comment by iacobucci** [comment]
For people weirdly sticking to gnome-shell v47 (like me), i've found a fix that solves this and a very related problem with suspension with nvidia cards:

first, do as @taoky says, and comment out those lines:

```diff
diff --git a/_stylesheet.scss b/_stylesheet.scss
index b23cc43..adc45af 100644
--- a/_stylesheet.scss
+++ b/_stylesheet.scss
@@ -251,10 +251,6 @@ $dock_style_modes: [null, shrink, extended, extended-shrink];
     }
 }
 
-.dash-item-container .overview-tile .overview-icon,
-.dash-item-container .show-apps .overview-icon {
-    background-color: rgba(255,255,255,0);
-}
 
 .dash-item-container .overview-tile:hover .overview-icon,
 .dash-item-container .overview-tile.focused .overview-icon,
```

then, create a `~/.themes/custom-adwaita-nobg/gnome-shell/gnome-shell.css` with:

```css
.dash-item-container .overview-tile .overview-icon,
.dash-item-container .show-apps .overview-icon {
    background: none;
}
```

lastly open Gnome Tweaks -> appearance -> shell -> Custom-adwaita-nobg

And it should solve it!
