### ISSUE TITLE
dash to dock theming support like plank themes?

### ISSUE THREAD

**Issue by fastrizwaan** [micheleg/dash-to-dock#218]
Please add support for themes,
![y4abyji](https://cloud.githubusercontent.com/assets/1161682/9680979/569e16f2-5318-11e5-841f-f978fc18f839.png)

http://www.deviantart.com/browse/all/customization/skins/linuxutil/applications/docks/?q=plank

http://rhoconlinux.github.io/plank-themer/

**Comment by micheleg** [comment]
Theme support is extensive thought the standard GNOME Shell theming system : https://micheleg.github.io/dash-to-dock/theming.html.  The extension aim at being integrated into the GNOME shell, thus inheriting it's look and style. Moreover, while I tried to keep the extension as theme-friendly as possible, I have no interest in developing multiple themes for the dock, and anybody interested has already the tools to do it.
