### ISSUE TITLE
Too little padding between icons

### ISSUE THREAD

**Issue by gnolooo** [micheleg/dash-to-dock#2181]
As I previously mentioned in #2160:

With latest Gnome 46 release, I'm facing a few issues with padding between icons.

Now icons are much smaller and with less padding (so they appear more compact). I had to significantly increase the icon size to get something visually similar to before, but they're still too tight (in my opinion).

For this reason, the icons no longer have the old, rounded overlay when hovering with the cursor, but now they have a much smaller and square overlay. Weirdly, the only icon that has the same padding and same overlay, is the applications icon. More in the pictures below.

Also, the dots are still way too near to the icons, but there's an [upstream bug being tracked](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7488) in which the issue is that scaling is not considered when rendering and placing the dots.

My take on this is that everything (not just the dots issue) could be related to scaling. The little padding, the icons not resized properly, all this sounds to me like a scaling-related issue.

Hope I explained myself.

### Additional informations
**OS:** Arch Linux
**DE:** Gnome 46.0
**Device:** Lenovo ThinkBook 13s G3 ACN, AMD Ryzen 7 5800U, 16 GB RAM
**Primary monitor:** Integrated 2560x1600 13" with 175% scaling
**Secondary monitor:** External Lenovo P27 3840x2160 27" with 150% scaling

### Pictures

Here you can see the applications icon, with same old padding and overlay:

![Schermata del 2024-03-26 13-56-25](https://github.com/micheleg/dash-to-dock/assets/76843243/b9a1241b-1b7b-4b7f-9974-f68924bb4ced)

Here you can see other icons with square overlay and much less padding:

![Schermata del 2024-03-26 13-56-49](https://github.com/micheleg/dash-to-dock/assets/76843243/dbf29aa2-e2d3-4daf-a354-e1755ed4064e)

For reference, this is what the old, beautiful dock used to look like (you can clearly see much more padding, correctly placed dots, big and rounded overlays etc):

![316875850-f01c5e30-a71f-4724-bdf5-65107a68f378](https://github.com/micheleg/dash-to-dock/assets/76843243/64181708-fa54-4786-b0f2-2320bf501727)

**Comment by horga83** [comment]
I am also seeing this.

**Comment by vanvugt** [comment]
Did #2172 (07cd4c5b315802d803366bc6529e80c44fef576e) fix this?

**Comment by gnolooo** [comment]
No it didn't.
When I posted the issue, I was on the latest version at that time, which already included that commit; to be sure, I just tried with current latest version, and (as I expected) it changed nothing.

**Comment by gnolooo** [comment]
Don't know how that can be related, but I just updated both my system and my shell theme (from an older version built for Gnome 45 and kinda broken on Gnome 46, to a new version built for Gnome 46) and now the correct spacing is back again, as well as the dots that are now placed in the right position:

![image](https://github.com/micheleg/dash-to-dock/assets/76843243/e1a1a317-f6b4-4f62-bc17-e8a70b111e68)

Did you also push new updates with fixes on this subject? Don't really now if the fix came from here, from Gnome's side, or from the theme update but I'm glad everything is now back to normal.

**Comment by vanvugt** [comment]
Extensions like dash-to-dock inherit most of their functionality from gnome-shell so it makes sense that a new gnome-shell version would change things. Maybe the fix was 07cd4c5b315802d803366bc6529e80c44fef576e, but that suggests it was only ever a bug in 46, not 45.

**Comment by gnolooo** [comment]
Everything clear, I just don't really get the last part:
> that suggests it was only ever a bug in 46, not 45.

I've never mentioned Gnome 45... wdym?

Also, I don't really think 07cd4c5b315802d803366bc6529e80c44fef576e fixed it, at least not by itself:

> Did #2172 ([07cd4c5](https://github.com/micheleg/dash-to-dock/commit/07cd4c5b315802d803366bc6529e80c44fef576e)) fix this?

> No it didn't. When I posted the issue, I was on the latest version at that time, which already included that commit; to be sure, I just tried with current latest version, and (as I expected) it changed nothing.
>
> Btw, just wanted to remind that spacing is not the only issue, there's also the size issue (currently, in my system it's set at 44px to visually match the previous size, while before Gnome 46 I used to achieve the same size at around 32px). Don't know if that's related though.
