### ISSUE TITLE
Feature Request - Add option to disable offsetting of items in top panel

### ISSUE THREAD

**Issue by ebrin03** [micheleg/dash-to-dock#2183]
I have my dock on the left of the screen, set to 'Panel mode: extend to screen edge', and intelligent autohide turned off. This results in the date + clock button at the center of the top panel being offset one dock-width to the right. I would love to have the option to disable this change in position.

![Untitled design](https://github.com/micheleg/dash-to-dock/assets/147595781/57e9b4bf-8010-45bf-ae78-97fc7c71200e)

**Comment by vanvugt** [comment]
It looks like that was [an Ubuntu patch introduced in 18.04](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1716432), but I cannot find it in Ubuntu 22.04 or 24.04. Maybe it's already been dropped?

**Comment by vanvugt** [comment]
Seems the feature was [upstreamed in gnome-shell 6 years ago](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/cd0af33947f8eb73a163ecef975728988ab51549). And the only way to undo it is to set your dock to autohide. I agree this is not ideal, but it does mean this is no longer a dash-to-dock bug. You will need to log [an issue with gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues) instead.
