### ISSUE TITLE
Any timeline for Gnome 46 compatible release date?

### ISSUE THREAD

**Issue by logicito** [micheleg/dash-to-dock#2187]
Thank you, one of the most important, if not, the most important Gnome extension I use

**Comment by rudy-in** [comment]
same here like its dead

**Comment by ryzendew** [comment]
```
git clone https://github.com/micheleg/dash-to-dock && cd dash-to-dock && make && make install 
```

log out and log in

**Comment by jakefoglia** [comment]
Any idea when gnome 46 support will make its way to extensions.gnome.org?

**Comment by plainee** [comment]
> ```
> git clone https://github.com/micheleg/dash-to-dock && cd dash-to-dock && make && make install 
> ```
> 
> log out and log in

not work for my archlinux, error is:

dash-to-dock on  master via  took 5s 
❯ make
sassc --omit-map-comment _stylesheet.scss stylesheet.css
make: sassc: 没有那个文件或目录
make: *** [Makefile:101：stylesheet.css] 错误 127

**Comment by ryzendew** [comment]
Arch : sudo pacman -S sassc fedora sudo dnf in sassc

**Comment by gabriel-suela** [comment]
> Arch : sudo pacman -S sassc fedora sudo dnf in sassc


> Arch : sudo pacman -S sassc
> 
> Fedora 40 sudo dnf in sassc
> 
> ```
> git clone https://github.com/micheleg/dash-to-dock && cd dash-to-dock && make && make install 
> ```
> 
> log out and log in


this install completly breaks gnome extensions for me

**Comment by kabe-inc** [comment]
On Arch, just install `gnome-shell-extension-dash-to-dock-git` from the AUR. Works just fine.

**Comment by wpatton** [comment]
Sure we can install manually but if release 90 works on gnome 46, what's holding up publishing to the gnome extensions site?

**Comment by johnlasseter** [comment]
Yeah, whats the hold up?

**Comment by rnoons** [comment]
The hold up is the devs don't feel it's ready, you're welcome to help contribute. Alternatively you can just pull from master, which will get you up and running. Then when the tag release is made switch to that and updates will continue to happen via gnome extensions.

**Comment by kaushiksahu18** [comment]
> On Arch, just install `gnome-shell-extension-dash-to-dock-git` from the AUR. Works just fine.

i have just installed it using
```bash
yay -S gnome-shell-extension-dash-to-dock-git
```

now please help me how to enable it what to do??

**Comment by kernelb00t** [comment]
v90 is out, this issue can be closed. The extension will be uploaded to gnome extension website when maintainers have the time, I would expect in a day or two.
