### ISSUE TITLE
Fixed/Dynamic transparency broken on latest gnome

### ISSUE THREAD

**Issue by joaocandre** [micheleg/dash-to-dock#2195]
I'm unsure if this is an issue with the extension or with mainstream Gnome, but after a recent update (Archlinux, Gnome v46), transparency on the dock seems to not work anymore:

<img src="https://github.com/micheleg/dash-to-dock/assets/1812344/7e81a96c-e298-47ef-a0ec-0c37201e4c0f" width=50% height=50%>

Background is always black, not matter how much opacity is set.

**Comment by jedrzejboczar** [comment]
Had the same problem, but I found that I have "Blur my Shell" installed and it caused this. I was able to fix this by going into Blur my Shell settings -> Dash -> Dash to Dock blur and disabling it.

**Comment by joaocandre** [comment]
I'll have to test, but yeah I do have "Blur my Shell" enabled. I guess it's an issue on their side.

**Comment by joaocandre** [comment]
Created a new
