### ISSUE TITLE
Incorrect external link on GitHub wiki

### ISSUE THREAD

**Issue by user501254** [micheleg/dash-to-dock#220]
I am referring to this page: https://micheleg.github.io/dash-to-dock/
Towards the end of the page, the footer content provides links to alternative projects: Plank, Cairo dock, Docky.

**The links to Cairo dock and Docky are incorrect (contain an extra quote character).**

So Instead of 
`<a href="http://glx-dock.org/&quot;">Cairo dock</a>, <a href="https://launchpad.net/docky&quot;">Docky</a>`

It should be 
`<a href="http://glx-dock.org/">Cairo dock</a>, <a href="https://launchpad.net/docky">Docky</a>`

Great work with the extension :+1:

**Comment by micheleg** [comment]
Thank you. Fixed by a5c33601c44d398e57b6f6aed9dbd9ea7686e410.
