### ISSUE TITLE
Window preview doesn't work anymore

### ISSUE THREAD

**Issue by daniesmar0** [micheleg/dash-to-dock#2202]
Hi, I have just updated to version 91 and I had configured the middle button of the mouse to cause an application to pop up a preview of its content but it does no longer work (neither with the window focused, minimized nor any other window status)
![previewNotWorking](https://github.com/micheleg/dash-to-dock/assets/149255345/2b9e92ca-430f-47c7-8f1d-29fafe0210f7)

**Comment by prvks** [comment]
same issue

**Comment by jmgs7** [comment]
Same issue too.

**Comment by vanvugt** [comment]
I can't reproduce the issue in v91, but that screenshot suggests some error should be in the log for the missing widgets. Please check your logs.

**Comment by catcombo** [comment]
Doesn't work for me too. Looks the same as on screenshots. Fedora 39, GNOME 45.5. I don't have any other extension installed, except Dash-to-dock.

> Please check your logs.

Where can I find the logs?

**Comment by jmgs7** [comment]
I also found out that the schema is not detected for any key
(at least in dconf editor): 

![image](https://github.com/micheleg/dash-to-dock/assets/30865599/ccb1e6ed-d4ea-4bb5-bd9d-1817cc60c1db)

![image](https://github.com/micheleg/dash-to-dock/assets/30865599/453dfb03-f8ee-4d67-b4a2-829104db1cb4)

**Comment by vanvugt** [comment]
> Where can I find the logs?

```
journalctl -b0
```

**Comment by catcombo** [comment]
> > Where can I find the logs?
> 
> ```
> journalctl -b0
> ```

https://gist.github.com/catcombo/86f240f040089e2222b284a4a841ede9

**Comment by 3v1n0** [comment]
It seems this affects only 45, right?

@sergio-costas can you maybe see if one of the porting changes could have affected this?

**Comment by sergio-costas** [comment]
@3v1n0 I'm on it...

**Comment by masterdokuro** [comment]
> It seems this affects only 45, right?

Today I upgraded to fedora 40, gnome 46 & dash-to-doc v91 and window preview is working as expected again.  Prior to upgrade (fedora 39, gnome 45 & dash-to-doc v91) it did not work.

**Comment by sergio-costas** [comment]
I have to test it in gnome 45.

**Comment by sergio-costas** [comment]
Ok, I installed it in gnome 45. How can I trigger this bug?

**Comment by masterdokuro** [comment]
Open up two windows of an application which is on the dash, say firefox as an example.  Also, have **Show window previews** enabled for the click action in behaviour.

When you click the icon no preview is shown, only a bar like in the screenshot from the OP.

**Comment by sergio-costas** [comment]
I think that I fixed it.
