### ISSUE TITLE
Message badge count clears after i open an app

### ISSUE THREAD

**Issue by samira2822** [micheleg/dash-to-dock#2203]
Hello

Just bought a new Samsung A05 and i have a really frustrating problem regarding whatsapp

I have more than 342 unread messages on whatsapp

once i just open WhatsApp the Badge count clears the whole message count from 342 to Zero

Same problem with text messages

I contacted Samsung but they don't have any solution for this problem

Wondering if there is a 3rd party app that might solve this issue?

**Comment by 3v1n0** [comment]
The dock relies on what the application tells us, so not sure it's really our problem.
