### ISSUE TITLE
Transparency issue with Adwaita on Gnome 46

### ISSUE THREAD

**Issue by Razer0123** [micheleg/dash-to-dock#2212]
Been using this extension for ages, ever since Gnome 46 transparency seems not to be working

Using Adwaita as a theme

![Schermata del 2024-04-29 17-48-10](https://github.com/micheleg/dash-to-dock/assets/1551395/249e6424-af61-4168-977e-c8e21e44cadb)

**Comment by vanvugt** [comment]
According to #2195 it was caused by Blur My Shell so try disabling that one.
