### ISSUE TITLE
Wrong windows numbers

### ISSUE THREAD

**Issue by chamfay** [micheleg/dash-to-dock#222]
Hi,
The nbr of opend windows (in nautilus) is wrong.
Please see image below.
http://up.harajgulf.com/do.php?img=200484

I'm using the last version of dash-to-dock and ubuntu gnome 15.04

Thanks.

**Comment by micheleg** [comment]
Hi,
Do you have icons enabled on the desktop? The desktop might counts as a window, which is clearly not the right thing.

**Comment by chamfay** [comment]
Yeh,
I enabled the desktop, but without any icon on it.

**Comment by micheleg** [comment]
Fixed by 13d9fe0a35686621ec2.
