### ISSUE TITLE
Improve 'app spread' UX - eliminate unnecessary workspace swiping

### ISSUE THREAD

**Issue by mlntr** [micheleg/dash-to-dock#2224]
When in the 'app spread' view, it only shows windows from the _current_ workspace. That means having to swipe through multiple workspaces to find the desired app window (even workspaces that don't contain any windows!)

It should be possible to directly see all app windows from all workspaces immediately, which would make it easier/faster to find the desired window as there'll be no unnecessary swiping through workspaces. (also this is how Mac's "app exposé" works)

![app spread - edit](https://github.com/micheleg/dash-to-dock/assets/17552475/ca50d9c3-d21d-4ecc-b67c-ea41f8eb74ef)

Alternatively workspaces that don't contain app windows could be omitted.

Extra feature if the second approach: it'd be helpful if the workspace previews indicate how many app windows each workspace has (could 'app spread' within the previews, or put a badge by each preview with the number of apps the workspace contains)

**Comment by vanvugt** [comment]
I agree this would be nice to have but it should be requested [upstream in gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues), not here.
