### ISSUE TITLE
[FEATURE REQUEST] add dock alignement

### ISSUE THREAD

**Issue by JE-Amouel** [micheleg/dash-to-dock#2231]
hi,
first of all, thank your extension, I appreciate all the customization options made available to the user, we feel that this is work done by someone with passion wanting to offer an elegant solution in terms of productivity, thank you again,

I hope that you would dare to allow me a little suggestion regarding a functionality that I would really like to have,

It turns out that the dock can be positioned on the 4 edges of the screen, something that I like, but it turns out that it can only be aligned at the center of the edge on which we have chosen to place it (Top center , bottom center, right center, left center),

I would like to be able to choose the alignment,
Would it be possible to add options to align the dock? (START, CENTER, END)

thanks.

**Comment by vanvugt** [comment]
I think we can merge this feature request with #362.
