### ISSUE TITLE
Dash to Dock crashes GNOME when entering the lock screen from the overview

### ISSUE THREAD

**Issue by Aethersan** [micheleg/dash-to-dock#2234]
Steps to reproduce:
1. Activate Dash to Dock
2. Enter the Overview
3. Press Control + L to enter the lock screen
- GNOME crashes and restarts

![Screenshot](https://github.com/micheleg/dash-to-dock/assets/155457202/8ae3231f-9686-4486-8277-05663a366f2c)

**Comment by vanvugt** [comment]
Duplicate of #2179
