### ISSUE TITLE
 Preview of two or more  opened windows after loading Ubuntu

### ISSUE THREAD

**Issue by e-rakavest** [micheleg/dash-to-dock#2235]
Don't show any preview two or more  opened windows  the same application(e.g chrome)when i open two windows in the same  application e.g chrome but when I logout and login then show evertything good. It's happen when I turn on Ubuntu 24.04 but after I turn of and turn on the extension everything works

https://github.com/micheleg/dash-to-dock/assets/31028332/09e48701-0b9d-4d47-8130-b9794ab6e9e4

**Comment by vanvugt** [comment]
I can see [this Chrome bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7727) but don't understand if you're trying to describe any other issues.

**Comment by e-rakavest** [comment]
> I can see [this Chrome bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7727) but don't understand if you're trying to describe any other issues.

I mean that we don't see preview two windows on the dock but when I logout and login again then show evertything good
![Selection_374](https://github.com/micheleg/dash-to-dock/assets/31028332/4d6cdadf-51df-4743-8fce-b3410fe9a56f)
