### ISSUE TITLE
Please add Sergio Costas

### ISSUE THREAD

**Issue by vanvugt** [micheleg/dash-to-dock#2242]
@micheleg, please give @sergio-costas commit privileges to the project. He is a Canonical engineer and the one doing most of the work here lately.

**Comment by vanvugt** [comment]
FYI @3v1n0

**Comment by micheleg** [comment]
Done!

**Comment by vanvugt** [comment]
Thanks!

**Comment by sergio-costas** [comment]
Thanks!
