### ISSUE TITLE
shell doesn't recover when suspend is activated from overview

### ISSUE THREAD

**Issue by LostinSpacetime** [micheleg/dash-to-dock#2243]
A stated in the title, the Gnome Shell doesn't recover from suspend when the suspend state is activated from the overview screen. This only happens if the dash-to-dock extension is active.

I encountered this issue on a Fedora 40 with Gnome 46 wayland and xorg. I didn't have this issue with Gnome 45.

This can be a problem for people (like me) who have an OLED screen and hide the top panel to avoid burn-in.

**Comment by alex27riva** [comment]
Hi, I have the same issue when locking the screen on the "activities" view.

**Comment by vanvugt** [comment]
Duplicate of #2179.

The proposed fix is in gnome-shell itself: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3252
