### ISSUE TITLE
Icons now have a gray circle background

### ISSUE THREAD

**Issue by horga83** [micheleg/dash-to-dock#2249]
Icons now have a gray circle background with the latest update in Arch as of July 5th.
Would like to have previous behaviour of transparent background for icon.
Happens under both X11 and Wayland.

**Comment by vanvugt** [comment]
Can you attach a screenshot?

**Comment by horga83** [comment]
Sure here you go.  This happened after updates to Arch so not sure if it is dash-to-dock or not.
![Screenshot from 2024-07-08 08-44-15](https://github.com/micheleg/dash-to-dock/assets/2425304/e95d3b98-d6d7-4cd9-a566-8b395d03216d)

**Comment by vanvugt** [comment]
Looks like you have a custom shell theme installed(?)

**Comment by horga83** [comment]
No shell theme installed, it has been fine for a few years and just
with the last set of Arch updates a few days ago it changed.

I have an idea that someone reported this a year ago and there was a
solution just can't find it now
If I do I'll post here.

Cheers
George



On Mon, 2024-07-08 at 18:20 -0700, Daniel van Vugt wrote:
> Looks like you have a custom shell theme installed(?)
> —
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

[1] view it on GitHub
    https://github.com/micheleg/dash-to-dock/issues/2249#issuecomment-2216000550
[2] unsubscribe

**Comment by horga83** [comment]
Just out of curiosity I tried dash2dock and it does not exhibit the
same issue.  I don't really like dash2dock but see it was bashed off
dash-to-dock code.



On Mon, 2024-07-08 at 18:20 -0700, Daniel van Vugt wrote:
> Looks like you have a custom shell theme installed(?)
> —
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

[1] view it on GitHub
    https://github.com/micheleg/dash-to-dock/issues/2249#issuecomment-2216000550
[2] unsubscribe

**Comment by titeya** [comment]
Same for me. 
Gnome 47 on Arch with Blur my Shell extention and default Adwaita theme.

![Capture d’écran du 2024-09-20 16-48-49](https://github.com/user-attachments/assets/de366821-5bdb-4af9-b934-835983758dd1)

**Comment by horga83** [comment]
I found that my ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css was renamed to stylesheet.css.bak.  I renamed it back to stylesheet.css and everything is normal again.

**Comment by sergio-costas** [comment]
Should close this, then?
