### ISSUE TITLE
Trash icon can only be used once

### ISSUE THREAD

**Issue by SuGotLand** [micheleg/dash-to-dock#2256]
When clicking on the Trash icon, `trash:///` should open in the file manager. But it only works the first time.  When I close `trash:///`, on the second or subsequent click, nothing happens. nothing happens. How should I fix this error?
![截图 2024-07-27 19-12-55](https://github.com/user-attachments/assets/a3ab4ac1-bac5-42c0-951f-bc8e72f0b7da)
![截图 2024-07-27 19-20-43](https://github.com/user-attachments/assets/5de49d8e-e4b3-4f99-929f-524683e87ef1)

**Comment by sergio-costas** [comment]
I'm unable to reproduce this. Which version of dash-to-dock are you using? Can you launch in a terminal a log with

    sudo journalctl -f

and then try to open the trash several times and see if there is an error message in the terminal window that can help us to know what's happening?

Have you also tried to disable other extensions to see if it is some kind of interference?

**Comment by SuGotLand** [comment]
'''
7月 29 20:48:44 powerli-PC gjs[8246]: Finalizing GtkCheckButton 0x648a56e95cd0, but it still has children left:
                                          - GtkLabel 0x648a56f0a870
7月 29 20:48:44 powerli-PC gjs[8246]: Finalizing GtkCheckButton 0x648a56f29f10, but it still has children left:
                                          - GtkLabel 0x648a56f2b840
7月 29 20:48:44 powerli-PC nemo[8618]: Current gtk theme is not known to have nemo support (WhiteSur-Light) - checking...
7月 29 20:48:44 powerli-PC nemo[8618]: Theme parsing error: gtk.css:5524:16: not a number
7月 29 20:48:44 powerli-PC nemo.desktop[8618]: ImportError: could not import gobject (error was: ImportError("cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)"))
7月 29 20:48:44 powerli-PC nemo[8618]: pygobject initialization failed
7月 29 20:48:44 powerli-PC nemo[8618]: nemo_python_init_python failed
7月 29 20:48:44 powerli-PC nemo.desktop[8618]: Fontconfig error: "/home/powerli/.config/fontconfig/fonts.conf", line 15: junk after document element
7月 29 20:48:59 powerli-PC sudo[8855]:  powerli : TTY=pts/0 ; PWD=/home/powerli ; USER=root ; COMMAND=/usr/bin/journalctl -f
7月 29 20:48:59 powerli-PC sudo[8855]: pam_unix(sudo:session): session opened for user root(uid=0) by powerli(uid=1000)

'''

**Comment by sergio-costas** [comment]
Oh, ok... you are using Nemo instead of Files... And it seems that there are several errors in your fonts configuration, and the theme that you are using seems broken too...

Can you try to launch the trash using a different theme?

**Comment by 3v1n0** [comment]
I remember testing nemo once, but I'm unsure what's needed for it... It depends also how it handles the calls, since we definitely try to open it again through the trash uri

**Comment by SuGotLand** [comment]
> Oh, ok... you are using Nemo instead of Files... And it seems that there are several errors in your fonts configuration, and the theme that you are using seems broken too...
> 
> Can you try to launch the trash using a different theme?

Ok, it is unrelated to theme, I use the default theme, the trash icon can only be used once too.

**Comment by sergio-costas** [comment]
And what happens if you use nautilus instead of nemo?

**Comment by SuGotLand** [comment]
> And what happens if you use nautilus instead of nemo?

I try nautilus， the trash icon can only be used once too.
