### ISSUE TITLE
Dash to dock blinks when opening brave browser

### ISSUE THREAD

**Issue by Asunt70** [micheleg/dash-to-dock#2257]
hi guys im currently presenting this problem, where brave browser makes the dash to dock blink, and bug. 
i tried to change the icon's position, but it doesnt work.

below i attached a screen recorder, it shows how the browser blinks and bugs, but it didnt show how the dash to dock blinks sadly
[Screencast from 2024-08-01 12-49-57.webm](https://github.com/user-attachments/assets/f3bc1b03-e9d6-404b-b5a2-0b8e976694f7)

**Comment by vanvugt** [comment]
The two blinks in that video are correct:
1. Launch animation (admittedly missing some frames)
2. Tooltip briefly shown (I assume the mouse pointer passed over the icon)

Please try taking a video with a phone or camera and attach it here so we can see if there are any unexpected issues.

**Comment by Asunt70** [comment]
https://github.com/user-attachments/assets/f4b7bcda-c202-4949-825b-df9690ba3d7c

this only happens when it's the first browser's opening. when it's running in background everything's okay

**Comment by vanvugt** [comment]
Thanks. It looks like the main issue is that half the dock has vanished. If you have any other extensions like blur-my-shell enabled then please try disabling/removing those and retest.

**Comment by Asunt70** [comment]
it worked thanks!
