### ISSUE TITLE
v94 crashes gnome-shell when invoking lock screen.

### ISSUE THREAD

**Issue by bennyb0i** [micheleg/dash-to-dock#2270]
After updating to the latest v94, gnome-shell crashes when the lock-screen is invoked, either manually (i.e., Super+L) or by system timer (e.g., set by gnome-control-center). Journal is repeatedly flooded with the following errors:

```
Aug 25 10:49:08 gnome-shell[1932]: ../glib/gobject/gsignal.c:2685: instance '0x64a82ef43800' has no handler with id '36764'
Aug 25 10:49:08 gnome-shell[1932]: Object .Gjs_ui_appDisplay_FolderView (0x64a82ef43800), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
    #1   7ffd4de6f200 I   file:///home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:184 (3e4f5c39a6f0 @ 214)
    #2   7ffd4de6f230 I   file:///home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:101 (3e4f5c39a380 @ 15)
    #4   7ffd4de6f3e0 b   file:///home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:101 (3e4f5c39a330 @ 54)
    #5   7ffd4de6f490 b   file:///home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:56 (3e4f5c39a0b0 @ 15)
    #7   7ffd4de6f5b0 b   file:///home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js:55 (3e4f5c39a060 @ 44)
    #8   64a82cafb428 i   file:///home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconsDecorator.js:61 (3e4f5c3b6b00 @ 43)
    #9   64a82cafb3a8 i   file:///home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconsDecorator.js:78 (3e4f5c3b6c40 @ 11)
    #10   64a82cafb2e0 i   file:///home/user/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:781 (3f34a7083ce0 @ 995)
    #11   64a82cafb248 i   file:///home/user/.local/share/gnome-shell/extensions/vertical-workspaces@G-dH.github.com/lib/appDisplay.js:375 (3f34a7083330 @ 17)
```

OS: Arch Linux x86_64
Kernel: Linux 6.10.6-arch1-1
DE: GNOME 46.4
WM: Mutter (Wayland)
WM Theme: Adwaita

Confirm the issue only arises when dash-to-dock extension is enabled. Tested by disabling all extensions, logging out then in again, and invoking lock-screen without issue.

Tested with only gnome-shell active, logging out then in again, and invoking lock-screen, gnome-shell crashes to login. Can be replicated by doing the same again.

**Comment by vanvugt** [comment]
Those log messages are not related to shell crashes. Perhaps you mean #2179?

**Comment by TheRealWolfick** [comment]
I am having the same thing. When my computer went to sleep (goes to the lock screen) gnome-shell completely crashed. Before the crash, my log is filled with the below screenshot.

![Screenshot from 2024-08-26 21-44-47](https://github.com/user-attachments/assets/fa3a365e-ef29-4e85-96bf-f31e1641f10f)

**Comment by sergio-costas** [comment]
@3v1n0 Here! Look at the upper capture: aztaskbar is calling something in dash-to-dock...

**Comment by 3v1n0** [comment]
It should be fixed by https://github.com/micheleg/dash-to-dock/pull/2273
