### ISSUE TITLE
memory leak... once again

### ISSUE THREAD

**Issue by Nekothegamer** [micheleg/dash-to-dock#2272]
I don't know why, but as of a few days at this point the extension started leaking on my system, making the shell go from it's usual ~100 MB to over 5 GB, which slows down the entirety of the shell down to a crawl. Again, i have no idea how it started, what i remember before it started leaking is that i was messing with the [GKT4 port of Desktop Icons NG](https://extensions.gnome.org/extension/5263/gtk4-desktop-icons-ng-ding/) and out of nowhere the whole gnome shell interface started to get really slow, and i only discovered today that it reached 6 GB in memory, and only a few minutes ago i found out it was dash to dock's fault, and now I'm here. 

if you want any info there it is:
OS: Fedora 40
Gnome version: 46.4
Extension version: the most recent one, v94
RAM: 16 GB
Display server/protocol: Wayland

UPDATE: this seems to be a bug within v94, since when downgrading to v93 the leak doesn't happen

**Comment by 3v1n0** [comment]
Please, check https://github.com/micheleg/dash-to-dock/pull/2273 it should fix it

**Comment by Nekothegamer** [comment]
yeah but it still needs to be merged...

**Comment by Nekothegamer** [comment]
Yes!, thank you!
