### ISSUE TITLE
if 32px Icon Size only 6 colums app grid 

### ISSUE THREAD

**Issue by pelach** [micheleg/dash-to-dock#2280]
If I set the icon size to 32px at Dash-to-do, there will only be 6 columns for the App Grib.
The icon size is also set to 32px on a laptop and still has 8 columns. Just like Gnome originally.
Where can you set up how many columns should be in the app grid?
Did others have this error? As if he did not recognize the resolution of the monitor. (only tip)
see screenshots:

Desktop 2560x1440:
![Desktop_1](https://github.com/user-attachments/assets/446bdb59-7bd9-4e09-8507-ee86ab3854de)
![Desktop_2](https://github.com/user-attachments/assets/f6b34860-74c3-4839-a44e-df152e51ba55)

Laptop  1920x1080:
![Laptop_1](https://github.com/user-attachments/assets/d2115095-8823-4c4c-817a-56df2f3d0402)
![Laptop_2](https://github.com/user-attachments/assets/07df3a30-a982-4ab1-98f2-32671b574b17)

**Comment by vanvugt** [comment]
That's a problem with gnome-shell, which you can [report upstream](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues). It's probably related to the vertical space allowed by the dock height, and the limited set of dimensions that gnome-shell is willing to use for the app grid. But really it's got little to do with dash-to-dock so I'm closing this.

They have rewritten part of this logic in GNOME 47 so maybe you won't have the issue anymore in 47.
