### ISSUE TITLE
Dash not showing when applying pressure

### ISSUE THREAD

**Issue by mambucodev** [micheleg/dash-to-dock#2288]
I updated today to gnome 47, and sometimes the dash doesn't come up when it's hidden. I've got intelli auto-hide activated when a focus windows is places on the dash area. I don´t know why but if I reload the extension or I disable and re-enable the intelli auto-hide option, it starts working again but then, after a while, it stops.

I'm on Arch Linux 6.10.10-arch1-1 with Gnome 47

Recording:
[Screencast From 2024-09-19 13-58-04.webm](https://github.com/user-attachments/assets/b6b04083-f8e0-4972-a5c6-47d0bce4a429)
PS: sorry but gnome recording doesn't show the mouse pointer, but I'm moving it up and down to the bottom of the screen to eventually show the dock. Also, the pressure in intelli auto-hide is set to `0`.

**Comment by Neo-29** [comment]
confirmed here on archlinux too
Must tweak the settings to make the dock appear, then first reboot.... it doesn't work anymore

**Comment by mrpeabody** [comment]
Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.

**Comment by Neo-29** [comment]
> Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.

Even after reboot the computer?

**Comment by mrpeabody** [comment]
> > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> 
> Even after reboot the computer?

Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.

**Comment by Neo-29** [comment]
> > > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> > 
> > 
> > Even after reboot the computer?
> 
> Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.

Workaround confirmed working 👍

**Comment by mambucodev** [comment]
> > > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> > 
> > 
> > Even after reboot the computer?
> 
> Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.

How do I reset /org/gnome/shell/extensions/dash-to-dock ? Should I just delete it?

**Comment by Neo-29** [comment]
> > > > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> > > 
> > > 
> > > Even after reboot the computer?
> > 
> > 
> > Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.
> 
> How do I reset /org/gnome/shell/extensions/dash-to-dock ? Should I just delete it?

Use ```dconf-editor```

**Comment by mrpeabody** [comment]
> > > > > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> > > > 
> > > > 
> > > > Even after reboot the computer?
> > > 
> > > 
> > > Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.
> > 
> > 
> > Workaround confirmed working 👍
> 
> Broken again.... Suddenly...

To me, fiddling with theme settings gets it broken again, so I don't touch them until it's fixed.

**Comment by mrpeabody** [comment]
> > > > > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> > > > 
> > > > 
> > > > Even after reboot the computer?
> > > 
> > > 
> > > Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.
> > 
> > 
> > How do I reset /org/gnome/shell/extensions/dash-to-dock ? Should I just delete it?
> 
> Use `dconf-editor`

or `gsettings reset-recursively org.gnome.shell.extensions.dash-to-dock`

**Comment by mambucodev** [comment]
> > > > > > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> > > > > 
> > > > > 
> > > > > Even after reboot the computer?
> > > > 
> > > > 
> > > > Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.
> > > 
> > > 
> > > How do I reset /org/gnome/shell/extensions/dash-to-dock ? Should I just delete it?
> > 
> > 
> > Use `dconf-editor`
> 
> or `gsettings reset-recursively org.gnome.shell.extensions.dash-to-dock`

I don't have this schema. I also tried running `gsettings list-schemas | grep 'dock'` but no result came out.

**Comment by mrpeabody** [comment]
> > > > > > > Full reset of dash-to-dock section in dconf fixes the problem, but yes, lots of issues, for example, dots/dashes no longer work in custom themes.
> > > > > > 
> > > > > > 
> > > > > > Even after reboot the computer?
> > > > > 
> > > > > 
> > > > > Correct! Reset /org/gnome/shell/extensions/dash-to-dock reboot, set it up and it works just fine.
> > > > 
> > > > 
> > > > How do I reset /org/gnome/shell/extensions/dash-to-dock ? Should I just delete it?
> > > 
> > > 
> > > Use `dconf-editor`
> > 
> > 
> > or `gsettings reset-recursively org.gnome.shell.extensions.dash-to-dock`
> 
> I don't have this schema. I also tried running `gsettings list-schemas | grep 'dock'` but no result came out.

![image](https://github.com/user-attachments/assets/03a4c1d4-3f61-4a15-9f9a-73cf086d9d29)

**Comment by Calosis** [comment]
Use latest git to fix the issue, or do not apply a custom color to the dock. Applying a custom color breaks the dock in 47, unless you use latest git.

**Comment by mrpeabody** [comment]
> Use latest git to fix the issue, or do not apply a custom color to the dock. Applying a custom color breaks the dock in 47, unless you use latest git.

dominant colors are still broken, even in the latest git version

**Comment by Mistakesos** [comment]
> > Use latest git to fix the issue, or do not apply a custom color to the dock. Applying a custom color breaks the dock in 47, unless you use latest git.
> 
> dominant colors are still broken, even in the latest git version

Yes,you're right. In my testing, only maximization (not full screen) was affected, and even when placed on the dock with a regular window, it can still be automatically hidden.

Turn off custom dock colors, logout, and login to restore auto hide to normal.
But there is a problem with the indicator, what I mean is the small dot under the icon. If it is default, it will be displayed on the icon, but if it is customized, it will completely disappear.

**Comment by Milli189** [comment]
> Use latest git to fix the issue, or do not apply a custom color to the dock. Applying a custom color breaks the dock in 47, unless you use latest git.

using the latest git was the solution for me

**Comment by mambucodev** [comment]
I should try disabling the dominant color once I come back home, I'll let you guys know in 2 days

**Comment by Mistakesos** [comment]
🎉🎉🎉Indicator and dock custom color issue is fixed. As far as I knew, the latest git version fixed pressure issue too. Try to update it or waiting for release. Remember to close this issue, thank you for reading, and have a nice day! 😄

**Comment by mambucodev** [comment]
> 🎉🎉🎉Indicator and dock custom color issue is fixed. As far as I knew, the latest git version fixed pressure issue too. Try to update it or waiting for release. Remember to close this issue, thank you for reading, and have a nice day! 😄

Thanks! I'll test in once I get home and close the issue once I assure my dock works correctly! 🥳
