### ISSUE TITLE
Dock glitches and applications disappear or duplicate.

### ISSUE THREAD

**Issue by ac2522** [micheleg/dash-to-dock#2290]
### Gnome-shell 42, Ubuntu 22.04.5

A couple issues :
After a couple minutes use, all applications disappear from dock:
![image](https://github.com/user-attachments/assets/04d4909b-1061-4f9c-8fd3-bcefd04565dd)
Using Super-A, then causes gnome to get stuck on application page, no way to escape.

Before that if you run super or super-A it displays 2 docks: 
![image](https://github.com/user-attachments/assets/c26f41cb-28c6-42c7-99c8-bd7435b7e5f8)

**Comment by vanvugt** [comment]
Do you have two docks enabled?
```
gnome-extensions list --enabled
```

**Comment by 0xGoenka** [comment]
anon@anon-linux:~$ gnome-extensions list --enabled
dash-to-dock@micxgx.gmail.com
ding@rastersoft.com
tiling-assistant@ubuntu.com
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com

Got same problem on ubuntu 24.04 fresh install

Not the duplicate one, but no more icon after a suspend then computer freeze

**Comment by vanvugt** [comment]
You need to disable one of:
* dash-to-dock@micxgx.gmail.com
* ubuntu-dock@ubuntu.com

Because they are from the same codebase and will conflict with each other.
