### ISSUE TITLE
dash-to-dock crashes gnome-shell on suspen\lock

### ISSUE THREAD

**Issue by OniiCookie** [micheleg/dash-to-dock#2297]
Issue: Everytime i lock my machine or put into suspend mode, dash-to-dock crashes gnome-shell.

gnome-shell[849]: JS ERROR: TypeError: dockManager is null
                                                getApps@file:///home/usersname/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1489:9
                                                getRunningApps@file:///home/usersname/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1502:12
                                                get@file:///home/usersname/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1890:59
                                                _syncRunningApplications@resource:///org/gnome/shell/misc/introspect.js:80:26
                                                IntrospectService/<@resource:///org/gnome/shell/misc/introspect.js:37:18
                                                @resource:///org/gnome/shell/ui/init.js:21:20
                                                
Gnome Version: 47

**Comment by Neo-29** [comment]
which disto?

**Comment by OniiCookie** [comment]
I'm running CachyOS, can confirm with extension disabled gnome-shell doesn't crash when system is locked or goes into suspend mode.

**Comment by vanvugt** [comment]
It looks like one of the issues relating to #1992. Please check that you don't have multiple "dock" extensions enabled:
```
gnome-extensions list --enabled
```

**Comment by OniiCookie** [comment]
I've disabled all the other extensions and will monitor and see how it goes!

**Comment by OniiCookie** [comment]
Looks like the same issue occurs, I've been having a look at other issues related and found this topic 'https://github.com/micheleg/dash-to-dock/issues/820', I believe it may be related, not sure if related but did another dump today before changing any settings as per issue#820.

Log:
Sep 27 14:24:36 cachyos-x8664 gnome-shell[2584]: JS ERROR: TypeError: dockManager is null
                                                 getApps@file:///home/username/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1489:9
                                                 getRunningApps@file:///home/username/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locations.js:1502:12
                                                 get@file:///home/username/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1890:59
                                                 _syncRunningApplications@resource:///org/gnome/shell/misc/introspect.js:80:26
                                                 IntrospectService/<@resource:///org/gnome/shell/misc/introspect.js:37:18
                                                 @resource:///org/gnome/shell/ui/init.js:21:20
Sep 27 14:24:36 cachyos-x8664 gnome-shell[2584]: **
Sep 27 14:24:36 cachyos-x8664 gnome-shell[2584]: libmutter:ERROR:../mutter/src/core/window.c:5799:meta_window_get_work_area_for_logical_monitor: assertion failed: (logical_monitor)
Sep 27 14:24:36 cachyos-x8664 gnome-shell[2584]: Bail out! libmutter:ERROR:../mutter/src/core/window.c:5799:meta_window_get_work_area_for_logical_monitor: assertion failed: (logical_monitor)
Sep 27 14:24:36 cachyos-x8664 gnome-shell[2584]: == Stack trace for context 0x5a9893c28ea0 ==
Sep 27 14:24:36 cachyos-x8664 gnome-shell[2584]: #0   5a9893d1cb68 i   resource:///org/gnome/shell/ui/init.js:21 (334bc4970c90 @ 48)
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Running GNOME Shell (using mutter 47.0) as a Wayland display server
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Device '/dev/dri/card0' prefers shadow buffer
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Added device '/dev/dri/card0' (amdgpu) using atomic mode setting.
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Created gbm renderer for '/dev/dri/card0'
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Boot VGA GPU /dev/dri/card0 selected as primary
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Obtained a high priority EGL context
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Using public X11 display :1024, (using :1025 for managed services)
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Using Wayland display name 'wayland-0'
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Sep 27 14:24:39 cachyos-x8664 gnome-shell[9739]: Will monitor session 6

seems to be the same error before it crashes gnome-shell. Any thoughts?

**Comment by OniiCookie** [comment]
For anyone that reads this, workaround:

- Lock machine using "CTRL+ALT+F1".
- No issues found even after system goes into suspend mode.

**Comment by Neo-29** [comment]
My workaround is I have up on the extension.
Too many issues along the way...
I'm fed up.

**Comment by vanvugt** [comment]
@OniiCookie,

"CTRL+ALT+F1" doesn't lock the machine. It just switches from the desktop to the login screen. You can go the other way with "Ctrl+Alt+F2" so the screen was never locked (unless you left it that way for so long that it locked in the background).

Please run this command to identify the possible causes of the log message:
```
grep -lr dockManager /usr/share/gnome-shell/extensions/ ~/.local/share/gnome-shell/extensions/
```
