### ISSUE TITLE
Support for AppIndicators / System Tray Vanished!?

### ISSUE THREAD

**Issue by fraber** [micheleg/dash-to-dock#2302]
Hi, I was successfully running dash-to-dock in Ubuntu 18.04 for years. I just did a fresh install of Ubuntu 24.04.01, installed dash-to-dock, and now the AppIndicators stay at the top and occupy a lot of space rather rather than appearing in some corner.

Is there any way to bring this feature back? I've spent several hours looking through the forums...

**Comment by 3v1n0** [comment]
Mh, this was never supported by this extension, sorry.
