### ISSUE TITLE
Opened apps indicator position

### ISSUE THREAD

**Issue by d47081** [micheleg/dash-to-dock#2317]
Hello, 

just updated to Fedora 41 (after Debian 12) and found that indicators for opened apps now placed on app icon:

![image](https://github.com/user-attachments/assets/0a51e1c7-f0bc-4437-9407-bb11fbf0b26b)

this white circle was under app icon before and now I can't see if the app is opened - is this okay or bug?

**Comment by sergio-costas** [comment]
It was fixed early this week in `main`. You have to wait until a new release is uploaded to the extensions page.

**Comment by sergio-costas** [comment]
I'm afraid the patch isn't in that version. V99 was created October 3, while the patch was merged October 8. It is still only in `master`.
