### ISSUE TITLE
Moving mouse to bottom of screen doesn't always open the dock

### ISSUE THREAD

**Issue by brianjmurrell** [micheleg/dash-to-dock#2320]
I find the reliability of opening the dock when it's auto-hiding to be really bad.  Most of the time simply moving the mouse to the bottom of the screen the dock does not open.  I usually have to move the mouse back up a small way and then back down to get it to finally open.

I'm using dash-to-dock version 96 on gnome-shell 46.5.  But to be clear, this is not new in this version.  This has been happening for a long time.  I've only just started getting frustrated enough with it lately to finally file an issue.

**Comment by vanvugt** [comment]
I think this can be grouped with either #2288 or #2303 (or other similar bugs).

**Comment by sergio-costas** [comment]
Maybe you have enabled the "Push to show: requires doing pressure to show the dock" option inside the "Intellihide" option? I have it disabled and showing the dock works like a charm...

**Comment by brianjmurrell** [comment]
> I think this can be grouped with either #2288 or #2303 (or other similar bugs).

Reading through both of those issues, I don't read anything that seems to be even close to what I am seeing.  I tend to doubt this is related to either of those issues.

> Maybe you have enabled the "Push to show: requires doing pressure to show the dock" option inside the "Intellihide" option? I have it disabled and showing the dock works like a charm...

I seem to have made it even worse.  I tried to just disable Intellihide and I was no longer able to get the dash to open with any activity at the bottom of the screen.  I then re-enabled Intellihide and still nothing would make the dash appear.  I even restarted gnome-shell and still no amount of activity at the bottom of the screen shows the dock any more.

So now the only way I can see the dock is by activating the shell overview mode, which frankly completely invalidates the entire point of using the dock.

**Comment by vanvugt** [comment]
If the title "Dash not showing when applying pressure" of #2288 is right then this should either be discussed there or someone would need to explain how it's different.
