### ISSUE TITLE
App Grid change ratio colums/rows  if dock is on left side

### ISSUE THREAD

**Issue by melomane63** [micheleg/dash-to-dock#2326]
Fedora 41 gnome 47 dash to dock 99 , resolution 1980x1080

if dock is on left ( or right) side , app grid change  from 8 columns and 3 rows to  6 columns and 4 rows, which destroys the aesthetic. use dash to panel on left side to mimics dash to dock, no problem.

work with screen resolution from 1368x768 and lower.

with ubuntu yaru theme on fedora or ubuntu 24.04 , work with  1600x900 and lower.

[Kooha-2024-11-05-11-46-32.webm](https://github.com/user-attachments/assets/7a495cff-5b7f-4079-a30c-529c4a52c1e5)

**Comment by melomane63** [comment]
ok, work with screen resolution from 1368x768 and lower. 

with ubuntu yaru theme, not work with 1980x1080, but yes with 1600x900 and lower.

**Comment by vanvugt** [comment]
It's due to the narrowing of the aspect ratio available to the icon grid, which is being tracked in ~~https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5791~~ https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2713 and https://bugs.launchpad.net/bugs/1987734
