### ISSUE TITLE
Dash to Dock is causing gnome-shell to crash on GNOME-47 

### ISSUE THREAD

**Issue by mrme8895** [micheleg/dash-to-dock#2340]
I've recently made the switch to Fedora and added the Dash to Dock GNOME extension but I've run into a bit of a fickle: whenever I try to lock my screen using the Super+L shortcut while in Overview mode, GNOME Shell unexpectedly quits.

This only seems to happen with the extension enabled and in Overview mode. Locking from the desktop works fine.

Has anyone else encountered this issue or have any suggestions on how to fix it?

**Comment by sergio-costas** [comment]
Duplicated https://github.com/micheleg/dash-to-dock/issues/2338
