### ISSUE TITLE
Option to move "Show Application" to the Left/Top

### ISSUE THREAD

**Issue by slacka** [micheleg/dash-to-dock#238]
I'm used to finding the launcher on the left of horizontal panels and top of vertical panels. Could you make the  "Show Application" button movable or give us an option to swap it's location?

**Comment by micheleg** [comment]
Hi, which Gnome version are you running? This option is already available but you need at least Gnome Shell 3.12.

![screenshot from 2015-10-15 10 55 55](https://cloud.githubusercontent.com/assets/1717310/10510504/642c0300-732b-11e5-9bd2-f081879e21f8.png)

**Comment by slacka** [comment]
My bad. Please close this issue. 

Thanks for creating and sharing such a useful extension.
