### ISSUE TITLE
doubled icons for certain apps

### ISSUE THREAD

**Issue by ItamarShDev** [micheleg/dash-to-dock#239]
When opening some  apps  from the dock (Popcorn time for example) 
the apps dock icon appears while a new app (original) icon added to the dock, creating a situation that the dock has two app icons
![Uploading Screenshot from 2015-10-15 16-11-11.png…](as seen here)

**Comment by algamer31** [comment]
Possible duplicate of #215

**Comment by micheleg** [comment]
Closing as duplicate.
