### ISSUE TITLE
Dock is visible on lock screen [3.8 backport]

### ISSUE THREAD

**Issue by iainhallam** [micheleg/dash-to-dock#242]
Happily using the 3.8-experimental branch, but I just noticed that the dock is now visible on both the lock screen and screen shield of CentOS 7. It's active, so I can launch things with it, and when I unlock they're running!

**Comment by micheleg** [comment]
That's means there's a bug which prevent it from properly loading/unloading it. There must be some errors. Anything in the logs? The error should appear also enabling/disabling the extension from gnome-tweak-tool.

**Comment by micheleg** [comment]
Updated again the experimental branch.

**Comment by iainhallam** [comment]
I've moved to the new version, and haven't seen this behaviour today. Hopefully that's squished it.
