### ISSUE TITLE
Autohide fails on Multiple Monitors.

### ISSUE THREAD

**Issue by cswartzvi** [micheleg/dash-to-dock#244]
First off I absolutely love this extension. Fantastic work!

I am having a little issue using dual monitors with gnome 3.16.4 (Fedora 22), specifically when using the default `Move window one monitor left/right/up/down` keyboard shortcut `Super+Shift+ArrowKey`. 

As you can see below, when I use the shortcut to move **from** the right monitor **to** the left monitor autohide fails to detect the window overlap until I alter the window size via the mouse (you can also use the restore, minimize, or split shortcuts). Furthermore, you can also see that when I move the window back **to** the right monitor autohide fails in a similar fashion. 

![dashtodock_issue01](https://cloud.githubusercontent.com/assets/1111348/10808320/5d8488b6-7dc0-11e5-81e2-9ea7bbcd12cf.gif)

It looks like the extension is failing to catch the `Move window one monitor left/right/up/down` command. Any ideas on a fix or workaround (besides not using the shortcut in the first place :smile: )?

Note: I have the *Only consider windows of the focused application* option disabled.

Thanks

**Comment by micheleg** [comment]
Yes, I can reproduce the bug. I'll have to investigate which event is triggered in this circumstance. This bug might be related to these  #27 #134  as well.

**Comment by micheleg** [comment]
I believe the bug should be solve in the branch ```keybinding_bug```. Could you check?

**Comment by cswartzvi** [comment]
Wow, thanks for the quick turnaround! The fix works great!

**Comment by micheleg** [comment]
Fix merged into master [7e41e23b] and backported to 3.16 [f0853dcd1d] and 3.14 [d5f2d9d90a].
