### ISSUE TITLE
Does not refresh icons list on new app opened or running apps closed

### ISSUE THREAD

**Issue by iJackUA** [micheleg/dash-to-dock#245]
When new app is opened it does not appear on dock
or when some app is closed it stays on dock (while not added to favorites)

When I go to extension settings and toggle for example "Shrink the dash" or other option that cause Dock repaint - it refreshes correctly (app appear or disappear as expected).

Dock v49
Gnome 3.18
Ubuntu Gnome 15.10
2 monitors

```
show-apps-at-top=false
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
show-show-apps-button=false
custom-theme-running-dots=true
custom-theme-shrink=true
background-opacity=0.84999999999999998
opaque-background=false
dash-max-icon-size=48

```

**Comment by micheleg** [comment]
Thanks for your bug report. Does it happen for all applications? Did you try disabling other extensions?

**Comment by iJackUA** [comment]
Weird. I can't reproduce it now. 
I have turned off all extensions and then enabled them one-by-one - but it was working on every step, and works now after reboots etc.

Sorry, seems to be false alarm (but weird as it was repeating described bug behavior before that, after system reloads etc., maybe turning Dash to Dock extension OFF/ON made the trick ).

**Comment by micheleg** [comment]
Good. Let me know if the problem reappears.
