### ISSUE TITLE
Chrome OS and Windows 7 like system tray integration

### ISSUE THREAD

**Issue by fastrizwaan** [micheleg/dash-to-dock#247]
Hi,
Could you please consider allowing 'system tray' and usermenu/system-menu (top right) into dash to dock? This will make it possible to have chromeOS and windows7 like user interface possible with gnome-shell, which will help a lot of legacy windows users to migrate to Linux. Thanks.

![chromeos-status-bar](https://cloud.githubusercontent.com/assets/1161682/10935061/7b84ad98-8309-11e5-9af7-4e5c859b6451.jpg)

![chromebook-screenshot-1](https://cloud.githubusercontent.com/assets/1161682/10935114/df49f662-8309-11e5-8b16-c9b823e6f54b.png)

**Comment by micheleg** [comment]
Hi,

this is not something highly prioritized in my todo list at the moment. It depends on the implementation of additional widgets to add to the dock which was considered in the past but never finalised (see also #163). However, If that gets implemented then this sort of customization would be easier to include.
I'm wondering if dash-to-dock is the right place for this of if it rather deserves its own extension.

**Comment by micheleg** [comment]
This extensions kind of does what you are asking for:
https://extensions.gnome.org/extension/898/mmod-panel/

**Comment by Lesik** [comment]
If anybody else is stumbling upon this, you should try [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/).

I don't think Dash to Dock should have this functionality, as its purpose is to be a panel, not a dock. I think this issue can be closed.

**Comment by Lesik** [comment]
If anybody else is stumbling upon this, you should try [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/).

I don't think Dash to Dock should have this functionality, as its purpose is to be a dock, not a panel. I think this issue can be closed.

**Comment by micheleg** [comment]
Agreed. If you want this you probably want Dash to Panel.

**Comment by fastrizwaan** [comment]
Yes, using dash to panel.

**Comment by Garethp** [comment]
Just commenting. While Dash To Panel looks like what I want, it doesn't have (or appear to be implementing any time soon) multi-monitor support like Dash to Dock has
