### ISSUE TITLE
it has been a while since the last release

### ISSUE THREAD

**Issue by user501254** [micheleg/dash-to-dock#251]
Recently some new features like custom running indicator were added which haven't seen an official release either on Github or GNOME Extensions website but are merged into the master branch.

**Comment by micheleg** [comment]
Hi, I didn't have time to prepare a release, and there were a couple of known issues I wanted to solve first, as well as other features almost mature but which I'm still not confident to release.

One reason is that I'm not running the latest gnome-shell version so I can't easily test it. If you are running current master can you confirm everything is working properly and there are no regressions?

**Comment by user501254** [comment]
I wasn't using the master branch but since you asked for it, I installed it for testing.
Here's what I found:

1. Switch workspaces by scrolling on the dock works only when scrolling over the "Show Applications" menu button and not for the full length of the dock.
2. Under appearance tab when using the built-in theme, running window indicators are invisible.

**Comment by micheleg** [comment]
Thanks for testing.

1. I think this is the wanted behaviour, for now (See #249 )
2. I'm not sure I have understood. Are you say that you can't see the indicators or that you can't see some options in the settings window?

**Comment by user501254** [comment]
I can't see the indicator dots.

**Comment by micheleg** [comment]
Are you using a custom theme?

**Comment by user501254** [comment]
Indicators are visible only on setting the custom colors and not in the built in theme.
(See Screenshots)

![screenshot from 2015-11-22 01-31-28](https://cloud.githubusercontent.com/assets/6129517/11320257/de8ec6c8-90b8-11e5-81a2-c7c5d3d044ca.png)
![screenshot from 2015-11-22 01-31-48](https://cloud.githubusercontent.com/assets/6129517/11320259/e2df6e44-90b8-11e5-9d1a-0ae89453247e.png)

**Comment by micheleg** [comment]
Is this a regression? Were the dots visible with the previous version? Also, are the dots visible with the default theme? Also which theme is that?

**Comment by user501254** [comment]
To answer your questions.
- probably, not entirely sure.
- Yes
- Yes (dots are visible when using the default shell theme)
- The theme in screenshot is the non transparent version of the [Arc theme](https://github.com/horst3180/Arc-theme#packages)

The (Arc) theme itself hasn't been updated since I started using the master branch. However, I will try with another 3rd party theme to see if the problem exists. Will let you know soon.

**Comment by user501254** [comment]
Tried with another 3rd party theme called Paper. The problem does not exists there.

**Comment by user501254** [comment]
@micheleg I have been using the master branch on Gnome 3.18 for quite some time now. Except for https://github.com/micheleg/dash-to-dock/issues/262, I did not face any problems what so ever. It is safe to do a new release.

On a side note, the issue in [this](https://github.com/micheleg/dash-to-dock/issues/251#issuecomment-158677963) comment was theme specific and that too got fixed after a recent update.

**Comment by micheleg** [comment]
Thanks a lot for testing the development version and reporting no issues. I will try to prepare a new release before the end of the year. I was planning to merge few others features/improvements still not merged into master ( e.g. #99, #255,  [#261](https://github.com/micheleg/dash-to-dock/issues/261#issuecomment-160924962)), but I will probably keep those for the next update.
