### ISSUE TITLE
Dock conflicts with Onboard keyboard

### ISSUE THREAD

**Issue by IoanaCiornei** [micheleg/dash-to-dock#252]
Running GNOME 3.18 on Arch Linux. Onboard is also docked to the bottom of the screen.
![screenshot from 2015-11-21 16-52-17](https://cloud.githubusercontent.com/assets/6203603/11318985/a8ff4d9c-905f-11e5-96a8-8290009efa07.png)

**Comment by micheleg** [comment]
Hi, I can reproduce the bug. I have no experience with on screen keyboards: what would be the expected behaviour? Should the dock be hidden (considering the keyboard as any other normal window), should the dock be shifted up and positioned on top of the keyboard?

**Comment by IoanaCiornei** [comment]
I think the dock should be hidden when using on screen keyboards.

**Comment by micheleg** [comment]
There is a branch ```onboard_bug``` with a tentative solution. It's still not perfect - it works only when intellihide is set to consider all windows -  and it will require further work. Could you test if it works reliably for you?

**Comment by micheleg** [comment]
The bug should be fixed now in master [23d846366], as well as in the gnome-3.14 [7ca6cc555] and gnome 3.16 [acbce16ab6] branches.
