### ISSUE TITLE
Shift+Click action properties visual problem

### ISSUE THREAD

**Issue by bosyi** [micheleg/dash-to-dock#256]
Shift+Click action after extension clean install for real is set to Minimize window, but in preferences is shown as Do nothing.

**Comment by micheleg** [comment]
Thanks for spotting the bug. It should be solved now in master (ebf8d4bd3f3b9072d72a264ec3975cd26b067a38). The fix is backported to 3.14 (a01141c9be81abe2536855df05850aad85387b6e) and 3.16 (2e1a4423de114c9465382a7ef470af31719c59a1).

**Comment by bosyi** [comment]
Thanks for fast fix!
