### ISSUE TITLE
[Feature Request]: Custom actions in Favorites

### ISSUE THREAD

**Issue by sdie** [micheleg/dash-to-dock#257]
Hi,
Could you please consider a way to configure the behaviour of favourites in the dock?
Right now favourites are only executed with default behaviour. A right-klick solution, to specify the start-up parameters, would be great.

An example is the terminal emulator [terminator] (https://launchpad.net/terminator), which allows to be started with optional parameters.

Right now I cannot see a way for configure the favorite icon with something like
`terminator -f --layout=foo`.

Cheers

**Comment by micheleg** [comment]
Hi,

This would require ad-hoc configurations for each possible apps, or an interface to let the user configure it, which I'd rather not implement. However, actions are already available for specific apps which define them. One example is Gedit ("Open a New Windows, "Open a New Document"). The way it works it though the .desktop file:

This is the relevant snippet from /usr/share/applications/org.gnome.gedit.desktop (this file might be somewhere else on your system)

```
[Desktop Action Window]
Name=Open a New Window
Exec=gedit --new-window
```
These should be the specifications: http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions

I think you can add you rpreferred custom actions by customizing the relevant .desktop files. Let me know if you need further help,

Michele
