### ISSUE TITLE
[Feature request] Support for gsettings

### ISSUE THREAD

**Issue by LouisDK1** [micheleg/dash-to-dock#258]
When I open gconf-editor I'm able to navigate to org > gnome > shell > extensions > dash-to-dock and set options like "dock-fixed". 

However it doesn't seems like I'm able to set these settings through gsettings.

Would you be interested in implementing that? :)

**Comment by micheleg** [comment]
Hi, could you explain hwo you would expect to be able to set these settings through gsettings?

**Comment by LouisDK1** [comment]
Typically you can use gsettings to get and set settings like:
gsettings get org.gnome.desktop.interface clock-show-seconds 
gsettings set org.gnome.desktop.interface clock-show-seconds true
gsettings set org.gnome.desktop.interface clock-show-seconds false

I use this to enable or disable a setting, by making a little bash script which is executed upon pressing a custom shortcut.
I could also just open dconf-editor and navigate to "org > gnome > desktop > interface" and change it manually, but I find the script quite faster to use once it has been setup.

**Comment by micheleg** [comment]
I think it depends on the locations gsettings lookf for the schemas. When extensions are installed in the user home, the schema is typically in ```~/.local/share/gnome-shell/extensions/extension-name/schemas/```. You need to force gsettings to look for it for instance with the GSETTINGS_SCHEMA_DIR environment variable.  For example:

```GSETTINGS_SCHEMA_DIR=~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/ gsettings cmd [...]```

will find the dash to dock schema too. I think it is a limitation of the current extension system, unless the extension is installed system-wide, as the upstream extensions do. I don't support such installation method yet.

I think dconf  directly reads the database and find the keys that have already been modified without needing the schema file to check consistency etc..

One note: you can use dconf from command line too, e.g.
```dconf list /org/gnome/shell/extensions/dash-to-dock/```

**Comment by LouisDK1** [comment]
Thank you for the info. I'm closing this issue.
