### ISSUE TITLE
Disabling "fixed-dock" doesn't hide dock in fullscreen instantly

### ISSUE THREAD

**Issue by LouisDK1** [micheleg/dash-to-dock#259]
Hi,

I've configured a shortcut to hide the dock when I press it.

However the dock is still shown when pressing this shortcut and have apps on my monitor in full screen. I have to change focus before it'll minimize.

Would you be able to make it hide instantly?

Whatever "intelligent hide" is enabled or not makes no difference.

The command my script is executing is this one: <b>dconf write /org/gnome/shell/extensions/dash-to-dock/dock-fixed false</b>

**Comment by micheleg** [comment]
Hi,
I'm not sure I have understood. The dock should always hide by itself when there are fullscreen apps, regardless of any settings. If not, there might be a bug. By toggling the dock-fixed key you are enableing/disabling autohide (For historical reasons the settings keys don't match any more the settings UI). Can you elaborate further?

**Comment by LouisDK1** [comment]
I've uploaded this video to show you what I mean: https://www.youtube.com/watch?v=GgCYB8enFLs

When disabling "dock-fixed" I need to change focus for the changes to take effect as it'll not hide instantly.

**Comment by micheleg** [comment]
Hi,
now I understand. I think this bug was incidentally fixed by 58164378d. Could you check current master? In any case I'll have to double check what's happen on the setting change,

**Comment by LouisDK1** [comment]
Seems to have been fixed in master.
Looking forward to a new stable release :)

**Comment by micheleg** [comment]
Keeping the bug open because I don't want to forget to check this further.
