### ISSUE TITLE
Add possibility to close only one current window if several windows of one app is opened by right click on icon in dock.

### ISSUE THREAD

**Issue by bosyi** [micheleg/dash-to-dock#261]
For now we have option to 'close X windows'.

**Comment by micheleg** [comment]
Hi,

there is a wip branch (https://github.com/micheleg/dash-to-dock/tree/windows_thumbnails)  including windows previews  in the menu, which also allows to close each specific window with a close button as in the overview

![windows_preview](https://cloud.githubusercontent.com/assets/1717310/11497922/0a7fbfa0-9814-11e5-874e-b1e2aea7c8ac.png)

In principle a closing button could be added to the list too, I'll take it in consideration.

**Comment by bosyi** [comment]
Hi,
It's not crucial principal but i think this way it will be more user friendly & native. Thus most of users do not have branch 'windows_thumbnails', but i will try to check that.

**Comment by micheleg** [comment]
The reason it is in a different branch is because it is still a work in progress (currently based on GNOME 3.14). When ready it will be released as an optional feature.

**Comment by bosyi** [comment]
How to force use extension for 3.14 in 3.18?

**Comment by micheleg** [comment]
You can somehow but it would not work (there is a reason if there are different versions). I rebased the code on current master in the windows_thumbnails_318 branch, check it out.

**Comment by bosyi** [comment]
i checkout to windows_thumbnails_318 but it still says it is not compatible with current version

**Comment by micheleg** [comment]
strange, you are sure you are running 3.18? Is it not loading or is it giving an error?

**Comment by micheleg** [comment]
My fault, I rebased it on 3.16. I can't quickly do the rebase now, I'll do it maybe this evening.

**Comment by micheleg** [comment]
I've merged the branch with the feature in master   [446c8efe24..72bd2c8], therefore I close this issue-
