### ISSUE TITLE
I cannot open Setting and it only runs like a dash

### ISSUE THREAD

**Issue by TommyJerryMairo** [micheleg/dash-to-dock#266]
When I first try to install it via yaourt an error occured:

convert: cairo-surface.c:928: cairo_surface_reference: Assertion `(_cairo_atomic_int_get (&(&surface->ref_count)->ref_count) > 0)' failed.
/tmp/yaourt-tmp-tjm/aur-gnome-shell-extension-dash-to-dock-git/./PKGBUILD: line 31:  2323 Aborted                 (core dumped) convert media/logo.{svg,png}

Then I install it by make&&make install, it seems installed but it only works like a dash on the left of the screen. I try to right click and left click the setting, but nothing heppend. Then I opened the Tweak-Tool and clicked the setting at the left of remove, a message shows:

GLib.FileError: Failed to open file '/home/tjm/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled': open() failed: No such file or directory
tack trace:
  getSettings@/home/tjm/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/convenience.js:66
  Settings<._init@/home/tjm/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:62
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
  buildPrefsWidget@/home/tjm/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:516
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

So, it is because of my environment(gnome 3.18.2) or my terrible skills to install it?

**Comment by micheleg** [comment]
Hi, there is a bug with recent librsvg. Have a look at #262 for a workaround. Closing as duplicate.
