### ISSUE TITLE
show apps icon offset?

### ISSUE THREAD

**Issue by person666** [micheleg/dash-to-dock#269]
The icon is not centered it is a bit up when it is moved to the front of bar and it looks too low when that option is not checked. 
![screenshot from 2015-12-23 02-14-14](https://cloud.githubusercontent.com/assets/16410790/11972483/eb49b0ec-a91a-11e5-9015-5f49a08543b8.png)

ps when will the thumbnails branch be added in to master it looks cool.

**Comment by micheleg** [comment]
Hi,

is the problem occurring also with the default theme or is it related to a custom theme (which theme are you using)? Does the shrink option  in the appearance panel in the settings affects the centering of the icon?

**Comment by person666** [comment]
It seems to only occur in novashell, but it is something in dtd that causes
it because it does not happen in simple dock.

**Comment by person666** [comment]
Do you know what could cause the incompatibility with the [novashell](https://github.com/utivis/nova-shell/tree/master/gnome-shell). 
ps what is the name of the app view icon element?

**Comment by micheleg** [comment]
Hi, the element should be style in the css of the theme through one of the following classes and elements: 'show-apps-icon', 'show-apps', 'ShowAppsIcon'.

**Comment by person666** [comment]
thanks

**Comment by person666** [comment]
The solution was to remove the padding from show-apps. I don't no why it was not showing up when using simpledock. thanks
