### ISSUE TITLE
The windows_thumbnails_318 branch will not run on arch gnome 3.18 

### ISSUE THREAD

**Issue by person666** [micheleg/dash-to-dock#270]
gnome tweak tool won't let me turn it on, shows an explanation mark and returns this error when clicking on settings.

```Gtk.BuilderError: /home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:1868:1 Duplicate object ID 'label4' (previously on line 627)```

```Stack trace:
  Settings<._init@/home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:35
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:400
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1```

**Comment by micheleg** [comment]
That branch is an attempt to rebase the development one, but unfortunately I rebased it wrongly. I haven't found the time to do it properly yet. I have the feature almost working on GNOME 3.14 on the branch ```windows_thumbnails```. You can try to rebase it against master if you want to test the feature.

**Comment by micheleg** [comment]
the branch ```windows_thumbnails_318```  should work now on 3.18.

**Comment by person666** [comment]
I get this error when trying to open the settings but the dock itself works. 

    Gtk.BuilderError: /home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui:845:1 Duplicate object ID 'label4' (previously on line 78)

    Stack trace:
      Settings<._init@/home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:68
      wrapper@resource:///org/gnome/gjs/modules/lang.js:178
      _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
      Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
      buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:524
      Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
      wrapper@resource:///org/gnome/gjs/modules/lang.js:178
      Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
      wrapper@resource:///org/gnome/gjs/modules/lang.js:178
      main@resource:///org/gnome/shell/extensionPrefs/main.js:397
      @<main>:1

**Comment by micheleg** [comment]
Fixed.

**Comment by person666** [comment]
Thanks for the quick fixes it looks great.
