### ISSUE TITLE
Polish translation update

### ISSUE THREAD

**Issue by psokol** [micheleg/dash-to-dock#274]
I've attached polish translation update.
[pl.po.zip](https://github.com/micheleg/dash-to-dock/files/76561/pl.po.zip)

**Comment by micheleg** [comment]
Thanks, I will merge it soon.

**Comment by micheleg** [comment]
Now merged in master [95cfd6fd72] and backported to 3.16 [6018f331] and 3.14 [0d9e68ed1].
