### ISSUE TITLE
Cannot change Dash to Dock settings

### ISSUE THREAD

**Issue by marasm76** [micheleg/dash-to-dock#275]
I have lost the ability to change the Dash to Dock settings. When I right click on the "Show Applications" button, and select "Dash to Dock Settings," nothing happens. Same thing in Gnome Tweak Tool; I go to Extensions and click on the little gear button, but nothing happens.

**Comment by person666** [comment]
Run these commands in terminal. 

`git clone https://github.com/micheleg/dash-to-dock.git` 
`cd dash-to-dock`
`make`
`make install`

Now hit alt-F2 and type "r" then hit enter.

See if it is fixed.

**Comment by marasm76** [comment]
That fixed it. Not sure why it stopped working in the first place.

**Comment by micheleg** [comment]
@marasm76  The version on the extension website (version 50) should already be ok, can you confirm?

**Comment by nwalmethule** [comment]
On Debian 10 I still have the same issue.

**Comment by rohitghali** [comment]
Arch here. Still have the same issue.

**Comment by Cmiroslaf** [comment]
Manjaro, the same issue
