### ISSUE TITLE
window thumbnails do not scroll

### ISSUE THREAD

**Issue by dffischer** [micheleg/dash-to-dock#277]
Using the [windows_thumbnails_318 branch](https://github.com/micheleg/dash-to-dock/tree/windows_thumbnails_318) (which, again, is a great feature), a long list of thumbnails can be higher than the screen itself, leaving no possibility to reach some items, including the `All Windows` caption to close the preview.

**Comment by micheleg** [comment]
Hi, thanks for testing the development branch. There have been a small problem with the rebase, it should be fixed now after last commit.

**Comment by dffischer** [comment]
Indeed, scrolling works fine now. Thank you for the quick processing.

**Comment by dffischer** [comment]
I just noticed another minor, but possibly related quirk. When the list is long enough for a scrollbar to appear, the smooth transition animation normally easing opening or closing the `All Windows` submenu does not occur.
