### ISSUE TITLE
Dock is too high after rebooting

### ISSUE THREAD

**Issue by SamusAranX** [micheleg/dash-to-dock#279]
So, yeah. Every time I reboot this system, the dock looks out of place.
![screenshot from 2016-01-13 21 34 56](https://cloud.githubusercontent.com/assets/676069/12307411/6558aa7a-ba3f-11e5-878f-0edd2342a8ce.png)

Unchecking and rechecking the "Panel mode: extend to the screen edge" option in Dash to Dock's settings remedies the problem until the next reboot. Does Dash to Dock assume a fixed panel height after booting? In the [theme I'm currently using](https://github.com/horst3180/Arc-theme), I have increased the panel's height to about 30px.

It's just a minor inconvenience, but it'd be great to see this fixed. Thanks for this tool. c:

**Comment by micheleg** [comment]
This looks similar to #241. Which extension and shell version are you running?

**Comment by SamusAranX** [comment]
Sorry, I'm not that familiar with GNOME. How do I find out what version I'm using?

**Comment by micheleg** [comment]
You can get the gnome shell version with this command:
```gnome-shell --version```
while the extension version is visible in the about panel of its settings (right click on the showapp icon, the topmost one in your screenshot)

**Comment by SamusAranX** [comment]
I'm using GNOME Shell 3.14.4 and Dash to Dock 48.

**Comment by micheleg** [comment]
I think the fix is already in the gnome-3.14 branch. Unfortunately I haven't release it yet on the extension website. Could you try to install this branch and check if the problem persists?

**Comment by SamusAranX** [comment]
That fixed it. Thanks!
