### ISSUE TITLE
Apps button doesn't allow scrolling if you searched last time

### ISSUE THREAD

**Issue by DylanGrayson** [micheleg/dash-to-dock#286]
If I click the apps button and load up the app screen, then type something in the search bar, then exit the overview by touching the hot corner, or any other way to exit the overview, scrolling is now disabled in the app view via the dock. This might seem like a rare scenario, but it happened to me twice until I figured out what caused it.

**Comment by micheleg** [comment]
Hi,

thanks for your bug report. I kind of not have understood the problem. What does "scrolling is now disabled in the app view via the dock" means? Also, would you mind reporting your Gnome Shell and extension version?

**Comment by micheleg** [comment]
Hi, any update me on this issue?
