### ISSUE TITLE
building from source fails

### ISSUE THREAD

**Issue by oberbapti** [micheleg/dash-to-dock#287]
Hi Michele,

thank you very much for this great extension! Today I found a minor bug. 
I cloned the git and ran "make" & "make install" but gnome-tweak-tool shows 
'not compatible with this shell version'.
When installing over extensions.gnome.org everything is working great.

Screens: [http://imgur.com/a/MCRms](http://imgur.com/a/MCRms)

Best regards

oberbapti

**Comment by micheleg** [comment]
Hi,

you might need to checkout the right branch depending on the version of GNOME shelll you are using. What GNOME shell version are you using?The master branch is usually meant for current stable (3.18 at the moment), while gnome-3.x branches are for the respective versions. While older versions are not updated any more, at the moment gnome-3.14, gnome 3.16 and master are all updated with the same features and bug-fixes.

**Comment by oberbapti** [comment]
Oh, sorry, my fault.
