### ISSUE TITLE
On Ubuntu 14.04 cannot change a dock's position

### ISSUE THREAD

**Issue by 3xal** [micheleg/dash-to-dock#288]
Actually i use Ubuntu gnome 14.04, and i cannot change a dock's position, it's fixed right

**Comment by micheleg** [comment]
It's my understanding that Ubuntu Gnome 14.04 uses GNOME Shell 3.10. If so, you need at least Gnome Shell 3.12, as the bottom option was not backported, or better Gnome Shell 3.14 to have all the additional features and fixes to date.

There is an experimental branch:

https://github.com/micheleg/dash-to-dock/commits/gnome-3.10-experiemntal

which you might want to try and have basic positioning support.
