### ISSUE TITLE
Move desktop icons to the right

### ISSUE THREAD

**Issue by jhasse** [micheleg/dash-to-dock#289]
I have desktop icons enabled via gnome-tweak-tool. The dash covers the first column of them. Is there a way to let the icons on the desktop have a padding on the left?

**Comment by micheleg** [comment]
Hi,
Unfortunately I'm not  aware of any solution for this (#17).

**Comment by jhasse** [comment]
I see. I've created a bug report for nautilus: https://bugzilla.gnome.org/show_bug.cgi?id=763063

**Comment by micheleg** [comment]
Thank you. Closing as duplicate.
