### ISSUE TITLE
Feature request: Make an option to change it to the bottom of the screen

### ISSUE THREAD

**Issue by rafaeldotjs** [micheleg/dash-to-dock#29]
I tried to hack it myself, but realized I would probably have to change the entire code. Is there an easy way?

**Comment by micheleg** [comment]
Bottom/right positioning has finally been implemented 4a738aa7a5e3e97dc5770bf1f48e4bed036a02e8

**Comment by varemenos** [comment]
That's great, thanks micheleg.
Any idea when this feature will be published in https://extensions.gnome.org?

**Comment by micheleg** [comment]
It is already available on the extensions.gnome.org website.

**Comment by marcvangend** [comment]
Thank you Michele! The bottom position works great.
