### ISSUE TITLE
Conflict with hidetopbar: the dock/topbar stay hidden after using maximized windows / full screen.

### ISSUE THREAD

**Issue by zapashcanon** [micheleg/dash-to-dock#298]
Hi,

I'm not sure if this bug is from Dash-to-Dock, but, when I watch a full screen video on Firefox, then, the dock won't reappear anymore in Firefox until I restart it. But it reappears if focus is on any other window.

I'm running Debian Unstable (amd 64), Gnome 3.18.2 with X, Dash to Dock 50 and Firefox ESR 45.0.1.

EDIT: Just asked someone, and the bug is also here with: Debian Testing (amd 64), Gnome 3.18.2 with X, Dash to Dock 50 and IceWeasel 44.0.2.

**Comment by micheleg** [comment]
Hi,

I can't reproduce the bug: 
* is this specific to Firefox/Iceweasel or does it happen any time you fullscreen an application?
* is the video a Flash video?
* there is a new release (v53) available, can you try to update and see if the problem persists?

Thank you

**Comment by Sancho-Panza** [comment]
Seems specific to Iceweasel/Firefox, but as I use Pixel saver extension, I never full-screen any other application: when windows are maximized, it's like full-screen...

I don't really know for the video, I think it's the case with both Flash video and HTML 5 players. (It was the case with HTML 5 player on YouTube).

I updated to v53, I'll tell you in one or two days if the problem persists and if it does, I'll give you video examples.

Thx!

**Comment by Sancho-Panza** [comment]
Hum... the problem appeared on atom today !

Atom and Firefox were running, when focus was on Atom, the dock didn't appear, but when I was on Firefox it appears.

So, I think it's not related to video only. Maybe to maximized windows used a long time, or idk what... I'll pay attention and try to tell you more as soon as possible.

**Comment by micheleg** [comment]
Thanks for your help. It's very important to be able to deterministically reproduce the bug in order to look for the solution.

**Comment by Sancho-Panza** [comment]
So @micheleg , for Atom, I don't really see when it exactly appears, maybe after a long time of use...

But for firefox, just watch this: http://www.canalplus.fr/c-emissions/c-le-petit-journal/pid6515-le-petit-journal.html?vid=1375753 (all the video and in fullscreen) ; and you should have the bug appearing when exiting full screen.

**Comment by micheleg** [comment]
I tried to reproduce the bug with no success: do I really need to play the whole video?

**Comment by Sancho-Panza** [comment]
Not sure if the whole video is needed, I think it's more like: the more you watch, the more chance there's that the bug appears.

But I realized it's maybe not only present in dash-to-dock, I've installed the extension "Hide top bar" and, when the bug appears, the dock stay hidden but so does the top bar...

Maybe it's a conflict with another extension, but as I've got a lot of extensions (25), it will take a little bit of time to figure out which one could cause the conflict...

My friend who has the same problem has some common extension with me, I'm going to ask her a list, and I'll give you those we have in common, it'll may help to reproduce the bug.

**Comment by Sancho-Panza** [comment]
Could you try with these extensions installed:

- Services systemd
- Hide legacy tray
- Hide top bar

I think the issue is linked to one of them, especially Hide top bar.

I've also noticed that, once the bug appeared on Firefox, if I start a new private Private Browsing window, the bug isn't present on this window, but is still present on the other window.

**Comment by micheleg** [comment]
Thanks for the additional information. I'll try to have a look at it.

**Comment by FMuro** [comment]
I'm also experiencing this issue. Fedora 23.

**Comment by BunnyApocalypse** [comment]
I am also having this bug on Arch, I'm fairly certain that it is triggered by hide top bar as it does not appear when I remove that extension.

**Comment by Sancho-Panza** [comment]
Don't know if this could help, but, I used to close/reopen firefox, atom or anything else to get the dock back. I found out that restarting the shell using:
    gnome-shell --replace &
Also works to get it back.

**Comment by zapashcanon** [comment]
It seems that the issue is fixed for me, didn't see this behavior for a long time. Can someone confirm ?

**Comment by zapashcanon** [comment]
@micheleg, closing as it seems to be solved...

**Comment by nickurak** [comment]
I appear to have hit this recently -- went looking for extension updates to see if i was behind, and noticed that the "TopIcons Plus" extension was in an error state. I restarted the shell to get that going again, and the problem went away. Hard to say how related they are, but seemed interesting to me.

**Comment by Natetronn** [comment]
I also hit this bug. I have Dash-to-Dock and hidetopbar. When watching a YT video, one that is embed, using full screen, upon exit my dock become unresponsive, my top panel become unresponsive as well. `gnome-shell --replace &` seems to have gotten me back to a working state, however.

**Comment by Imperial-Dragon** [comment]
I also had this bug in Arch for firefox. I changed the **full-screen-api.ignore-widgets** option in **about:config** to **true**. It seems to have solved the issue (At least for firefox). It does make dock reappear in Full screen mode too though (which I don't mind). I didn't get this issue for any other application. 
Hope this helps.

**Comment by bg2908** [comment]
> I also had this bug in Arch for firefox. I changed the **full-screen-api.ignore-widgets** option in **about:config** to **true**. It seems to have solved the issue (At least for firefox). It does make dock reappear in Full screen mode too though (which I don't mind). I didn't get this issue for any other application.
> Hope this helps.

Tks. This fix it for me too

**Comment by mridul-verma2005** [comment]
hey so i am using the extension hide top bar and dash to dock and experiencing the issue that when my chrome is open both the hide to bar and the dock to panel arent working correctly and glitching ( i am using intellihide in docK) when i move my cursor to the dock or to the panel the are not showing or glitching , idk why this happening

**Comment by BerkeSinanYetkin** [comment]
> I also had this bug in Arch for firefox. I changed the **full-screen-api.ignore-widgets** option in **about:config** to **true**. It seems to have solved the issue (At least for firefox). It does make dock reappear in Full screen mode too though (which I don't mind). I didn't get this issue for any other application. Hope this helps.

this just about works for me too. Though I needed to restart gdm too on Ubuntu 24.04.
