### ISSUE TITLE
Feature request: Allow page scrolling when scrolling over the dock

### ISSUE THREAD

**Issue by antistress** [micheleg/dash-to-dock#30]
Usecase : 
1. deactivate "Switch workspace when scrolling over the dock" 
2. the user was scrolling his document with his mouse wheel but the dock suddendly appears behind the pointer and he can't scroll anymore without moving his mouse.

-> it would be great to allow user to scroll his document behind the dock even when the dock is shown (=the dock shouldn't interfere with page scrolling)

Thanks !

**Comment by micheleg** [comment]
Apart from technically not possible (as far as I know), it also doesn't make too much sense to me. I think that after two years with the pressure sensitivity and the possibility to move the dock somewhere else (bottom) the problem should have been mitigated. Closing.
