### ISSUE TITLE
Wrong input region with intellihide disabled and full-screen windows

### ISSUE THREAD

**Issue by micheleg** [micheleg/dash-to-dock#301]
From the extension website:

> After last update, the panael seems to be always on top (events aren't fired), even if some fullscreen application override it. I.E i'm using virtualbox, on the left edge (extension position), i can't click the VM elements. Same thing playing fullscreen video with vlc.

Shell version: 3.18.4.
Extension version: 53

Probably due to https://github.com/micheleg/dash-to-dock/commit/916185190b640006919c3bf74fdbf98ba7284743

**Comment by thepasto** [comment]
I submitted the bugreport, i can confirm the problem occours only when intellihide is off.

Thanks again for your work!

**Comment by soal** [comment]
Hi,
if it helps i figured that this bug presents only with X11 session. With Wayland session everything ok.

**Comment by micheleg** [comment]
Thanks for the additional information.

**Comment by micheleg** [comment]
Hi,

I believe the bug is solved in this branch:

https://github.com/micheleg/dash-to-dock/tree/bug_inputregion_fullscreen

Could you test it and see if everything is ok?

**Comment by thepasto** [comment]
Yeah! Fixed for me! Thanks again!! Keep up a good work!

**Comment by micheleg** [comment]
Please double check again, I just updated the branch because of another regression. And keep an eye on any other strange behaviour I might have introduced with these changes. Thanks for your time.

**Comment by thepasto** [comment]
Still ok here, anything wrong also after the last commit. If you need more test just ask!
Thanks again

**Comment by soal** [comment]
Thanks @micheleg, everything fine)

**Comment by thepasto** [comment]
@micheleg Just found another problem. I don't know if related to this bug.
I'm running dropdown terminal extension too, and it goes under the dock. In the past the dropdown was correctly resized. Here's a [screenshot](https://drive.google.com/file/d/0B-yQDH0HYifnM0dsV1cxS3JQM0k/view?usp=sharing).

Thanks

**Comment by micheleg** [comment]
@thepasto was the problem with the drop down terminal extension introdued by a specific update of either dash to dock or  drop down terminal itself?

**Comment by thepasto** [comment]
@micheleg  Hmm... Well it's a bit hard to say! There were too many updates for both extensions. If you think it could be a drop down terminal issue, i will report it there.
Thanks

**Comment by micheleg** [comment]
@thepasto I have the feeling it might be due to some changes either in gnome-shell itself or in the dropdown terminal extension. This is because I can't think of any change that could affect the positioning of the terminal window. Would you mind trying to report the bug to the dropdown terminal extension?

**Comment by thepasto** [comment]
@micheleg  Yeah sure! I will report it there immediately. Thanks for your time, your help and your great extension once again!

**Comment by ksdev-pl** [comment]
I have probably the same problem with a jetbrains ide (phpstorm) - when the ide is in the full screen mode I cannot click in the place, where the dash to dock is normally: https://youtrack.jetbrains.com/issue/WI-31914

**Comment by thepasto** [comment]
@micheleg about my problem with drop down terminal extension, i found a solution, if any other is interested i posted here the solution. So for me this bug is completely solved. You can close it!

Thanks

**Comment by micheleg** [comment]
Ok.
