### ISSUE TITLE
performance hit due to launch animation

### ISSUE THREAD

**Issue by fastrizwaan** [micheleg/dash-to-dock#302]
Hi,

If you try plank or simple-dock which does not have "launch animation", the applications start faster. Please provide an option to disable "launch animation" (on clicking the icon on the dash-to-dock)

https://extensions.gnome.org/extension/815/simple-dock/

Thanks.

**Comment by micheleg** [comment]
Hi,

can you please report your GNOME Shell and extension versions? I'm a bit surprised that the animation is affecting the application launch: how do you measure it? Does the problem also occur with the extension disabled, i.e. from the default dash inside the overview?

**Comment by fastrizwaan** [comment]
it's good now in fresh install of fedora 23.
