### ISSUE TITLE
Some programs are showing up twice on the bar

### ISSUE THREAD

**Issue by ignacio-vc** [micheleg/dash-to-dock#306]
Hello. I've been having an issue when using dash-to-dock with certain programs. I have both 'Favorites' and 'Running' enabled in the extension menu. For most applications, if they are already running then they'll just take the place of the 'Favorite' icon. However - with programs like Firefox, they seem to repeat themselves: once for the 'Favorite' tag, and once for the 'Running' tag. Clicking on the Favorite icon just spawns new windows of running Firefox.

Is there any way you could make it so that Firefox's running process overwrites the Favorite icon when open?

If it's of any use to you, I'm running Debian Testing and Unstable on two machines, same problem. GNOME version is 3.18.2. It seems to happen regardless of if I have other extensions enabled or disabled.

![screenshot from 2016-04-09 12-59-09](https://cloud.githubusercontent.com/assets/11606473/14407149/2565678a-fe84-11e5-923c-e83a9d9d7d7f.png)

**Comment by micheleg** [comment]
Hi Ignacio ,

this is similar to #215, although it's the first time it happens with Firefox. Are you sure those are not indeed two different installations of Firefox, or that it is not related to the recent iceweasel -> firefox rename in Debian?

It would help if you could please check if the problem also occurs in the default dash, i.e. with dash-to-dock disabled.

**Comment by ignacio-vc** [comment]
Oh goodness. I feel very silly now. Yeah, it totally had to do with the rename. There are actually two firefox icons: one named Firefox and the other Iceweasel->Firefox, but they're the same program

Thanks a bunch, sorry to bother you. Great extension man
