### ISSUE TITLE
Show all windows from the application

### ISSUE THREAD

**Issue by feeef** [micheleg/dash-to-dock#310]
First of all, thank you for this great extension! I love it.

It would be great to have an option to bring up all the windows of the clicked application, from the current workspace at once (Mac OS default dock behaviour).  At the moment only "Cycle through windows" option is available.

Thank you!

**Comment by micheleg** [comment]
Thanks for your suggestions. I'm wondering, how does this differ from the current behaviour with the "do nothing" option set? I realize it's not really clear, and the wording should probably be improved.

**Comment by feeef** [comment]
@micheleg , you are right "do nothing" is the behaviour I was describing. 

I thought that "do nothing" was just there to disable the dock and I didn't even try it. I am sorry about that.

Maybe "do nothing" should be called "show all"? But this would be another issue I guess so I close this one anyway!

Thanks again!

**Comment by micheleg** [comment]
Yes, the original idea of the "do nothing" was do nothing different from the default behaviour... I created issue #312 so I don't forget to fix the wording.
Thank you.
