### ISSUE TITLE
Show Show Applications Icon

### ISSUE THREAD

**Issue by lemonface** [micheleg/dash-to-dock#315]
Under the behavior tab is an option, the third checkbox from the top, the word 'Show' is repeated so the option reads 'Show Show Application Icon', 

I understand that it's correct because that's exactly what it does but it is a little off. I'd suggest using inverted commas or calling it simply 'Applications Icon'

![screenshot from 2016-05-18 22-56-03](https://cloud.githubusercontent.com/assets/16198124/15376270/cc4e97a2-1d4b-11e6-8732-6a181afbdcaf.png)

**Comment by micheleg** [comment]
Yes, it makes sense to avoid the weird repetition. Fixed by 2fa5f0c7f0e9. Thank you.
