### ISSUE TITLE
Low resolution "placeholder dot" used when moving icons around

### ISSUE THREAD

**Issue by veggiedefender** [micheleg/dash-to-dock#317]
* Extension version - `53`
* Gnome Shell version - `3.20.2`
* Linux distribution and version - `Arch` (everything is up to date)
* Whether you have a multi-monitor configuration - `No`
* Your settings: include the output of the command dconf dump /org/gnome/shell/extensions/dash-to-dock/

```
animate-show-apps=true
show-apps-at-top=false
extend-height=false
dock-fixed=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
preferred-monitor=0
custom-theme-customize-running-dots=false
show-favorites=true
apply-custom-theme=false
show-running=true
custom-theme-running-dots=false
dock-position='LEFT'
custom-theme-shrink=false
background-opacity=0.33000000000000002
custom-theme-running-dots-border-width=0
dash-max-icon-size=64
opaque-background=true
height-fraction=1.0
icon-size-fixed=true
```

I have the Flat-Plat theme for my GTK+ and Shell theme, and Paper icons/cursor installed via the AUR.

It looks normal when I use the default shell theme but I think it also has something to do with the dash to dock extension as well because the dot looks normal when I have the Flat-Plat theme without the dash to dock extension. Here are some screenshots.
![screenshot from 2016-05-22 13-31-48](https://cloud.githubusercontent.com/assets/8890878/15455454/cb8a390a-2022-11e6-871b-757e32b384c8.png)
![screenshot from 2016-05-22 13-32-25](https://cloud.githubusercontent.com/assets/8890878/15455456/cb8cc5da-2022-11e6-96f4-406dc9e2497e.png)
![screenshot from 2016-05-22 13-38-35](https://cloud.githubusercontent.com/assets/8890878/15455455/cb8c2dbe-2022-11e6-8378-37ac95e2061c.png)

**Comment by micheleg** [comment]
Hi,

I have some trouble identifying the problem: which of the screenshot above shows the wrong behaviour?

**Comment by veggiedefender** [comment]
Sorry I wasn't clear enough! Hopefully this helps:

First screenshot is with dash to dock **with** the FlatPlat shell theme enabled. Note the ugly pixelated dot under the steam logo

Second screenshot is the FlatPlat theme **without** dash to dock enabled. The dot under the steam logo is what it *should* look like, not all blown up like the in the first screenshot.

Third screenshot is dash to dock **without** the FlatPlat theme enabled. The dot is normal resolution but it's the default one.
