### ISSUE TITLE
Strange behaviour when clicking the dock with a panel window open

### ISSUE THREAD

**Issue by edwin-v** [micheleg/dash-to-dock#32]
If you open a panel window (say the calendar) and click on the dock without closing it, then it will first close the panel window. This is as expected. But (left) clicking the icon again will bring up the right click menu. This is not as expected.

Note: tested on Gnome 3.6.

**Comment by zapashcanon** [comment]
I tried to reproduce this, with no success. @micheleg, my guess is that it has been fixed upstream, thus, you may close this issue ?

**Comment by micheleg** [comment]
I confirm. It seems to work fine now in Gnome Shell 3.22. Closing.
