### ISSUE TITLE
Allow user to increase autohide cursor sensitivity

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#322]
I have autohide enabled and I am having some trouble getting the Dock to show, I have to do a lot of wiggling of my cursor at the bottom of the screen to get it to come up. So I think that it would be nice if it allowed one in the settings to change its autohide show again sensitivity level so that one could increase the area the cursor has to move into to bring up the Dock again.

**Comment by Sancho-Panza** [comment]
You can already do that:

![capture du 2016-05-28 23-45-47-tmp](https://cloud.githubusercontent.com/assets/16472988/15630166/24d150dc-252f-11e6-924c-f07afab14e0a.png)

![capture du 2016-05-28 23-45-13-tmp-bis](https://cloud.githubusercontent.com/assets/16472988/15630168/27b21c32-252f-11e6-9518-fd7f781053af.png)

**Comment by SeventhSonOfASeventhSon** [comment]
Ah, names not so obvious, but got it now!
