### ISSUE TITLE
Settings panel should be accessible through the Dock

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#323]
Perhaps this would be enabled by default but configurable like the "Show Applications" button, and like with Docky you could just have a little icon with a logo on it which when clicked would bring up a list of possible options to click one being the settings panel, or you could just have a little button with an image of a gear or toolbox or something like that on it which one pressed would bring up the settings panel to mean that you don't have to go into the gnome-tweak-tool every time you want to start it up.

**Comment by Sancho-Panza** [comment]
Just right-click on the "Show application". ;)

**Comment by SeventhSonOfASeventhSon** [comment]
Ah, that wasn't immediately obvious, but thanks for letting me know!
