### ISSUE TITLE
There should be an option for just a normal autohide

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#324]
Annoyingly I have found that if I open any program through any means, be that Terminal, or Firefox, or any other program, the Dock stays showing unless the program is full-screen, so it's an intelligent hide, but I don't want that, I want it to be hidden all the time unless my mouse goes over the bottom of my screen where it is. So like with Docky I think that there should be options in the settings to choose between a standard autohide that I have described, and also and intelligent one which only hides when the selected program is not on the area where the Dock is.

**Comment by Sancho-Panza** [comment]
You can already do that:

![capture du 2016-05-28 23-45-47-tmp](https://cloud.githubusercontent.com/assets/16472988/15630137/b62cb8a6-252e-11e6-9d5f-1555cbc3900c.png)

![capture du 2016-05-28 23-45-13-tmp](https://cloud.githubusercontent.com/assets/16472988/15630143/c7c50dfc-252e-11e6-9dda-1a87586e7c54.png)

**Comment by SeventhSonOfASeventhSon** [comment]
Oh right, sorry, just didn't notice that for some reason...
