### ISSUE TITLE
Dock often fails to show when autohide is active

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#328]
I find that very often when I move my cursor down to where the Dock is located no matter what I do (and I have it on a reasonably sensitive setting) it won't show, it shows if I go into the Activities Overview, but even if I launch an application through it in there it still doesn't come up. Seemingly the only thing I can do is either restart `gnome-shell` or go into the AO and launch the Dash to Dock settings, then all returns back to normal.

I am running Ubuntu GNOME 16.04 with GNOME 3.20.

**Comment by zapashcanon** [comment]
Hi, are you using Hide top bar ? (see #298)

**Comment by SeventhSonOfASeventhSon** [comment]
@zapashcanon, No, I am not.

**Comment by micheleg** [comment]
@zapashcanon: could you please confirm if the problem occurs disabling all other extensions, if you are using more than one screen, if you are running on wayland or X11, and if you see any errors (https://micheleg.github.io/dash-to-dock/development.html#bugreporting)

**Comment by zapashcanon** [comment]
@micheleg I guess you meant @SeventhSonOfASeventhSon  ;)

**Comment by micheleg** [comment]
yes, sorry.

**Comment by SeventhSonOfASeventhSon** [comment]
@micheleg, The problems still occurs when disabling all other extensions, I am only using the one screen (I have a laptop so the screen is built-in and I don't have an external one), I am running X11, and no, I see no errors. Is there a log or something where any debugging information would be logged from or about the extension?

**Comment by micheleg** [comment]
You can try reloading gnome shell by running in a terminal

```gnome-shell --replace```

and look for relevant errors there. Please note that if you close the terminal Gnome Shell will be closed too.

**Comment by zapashcanon** [comment]
`gnome-shell --replace &`

And Gnome Shell won't be closed. ;)

**Comment by micheleg** [comment]
@zapashcanon: it doesn't work for me. I usually run ```gnome-shell --replace``` from the ```alt+F2``` dialog.

**Comment by zapashcanon** [comment]
I have an alias to restart it, as I have to do it very often and it works, it may depends on Gnome Shell version or something else ?

**Comment by skewty** [comment]
I am experiencing a similar issue.  Mine is with Remmina and a Fullscreen session.

To reproduce:
1) Start a Fullscreen session to a host (RDP in my case)
2) Trigger the Minimize Hotkey (Control_R + F9 by default I think)
3) Alt + Tab to get back to the Fullscreen session.

The dock is over top of the Fullscreen session at this point.
I can interact with the dock as usual but it will not timeout and disappear.

Clicking on my Linux Chromium web browser window on another monitor causes the dock to disappear.

Dash-to-Dock seems to be missing the Fullscreen focus change.

**Comment by skewty** [comment]
@micheleg @zapashcanon Even easier is the built in shortcut for restart gnome-shell.

`Alt+F2` then `r` then `Enter`

**Comment by zapashcanon** [comment]
@skewty, yep, but using a terminal, you can get (useful ?) logs live. :)

**Comment by micheleg** [comment]
I still can't reproduce the bug on my system, it might depend on the conflict with some other extension (I can't reproduce it even with the hide-topbar extesnsion)

**Comment by skewty** [comment]
I disabled all my other extensions. So you can rule out an extension
conflict.

**Comment by micheleg** [comment]
To recap: 
* which Shell and extension version?
* alt r + enter is enough to trigger the problem?

**Comment by SeventhSonOfASeventhSon** [comment]
GNOME Shell version: `3.20.3`
Extension version: `53`

In my case, I don't know for others though, but alt r + enter was more likely to fix the problem than cause it. In fact I do that regularly due to other issues and it has never caused it, the issue with the extension in my case only comes to me at random.

Perhaps this could be a distro issue? What distros are we all on?

**Comment by cpaulik** [comment]
I can reproduce this very consistently with chromium + hidetopbar on arch. Just open a youtube video - go full-screen for a second and both do not show up anymore. This also affects https://github.com/passingthru67/workspaces-to-dock . 

As others have noted the docks work again when a non full-screen window is focused even with chromium still maximised.

GNOME shell version: 3.22.1

**Comment by zapashcanon** [comment]
@cpaulik, @SeventhSonOfASeventhSon said he's not using hidetopbar, but the issue you're talking about is also known, see #298.

**Comment by cpaulik** [comment]
ok. how could we go about solving this? I tried debugging this a little bit and it seems that there is nothing wrong in hidetopbar of dash to dock. 

Also I'm now running this on wayland as a test and have not yet had the problem.

**Comment by micheleg** [comment]
I'm still not able to reproduce this bug. 
* I'm on debian, Gnome Shell 3.22.1
* I installed hide top bar without changing any of its settings.

I can play fullscreen a youtube video in chromium withou seeing any misbehaviour. 
@cpaulik: what are your detailed intellihide settings? What is the dock behaviour? What is the expected behaviour?

**Comment by cpaulik** [comment]
Hidetopbar settings 
![image](https://cloud.githubusercontent.com/assets/380927/20233626/cdb46822-a871-11e6-8788-196d3d450622.png)

dash to dock settings:

![image](https://cloud.githubusercontent.com/assets/380927/20233632/eef6af7c-a871-11e6-8d6f-2e1ed24012b6.png)


The dock is not visible in gnome-shell but I've put a `global.log` statement at https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L731 and it seems that the dock shows successfully but it is not visible. 

I have the same problem with the topbar. The difference is that I can click the topbar even when it is not visible which is also quite strange behaviour.

**Comment by SeventhSonOfASeventhSon** [comment]
Perhaps I should just mention, although I was experiencing this on the latest Ubuntu version (16.10), now that I have switched to Arch with GNOME 3.20 I no longer experience the issue.

**Comment by zapashcanon** [comment]
@SeventhSonOfASeventhSon, #298 is now solved, moreover, it seems to be fixed for you since you changed your system. @micheleg close ?
