### ISSUE TITLE
Error while opening dash to dock setting window

### ISSUE THREAD

**Issue by vasanthegde** [micheleg/dash-to-dock#329]
I have downloaded zip file and added successfully in tweak tool but whenever I tried to open setting window it popes up the error message.
Even `gnome-shell-extension-prefs dash-to-dock@micxgx.gmail.com` pops up the same error.
I have been using gnome-shell 3.18.4.

 **This is what it shows in the window**

```
GLib.FileError: Failed to open file '/home/vasant/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled': open() failed: No such file or directory

Stack trace:
  getSettings@/home/vasant/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/convenience.js:64
  Settings<._init@/home/vasant/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:58
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/lang.js:110
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:213
  buildPrefsWidget@/home/vasant/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:533
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

```  `

So basically I can't really use the any feature of dash-to-dock.

**Comment by franglais125** [comment]
You can try the following:

`cd ~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com`
`glib-compile-schemas schemas/`

**Comment by micheleg** [comment]
If you want to install the extension via the tweak tool, you need the release zip file with the schemas already compiled. You can get if from:

https://micheleg.github.io/dash-to-dock/releases.html

If you want to run the latest version from github you need to compile with simple ```make``` and ```make install``` commands:

https://micheleg.github.io/dash-to-dock/download.html#manualinstallation
