### ISSUE TITLE
Minimize an active window on click

### ISSUE THREAD

**Issue by NIXOYE** [micheleg/dash-to-dock#330]
I really would like to be able to click the icon of an application thats already open and focused to minimize it like Simple Dock https://extensions.gnome.org/extension/815/simple-dock/

**Comment by micheleg** [comment]
Hi,

how is this different from the option already offered through the extension settings?

![screenshot from 2016-06-11 13 14 34](https://cloud.githubusercontent.com/assets/1717310/15985006/771b318a-2fd6-11e6-883f-dd8f77e4ae1e.png)

**Comment by NIXOYE** [comment]
wow. never realized that was there, thanks.

**Comment by micheleg** [comment]
Good.
