### ISSUE TITLE
po/ru.po:5: 警告：头部缺少文件头“Language-Team

### ISSUE THREAD

**Issue by rechie1995** [micheleg/dash-to-dock#337]
`➜  dash-to-dock git:(master) make

msgfmt -c po/hu.po -o po/hu.mo

msgfmt -c po/ja.po -o po/ja.mo

msgfmt -c po/tr.po -o po/tr.mo

msgfmt -c po/fr.po -o po/fr.mo

msgfmt -c po/sr.po -o po/sr.mo

msgfmt -c po/de.po -o po/de.mo

msgfmt -c po/es.po -o po/es.mo

msgfmt -c po/sr@latin.po -o po/sr@latin.mo

msgfmt -c po/pt_BR.po -o po/pt_BR.mo

msgfmt -c po/pl.po -o po/pl.mo

msgfmt -c po/cs.po -o po/cs.mo

msgfmt -c po/it.po -o po/it.mo

msgfmt -c po/ar.po -o po/ar.mo

msgfmt -c po/pt.po -o po/pt.mo

msgfmt -c po/nl.po -o po/nl.mo

msgfmt -c po/ru.po -o po/ru.mo

po/ru.po:5: 警告：头部缺少文件头“Language-Team”

msgfmt -c po/zh_CN.po -o po/zh_CN.mo

msgfmt -c po/sk.po -o po/sk.mo

`

make 一下就出现这个警告，请大神来看看，该怎么解决？
Print the waring while I just enter make .How do I do to deal with?please.

**Comment by micheleg** [comment]
Hi. This should not stop you from  installing (```make install```) the extension. In any case I fix the warning in master (55a2f567d)

**Comment by rechie1995** [comment]
Thank you ,and I had done it.
