### ISSUE TITLE
More options for shift+click action

### ISSUE THREAD

**Issue by Edenhofer** [micheleg/dash-to-dock#340]
Please expand the options for shift-clicking to those which are available for a normal click. E.g. allow to cycle through windows with a shift-click instead of a normal click.

**Comment by micheleg** [comment]
Hi, this is something not complicated to do which however I've never ended up implementing (mainly because of lack of personal interest). See also #148.

**Comment by franglais125** [comment]
I think this can be closed now?

@Edenhofer you can check out pull #349

**Comment by Edenhofer** [comment]
Works flawless! Thansk @franglais125 for your effort!
