### ISSUE TITLE
Window counter indicators: wrong coordinates for Bottom or Right positions

### ISSUE THREAD

**Issue by franglais125** [micheleg/dash-to-dock#343]
On Gnome 3.20 (using the master branch, but I can reproduce this on version 53), when using the dock at the bottom or at the right, the window counter indicators are not drawn at the correct coordinates. If we choose a large border width (say 4 or greater), we can only see half of each dot (and then the problem is obvious):

![screenshot from 2016-07-02 01-45-45](https://cloud.githubusercontent.com/assets/19195975/16538577/b855eaa2-3ff6-11e6-8b58-fb02b3395c78.png)

I think this patch [75c40c684de920e5fb0d7ce657905cc040cd5801] solves the issue.

Look with the patch applied:

![screenshot from 2016-07-02 01-50-48](https://cloud.githubusercontent.com/assets/19195975/16538607/86e86264-3ff7-11e6-99c3-ef57f19eb6a2.png)

Thanks for looking into it!

**Comment by micheleg** [comment]
Thanks for spotting the problem.  I have to recheck the math and the logic of the positioning. I'm not sure if your proposed solution is the right one, or if it just compensate for my mistake somewhere else.

**Comment by franglais125** [comment]
Sounds good, cheers!

**Comment by micheleg** [comment]
I think I fixed it in the branch https://github.com/micheleg/dash-to-dock/commits/fix_running_dots

Your fix was ok, but I went though the logic of the positioning and made it more direct.

**Comment by franglais125** [comment]
I tested your branch, but I now see two problems:
 - The separation of the dot from the edge of the screen changes as the border width is increased. I don't claim that this is the proper solution, but here is how I 'fixed' the first problem: Patch [0b1782b6e68549bae2d325d240d42b3f362ce30c]
![screenshot from 2016-07-09 16-32-30](https://cloud.githubusercontent.com/assets/19195975/16710137/da4cbad0-45f2-11e6-9573-b2335eeea573.png)
![screenshot from 2016-07-09 16-32-42](https://cloud.githubusercontent.com/assets/19195975/16710136/da4a1c58-45f2-11e6-9950-423b823f4650.png)

 - If the border width is large enough (>8 for me), the dot is not properly filled. I am still trying to find a pretty fix for this.
![screenshot from 2016-07-09 16-32-55](https://cloud.githubusercontent.com/assets/19195975/16710138/e5c24470-45f2-11e6-8cc4-881f05f1d6b0.png)

**Comment by micheleg** [comment]
I've updated the branch with your correction on the position and a possible fix for the wrong rendering.

**Comment by franglais125** [comment]
It's working great now, thanks for the fix!

Maybe just add a `let` in line 338? Other than that, I think you can close the issue.

**Comment by micheleg** [comment]
Right. Fixed and merged into master [067048fc, 87376ee].
