### ISSUE TITLE
Should go back to desktop on esc after clicking the show app icons

### ISSUE THREAD

**Issue by micheleg** [micheleg/dash-to-dock#345]
Ricardo:
>If I click on activities on the top left corner and then I click on the applications icon, if I press the esc key it goes back to activities overview; if I click on applications icon directly from the dock it goes directly to the applications overview but if I press esc key it doesn't go back to the desktop but to the activities overview, that's what I was trying to explaing, it should go back to the desktop not to activities overview when I hit esc key

**Comment by franglais125** [comment]
Isn't this issue the same as https://github.com/micheleg/dash-to-dock/issues/339 ?

**Comment by micheleg** [comment]
Yes, apparently I opened the issue twice. Closing as duplicate of @339.
