### ISSUE TITLE
Limit the popup menu on right click

### ISSUE THREAD

**Issue by ItamarShDev** [micheleg/dash-to-dock#346]
When right clicking on chrome for example, the opened windows title are way too wide
is it possible to set max width and use ellipse or such?
![unnamed](https://cloud.githubusercontent.com/assets/953371/16658305/917c8ce8-446e-11e6-8b69-3bc018f90e3a.png)

btw, if you'll point me to the part in the code i'll happily do it :)

**Comment by micheleg** [comment]
This is definitely a good idea. One way would be to set the "max-width" css rule somewhere. Either to the labels or to the popupmenu itself.

**Comment by ItamarShDev** [comment]
I know, I've searched for it in the code. 
But for the life of me I can't find the context menu in the code

**Comment by micheleg** [comment]
The code building the menu is here: 

https://github.com/micheleg/dash-to-dock/blob/master/appIcons.js#L503-527 . 

However, all windows menu are hidden  in the parent function:

https://git.gnome.org/browse/gnome-shell/tree/js/ui/appDisplay.js#n1822

**Comment by micheleg** [comment]
Maybe we could redefine the "_appendMenuItem" (https://git.gnome.org/browse/gnome-shell/tree/js/ui/appDisplay.js#n1922) setting the max-width when the label is created?

**Comment by ItamarShDev** [comment]
will try it all this evening!
wow! thanks

**Comment by ItamarShDev** [comment]
[pull request](https://github.com/micheleg/dash-to-dock/compare/master...ItamarShDev:master) sent

**Comment by ItamarShDev** [comment]
the pull request was a faulty one

**Comment by micheleg** [comment]
Yes, that way all popup menu inherit the max-width.  I think we should  either apply a class to the element and use id in the css, or aply directly the settings to the popupmenu.

**Comment by ItamarShDev** [comment]
Both sounds fine.

**Comment by ItamarShDev** [comment]
My PC is at the lab, apparently it didn't want to drink water :P
I'll get back to it when it's back from the lab
