### ISSUE TITLE
qt apps always open new icon

### ISSUE THREAD

**Issue by bune1991** [micheleg/dash-to-dock#352]
qt apps dont group in dock always open new icon so when i open any qt apps from favorites it open new icon

**Comment by zapashcanon** [comment]
Isn't it the case without dash-to-dock ?

**Comment by bune1991** [comment]
it's with dash-to-dock  gnome 3.20 debian stretch

**Comment by micheleg** [comment]
@bune1991 what @zapashcanon  was saying is: if you disable the extensions, are the qt apps gouped correctly in the default dock inside the overview? The feeling is that it is an upstream bug. Also, can you provide an example applications giving you this problem? I'm on  debian stretch too.

Possibly related issues: #239, #215.

**Comment by bune1991** [comment]
the problem in default dock too i think gnome problem 
dolphin konsole kdenlive ksysguard
