### ISSUE TITLE
Reorganizing icons is impossible if "Show favorite applications" is OFF

### ISSUE THREAD

**Issue by rsommerard** [micheleg/dash-to-dock#353]
It is impossible to reorganize the icons on the dash if the "Show favorite applications" option is OFF. When this option is enabled, it is possible to reorganize icons.

-- Romain

**Comment by micheleg** [comment]
The reason is that only favorites applications can be ordered on the dock, while running are automatically positioned. Therefore, if the favorites are not shown there is really nothing to be organized.

**Comment by rsommerard** [comment]
Yeap, that make sense. :)

Thanks for your reply.

**Comment by M1cha** [comment]
@micheleg actually, that does not make sense.
Even non-favorite applications should be movable. It's very annoying when you just want to organize things and at the next reboot you have to see that your dock is full of favorites because dash-to-dock automatically activated it for every app you moved around.

You're doing a great job with this project and I'd really love to see support for this.

**Comment by micheleg** [comment]
@M1cha sorry for the late reply. What you are proposing is definitely an alternative behaviour. At the moment, I'm basing the dock to the default dash code, which doesn't allow to oder non-facorites launchers. 

Are you aware of a dock or similar launcher that allows to order the non-favorites applications? I'm a bit puzzled by how this would work. When you move a launcher aorund, how would you decide what ordinal number to assign to the applications? You might explicitely put it before the launchers shown at the moment of interaction, but what about the other applications you previously ordered?

**Comment by M1cha** [comment]
I don't know what came first, the implementation or my expectation of this behavior :P (I've used a lot of distros over the years).

Can you explain me why you need ordinal numbers? I'd expect that it's just some kind of list and when it gets stored in a configuration file you ignore the non-favorites and store the favorites in order.

**Comment by micheleg** [comment]
By ordinal number I just mean ordering  the list. The issue I see is the following:
* you have firefox pinned (favorite) and terminal running  (non-favorite), and move terminal jsut after it: the ordering is now:
1. firefox
2. terminal
* You now close terminal, and open nautilus, and move it just after firefox. Now the ordering is:
1. firefox
2. terminal or nautilus?
So when you open both terminal and nautilus, in which order should the launcher be shown? I'm not saying it can't be solved, but it is not obvious to me  what would be a non confusing behaviour. 

A seconday issue is that at the moment the reordering of launchers correspond to the pinning (make them favorites) of them. For reason of consistency I'm temped to keep it like that (but let's see what's going on upstream, they might get rid of the dash all toghether).

**Comment by M1cha** [comment]
I'd expect that new windows of non-favorite applications would always appear at the end of the list because ordering non-favorites is something temporary which should not be saved.
