### ISSUE TITLE
Not reviving instances running in background anymore

### ISSUE THREAD

**Issue by nd2s** [micheleg/dash-to-dock#359]
I recently upgraded to a newer laptop, installed Arch Linux (again) and must have gotten a newer version of dash-to-dock in the process (although I am not certain).

What used to be: I could start Gajim from the dock, the icon would appear in the tray icon area. I could close the main window and Gajim would run in the background (the dash indicator would say 0 open windows for Gajim). When I then "started" Gajim again from the dock, it would open the window of the background instance again.

But now it always starts a new Gajim process, which is very annoying.

I am not sure if this is a bug in dash-to-dock or a problem with how Gajim is called. I noticed this also happens on FreeBSD.

**Comment by franglais125** [comment]
I can reproduce your problem with Gajim, although I am not sure the fault lies with Dash-To-Dock.

If you try to do the same with other programs the behaviour may vary. For instance, I tried to do the same with Transmission, and it opens the old instance, not a new one.

If no window is open for a given app, usually (depends on your settings) dash-to-dock will try to open_new_window() or something like that. Now the app has to interpret this command properly.
In the case of Gajim, if I don't use dash-to-dock but the overview, I get the same problem: a new instance is created, which may indicate again that Dash-To-Dock might not be the problem.

You can try to download an older version of dash-to-dock from this site and see if that fixes the problem. My guess would be that either you have a newer version of Gnome-Shell or a newer version of Gajim, where the behaviour was changed. Do you know if that's the case?

Hope it helps!
Cheers

**Comment by nd2s** [comment]
I just tried installing an older version, but Arch is running on GNOME 3.20, and the latest version 53 seems to be the only one compatible with that (I compiled v52 but got "Invalid Extension" error). So it probably isn't that.

I am now pretty sure it isn't Gnome-Shell nor Gajim either, though. Because on my old laptop I also had a fully updated Arch Linux. And I just checked both packages: they haven't been updated in a the last month. (Also: FreeBSD is running with GNOME 3.18 afaik).

Still could be some other package, though. Or some problem with configuration so that it kept working on the old system, but fails on the new. Too bad my old Arch installation is gone.

**Comment by franglais125** [comment]
Well, I have to say I am surprised. I had tested the problem on Debian Testing (Gnome 3.20) since you had that problem on Arch (bleeding edge).

But just now I tested again on Debian Stable (Gnome 3.14, and a much older version of dash-to-dock) and I see the same problem (a new instance is created). So I don't know how you managed to *not* have this before, but this has been the behaviour on Gnome and Dash-To-Dock since the 3.14 days.

Again, no problem with Transmission, so the problem is not inherent to Dash-To-Dock...

**Comment by nd2s** [comment]
I have no clue why that worked. For now I found a (crappy) workaround, in case someone has the same problem:

In `/usr/share/applications/gajim.desktop` I replaced the `Exec=gajim` line with `Exec=gajim-remote toggle_roster_appearance || gajim`. This will of course be overridden when Gajim gets an update... Also remote support in Gajim needs to be enabled, and the python2-dbus package needs to be installed.

I hope I will find the real reason why this worked before..

I am closing this ticket because it doesn't seem to be the fault of Dash-to-Dock. Thanks for your time.

**Comment by micheleg** [comment]
Hi @nd2s, just top be sure it is unrelated to dash-to-dock, do you have the same problem if you disable the extension and you use the dock inside the overview?

**Comment by franglais125** [comment]
@micheleg Although I didn't open the issue, I can confirm this issue is present even with Dash-to-dock deactivated (using the dock from the overview).

I tested this on Gnome 3.14 and 3.20.

**Comment by nd2s** [comment]
Yeah it doesn't work. Unfortunately my workaround stopped working as well after a reboot. No idea why.

**Comment by nd2s** [comment]
You probably won't believe me when I tell you it just started working on it's own.. Without my workaround. There is some black magic at work here.

It doesn't work all the time, though. The first time I closed the window and "started" Gajim again, it tried to create a new instance. But now it always toggles the window.
