### ISSUE TITLE
Journal Extension Compatibility

### ISSUE THREAD

**Issue by jsnj** [micheleg/dash-to-dock#36]
I'm trying the latest version up for review that's the first release with the app button. Works well so far. The new Journal extension for GS 3.6 places a history button on the default GS dash. Although it's probably too early to offer compatibilty w/the new Journal extension(which has yet to be posted to the extension site), I'd thought I'd provide a heads up for future compatibility.

https://github.com/seiflotfy/gnome-shell-zeitgeist-extension

**Comment by micheleg** [comment]
Closing as the extension doesn't seem to exist any more.
