### ISSUE TITLE
get_theme_node() spamming with errors after screen unlock

### ISSUE THREAD

**Issue by franglais125** [micheleg/dash-to-dock#361]
Hi,

I'm opening this issue following this comment https://github.com/micheleg/dash-to-dock/issues/37#issuecomment-239721213. @ticpu

I am trying to find the culprit for such a crash, and so far at least I uncovered one problem when unlocking the screen.

theming.js:
There is a protection to avoid a crash (or critical errors) https://github.com/micheleg/dash-to-dock/blob/master/theming.js#L111

dash.js:
There is no protection against the same problem.
Patch: [d5243934d997252f212acb9412283c0cf2cdb27f]

I'll include a log of the errors shortly.

**Comment by franglais125** [comment]
Here is the log: https://gist.github.com/franglais125/80c3386cd3b6f2e8d29a2bf20d374d2f

I check the fix I provided above on Gnome 3.20 and 3.14. I don't know if it can introduce a problem somwhere?

**Comment by franglais125** [comment]
@micheleg Can you reproduce the problem on your setup?
Although the problem started as a multi-monitor issue, I get the errors without the multi-monitor patches as well.

More info:

1. It happens only if the "User themes" extension is enabled (I tested using Adwaita and Arc themes)
2. I can trigger it simply by locking and unlocking the screen.
3. I can also trigger it by disabling/enabling any other extension (probably do to a reload of the extensions).

**Comment by micheleg** [comment]
I'm confused now by this issue. Does it relate to the multimonitor branch?

**Comment by franglais125** [comment]
I think this issue is more general, but it's just that when using the multi-monitor branch it becomes very prominent, due to having many dock instances with all its objects. Simply locking/unlocking the screen was enough to trigger the error messages.

To prevent crashes for myself and testers (like @tipcu who first reported this), I added a fix to the multi-monitor branch, so it is never affected by this AFAIK. This is the patch currently in that branch [0b682d2ca7d2f874d719beb7e690e62abfe00f08].

In the end, if you add that commit or a similar fix, this issue can be closed.

**Comment by micheleg** [comment]
I've merged your patch as [6affa87698].

**Comment by franglais125** [comment]
Sounds good, thanks. I rebased the _multi_monitor_ branch after this. It's now down to 6 commits ahead your _master_ branch.
