### ISSUE TITLE
Alt-tab sometimes makes the dock visible when it should be hidden

### ISSUE THREAD

**Issue by Curly-** [micheleg/dash-to-dock#366]
Sometimes when alt-tabbing, the dock becomes visible, with autohide enabled. This happens without the cursor being over the dock area. To make the dock disappear, I need to alt-tab to another windows and back again, or minimise, then maximise the current window.

**Comment by micheleg** [comment]
Gnome and extension versions? Please try to identify a pattern so that I can reproduce the issue.

**Comment by Curly-** [comment]
GNOME Shell 3.20.4
Dash to Dock 53

**Comment by Curly-** [comment]
Just realised I have [this extension](https://extensions.gnome.org/extension/97/coverflow-alt-tab/) enabled. The bug only happens when that extension is enabled.

**Comment by micheleg** [comment]
Can you try with latest release (v54)?. A problem with coverflow-alt-tab was fixed there (#303).

**Comment by Curly-** [comment]
I think that's fixed it. Thank you!
