### ISSUE TITLE
Problem with Gnome 3.20.4

### ISSUE THREAD

**Issue by RojoC** [micheleg/dash-to-dock#368]
I'm using dash-to-dock smoothly before update Gnome Shell to 3.20.4 after the update it gives "Outdate" error.

**Comment by micheleg** [comment]
This is strange, minor point release should not cause an "Outdate" error. Have the problem disappeare upon gnome-shell restart?

**Comment by ningen** [comment]
I have "Outdated" error too on Debian Stretch with Gnome version 3.21.90.

**Comment by franglais125** [comment]
@ningen you need to explicitly add support for this.
Debian Stretch has Gnome-Shell 3.21.91
https://packages.debian.org/search?keywords=gnome-shell

open: `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json`
And add "3.21.91" to the line:
`"shell-version": ["3.18", "3.20"],`

So it looks like this:
`"shell-version": ["3.18", "3.20", "3.21.91"],`

If the Shell gets updated again, you'll have to do it again. Eventually version 54 of the extension will be released and Gnome 3.22 will be supported.

**Comment by micheleg** [comment]
Version 54 is under review, but it will explicitly support only the stable release. When you run unstable versions, it is advisable to disable the extension check.
```
gsettings set org.gnome.shell disable-extension-version-validation "true"
```

Apparently, this won't be necessary any more from next release

https://git.gnome.org/browse/gnome-shell/commit/?id=5e0e3edc7be44c9e370604f1d3514efc37e68a94

This has nothing to do with the original problem of the  "outdated"  error with stable point release, which are not required to be listed explicitly.

**Comment by ningen** [comment]
@franglais125, @micheleg thanks quick answers! "disable-extension-version-validation" solution worked for me.
