### ISSUE TITLE
Option to configure display delay

### ISSUE THREAD

**Issue by rugk** [micheleg/dash-to-dock#370]
Personally I would like to lower the hover delay/timeout until the dock is shown to make it showing faster.
However there is no setting for this, so I'd propose to add this.

This option is e.g. present in workspaces-to-dock.

**Comment by franglais125** [comment]
Isn't this already implemented?

Here is a screenshot of the extra options for Intellihide:
![screenshot from 2016-09-02 17-58-10](https://cloud.githubusercontent.com/assets/19195975/18219334/d5fd7180-7136-11e6-8540-dab2fff951ae.png)

You can change the various delays to 0 if you like.

**Comment by rugk** [comment]
I have Version 51 and there I cannot see this.

Using Debian Jessie and GNOME here.

**Comment by franglais125** [comment]
Ah, I see.

I think @micheleg might push an update for 3.14 (you can see the difference in his 3.14 reorganization branch), but I'm not sure.

Also, I am not sure if it includes that feature though. I'm on my phone now, I'll check later.

**Comment by micheleg** [comment]
@rugk Those settings should be available in version 51 too. They are under the gear menu near the intellihide toggle button.
