### ISSUE TITLE
Option for magnify mode on hover

### ISSUE THREAD

**Issue by rugk** [micheleg/dash-to-dock#371]
I would like an option, which magnifies the current icon when one hovers over it.

:green_apple:OS has this feature e.g. (It should look similar here, so that also the icons nearby are magnified, which makes it look more fluid)

**Comment by franglais125** [comment]
This sounds like a duplicate of https://github.com/micheleg/dash-to-dock/issues/357

**Comment by rugk** [comment]
Yeah it is. Could not found it before, so thanks for pointing it out.

**Comment by salomonhome** [comment]
heard this code snippet would work

function plotOnBell(x, scale, stdD, mean) {
    if (scale === void 0) { scale = false; }
    if (stdD === void 0) { stdD = .125; }
    if (mean === void 0) { mean = 0.5; }
    //It returns values along a bell curve from 0 - 1 - 0 with an input of 0 - 1.
    if (scale) {
        return 1 / ((1 / (stdD * Math.sqrt(2 * Math.PI))) * Math.pow(Math.E, -1 * Math.pow(x - mean, 2) / (2 * Math.pow(stdD, 2))));
    }
    else {
        return ((1 / (stdD * Math.sqrt(2 * Math.PI))) * Math.pow(Math.E, -1 * Math.pow(x - mean, 2) / (2 * Math.pow(stdD, 2)))) * plotOnBell(.5, true, stdD, mean);
    }
}


but which is the file to be edited?

**Comment by rugk** [comment]
@salomonhome better post this in https://github.com/micheleg/dash-to-dock/issues/357
