### ISSUE TITLE
option to only show the running applications of the current workspace

### ISSUE THREAD

**Issue by chrpinedo** [micheleg/dash-to-dock#374]
Add one new feature to show the running applications of the current workspace. Nowadays, if I choose "show running applications", it shows in the dock all the running applications of every workspace.

Regards,

Christian

**Comment by franglais125** [comment]
This option has already been implemented, you just need to wait for a new release to happen :)
See issue https://github.com/micheleg/dash-to-dock/issues/204

**Comment by chrpinedo** [comment]
Thanks this is really cool!!! I close the issue to avoid disturbing ! Closing as implemented by #325.
