### ISSUE TITLE
Dynamic transparency

### ISSUE THREAD

**Issue by fb87** [micheleg/dash-to-dock#376]
Would be very neat if you could copy the code of the extension „Dynamic Top Bar“ and apply it for the dock, so that the dock two transparency settings!

**Comment by micheleg** [comment]
Is this the same behaviour described in #375?

**Comment by fb87** [comment]
Yes, it is…

**Comment by micheleg** [comment]
Ok, I'm closing this as duplicate then. Please refer to #375.
