### ISSUE TITLE
Dash to dock minimized windows does not raise when clicking icon

### ISSUE THREAD

**Issue by Dark-Passenger** [micheleg/dash-to-dock#380]
Earlier on clicking icon(set to minimize) the window used to get minimized and on clicking again the window got maximized.

With latest update this does not work.

Distro Fedora 24 x86_64

**Comment by franglais125** [comment]
Did you just update to version 54 of the extension?
If so, then this was likely introduced when adding more 'click options' [08bc3629dceaadd213d07eac94958c438a4f3e18].

The good news is that there is already a fix in a PR: https://github.com/micheleg/dash-to-dock/pull/360 (first 4 commits).

**Comment by micheleg** [comment]
@Dark-Passenger: it seems to work for me.Is it not working at all or have the behaviour changed?

**Comment by franglais125** [comment]
@micheleg I think it's the same problem we discussed here: https://github.com/micheleg/dash-to-dock/pull/349#issuecomment-240546202

At that point we included the fixes in PR 360

**Comment by micheleg** [comment]
Mmmm,  I thought  I had followed your suggestion and restored the previous behaviour, although it is not so clear to me which is the best behaviour...

**Comment by franglais125** [comment]
Yeah, it's not something I use personally, but it does feel like a regression to someone who actually uses it.

You did prepare a branch for it (https://github.com/micheleg/dash-to-dock/tree/development), and then I rebased the Hotkeys work (pull 360) on it.

I guess I got confusing at some point :)

**Comment by micheleg** [comment]
I see. I was in a hurry making the release for 3.22 and I forgot about those patches. I will merge them to master asap.

**Comment by franglais125** [comment]
Awesome, thanks!

I'll rebase the hotkeys implementation once you do that.

**Comment by micheleg** [comment]
Merged those changes into master. @Dark-Passenger , would you be able to test if this solve your problem?

**Comment by franglais125** [comment]
@micheleg I think your last commit [58f15e2b7a3d07039de52c51c5a4defd2d90cc66] has a typo: `CTRL_MASK` should be `CONTROL_MASK`

**Comment by micheleg** [comment]
Yes, fixed the typo.

**Comment by sbsbs15** [comment]
It works now, please update the extension at extensions.gnome.org 

Thanks!!

**Comment by Dark-Passenger** [comment]
@micheleg works now thanks closing issue.

**Comment by uovo** [comment]
I'm using the latest revision but can't get it to work. All I want is to maximize when the window is minimized and vice versa. None of the new options seem to allow that. Am I missing something?

**Comment by franglais125** [comment]
@uovo the problem has been fixed in the `master` branch, but no new version was uploaded to extensions.gnome.org yet.
I guess you are using version 54? If not, what do you mean by "the latest revision"?

**Comment by uovo** [comment]
I'm using the master branch. I'm at 1183576b4ad76ee4a822a282042c4273bced6520.

**Comment by franglais125** [comment]
Ok... So:
- Obvious question, but did you restart the shell after installing **master**?
- What version of Gnome Shell are you using?
- The option you should choose is "_Minimize_" for **Left Click**. It won't work with Shift+Click for instance. So if you choose "_Minimize window_" for Shift+Click, you won't be able to un-minimize the window.

**Comment by uovo** [comment]
OK, I set the left click option to Minimize and "Reset to defaults" the other settings. It's working now. Thanks!

**Comment by Dark-Passenger** [comment]
and ... broken for me on restarting shell.

Was working fine yesterday and now its broken :(

version gnome - 3.20

**Comment by Dark-Passenger** [comment]
on master latest commit.

**Comment by micheleg** [comment]
@Dark-Passenger any updates? Are you still experiencing the bug?

**Comment by Dark-Passenger** [comment]
fresh install.

added the patch. all working for the past few days, so can confidently say the issue has been fixed.
