### ISSUE TITLE
Have close buttons next to windows in right-click list

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [micheleg/dash-to-dock#382]
I believe this is present in the Unity launcher, and it is a good feature, however GNOME doesn't really need it because it has the AO and anyone not using this or a similar extension is likely to use the AO for this.

However, for those of us who want to be able to use the dock without having to be in the AO I think that it would be nice if when right-clicking upon a docked application for the list of currently open windows which one may go to to allow you to close the windows easily as well. So basically each entry would just have a little "x" close button next to it which one could use to close individual windows without having to go to them or into the AO.

**Comment by micheleg** [comment]
This was partially implemented in a wip branch with the windows thumbnail option (see #261). However such option hasn't landed yet. Closing as duplicate  of #261.
