### ISSUE TITLE
Dock covers desktop icons

### ISSUE THREAD

**Issue by privatemajory** [micheleg/dash-to-dock#387]
Hi.
I really like this extension, but it would be better if there was no desktop "space" behind the dock, so desktop icons wouldn't be covered like in the image below. Maybe this should be added as an option.
Many thanks!
![capture du 2016-10-20 08-35-28](https://cloud.githubusercontent.com/assets/19147367/19547467/da604b1e-96a0-11e6-94d4-b37dd0656144.png)

**Comment by micheleg** [comment]
This can't be solved at the extension level. See #17 . Close as duplicate.
