### ISSUE TITLE
some maximized GTK (qt apps, firefox works good) applications doesn't occupy all the screen after unlock

### ISSUE THREAD

**Issue by m-khvoinitsky** [micheleg/dash-to-dock#390]

**Comment by micheleg** [comment]
This is definitely the expected behaviour. However, the opposite can happen if there's a bug. Can you reproduce this bug?

**Comment by m-khvoinitsky** [comment]
Unfortunately, no. This was happening after installation of an extension. But after relogin it seems doesn't reproduces anymore. I'm running wayland session, by the way.

However, there is another problem: when I lock the screen, panel hides, after unlock it appears again, but some maximized GTK (qt apps, firefox works good) applications doesn't occupy all the screen. There is a gap on the right:
![screenshot from 2016-10-26 12-23-23](https://cloud.githubusercontent.com/assets/16675892/19720547/48a8ceae-9b77-11e6-88e9-a8a4ec875d14.png)
Here it's tiny (I've marked it with red arrows), but yesterday it was same width as dock and it's size was growing after sequential screenlocks.

**Comment by micheleg** [comment]
I'm tempted to say it's either not due to this extension or due to an incompatibility with other extensions. Could you confirm if the problem appear only with dash-to-dock enabled?

**Comment by m-khvoinitsky** [comment]
I apologize for messing up this bugreport.
Initial problem (Dock is not hidden while screen is locked) just appeared again.
Can you tell how I can debug this issue to provide you more details (may be some looking glass snippet)?
I'll try not to relogin until that moment.

P. S. may be it's better to split this bug to two separate.

**Comment by franglais125** [comment]
What distro and what Gnome-Shell version are you using?

**Comment by m-khvoinitsky** [comment]
Archlinux, 3.22, Wayland.

**Comment by micheleg** [comment]
If the proble occur again, plese look for some error message (See info here https://micheleg.github.io/dash-to-dock/development.html#bugreporting)

**Comment by micheleg** [comment]
Closing this old issue as the bug is not confirmed, but feel free to reopen it.
