### ISSUE TITLE
ERROR message from GNOME Extension and no Dock

### ISSUE THREAD

**Issue by ushabuntu** [micheleg/dash-to-dock#393]
![2016-10-29 10-28-18](https://cloud.githubusercontent.com/assets/23134021/19827996/09b22c60-9dc3-11e6-9a66-94d0ce34de87.png)

The dock is not working, after an attempted update from the Gnome Extension site. 
Tried installing specific version all the way down to 3.14 and no success. 

Using Ubuntu Gnome 16.04.1, Kernel 4.4.0-45, Gnome 3.18.5

**Comment by micheleg** [comment]
Can you confirm if the problem persist even after restarting the shell? Have you tried alternative installation methods: https://micheleg.github.io/dash-to-dock/download.html#manual_installation

**Comment by ushabuntu** [comment]
yes. it does.

I tried installing manually (not from source, though), tried removing and
rebooting and installing again, tried all the versions from 3.18 upwards,
but nothing works.
The manual install shows in every single one the message "Incorrect
extension", and the normal install through the Gnome Extension site shows
the red ERROR button.

:(

--
Uri

**Comment by ushabuntu** [comment]
ok, i solved it, but i have NO IDEA HOW.

i uninstalled again and again, then went to my laptop (that has Ubuntu
Gnome 16.04.1, similar to my desktop) to check the version number i have
working on it.

It was 53, but i didn't see which Gnome version.
I tried both 3.18 and 3.20. non worked from the manual Tweak tool.

then when i wanted to remov them again from the tweak tool menu of
extensions, i couldn't find it at all.

so i tried installing it again from the website.

and it worked!

:)

May i will never see this error again. Kudos for the best extension ever!

:))

--
Uri

**Comment by micheleg** [comment]
Good, closing this then.
