### ISSUE TITLE
Dock dissapears when i close Activities

### ISSUE THREAD

**Issue by Mukhametvaleev** [micheleg/dash-to-dock#395]
When i open activities and then return to desktop dock is dissapearing and not showing

**Comment by Mukhametvaleev** [comment]
I am find out that problem is only with enabled "hide dash x" extension

**Comment by micheleg** [comment]
Hi Andrei,

sorry for the late reply. You are trying to use two extensions that are both messing with the default dock and they are therefore conflicting with each other. For the moment I can only suggest you to use one of the two. My understanding is that you would like to hide the dock in the overview, possibly with autohide behaviour. This feature has been already proposed (#25), but has not been implemented yet.
