### ISSUE TITLE
Can't add QT applications to favourites

### ISSUE THREAD

**Issue by davethecipo** [micheleg/dash-to-dock#396]
Hello!

I can easily add GTK applications to favourites with a right click in order to show them on the dock even when they're not running. I can't say the same for QT applications.

Steps to reproduce:
 
- open a QT application like konsole, dolphin
- right click on the icon in the dock
- "add to favourites" doesn't appear

Configuration:

- Extension version 55
- gnome-shell 3.22.1+2+g5a08886-1
- Arch linux (updated)
- 2 monitors 

```
dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
apply-custom-theme=true
preferred-monitor=0
dock-fixed=true
require-pressure-to-show=false
dock-position='BOTTOM'
intellihide-mode='MAXIMIZED_WINDOWS'
show-apps-at-top=true
```

Further info:

- All other extensions have been disabled
- I can't find any error panel in Looking Glass
- No errors reported by `journalctl /usr/bin/gnome-session -f` (run as root)
- No errors in `~/.xsession-errors`
- resetting settings doesn't change the behaviour
- Running `gnome-shell --replace`  gives errors but they don't seem related to the extension

```
gnome-shell --replace

(gnome-shell:3900): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(gnome-shell:3900): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(gnome-shell:3900): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(gnome-shell:3900): Gtk-WARNING **: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
Gjs-Message: JS LOG: Failed to launch ibus-daemon: Esecuzione del processo figlio "ibus-daemon" non riuscita (File o directory non esistente)
Gjs-Message: JS LOG: No permission to trigger offline updates: Polkit.Error: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: Action org.freedesktop.packagekit.trigger-offline-update is not registered
```

**Comment by franglais125** [comment]
I can confirm this issue on Gnome 3.22. However, it seems to me that this is an upstream problem.
I tested this with both Dolphin and Konsole, a few comments:
 - I managed to make it favorite by dragging the icon from the overview to the dash
 - Once it is a favorite, it doesn't work well: opening Dolphin will open a new (identical) icon on the dash.
 - "Add to favorites" is missing from the context menu
 - The 3 items listed above are true as well on the default dash from the Shell, without the extension.

[See screenshots in the next comment].

@davethecipo can you confirm that this is a problem also on the regular dash, i.e. with dash-to-dock disabled?

**Comment by franglais125** [comment]
**With Dash-to-dock**

Can't make it favorite from context menu:
![screenshot from 2016-11-09 10-42-11](https://cloud.githubusercontent.com/assets/19195975/20144197/da53e99a-a669-11e6-9b8b-59d8a97a3567.png)

You can make it favorite by dragging, but doesn't work properly:
![screenshot from 2016-11-09 10-41-53](https://cloud.githubusercontent.com/assets/19195975/20144198/da552468-a669-11e6-8a8a-66f8d2b0862c.png)

**Comment by franglais125** [comment]
Dash-to-dock **disabled**

Same problems as above:
![screenshot from 2016-11-09 10-42-37](https://cloud.githubusercontent.com/assets/19195975/20144279/1b47a798-a66a-11e6-9ffa-e4fdc9b50a3e.png)
![screenshot from 2016-11-09 10-43-15](https://cloud.githubusercontent.com/assets/19195975/20144278/1b462a1c-a66a-11e6-9b8e-3b2d3fc92364.png)

**Comment by davethecipo** [comment]
@franglais125 you're right, this seems an upstream problem, I didn't think about disabling dash to dock before reporting the bug.

**Comment by micheleg** [comment]
It really seems an upstream issue. Have you submitted an upstream bugreport?

**Comment by davethecipo** [comment]
No, I don't know exactly where I should report it

**Comment by micheleg** [comment]
I think it should be reported  to the gnome shell bug tracker https://bugzilla.gnome.org/page.cgi?id=browse.html&product=gnome-shell

**Comment by davethecipo** [comment]
Thanks, I reported the [bug](https://bugzilla.gnome.org/show_bug.cgi?id=774353). I'm not confident though, there're similar bugs that have been marked as duplicates of [this one](https://bugzilla.gnome.org/show_bug.cgi?id=654775) which is really old and nobody seems to care about.

**Comment by micheleg** [comment]
I've seen your bug report upstream in gnome and kde, therefore I'm closing this issue.
