### ISSUE TITLE
Can't enable in Tweak Tools

### ISSUE THREAD

**Issue by DylanMeeus** [micheleg/dash-to-dock#397]
On Debian 8, I can see the extension in my extensions list of the tweak tool, but it is impossible to enable. There is an error sign next to it, but it does not tell me which error there is. Which way can I find out the error?

**Comment by highvoltage** [comment]
Hey Dylan, how did you install the extension? From a tarball, the extensions site or perhaps the package from Debian 9?

**Comment by micheleg** [comment]
Hi Dylan, my best guess is that you installed a non compatible version. What version do you have?

**Comment by Eastvv00d** [comment]
Hi, i have the same issue.
Debina 8.7 + GNOME Shell 3.14.4 . I am cloned latest version from this repository and try different methods of installation, but i have the same results. 

I try to check log, еhat's what I got:

sudo journalctl /usr/bin/gnome-session -f -o cat

Failed to get data: Cannot assign requested address
Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
Gjs-Message: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
(gnome-shell:26296): Gjs-WARNING **: JS ERROR: Exception in callback for signal: startup-complete: Error: Requiring GSystem, version none: Typelib file for namespace 'GSystem' (any version) not found
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:216
_emit@resource:///org/gnome/gjs/modules/signals.js:124
LayoutManager<._startupAnimationComplete@resource:///org/gnome/shell/ui/layout.js:704
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
LayoutManager<._startupAnimation@resource:///org/gnome/shell/ui/layout.js:658
wrapper@resource:///org/gnome/gjs/modules/lang.js:169
LayoutManager<._prepareStartupAnimation/id<@resource:///org/gnome/shell/ui/layout.js:650

**Comment by micheleg** [comment]
You can't install current master version on 3.14. The master branch only support 3.18 and above. Latest release for 3.14 is version 51 (https://micheleg.github.io/dash-to-dock/releases.html)

There's also a gnome-3.14 branch (https://github.com/micheleg/dash-to-dock/tree/gnome-3.14) which is slightly more updated.

**Comment by Eastvv00d** [comment]
Thanks a lot!! v51 work for perfect

**Comment by franglais125** [comment]
@Eastvv00d if you were looking for new features, this is the (customized) branch I was running on Debian Jessie https://github.com/franglais125/dash-to-dock/tree/gnome-3.14-custom

I backported some features like hotkeys, multi-monitor and window previews.
