### ISSUE TITLE
Settings no opening 

### ISSUE THREAD

**Issue by rainer2208** [micheleg/dash-to-dock#398]
When I click on the tab or menu for the Dash Dock Settings, the settings don't open and I get an error message from gnome shell: 

Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

I have tried removing and reinstalling Dash-to-Dock in several ways (site, zip), but all to no avail. 

Hopefully this helps to improve this nice feature. A screenshot is attached. 

Rainer

![dash-to-dock](https://cloud.githubusercontent.com/assets/23400899/20215807/aafa2b18-a7f5-11e6-8a8b-fc0354cd8212.png)

**Comment by zapashcanon** [comment]
Hi,

Which OS and version of gnome-shell are you using ?

**Comment by rainer2208** [comment]
Hello, thanks for the reply ... 

My OS is Ubuntu 16.10 and I am using the Gnome Shell version 3.22.1 . 

I added the extension a couple of days ago, and it worked perfectly. I guess the settings stopped working after I made an upgrade. 

Rainer

**Comment by zapashcanon** [comment]
How did you "add" the extension ? From gnome shell extension website ?

**Comment by micheleg** [comment]
This look pretty strange. Can you open the settings of other extensions?

**Comment by rainer2208** [comment]
Guys, I have added the extension from the website, removed it and added it from the zip file, and again added it from the website. All to no avail. Right now I have checked the other extensions and all work fine. Also, I have updated the system. 

The problem still persists and is only with Dash-to-Dock. 

Funny, right? 

I hope this helps.

**Comment by micheleg** [comment]
If you open looking glass (`alt+f2`, then type `lg` and press  enter) and in the command window you type:
`imports.gi.Clutter`
what do you get?

Maybe there is some missing package (although I don't understand how the shell would be running). Can you try to install some gir****clutter*** package?

**Comment by rainer2208** [comment]
On imports.gi.Clutter the output is: 

r(1) = [object GIRepositoryNamespace]

About importing any gir*clutter package, I really don't know how to do that. I have searched the internet on the topic, but couldn't find any useful orientation. 

What would be a way?

**Comment by micheleg** [comment]
Could you check if you have these packages installed?

http://packages.ubuntu.com/search?keywords=Clutter+gir&searchon=names&suite=yakkety&section=all

Not that it makes sense to me, but just to be sure.

`sudo apt-get install gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-gtkclutter-1.0`

**Comment by rainer2208** [comment]
Michele, that solved the issue. 

Before, I had tried to install the missing libs through apt-get install clutter,  but the system couldn't locate it. 

I also don't know how the libraries could suddenly go missing, since the extension worked well when I first installed it. 

Well, now everything works fine ...

Many thanks for your kind assistance.

**Comment by micheleg** [comment]
Good, closing this.

**Comment by MyAssingment** [comment]
try this on your terminal

sudo apt install gir1.2-gtkclutter-1.0

**Comment by auipga** [comment]
For Archlinux users: install `clutter-gtk`
