### ISSUE TITLE
Counter indicators

### ISSUE THREAD

**Issue by vendforce** [micheleg/dash-to-dock#402]
What do I need to change or comment out in appicions.js to completely remove the counter indicators
I dont want to have any counter indicators showing maybe it would be great if you could add an option to hide counter indications all together

Thanks

**Comment by micheleg** [comment]
The option is the appearance panel, just disable "Show windows counter indicators".

**Comment by vendforce** [comment]
It still shows a small dot

**Comment by micheleg** [comment]
That's probably due to the theme. Is the dot shown also in the dash when you disable the extension?

**Comment by 73** [comment]
I found this issue with the same question. However, to answer the question: *Yes, they are.*
