### ISSUE TITLE
setting Panel mode: extend to the screen edge cover  the status bar

### ISSUE THREAD

**Issue by zosy** [micheleg/dash-to-dock#404]
ENV
os: archlinux with gnome 3.22.2
dash-to-dock: git clone
problem: setting Panel mode: extend to the screen edge cover  the status bar
see the screenshot below
![screenshot from 2016-11-14 20-46-01](https://cloud.githubusercontent.com/assets/3468935/20265542/44cf51f8-aa37-11e6-8fe1-5edfea12bbc6.png)

**Comment by zapashcanon** [comment]
Seems like a duplicate of #168.

**Comment by micheleg** [comment]
Closing as duplicate of #168. Please refer to that discussion.
