### ISSUE TITLE
Bug in the corners of the dock

### ISSUE THREAD

**Issue by PhoeniZ** [micheleg/dash-to-dock#405]
Hi everyone.

I have installed dash to dock and i have a small bug, i see a dark pixels at the corner of the dash:

![captura de pantalla de 2016-11-15 22-00-49](https://cloud.githubusercontent.com/assets/23486482/20324330/79475dbe-ab80-11e6-8bb5-c73ac26157b5.png)

Extension version: antergos/gnome-shell-extension-dash-to-dock 1:v53-1 
Gnome Shell version: Versión 3.22.2
Linux distribution and version: Antergos
Your settings: 

```
pressure-threshold=0.0
autohide-in-fullscreen=true
animate-show-apps=true
show-apps-at-top=false
extend-height=false
dock-fixed=false
intellihide=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
opaque-background=true
show-delay=0.25
show-show-apps-button=true
animation-time=0.20000000000000001
require-pressure-to-show=true
show-running=true
custom-background-color=false
hide-delay=0.20000000000000001
autohide=true
apply-custom-theme=false
preferred-monitor=0
custom-theme-running-dots=false
dock-position='BOTTOM'
custom-theme-shrink=true
background-opacity=1.0
height-fraction=1.0
dash-max-icon-size=46
background-color='#204a87'
icon-size-fixed=false
isolate-workspaces=false
```

I tryied to disable other extensions, reinstall the extension, change options of extension and nothing works for me, but if i try "shrink dock" the curve borders disapear and turn it like a rectangle:

![captura de pantalla de 2016-11-15 22-16-09](https://cloud.githubusercontent.com/assets/23486482/20324513/2fc9f060-ab81-11e6-8510-00df60e0928f.png)

Sorry for my english and thank you for this nice extension.

**Comment by micheleg** [comment]
Most likely a theme related issue (Like #388 ?) Could you please confirm if the problem occurs also with the default theme?

**Comment by PhoeniZ** [comment]
> Most likely a theme related issue (Like #388 ?) Could you please confirm if the problem occurs also with the default theme?

Omg it's solved! I have Numix-Frost theme and switching by default theme the problem is solved.

Thank you!!

**Comment by micheleg** [comment]
Ok, as for the discussion for the other bug I don't think i can really look after all possible themes. Closing.
