### ISSUE TITLE
Animation lag when apps are minimized

### ISSUE THREAD

**Issue by ghost** [micheleg/dash-to-dock#406]
I'm getting animation lag when apps are minimized  and press the "show application icon".
The issue appears only when apps are minimized.
I'm running manjaro and gnome 3.22.2.
I attach also a video.

[Screencast_24-11-2016_02:47:04 ΜΜ.zip](https://github.com/micheleg/dash-to-dock/files/611350/Screencast_24-11-2016_02.47.04.zip)

**Comment by kouros17** [comment]
Ok, I found that the problem caused by **"native window placement"** extension.
If I disable it then the "animation lag" is not displayed. :)

**Comment by micheleg** [comment]
Does the problem also occurs if you trigger the animation from inside the overview (with and without dash-to-dock enabled)?

**Comment by kouros17** [comment]
No it only occurs with **"dash-to-dock"** and  **"native window placement"** simultaneously activated. If i disable  the **"native window placement"** the animation works normally without lags.

**Comment by vanvugt** [comment]
GNOME 3.22 is probably not supported by any distros anymore. Please report new issues for any new bugs that you find.
