### ISSUE TITLE
New window icons are created between the favourites and the old ones

### ISSUE THREAD

**Issue by nicman23** [micheleg/dash-to-dock#415]
With latest commit, when new windows are created, the new icon, ends up between the permanent launchers and the already open windows.

A more sane approach would be to go the end of the dock (and by end i mean the furthermost position from the first pinned application).

**Comment by micheleg** [comment]
Hi, which commit are you referring to?

**Comment by nicman23** [comment]
the latest from master.

**Comment by micheleg** [comment]
The latest commit in master is a translation [d18f2d6c452fc2d86fc06470f78c4f2ea83e4d41]. Are you sure?

**Comment by nicman23** [comment]
will redownload and remake the extension and write back

**Comment by osmandemirhan** [comment]
Hi,
This happens when the "Isolate workspaces" option is selected. The icon of the active window moves at the en of the Favorites icons. When another window selected, then this windows icon replace the last one. This likes fliping and flopping...

I use latest code from repository on Ubuntu Gnome 16.20 (Gnome 3.20).

Thanks for your efforts.

**Comment by franglais125** [comment]
@micheleg not sure, but perhaps this is the same thing you fixed in this branch https://github.com/micheleg/dash-to-dock/tree/fix_running_order
However, it was never merged.

@nicman23 or @osmandemirhan does that branch fix the issue for you?

**Comment by osmandemirhan** [comment]
@franglais125 yes, this is exactly the case. I tried the branch and my issue fixed. Thanks a lot.

**Comment by nicman23** [comment]
cannot confirm, i do not use gnome at this install

**Comment by micheleg** [comment]
I've merged the fixes in master [39041f4f902f354, 805fd6c4d7]. Thanks @franglais125.
