### ISSUE TITLE
#request: AutoHide actived on all width screen border

### ISSUE THREAD

**Issue by yattamax** [micheleg/dash-to-dock#432]
Like MacOS, the autohide option are more usefull if enabled when mouse is over all width of side screen and not only over the width of the dock

this option can improve usability :)

**Comment by micheleg** [comment]
I had considered this behaviour. It's not a bad idea, as one doesn't know in advance where he can push.

**Comment by micheleg** [comment]
What should happen after triggering the dock showing away from it in the case the user doesn't hover it? Should it hide after a certain amount of time? Should it happen after the mouse is far away enough form the sensitive screen edge?

**Comment by micheleg** [comment]
A quick implementation https://github.com/micheleg/dash-to-dock/tree/experimental_whole_edge_sensitive. It works only if pressure sensitivity is in use). There's a 1 second delay before the dock hides if you don't hover it.

**Comment by yattamax** [comment]
in osx, the dock disappear when cursor go out from the height of the dock and continue to be visible if mouse is over the virtual area of the dock

**Comment by micheleg** [comment]
I updated the experimental branch with the described behaviour: the dock hiding is triggered if the mouse if farther than the dock height/width away from the screen edge.

**Comment by yattamax** [comment]
goooood :)

very usable now ;)

**Comment by micheleg** [comment]
Merged into master [39041f4f902f354].
