### ISSUE TITLE
Multimonitor setup

### ISSUE THREAD

**Issue by Taskkill** [micheleg/dash-to-dock#433]
Would it be possible to have dock on two screens? For me it would be really appreciated feature. For example I use notebook screen as primary monitor, while having two bigger screens attached as secondary monitors. I would like to have two docks on bottom of both of these two secondary monitors.

Thanks for consideration.

**Comment by micheleg** [comment]
Have a look at #37. There's a tentative implementation there. I'm closing this issue as a duplicate.

**Comment by Taskkill** [comment]
Sorry, I did not search enough. Thanks for info.
