### ISSUE TITLE
windows with long title issue while dash is in panel mode

### ISSUE THREAD

**Issue by atefhares** [micheleg/dash-to-dock#437]
If you have a window of an App opened and this widows has a long title then pressing right-click on App will not show right-click-menu options correctly !

![screenshot from 2017-01-23 03-45-02](https://cloud.githubusercontent.com/assets/14354272/22188532/da699cdc-e11e-11e6-9e39-027b09a95a2c.png)

**Comment by zapashcanon** [comment]
I guess using the same fix that was used in gnome-shell-extension-radio/38 could fix it.

**Comment by atefhares** [comment]
@zapashcanon the code is different in extensions.js and I don't have player.js

**Comment by zapashcanon** [comment]
@atefhares, this was not for you particularly but to anyone who might want to fix it in the extension. I mean, just breaking line after a fixed number of chars should do the trick.

But indeed, I checked and it looks like the text is not handled by dash-to-dock, so, would require a little bit more of work.

**Comment by micheleg** [comment]
Have a look at the branch https://github.com/micheleg/dash-to-dock/tree/fix_large_popupmenu. I tried to limit the popupmenu width to 400 px. Does it work? Any suggestion for improvements?

**Comment by atefhares** [comment]
@micheleg It is better now and Adding the screen previews is great addition but I think it will be better if previews are showed without the need of clicking on All Windows, I have two suggestions (maybe not the best but could be nice)
a- previews are showed directly on menu and user can scroll it Horizontally one per scroll instead of being continuous vertical scrolling.
b- long right click show All previews Horizontally and if previews are longer than some width (the width of previews panel) then the user can scroll them smoothly.

**Comment by micheleg** [comment]
One problem at a time ;) Does the commit fix *this* issue? Is it reliable?

**Comment by atefhares** [comment]
:D, For the long Title It is Acceptable for me now, the screen shot is exactly the previous one after fix
![screenshot from 2017-01-24 01-10-38](https://cloud.githubusercontent.com/assets/14354272/22227319/6d964758-e1d3-11e6-8002-ec6242894741.png)

**Comment by micheleg** [comment]
Wasn't the issue in the previous screenshot with windows preview disabled?

**Comment by atefhares** [comment]
yes it is the same
![screenshot from 2017-01-24 01-54-53](https://cloud.githubusercontent.com/assets/14354272/22228255/ad051bc6-e1d8-11e6-86d5-baa869170389.png)

**Comment by micheleg** [comment]
Ok, merged in master [f6bad6135c9].
