### ISSUE TITLE
No bottom option for Ubuntu Gnome 14.04 with Gnome 3.9.90 

### ISSUE THREAD

**Issue by Erwol** [micheleg/dash-to-dock#440]
It looks like in this version of Gnome the option for moving the dock to the bottom doesn't appear in any place (when installing the extension[ from here](https://extensions.gnome.org/extension/307/dash-to-dock/)). If I try to clone and compile the last version of the project, then the extension's marked as outdated.

**Comment by micheleg** [comment]
Unfortunately you need at least GNOME 3.12 to have the bottom placement option.
