### ISSUE TITLE
Whole monitor edge autohide sensitive interfere with the show activities button

### ISSUE THREAD

**Issue by micheleg** [micheleg/dash-to-dock#441]
As pointed out in https://github.com/micheleg/dash-to-dock/issues/399#issuecomment-275291224.

**Comment by micheleg** [comment]
Should have been fixed by 393c4acc09f405.

**Comment by zeroepoch** [comment]
Thanks!  Works much better now.  The activities hot corner works like before now.

**Comment by lbrfabio** [comment]
Works better but if you use hidetopbar, the problem is still there. 
Somehow changing _y1 = workArea.y;_  to _y = 1;_  solved the problem for me

**Comment by micheleg** [comment]
@lbrfabio: thanks, I've firther shrinked the sensitive area by one pixel [0f2fa2fd05a2bd5]. This also avoids conflicting with the legacyBar on the bottom left corner

**Comment by lbrfabio** [comment]
Hi, thanks for the quick response with a new commit. 
Anyway, I'm not sure for the other St.side, but for the LEFT one, I think you should probably change:
`y1 = workArea.y + 1;`  instead of `y1 = workArea.y - 1` _(the same configuration of St.side.RIGHT)_.

**Comment by micheleg** [comment]
You are right. Should be fixed now [bb271989eff]. Thank you!
