### ISSUE TITLE
Icon size not updated on settings change.

### ISSUE THREAD

**Issue by micheleg** [micheleg/dash-to-dock#442]

**Comment by micheleg** [comment]
Look like a false alarm, maybe some spurious state while developing the extension, as it seems to be working now. Closing.

**Comment by franglais125** [comment]
Ah, I forgot to comment about this before.

Did you perhaps mean to say the size of the number overlay, when adjusting the icon size? It is not updated until a dash redisplay is triggered (minor issue IMO).

**Comment by micheleg** [comment]
No, the icon size itself seemed not to be updating unless a redraw of the dash was forced. What you describe is a different issue.

**Comment by micheleg** [comment]
I think this makes sense and fix this minor issue 0f2fa2f.

**Comment by franglais125** [comment]
Indeed, ff6957d9123afb6527d34ad63ffd0ac51a8a10a7 fixes the size problem.
