### ISSUE TITLE
"Trigger zone" for showing dock is incorrect on dual monitor setup

### ISSUE THREAD

**Issue by Cybolic** [micheleg/dash-to-dock#444]
I have a setup with my main monitor running at 3440x1440 and a second monitor running 1920x1200 on the left. The issue is that, probably due to the different resolutions, the dock will only appear when hovering a bit above the middle of the left side (about 25% screen height from the top), not when hovering over the middle. When the dock is set to appear on the bottom of the screen, the problem is more visible, with the trigger zone being almost all the way to the left of the screen. In both cases the actual trigger zone is only a few pixels in size, so showing the dock becomes fairly tricky.

I've attached a visualisation of where the trigger zones appear; I drew it on top of scaled screenshots, so the locations are fairly accurate (the sizes are not, though).

One important detail is that this issue only appears after a few hours of use and that a quick toggle of the Dash to dock extension in Tweak Tool "resets" the problem.

![dash-to-dock-dual-setup-bug](https://cloud.githubusercontent.com/assets/1196197/22555917/10a4fbbe-e96e-11e6-8df2-431d2ce81d15.png)

**Comment by franglais125** [comment]
It sounds like you are being affected by this https://github.com/micheleg/dash-to-dock/issues/399.
That issue was fixed in recent commits (hopefully for you too), but it's not yet available through extensions.gnome.org.

Can you test the master branch to see if the problem goes away?

**Comment by Cybolic** [comment]
Thanks, I think it's been fixed, it hasn't popped up since I switched to the master branch. Closing.
