### ISSUE TITLE
Blur effect (feature request)

### ISSUE THREAD

**Issue by scottmangiapane** [micheleg/dash-to-dock#448]
This dock is awesome, thanks for making it! The only thing I wish it did differently is to have a 'Gaussian Blur' effect, like the dock on macOS or the Unity search menu. Is this something that could be added?

![Screenshot](https://cdn.arstechnica.net/wp-content/uploads/2014/10/dock-slices-wide@2x.png)

**Comment by zapashcanon** [comment]
Looks like a duplicate of #429.

**Comment by scottmangiapane** [comment]
Similar to that, yes. But ideally blurring the background image as well (notice that in the screenshots, the color is a translucent gradient not a single color throughout).

**Comment by micheleg** [comment]
A blur effect could be nice and it would brighten up a bit the desktop probably. It is also a not trivial and computational consuming effect. It's not a new request. I'm closing this as a duplicate of #224.

**Comment by subbame** [comment]
This would be an awesome feature. I have been supporting Dash to Doc for ages and without this extension, Gnome would be incomplete. I know not having this feature will not hinder anything but it would make the icons pop out and look cool with gaussian blur.
