### ISSUE TITLE
[Feature Request] Disabling intellihide - "always on top"

### ISSUE THREAD

**Issue by RandomAntergosUser** [micheleg/dash-to-dock#449]
hey there,

would be great if we could have the dash to dock always on top (by disabling intelligent autohide) without having those empty spaces when using a full-sized window (e.g.: browsing the internet)
screenshot (how it is/how i am suggesting to be) here: [here](http://imgur.com/a/L49Uk)

cheers

**Comment by zapashcanon** [comment]
Hi,

Looks like you can already have this behavior.

Enable intellihide, and then, use these settings for it:

![capture du 2017-02-24 20-57-07](https://cloud.githubusercontent.com/assets/16472988/23318753/f8eff77c-fad3-11e6-8ed5-bee344895192.png)

**Comment by RandomAntergosUser** [comment]
you made my day... thanks a lot! I didn't manage to figure it out myself and I didn't find anything on the web

**Comment by micheleg** [comment]
I'm not sure I understand how those settings give the desired behaviour as shown in the first linked screenshot. Or i haven't understood the desired behaviour.

**Comment by micheleg** [comment]
Closing as the issue seems to be solved.

**Comment by zapashcanon** [comment]
Sorry for not responding the first time @micheleg.

For the record, what @RandomAntergosUser meant is that, he wanted to have the dock always on top. Unfortunately, if he does it by disabling intellihide, he will waste some space (his second picture). The solution is just to enable intellihide but to disable the two option hiding the dock. The dock will always be here on top, but with no space waste.

**Comment by ConorHenry** [comment]
This should be reopened. The proposed solution doesn't work on at least Pop_OS 19.10. The dock still autohides when activating overview and does not reappear automatically, as well as with a few other actions I haven't fully nailed down. There should really just be a checkbox for this.
