### ISSUE TITLE
pressure sensitivity blocks top-left hot corner

### ISSUE THREAD

**Issue by sojusnik** [micheleg/dash-to-dock#451]
When [pressure sensitivity](https://micheleg.github.io/dash-to-dock/news/2014/04/08/pressure-sensitivity-implemented.html) is enabled, then the mouse cursor has to be moved twice to the top-left hot corner to enable the overview mode in Gnome. Without the sensitivity, it's enough to move it once.

This appeared after the last update. Using the latest version on Ubuntu 16.10 (mostly Gnome 3.20).

**Comment by Leeo97one** [comment]
I've exactly the same problem.

Extension version: 56
Gnome Shell version: 3.22.3
Linux distribution and version: Linux leeo-arch-pc 4.10.3-1-ARCH #1 SMP PREEMPT Wed Mar 15 09:17:17 CET 2017 x86_64 GNU/Linux
Multi-monitor configuration : 1 monitor
Settings:
```
[leeo@leeo-arch-pc ~]$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
animate-show-apps=false
shift-click-action='minimize'
shift-middle-click-action='quit'
extend-height=false
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
click-action='cycle-windows'
show-delay=0.10000000000000002
animation-time=0.10000000000000002
scroll-action='switch-workspace'
hide-delay=0.49999999999999961
autohide=true
apply-custom-theme=true
require-pressure-to-show=true
dock-position='LEFT'
height-fraction=0.90000000000000002
preferred-monitor=0
dash-max-icon-size=64
middle-click-action='launch'
isolate-workspaces=true
```

**Comment by micheleg** [comment]
I think  this issue was fixed in master [0f2fa2fd05a2b], could you have a look at it? The fix will be included in the upcoming release.

**Comment by Leeo97one** [comment]
Yeah, it works! Thanks.

**Comment by Leeo97one** [comment]
Yes, it works for me ;-)
