### ISSUE TITLE
Settings UI Cuts off Vertically

### ISSUE THREAD

**Issue by redvimo** [micheleg/dash-to-dock#452]
Hi, micheleg. I am Vimalan.
The Settings GUI for the dash-to-dock extension get's cut off the screen vertically, as visible in the screenshot attached. I think maybe a ScrolledWindow would solve this?
Thanks.
![screenshot from 2017-03-16 09-26-20](https://cloud.githubusercontent.com/assets/16490763/23986012/b19d5d4a-0a2a-11e7-8575-2099c4d0e445.png)

**Comment by redvimo** [comment]
I forgot to mention I am using Ubuntu Gnome 16.10. I installed the extension via the gnome extension website.

**Comment by franglais125** [comment]
This is somewhat improved by [73f5c14796cbda8c524cb1c3b60825cb70064141], where the settings are reordered and the window then fits in a 1366x768 screen.
When the next version comes out, hopefully it will include this, as the change is already in master.

**Comment by redvimo** [comment]
Ok thanks. By master, you mean installing from the latest git rather than gnome extensions?

**Comment by franglais125** [comment]
Well, yes, if you install from git master you'll get the fix, but I wasn't suggesting that you did that :)

Give it a try if you are willing to!

```
git clone https://github.com/micheleg/dash-to-dock
cd dash-to-dock
make && make install
```

Or  zip file: https://github.com/micheleg/dash-to-dock/archive/master.zip

**Comment by redvimo** [comment]
I will definitely try it out, and find more bugs. Im fiddling around with
gnome, got bored with xubuntu, and unity.
