### ISSUE TITLE
Number shortcuts

### ISSUE THREAD

**Issue by xionluhnis** [micheleg/dash-to-dock#46]
Hi,

on Ubuntu's left dock, there is a feature which I find quite useful: when pressing and holding <Super>, the icons in the dock each get a label (usually a number being the index of the icon from the top, except for the trash and some other special cases), and if the user press that label key before releasing <Super>, then it executes the corresponding application (and we can press several, executing several applications).

Would it be possible to implement that for dash-to-dock? In the case of auto-hide / intelli-hide, I guess we have to wait x-seconds, and then show it if the key trigger hasn't been released yet, so that we show the labels.

**Comment by micheleg** [comment]
I'm closing this issue as it is implemented and being refined in #360.
