### ISSUE TITLE
Hide dots feature stop working?

### ISSUE THREAD

**Issue by MartinPL** [micheleg/dash-to-dock#460]
Not sure if this feature works like this. But with that setup the dot should not be visible?
http://i.imgur.com/OJ2nY8B.png

**Comment by micheleg** [comment]
Which version? Are you sure the dots are not provided by the theme?

**Comment by MartinPL** [comment]
v57 from extensions.gnome.org, http://i.imgur.com/N9ERGVx.png

**Comment by micheleg** [comment]
From your last screenshot it seems the extension is working as expected. Those blue lines are provided by the default upstream dash, so when you disable the dots you are actually reverting to these defaults.
