### ISSUE TITLE
"Push to show" option in Autohide menu is broken

### ISSUE THREAD

**Issue by WizardOfTheWest** [micheleg/dash-to-dock#461]
The "Push to show" option in the Autohide menu currently does nothing, no matter what the threshold value is set to. Tested from both extensions.gnome.org and the AUR.

![push-to-show](https://cloud.githubusercontent.com/assets/20919064/24533968/55410538-1588-11e7-92d1-a66d1fea7126.png)

**Comment by micheleg** [comment]
Do you mean that the push to show option is enabled regardless of the settings or disabled regardless of the settings?

**Comment by WizardOfTheWest** [comment]
It's disabled regardless of the setting.

**Comment by micheleg** [comment]
Would you mind opening looking glass (```Alt+F2```, then execute the ```lg`` command) and see for this what the command ```global.display.supports_extended_barriers()``` return?

**Comment by WizardOfTheWest** [comment]
`global.display.supports_extended_barriers()` returned:

`r(0) = true`

**Comment by micheleg** [comment]
Do you have multliple screens? Would you mind providing your settings? You can print them with:

```dconf dump  /org/gnome/shell/extensions/dash-to-dock/```

in a terminal.

**Comment by WizardOfTheWest** [comment]
Only have the 1 screen, here are my settings:
```
scroll-switch-workspace=true
preferred-monitor=0
custom-theme-running-dots=true
height-fraction=1.0
show-windows-preview=true
show-running=true
require-pressure-to-show=true
pressure-threshold=100.0
show-show-apps-button=true
shortcut=['<Super>q']
middle-click-action='launch'
custom-theme-running-dots-border-width=0
show-favorites=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
opaque-background=true
shift-click-action='minimize'
minimize-shift=false
scroll-action='cycle-windows'
background-opacity=1.0
autohide=true
show-apps-at-top=false
isolate-workspaces=false
shift-middle-click-action='launch'
dock-fixed=false
autohide-in-fullscreen=false
custom-theme-customize-running-dots=true
click-action='minimize'
extend-height=true
custom-theme-running-dots-color='#729fcf'
dash-max-icon-size=48
apply-custom-theme=true
animate-show-apps=true
custom-theme-running-dots-border-color='#ffffff'
custom-theme-shrink=true
dock-position='RIGHT'
icon-size-fixed=false
```

**Comment by WizardOfTheWest** [comment]
I COMPLETELY FORGOT to mention, this only happens when the dock is on the right.
Top, Left, Bottom, all work except for Right.

**Comment by micheleg** [comment]
Oh, yes, I can reproduce the bug.

**Comment by micheleg** [comment]
It should be fixed now by 85f6b8bcbd2a6ce5d9. Can you double check?

**Comment by WizardOfTheWest** [comment]
Can confirm 85f6b8bcbd2a6ce5d975cec234e7206a53bbb4cf fixed it.

**Comment by micheleg** [comment]
Perfect. Thank you for spotting and reporting the bug.
