### ISSUE TITLE
Dock does not reserve space in dual head setup.

### ISSUE THREAD

**Issue by c4software** [micheleg/dash-to-dock#47]
Hi,

In one head setup when you expand the dock its reserve space to not overlap window behind it. But in my case.

Two monitor (with the Nvidia proprietary driver) its seems not working.

==> If i setup the dock to be exanded on the second monitor its working.
==> If i setup the dock on the main/principal monitor the space is not reserved.

![Capture du 2012-12-26 08:25:13](https://f.cloud.github.com/assets/988914/30868/9027a1e6-4f2d-11e2-9a08-f5f1fa1824d3.png)

**Comment by micheleg** [comment]
I'm not sure, but the situation should be improved since gnome 3.14. Can anybody confirm?

**Comment by MatejSpindler** [comment]
@micheleg 
I just tested Dash to dock and yes it is reserving space in the middle between two monitors.

**Comment by micheleg** [comment]
Perfect.
