### ISSUE TITLE
dash-to-dock used with hide-top-bar

### ISSUE THREAD

**Issue by mnwstl** [micheleg/dash-to-dock#473]
Hello! I started using dash-to-dock, but I already used hide-top-bar. I observed two situations:
1 - With maximized applications everything works fine. (Fig.01)
2 - Without maximizing, the top bar overlaps the first icon. (Fig.02)
I do not know if the icons are set below the top bar.
Tanks!

![01](https://cloud.githubusercontent.com/assets/22776404/25024890/3d0c7ac6-2076-11e7-983c-3e3779d114dd.png)
![02](https://cloud.githubusercontent.com/assets/22776404/25024915/4efd8658-2076-11e7-9b0c-6a326bf8975c.png)

**Comment by micheleg** [comment]
Hi, this sort of issues are almost unavoidable as extensions are free to change everything in the shell. Given the authohide applied to the panel, dash-to-dock is acting effectively as if the panel was not there.

Let's pretend we have complete reciprocal awareness of the panel/dock status (not easy). What would  be the desirable behaviour?
 
* Sliding up/dock the dock
* Adding a padding to the dock
* adding a padding to the panel
* something else

*

**Comment by mnwstl** [comment]
Hi! I moved in some configurations of the two extensions and now I can hide the panel even with the windows not maximized. I thought it was good! Dash-to-dock is a very useful extension!

![03pic](https://cloud.githubusercontent.com/assets/22776404/25072833/09ce7aac-22af-11e7-811e-9cea2789bcb3.png)

**Comment by alanlivio** [comment]
I also have the same problem.
@mnwstl, how do you fix it?

![screenshot from 2017-08-26 11-40-35](https://user-images.githubusercontent.com/604808/29742327-8c804096-8a53-11e7-8984-ee8021458d3c.png)
