### ISSUE TITLE
Add new apps to dash

### ISSUE THREAD

**Issue by jrock2004** [micheleg/dash-to-dock#477]
Ok, so I know you can add favorites and show favorites in dash to dock, but is this the way to add new icons to the dash? I would think favorites would have different functionality. Thanks for the help

**Comment by micheleg** [comment]
Hi John, 
what do you mean by adding a new icon? What sort of thing that is not an application would you like to add?

**Comment by Austint30** [comment]
You can add applications to the dock by clicking the show applications button (the grid icon thingy) on the dock or go to activities > show applications button. You will be looking at a grid of all of the applications you have installed, find the application you want to pin and click and drag it to the dock. It's as simple as that. If your application is already running, you can also right click the application icon and click "Add to Favorites".
