### ISSUE TITLE
Feature request: show dash on multiple monitors?

### ISSUE THREAD

**Issue by jessedubord** [micheleg/dash-to-dock#484]
Would be a nice optional feature in future releases to be able to show the dash on multiple monitors, at the same time (not just on one monitor or the other). Maybe in the "Show the dock on" dropdown box, there's an option for "Both" or "All" that will put the dash on all monitors?

That way, the user wouldn't have to move the mouse all the way to the left side of the first monitor if they're working in the right monitor.

Just a thought for consideration. The extension rocks! Thanks.

**Comment by franglais125** [comment]
This is already in the works, and hopefully will be merged soon!

Issue: https://github.com/micheleg/dash-to-dock/issues/37
PR: https://github.com/micheleg/dash-to-dock/pull/457

:)

**Comment by micheleg** [comment]
Yes, hopefully I'll merge it by the end of this week. Closing this issue as duplicate.
