### ISSUE TITLE
The extenstion wont be removed and the docks are not dissapearing

### ISSUE THREAD

**Issue by snirlugassy** [micheleg/dash-to-dock#491]
![screenshot from 2017-04-28 21-47-11](https://cloud.githubusercontent.com/assets/21089538/25542747/7bbfd280-2c5c-11e7-8e64-a0e1d9ef7438.png)

And this is after the 'remove' from the GNOME teack > extantions > remove

**Comment by micheleg** [comment]
This can happen if there's a bug and the extension crashes before cleaning up the system. Can you reproduce the bug or did it happen only once?

**Comment by snirlugassy** [comment]
Solved after a re-install and a restart. 
Thank you!
