### ISSUE TITLE
gnome-shell crash with dash-to-dock with dual monitors

### ISSUE THREAD

**Issue by colinl** [micheleg/dash-to-dock#493]
Using Ubuntu 17.04 on a laptop with an external display on its right hand side all is well with dash-to-dock provided the laptop display is set to the primary display. However if I set the external display to be the primary display (with dash-to-dock disabled) then as soon as I enable it gnome-shell crashes and I am logged off. See attached excerpt from syslog. I have to remove .local/share/gnome-shell in order to recover the situation.
I think it may be associated with particular settings in dash-to-dock as I think initially it was ok, till I adjusted some settings, but not certain about that. I am not sure how to set the settings back to default in order to test this.
[gnome-shell-crash.txt](https://github.com/micheleg/dash-to-dock/files/966086/gnome-shell-crash.txt)

**Comment by micheleg** [comment]
Hi,

can you confirm the bug is reproducible (even after full shell reload) and without other extensions loaded?

**Comment by colinl** [comment]
I can confirm that it is reproducible every time, I have not other extensions loaded. Not sure what you mean by a full shell reload. If I power cycle and try to logon then gnome-shell crashes in the same manner and I get logged off again.
Further info, I have determined that I can put the dash on the second display by selecting that in the dash-to-dock (rather than switching primary/secondary settings in system settings) and it works perfectly.

**Comment by colinl** [comment]
However I note that if I enable the extension on the primary monitor with the primary monitor being the laptop display, then change the system settings so the primary monitor is the external display then dash-to-dock initially works ok on the external monitor. It is not till I logout and in or disable and enable the extension that it crashes.

**Comment by franglais125** [comment]
@colinl what version of dash-to-dock are you using?

I'll try and see if I can reproduce it.

**Comment by colinl** [comment]
Thanks Fran, it is version 57.
Colin

**Comment by franglais125** [comment]
@colinl I've been trying to reproduce it on two monitors, but I still can't.

Can I ask you to try the two following things?
1. Check if the current git master works well for you. There were a number of changes to how monitors are handled.
2. Can you post the output of `dconf dump /org/gnome/shell/extensions/dash-to-dock/` ?

**Comment by colinl** [comment]
To try the latest from git do I just copy the files over the top of the existing ones?

dconf dump gives:
[/]
animate-show-apps=false
show-apps-at-top=true
extend-height=true
dock-fixed=true
force-straight-corner=false
scroll-action='cycle-windows'
custom-theme-running-dots=true
height-fraction=0.72999999999999998
custom-theme-shrink=true
preferred-monitor=0
dash-max-icon-size=32
opaque-background=false
shortcut=['<Super>q']

**Comment by franglais125** [comment]
To install current master:
```
git clone https://github.com/micheleg/dash-to-dock/
cd dash-to-dock/
make && make install
```

And then log out and log in, or restart the session (Alt+F2 and "r")

**Comment by colinl** [comment]
Before trying the current master I determined that with Intelligent autohide On it does not fail.
Unfortunately I probably have not time now to try master, will try that tomorrow.

**Comment by colinl** [comment]
I managed to find time and can confirm that it still fails with master, but again only if intelligent autohide is Off.

**Comment by micheleg** [comment]
I can't reproduce this either. I need some other information that can help: 
* GNOME Shell version
* X11 or Wayland?
* your screen resolution and arrangement (i.e., if the resolution are different, how they are aligned)

**Comment by colinl** [comment]
Gnome shell version is 3.24
X11
Laptop is 1366x768, External monitor 1280x1024
Arranged with laptop on left, top aligned

**Comment by colinl** [comment]
If I set the vertical resolution so the displays are both 768 high then the problem does not appear.

**Comment by micheleg** [comment]
Thanks for the additional information. I still can't reproduce the bug though. I'll try to get 3.24 running.

**Comment by colinl** [comment]
I have some s/w knowledge (though not specifically with gnome-shell extensions), if there is anything I can do to help debug it then let me know.

**Comment by colinl** [comment]
Another snippet of info, I have to have Extend to Screen Edge set to make it fail. I have the dock on the left hand side.

**Comment by franglais125** [comment]
Ok... So I installed a clean Ubuntu 17.04 and can finally reproduce your bug.

Here is an error log: https://gist.github.com/franglais125/f6e01d9580cd5f522148e88894980b26

I'll try to debug this. Let's see how it goes.

@micheleg due to the newer Gjs, dash-to-dock is spitting new warnings. I can submit a patch for this as well.

**Comment by colinl** [comment]
@franglais125 great, thanks again for looking into this.

**Comment by micheleg** [comment]
Thanks for looking into this.

**Comment by franglais125** [comment]
@colinl Today there were a bunch of updates on ubuntu 17.04, including gnome shell, mutter, gnome-control-center, etc.

Since I updated these packages, I can't reproduce the issue anymore (I tried for over 20 minutes thinking I had changed something, and then remembered the updates). Perhaps an upstream fix made the issue go away.

Can you try and see if the bug is still present? Update your packages and reboot before trying of course :).

```
sudo apt update
sudo apt upgrade
```

**Comment by colinl** [comment]
Sadly the updates have not helped here.
I picked up the updates (including gnome-shell etc) and, full of hope, rebooted and restored the options that seem to cause the crash (Intelligent Autohide Off, Extend to screen edge On) and disabled/enabled the extension and it crashed again. Tried rebooting again with the options still set and it crashed on login as previously.

**Comment by colinl** [comment]
I don't think I said previously but this is actually an install of standard Ubuntu with gnome shell added using
sudo apt install ubuntu-gnome-desktop^
though since you did manage to replicate it I presume that is not an issue.

**Comment by franglais125** [comment]
Ugh, too bad it isn't fixed. I'm traveling now, but I'll get back to this next week.

**Comment by colinl** [comment]
I don't know whether this is a clue but I notice that with autohide Off and also extend Off (which does not crash) that if I have Tweak Tool on the external monitor and switch the extension off and on that the screen flashes oddly before showing the correct display. I think it is drawing the tweak too window on the internal monitor then moving it back to the correct one. Also the dash 'bounces' as it is drawn in a way that it does not if Autohide is ON.  Probably not useful but I thought I should mention it just in case.

**Comment by franglais125** [comment]
I've traced this to a problem with the monitor areas.

When `_resetPosition()` is called, sometimes the width and height are negative.
`let workArea = Main.layoutManager.getWorkAreaForMonitor(this._monitorIndex);`

I've printed the height and width in a log:
```
May 10 19:16:32 franglais125-Vostro-V131 gnome-shell[28412]:  ## N Monitors: 2
May 10 19:16:32 franglais125-Vostro-V131 gnome-shell[28412]:  ## Monitor Index : 0
May 10 19:16:32 franglais125-Vostro-V131 gnome-shell[28412]:  ## WIDTH : -1
May 10 19:16:32 franglais125-Vostro-V131 gnome-shell[28412]:  ## HEIGHT: -1
May 10 19:16:32 franglais125-Vostro-V131 gnome-shell[28412]:  ## X : 1024
May 10 19:16:32 franglais125-Vostro-V131 gnome-shell[28412]:  ## Y: 0
```

I'll try to investigate more, but this is rather time consuming, as dealing with shell crashes is not so nice...
- This seems to happen when the external monitor has a width smaller than the primary monitor, but a height larger than the primary monitor.
- I suspect that something like `workareas-changed` has to be dealt with more care.
- Under Wayland, the same problem arises but the system recovers successfully.

@micheleg any thoughts?

**Comment by micheleg** [comment]
Thanks for your investigation. As it happens with intellihide off and the extended mode on, I'm wondering if we are interfering with the workarea calculation, as the dock itself becomes part of the chrome to be not considered as part of the workarea.

Is it the size of the workarea which is returned as size of -1 directly?

What system did you manage to reproduce the bug in?

**Comment by franglais125** [comment]
The size of `workArea.width` and `workArea.height` are returned as `-1` directly. These two values are used in many calculations, so it's understandable that the shell is crashing.

For reproducing this I installed Ubuntu 17.04 on an external disk. Here is the info:
- Using dash-to-dock from master
- Ubuntu 17.04, so Gnome Shell 3.24
- Laptop with 1366x768, external with 1024x768
- Laptop is the primary monitor
- Dock on laptop

I'll keep testing to see if I can pinpoint the origin of the problem.

**Comment by franglais125** [comment]
@micheleg some more info:

I've found that this line [https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L1072] is for some reason misbehaving. I don't think it's the assignment of `this.actor.x = pos_x;` itself, but how this is interpreted somewhere else in the code.

My external monitor is set to 1024x768. If I manually set `this.actor.x = 0` or `this.actor.x = 1023` or `this.actor.x = 1025`, I don't see any errors (of course the rendering is then off). But there is something specific about setting it to `this.actor.x = 1024`.

Any idea of what it could be?

@colinl I've uploaded a workaround (not a fix) to this branch https://github.com/franglais125/dash-to-dock/tree/gnome_3.24. Can you try if it is usable on your setup? All I'm doing is not calling `_resetPosition()` when enabling.

**Comment by franglais125** [comment]
Another way to avoid the crash is to reduce the `actor.height` by 1 (or simply setting to any other number) in line https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L1076. But again, this is not a fix, simply a symptom.

example:
`this.dash._container.set_height(this.actor.height - 1);`

or
`this.dash._container.set_height(600);`

**Comment by colinl** [comment]
@franglais125 your gnome_3.24 branch has stopped it crashing for me too.

**Comment by colinl** [comment]
Is this still awaiting a fix? I am still using the workaround at https://github.com/franglais125/dash-to-dock/tree/gnome_3.24 but would like to revert to the standard version when possible.

**Comment by franglais125** [comment]
@colinl this hasn't been fixed. My main system runs Debian Stretch, so I'm stuck on Gnome 3.22, where the bug doesn't happen.

I sometimes log in to 3.24 (Ubuntu), and try to do some debugging, but that's very sporadic., sorry.

Meanwhile, I have just updated the branch to include the latest work from master, so you are at least closer to upstream...

**Comment by colinl** [comment]
OK, many thanks.
Keep up the good work on this very useful extension.

**Comment by colinl** [comment]
I have just updated the branch using git pull and it says there are merge conflicts, which I don't understand, probably down to my lack of knowledge on git.  I had not committed any changes locally.

colinl@tigger:~/temp/dash-to-dock-franglais$ git status
On branch gnome_3.24
Your branch is up-to-date with 'origin/gnome_3.24'.
nothing to commit, working tree clean

colinl@tigger:~/temp/dash-to-dock-franglais$ git pull
remote: Counting objects: 375, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 375 (delta 161), reused 163 (delta 160), pack-reused 210
Receiving objects: 100% (375/375), 191.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (257/257), completed with 34 local objects.
From https://github.com/franglais125/dash-to-dock
 + 25266ec...f16df5a gnome_3.24                -> origin/gnome_3.24  (forced update)
 * [new branch]      favs_on_main              -> origin/favs_on_main
 + bc920e4...058e97d master                    -> origin/master  (forced update)
 + f80f92f...b3d03c4 monitor_isolation         -> origin/monitor_isolation  (forced update)
 + 115e5d3...59aac6e right_click_menu_squashed -> origin/right_click_menu_squashed  (forced update)
 * [new branch]      string_format             -> origin/string_format
 * [new branch]      transparency              -> origin/transparency
 * [new branch]      unity7                    -> origin/unity7
 * [new branch]      unity7_rebased            -> origin/unity7_rebased
Auto-merging docking.js
Auto-merging dash.js
CONFLICT (content): Merge conflict in dash.js
Automatic merge failed; fix conflicts and then commit the result.

The conflict is
@@@ -635,7 -635,7 +635,11 @@@ const MyDash = new Lang.Class(
          let firstButton = iconChildren[0].child;
          let firstIcon = firstButton._delegate.icon;
  
++<<<<<<< HEAD
 +        let natHeight, natWidth;
++=======
+         let minHeight, natHeight, minWidth, natWidth;
++>>>>>>> f16df5a1751ec87c63e54e3302a238e10e352461
  
          // Enforce the current icon size during the size request
          firstIcon.setIconSize(this.iconSize);
@@@ -778,7 -780,7 +784,11 @@@
          let oldIndex = 0;
          while ((newIndex < newApps.length) || (oldIndex < oldApps.length)) {
              // No change at oldIndex/newIndex
++<<<<<<< HEAD
 +            if (oldApps.length > oldIndex && oldApps[oldIndex] == newApps[newIndex]) {
++=======
+             if (oldApps[oldIndex] && oldApps[oldIndex] == newApps[newIndex]) {
++>>>>>>> f16df5a1751ec87c63e54e3302a238e10e352461
                  oldIndex++;


Should I just chuck it and re-clone from  https://github.com/franglais125/dash-to-dock/tree/gnome_3.24?

**Comment by franglais125** [comment]
The reason is I had included some fixes for run time warnings, which were included in the master branch eventually. Upon rebasing, I removed those fixes.

If you don't know your way around git, then sure, you can clone from scratch.

**Comment by colinl** [comment]
OK, thanks

**Comment by colinl** [comment]
For info I have installed Ubuntu Artful daily iso on another laptop. This installs what I assume is a tweaked version of dash-to-dock, ubuntu-dock. This also shows the problem, even though I am using Wayland. I have reported a bug against ubuntu-dock, cross referencing this issue from there.
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1712661

**Comment by micheleg** [comment]
@franglais125 : can you point me at the "fix"? Is it just this  https://github.com/franglais125/dash-to-dock/commit/f16df5a1751ec87c63e54e3302a238e10e352461?

**Comment by franglais125** [comment]
@micheleg indeed, the "fix" is simply removing the manual `_resetPosition()` call, which is not really a fix I'd say. I don't remember exactly, but I think removing this line was causing the dock not to be displayed correctly, at least until there is something else triggers a call to `_resetPosition()`.

In the case of multi-monitor setups (as is the case for @colinl ), it seems that `workareas-changed` is emitted a few times, and hence the dock is correctly positioned in the end.

Perhaps we can conditionally call `resetPosition`, depending on the number of monitors? In any case, as I mentioned before, I don't know exactly what the cause of the bug is, but some things are weird for sure (with some sizes being `-1`, etc.).

**Comment by micheleg** [comment]
Wasn't the issue due to some negative size returned? Can't we filter out those cases instead? Stil a workaround but at least it should not have negative effects.

**Comment by franglais125** [comment]
Yes, I remember getting negative sizes, but (AFAIR) filtering out those cases was still not enough - I can't remember if it would still crash, or if some other problem would arise.

I'll have to get back to trying that and test it. I can't remember why, but when I tried doing that it didn't really work for me.

Sorry I can't provide more info now, as I'm traveling, so I don't have a second monitor to reproduce this.

**Comment by Alexander-Serov** [comment]
Confirm the same bug on my dual monitor setup with Ubuntu Gnome 16 LTS.

**Comment by franglais125** [comment]
@Alexander-Serov from what I recall, this was only a problem with Gnome 3.24 and later. Can you provide relevant info from the logs?

```
sudo journalctl /usr/bin/gnome-shell
```

**Comment by franglais125** [comment]
@colinl By the way, could you try this branch https://github.com/franglais125/dash-to-dock/tree/fix_maximize_unlock ?

It's not a fix intended for this issue, but I'm changing a bit the initialization process, which might help with this crash. Thanks!

**Comment by colinl** [comment]
@franglais125 no the fix_maximise_unlock branch does not help, it still crashes in the same way.

**Comment by franglais125** [comment]
@micheleg I tried again to have a look at this issue, but it's really hard to track the source of the problem.

Here is a branch with a "fix" for some problem I haven't found the source of: https://github.com/franglais125/dash-to-dock/tree/fix_init_crash. @colinl can you test this branch?

I'll try to give as much information as I can for this crash:

- The problem occurs with an external monitor attached, using both monitors.
- If the dock is on the LEFT, I can only reproduce this when the dock is on the monitor with the smaller height.
- My guess is that at the initialization stage, the various objects are not assigned the proper values at all times (by some manual logging I found the maximum height to vary a lot, from 50px to the maximum height allowed in my monitor, 800px).

Again, removing the `_resetPosition()` call avoids the problem. Here is the code flow as far as I could see:
1. The Shell initializes
2. `_resetPosition` is called, which sets: `this.dash._container.set_height(this.actor.height)`
3. This call triggers some restructuring, as there is a new object constraining the size, and it is within this new restructuring that the errors are triggered.
4. Since a `workareas-changed` signal is emitted, we return to `resetPosition`, where we finally see that the workarea is nonsense, with negative values, but at this point even if we `return;` on negative values, the errors are ensuing.
5. Shell crash.

Using straight from the termina `gnome-shell --replace` instead of looking at the logs I could get some more information, here are some new errors I wasn't seeing before:
```
Window manager warning: Region to merge was empty!  Either you have a some pathological STRUT list or there's a bug somewhere!
Window manager warning: Region to merge was empty!  Either you have a some pathological STRUT list or there's a bug somewhere!
Clutter-WARNING **: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00
GLib-GObject-WARNING **: value "-1.000000" of type 'gfloat' is invalid or out of range for property 'height' of type 'gfloat'
```

and then a long repetition of `Clutter-WARNING **: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00`.


In the end, this makes me think that there might be a problem with the LayoutManager not properly checking for all the objects' sizes and so on, but it becomes really hard to debug, especially since I don't know what `StWidget` has the negative size.

Any thoughts?

**Comment by micheleg** [comment]
Thanks a lot for the debugging. So we are causing the bug by merely registering out actor for struts tracking, when we change its size. A couple of quick thoughts:

* can it have something to do with the way we play with the tracking system, i.e. the fact that we track certain actor but not their parent (use ```Main.layoutManager._trackActor()``` directly instead of Main.layoutManager.addChrome()```)? 

* can it have something to do with the constraint machinery (https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L279)? This is something we inherited from the original dash, and which I  never managed to get rid off.

**Comment by franglais125** [comment]
Thanks for the feedback, appreciated.

> So we are causing the bug by merely registering out actor for struts tracking, when we change its size

Exactly!

> - can it have something to do with the way we play with the tracking system, i.e. the fact that we track certain actor but not their parent (use Main.layoutManager._trackActor() directly instead of Main.layoutManager.addChrome()```)?

If I use `Main.layoutManager._trackActor(this._slider.actor, {affectsStruts: false});`, note the use of `false`, the errors go away, which is in accordance to what I was describing before.
Quickly trying to use `addChrome` instead of `_trackActor` is not fixing the problem for me, but I'll keep trying.

> - can it have something to do with the constraint machinery (https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L279)? This is something we inherited from the original dash, and which I never managed to get rid off.

I tried removing this entirely and the problem persists, so I guess this is not the cause.

----------------------------------------------
Another thing that seems to work for me is moving `resetPosition` to the _initialize()` function, which is called when the actor is ready to be painted. In nature, this is very similar to the `Mainloop.add_idle` fix.

**Comment by franglais125** [comment]
Just a side note: Using `Mainloop.add_idle` I noticed that a few things are smoother. For instance, I now get a nice animation when I change the dock position (e.g. from bottom to left), I had never seen this before. Just a nice touch.

**Comment by franglais125** [comment]
@micheleg wrt the previous "fixes" (delaying the `resetPosition` call), they are actually rather incomplete. While it works upon initialization of the Shell, the errors still appear when e.g. changing the dock position.

While testing, I noticed that the dock as a whole would flicker and 'migrate' screens. This led me to believe that perhaps the `Main.layoutManager` is not finding the correct monitor for the actor when executing `_updateRegions()`. Here is the function that I think is misbehaving: https://github.com/GNOME/gnome-shell/blob/master/js/ui/layout.js#L919

I tried adding a small quantity to `this.actor.x` to make sure the actor is in the appropriate monitor, and this finally seems to fix all errors for me. You can find the new commit in the updated branch: https://github.com/franglais125/dash-to-dock/tree/fix_init_crash [36bf7fe2ba5f9cbe6c938f54ec656ccdfab8e7c1]. The second commit there is only a corollary,

What do you think?

**Comment by micheleg** [comment]
Not a fan of the proposed workaround: for instance, are we sure the values gets rounded? But it seems we are close to the solution. I was trying to reproduce the bug, in a virtual machine to simulate the presence of two screens. I tried with an Ubuntu 17.10 vm (G.S 3.26), but I couldn't reproduce it.  I set the left/primaty scren to a resolution smaller the the secondary one, dock on left, disabled intellihide. Do you know if the bug is also affecting 3.26?

**Comment by franglais125** [comment]
It is reproducible in Gnome 3.26 and 3.24 AFAIK (I also tested this with the unstable package from Debian sid).

I'm on my phone now, but here is what I remember from my setup to reproduce this (I can reproduce it 100% of the times once I can get the right combination):

- laptop on the left, external monitor on the right
- laptop: 1366x768
- external: 1280x800 and set to primary (hence with the top panel).
- dock placed on the left of the external monitor (so at the edge of both screens)
- happens on both xorg and wayland

Now simply restart the session or change the dock's position.

In the past I also tried to reproduce this in a VM but never managed to, so perhaps it's better if you stick to hardware.

**Comment by franglais125** [comment]
Btw, I was trusting `_updateRegions` with the rounding as there is some rounding happening, I'll double check later!

**Comment by Alexander-Serov** [comment]
@franglais125 Sorry, the logs were empty

**Comment by Alexander-Serov** [comment]
As for the crash, in my case it does not crash completely, but loses all the icons, son only the 9 white dots are left. If I could right-click the dots and choose something like "re-initialize dash-to-dock", that would be pretty much a workaround for me. 

Unfortunately, I cannot comment on reproducibility of the bug, because for me it happens somewhat randomly. More often however when I hot-plug in an extra screen or on the moment, when the screen get unlocked. Hope this helps at least a bit.

**Comment by franglais125** [comment]
@Alexander-Serov would you mind perhaps opening a new issue with the following:
- description
- OS version (Ubuntu 16.04 I guess)
- dash-to-dock version, other extensions that might conflict?
- whenever you find the problem again, perhaps a screenshot if the logs are empty...

**Comment by Alexander-Serov** [comment]
@franglais125 Sure, I will open a new issue then the next time the bug reproduces. Thanks!

**Comment by franglais125** [comment]
@micheleg I can now confirm the conditions I listed before, but I add one more:

- The two screens have to be aligned at the top.

My guess is that this somehow confuses the `findIndexForActor` function.

**Comment by franglais125** [comment]
@micheleg Here is a debug branch: https://github.com/franglais125/dash-to-dock/tree/debug_crash

In that branch, I'm injecting `findIndexForActor()`. What we can see is the position and size of the `_slider.actor` just before the `layoutManager` tries to find the monitor for it. It seems that in some situations, the positions and dimensions are very slightly displaced (1 part in 2^14, oddly specific). Upon initialization of the `_slider` object, its width is zero. The slightest displacement hence places the dock on a different monitor.

I can't reproduce this problem at all resolutions, so this is perhaps a bug upstream that has to do with dimensions of screens, etc.

As an example, here is my output for the above branch (**monitor migration**!):
```
gnome-shell: x,y:  1365.9998779296875, 0.00006103515625
gnome-shell: w,h:  0, 799.9998779296875
gnome-shell: iMon: 0
org.gnome.Sesktop[1339]: Window manager warning: Region to merge was empty!  Either you have a some pathological STRUT list or there's a bug somewhere!
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00 
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00 
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00
gnome-shell: clutter-actor.c:10050: Actor 'StWidget' tried to allocate a size of -1.00 x -1.00
gnome-shell: x,y:  1365.9998779296875, 0.00006103515625
gnome-shell: w,h:  51.0001220703125, 799.9998779296875
gnome-shell: iMon: 1
gnome-shell: x,y:  1365.9998779296875, 27.00006103515625
gnome-shell: w,h:  51.0001220703125, 772.9998779296875
gnome-shell: iMon: 1
```

Normally the position should be (I see round numbers with other resolutions):
- x: 1366
- y: 0 or 27 (when the top panel is added)

If we could initialize (or assign at some point) the `_slider` with some width, this problem could be averted, as even if the position is slightly off, the rectangle will overflow into the right screen... Or, any other ideas?

**Comment by morozsm** [comment]
The issue is also reproducible on Fedora 27 Beta, Gnome 3.26 wayland.

**Comment by franglais125** [comment]
@morozsm Just to be sure that it is the same issue, could you provide part of the output of `sudo journalctl /usr/bin/gnome-shell` when the error occurs?

**Comment by micheleg** [comment]
I'm thinking, should we round the positions (and maybe also the returned preferred/natural width.height) in the implementation of DashSlideContainer? I cannot reproduce the bug, can anybody give a try to:

https://github.com/micheleg/dash-to-dock/tree/experimental_dashslider_round

**Comment by colinl** [comment]
@micheleg in order to try the experimental_dashslider_round branch I first tried the master and I can't get it to fail at all (with up to date Ubuntu 17.10) so whether something else has changed (I have recently upgraded to 17.10 from 17.04) I don't know.
I am not entirely sure whether I am using Wayland or not, I see:
$ echo $XDG_SESSION_TYPE
x11
$ echo $DESKTOP_SESSION
ubuntu
Gnome is 3.26.1

**Comment by stronnag** [comment]
Another data point. User of dash to dock since forever. When Arch introduced Gnome 3.26  the desktop crashed frequently. As a last resort, replacing dash to dock with plank restored complete desktop stability:

* Dual monitors (1920x1080 main ; 1280x124 secondary)
* Intel graphics
* Arch (testing enabled)
* Happens on both Xorg and Wayland; at least Xorg would usually (but not always) preserve the session
* Occurs with `experimental_dashslider_round` as well.

I can reliably crash the shell via dash to dock active by exposing the dock's expanded area (I have intellihide enabled), .e.g. opening a window that would cover the expanded dock area, or minimising a maximised window; in the latter case, a crash will result about 1 time in 4.

**Comment by dodiak** [comment]
Hi folks,
any update here? I am suffering the same problem. Debian 9, Wayland, gnome-shell 3.22.3-3
thanks
Jozef

**Comment by vanvugt** [comment]
[Ubuntu 17.04 is no longer supported](https://wiki.ubuntu.com/Releases).

If you find any bugs in a current version of Ubuntu then please report them using the `ubuntu-bug` command.
