### ISSUE TITLE
Override default settings seem not work for all keys

### ISSUE THREAD

**Issue by Ste74** [micheleg/dash-to-dock#496]
Hi there , i have override this keys for Manjaro Gnome edition 
https://github.com/manjaro/manjaro-gnome-settings/blob/devel/schemas/99_manjaro-settings.gschema.override#L32
but seem not change all keys i changed .. is expected this behavior i.e. is need change the .xml schema into the /schemas folder ? 
I already change this for other extension but because this extension ( like gnomenu ) not provide a valide key to parse .. your extension provide the right keys :) 

thank you 
Stefano

**Comment by micheleg** [comment]
Closing as duplicate (as you found out).
