### ISSUE TITLE
Chrome - Dropdown menus don't work

### ISSUE THREAD

**Issue by mdahlke** [micheleg/dash-to-dock#497]
When Intelligent autohide is off and the position is set the "Bottom", dropdown menus (<select> elements) don't open properly in Chrome.

Chrome Version 58.0.3029.96 (64-bit)

**Comment by micheleg** [comment]
Hi, please define "not properly": is it a metter of position, visibility (overlapping) or what?

**Comment by mdahlke** [comment]
the <option> items didn't appear and it would float to the right. The dropdown would show, but the items were invisible. You could still use your arrows to navigate it.

Can't really help much more because I uninstalled the extension, sorry.

**Comment by micheleg** [comment]
I cannot reproduce this on my system. It would be nice if you could provide a screenshot, even if you are not directly using any more the extension.
