### ISSUE TITLE
Notification Count for Thunderbird

### ISSUE THREAD

**Issue by jdgwf** [micheleg/dash-to-dock#498]
Feature Request - I'm sure that many of us are moving from Ubuntu Unity to test the waters and are using your awesome work. I was wondering if you could add a Notification Count for Thunderbird, etc. (unread email messages).

**Comment by micheleg** [comment]
There was an initial implementation of this (#20). Have a look at that discussion. A stopping reason is that proper notifications count, that is with the app notifying what number to show, is not possible in GNOME without the ubuntu patches. That means for instance we could show the number of unread notifications from thunderbird, not the number of unread messages which is unknown to us. Closing as duplicate. Please follow #20 for further discussions.
