### ISSUE TITLE
[request] Hide active App when dock icon clicked

### ISSUE THREAD

**Issue by jdgwf** [micheleg/dash-to-dock#500]
Option to "hide" active window when Dock icon is pressed. Sorry for the issue request spam - just looking at usability.

**Comment by micheleg** [comment]
Hi, by "hide" do you mean "minimize"? If so this option is available already in the click actin settings.

**Comment by GNOME-IS-LIFE** [comment]
look at the settings page of the extension before creating an "Issue" *face palm*

**Comment by micheleg** [comment]
@GNOME-IS-LIFE: Please abstain from such pointless comments.

**Comment by jdgwf** [comment]
@micheleg - thank you! I didn't see that initially in the click behavior drop down
