### ISSUE TITLE
electron window won't show up when Dash to dock is enabled

### ISSUE THREAD

**Issue by sonnyp** [micheleg/dash-to-dock#502]
Step to reproduce:
- Enable Dash to dock
- Install electron
- Open a terminal and run `electron` (or https://github.com/electron/electron-quick-start#to-use)

Result:
The electron window won't show up.

Expected result:
The electron window shows up

Env:
- Arch Linux
- electron 1.4.16-2
- Gnome 3.24.1-1
- Dash to dock 57
- X11 or wayland

Weird, it works fine when Dash to dock is disabled.

**Comment by micheleg** [comment]
You mean that if you launch an application (electron) from the terminal  the windows doesn't show up because of dash to dock? This is very weird... 

Any error in the log?
```journalctl /usr/bin/gnome-shell```

**Comment by sonnyp** [comment]
Yes that's what I meant but cannot reproduce...
