### ISSUE TITLE
"Move the applications button at the beginning fo the dock" also moves the button up by a couple of pixels

### ISSUE THREAD

**Issue by Jazqa** [micheleg/dash-to-dock#503]

**Comment by micheleg** [comment]
I'm not sure I can identify the issue? Could you post a screenshot highlighting it? I this with the default theme or with a custom one, and with which extension settings?

**Comment by Jazqa** [comment]
This occurred with the vanilla theme and the arc-theme with "forced straight corner" -setting on Fedora 25 while I was trying to achieve a pixel-perfect dock with square icons. I can not replicate it on Debian even if I install the newest version of dash-to-dock so safe to say, something else was causing it.

It was a silly issue anyways, only noticeable if trying to achieve a pixel-perfect dock.
