### ISSUE TITLE
Icons dissappear on scroll

### ISSUE THREAD

**Issue by mutlucan96** [micheleg/dash-to-dock#505]
Hi.
If "fixed icon size: scroll to reveal other icons" setting is selected, scrolling on dash makes all icons disappear.

https://youtu.be/ktR_ji_yybs

**Comment by micheleg** [comment]
Thanks for the video. Would you mind checking for some errors in the log with:
```
journalctl -f /usr/bin/gnome-shell
```

**Comment by mutlucan96** [comment]
Here it is:
`May 24 11:13:11 LG-A520 gnome-shell[1219]: JS WARNING: [resource:///org/gnome/shell/ui/panel.js 342]: reference to undefined property this.menu.actionGroup
May 24 11:13:11 LG-A520 gnome-shell[1219]: JS WARNING: [resource:///org/gnome/shell/misc/ibusManager.js 196]: reference to undefined property this._engines[id]
May 24 11:13:11 LG-A520 gnome-shell[1219]: JS WARNING: [resource:///org/gnome/shell/ui/status/network.js 1897]: reference to undefined property this._mainConnectionStateChangedId
May 24 11:13:12 LG-A520 gnome-shell[1219]: JS WARNING: [/home/mutlu/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js 780]: reference to undefined property oldApps[oldIndex]
May 24 11:13:12 LG-A520 gnome-shell[1219]: JS WARNING: [/home/mutlu/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js 642]: assignment to undeclared variable minWidth
May 24 11:13:12 LG-A520 gnome-shell[1219]: GNOME Shell started at Wed May 24 2017 11:13:10 GMT+0300
May 24 11:13:22 LG-A520 gnome-shell[1219]: JS WARNING: [/home/mutlu/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js 124]: reference to undefined property this._focusAppId
May 24 11:13:24 LG-A520 gnome-shell[1219]: JS WARNING: [resource:///org/gnome/shell/ui/windowManager.js 1617]: reference to undefined property actor._windowType
May 24 11:13:30 LG-A520 gnome-shell[1219]: JS WARNING: [resource:///org/gnome/shell/ui/dash.js 760]: reference to undefined property oldApps[oldIndex]
May 24 11:13:30 LG-A520 gnome-shell[1219]: JS WARNING: [resource:///org/gnome/shell/ui/appDisplay.js 1298]: reference to undefined property this.name

`

This doesn't happen on yours? I tried with a fresh install but that happens anyway.

**Comment by micheleg** [comment]
No, I can't reproduce this bug on my system. Could you confirm which is your version number of gnome shell and the extension?

**Comment by mutlucan96** [comment]
GNOME Shell 3.24.1
Dash to Dock 57  (found in "about" tab of extension settings)

**Comment by mutlucan96** [comment]
I've updated the extension and the problem solved.
Thanks.
