### ISSUE TITLE
1px margin on the right of the dock

### ISSUE THREAD

**Issue by ktmn** [micheleg/dash-to-dock#508]
Sorry about whining about a pixel, but...

http://i.imgur.com/MhUi0kt.png

There is 1px space between maximized window and the dash. Is that by design?

The dash is positioned on the left, no autohide, in panel mode, extension version 57, Gnome shell 3.24.1, Ubuntu Gnome 17.04. Doesn't matter if using built-in theme or not. Also tried changing Gnome theme, but the behavior remained.

**Comment by micheleg** [comment]
I'm glad to see people reporting about a pixel, as it means all the others are working well!

That's not by design for sure.  I can't reproduce it on my machine (But I've tested it on 3.22 and 3.25). I understand that you tested both Shell and Gtk themes, right?

I think it's unlikely, but did you try disabling all other extensions (if any)? What are your settings? Jst copy the output of the command:
``` dconf dump  /org/gnome/shell/extensions/dash-to-dock/```

**Comment by ktmn** [comment]
> I understand that you tested both Shell and Gtk themes, right?

I didn't try changing the shell theme... and that was it! The gap is only there with the Paper shell theme and not with Default.

Here's the config anyway, just in case you need it

```
require-pressure-to-show=true
preferred-monitor=0
show-apps-at-top=true
show-windows-preview=true
extend-height=true
dock-fixed=true
force-straight-corner=false
click-action='minimize'
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
animation-time=0.15000000000000002
scroll-action='cycle-windows'
hide-delay=0.10000000000000002
custom-theme-customize-running-dots=false
pressure-threshold=150.0
apply-custom-theme=false
custom-theme-running-dots=true
dock-position='LEFT'
custom-theme-shrink=false
custom-theme-running-dots-border-width=1
height-fraction=0.90000000000000002
dash-max-icon-size=48
opaque-background=false
shortcut=['<Super>q']
icon-size-fixed=false
isolate-workspaces=true
```

I guess I will try to tinker with the Paper theme to fix it, thanks.
