### ISSUE TITLE
"Show on all monitors" does not work

### ISSUE THREAD

**Issue by f3flight** [micheleg/dash-to-dock#514]
Hi there,

"Show on all monitors" does not work for me - I've ticked it but the dock is still on one monitor only (I have 2), I can still move it via the monitor selection dropbox, so looks like at least for me the new checkbox does not change anything.

**Comment by micheleg** [comment]
Hi, can you confirm if you are using X or Wayland? Also, would you mind checking in the logs for relevant messages:
```journalctl -f /usr/bin/gnome-shell```

**Comment by f3flight** [comment]
Wayland.

It's actually started working after reboot! IN logs I have this when I disable or enable the tick:

Jun 05 15:13:41 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x4ca3ce0 Gjs_ShowAppsIcon.dash-item-container] connect method
Jun 05 15:13:41 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x4ca3ce0 Gjs_ShowAppsIcon.dash-item-container] disconnect method
Jun 05 15:13:41 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x4ca3ce0 Gjs_ShowAppsIcon.dash-item-container] emit method
Jun 05 15:13:43 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x581b840 Gjs_ShowAppsIcon.dash-item-container] connect method
Jun 05 15:13:43 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x581b840 Gjs_ShowAppsIcon.dash-item-container] disconnect method
Jun 05 15:13:43 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x581b840 Gjs_ShowAppsIcon.dash-item-container] emit method
Jun 05 15:13:43 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x63cf0d0 Gjs_ShowAppsIcon.dash-item-container] connect method
Jun 05 15:13:43 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x63cf0d0 Gjs_ShowAppsIcon.dash-item-container] disconnect method
Jun 05 15:13:43 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x63cf0d0 Gjs_ShowAppsIcon.dash-item-container] emit method

I guess we can close this one, seems functional for me now.

**Comment by micheleg** [comment]
Good. Is that warning error occurring even after rebooting the system?

**Comment by f3flight** [comment]
Yes, for me it shows up every time I tick or untick the checkbox (3 times for each panel/monitor?), and when I open settings window I get this:
Jun 05 16:52:18 pulsar gnome-shell[968]: setup_framebuffers: assertion 'width > 0' failed

so open of settings + untick + tick =:
: settings 
Jun 05 16:52:18 pulsar gnome-shell[968]: setup_framebuffers: assertion 'width > 0' failed
: untick
Jun 05 16:52:30 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x6c46c50 Gjs_ShowAppsIcon.dash-item-container] connect method
Jun 05 16:52:30 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x6c46c50 Gjs_ShowAppsIcon.dash-item-container] disconnect method
Jun 05 16:52:30 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x6c46c50 Gjs_ShowAppsIcon.dash-item-container] emit method
: tick back
Jun 05 16:53:47 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x739d250 Gjs_ShowAppsIcon.dash-item-container] connect method
Jun 05 16:53:47 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x739d250 Gjs_ShowAppsIcon.dash-item-container] disconnect method
Jun 05 16:53:47 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x739d250 Gjs_ShowAppsIcon.dash-item-container] emit method
Jun 05 16:53:47 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x6342440 Gjs_ShowAppsIcon.dash-item-container] connect method
Jun 05 16:53:47 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x6342440 Gjs_ShowAppsIcon.dash-item-container] disconnect method
Jun 05 16:53:47 pulsar gnome-shell[968]: WARNING: addSignalMethods is replacing existing [0x6342440 Gjs_ShowAppsIcon.dash-item-container] emit method

I'm using Arch Linux, and gdm & gnome-shell 3.24.2-1

**Comment by micheleg** [comment]
For the warning I have created #526.
