### ISSUE TITLE
Positioning, app button setting + contribution?

### ISSUE THREAD

**Issue by lefamz** [micheleg/dash-to-dock#52]
Hi,
I like this extension a lot. A moment ago I had an idea for update. First, I don't like the shortcut button for showing applications. It would be nice to have an option in settings for hiding this and let the user decide. Second, sometimes I'd like to have the extension on the right side of screen, because of the second monitor. So this option would be nice, too :)

Also I'm offering the contribution to this project. My name is Michal Zajacik, I hold bachelor degree in computer science. I'm pursuing msc degree in Artificial intelligence. Currently I'm visiting course of Opensource Programming. The goal is to teach us how to contribute to open projects and how to communicate with other developers. So I'd like you to offer my help. I have skills with Java (from school and work), C, C++ ... JavaScript just little, but I assume I would learn it easily. If you let me, I could do the adjustments by myself, help you with bug fixing or implementing any other functionality. I could provide also the knowledge of Czech language.

Feel free to contact me via mail michal@zajacik.eu !

Thanks for reply!
Michal

**Comment by micheleg** [comment]
Hiding of Show Applications button and right placed dock options were both implemented time ago, so I'm closing this issue.
