### ISSUE TITLE
Suggestion: Allow different colors and/or opacity for the dock theme when there is a window maximised or not

### ISSUE THREAD

**Issue by charlesmilette** [micheleg/dash-to-dock#520]
This way I could have a black dock background when I have a window maximised, and have the dock background fully transparent when it is not.

Kinda like activities configurator does.

**Comment by micheleg** [comment]
Hi, something being considered is an automatic transparency option #513, similar to how the top panel will behave in GNOME 3.26.

**Comment by charlesmilette** [comment]
As long as I'm able to edit the transparency values (as I don't like 20%, I prefer fully transparent) it would be fine for me.

**Comment by franglais125** [comment]
I don't mind making the value for the dynamic transparency a setting. Or doing something like: https://github.com/micheleg/dash-to-dock/pull/62.

Hence the dynamic nature of the transparency would be a simple checkbox.

@micheleg would that be better?

The way I had it set up was to follow the 20% from upstream, but making it tunable shouldn't be a problem.

**Comment by charlesmilette** [comment]
Yeah, kinda like #62.

> I found out, that it doesn't work when the session is locked and unlocked again. It probably has something to do with "theme changed" event. I will try to look at it.

Huh, same thing happens with activities manager.

-- 
Envoyé de mon Gmail

**Comment by franglais125** [comment]
@charlesmilette I have updated the PR with this request.

It respects the color (this was already the case) and the opacity selected by the user from the UI.

**Comment by charlesmilette** [comment]
Thank you! I'll be closing this issue now
