### ISSUE TITLE
[Multi Monitor] Show only selected monitor application on each dock

### ISSUE THREAD

**Issue by ItamarShDev** [micheleg/dash-to-dock#521]
Hey the @micheleg,
Multi monitor works great!
Is there any way of making each instance of the dash to show the apps of the appropriate screen?
![image](https://user-images.githubusercontent.com/953371/27117273-8ef79f94-50de-11e7-835c-d82679f83eda.png)
In the picture you can see that the docks are the same on both screen right now

**Comment by franglais125** [comment]
@ItamarShDev I have a working branch that isolates the monitors. You can find it here:
https://github.com/franglais125/dash-to-dock/tree/monitor_isolation.
You'll have to tick the option "Isolate monitors".

I'll open a PR soon, when the active ones are resolved. In the meantime, do you mind testing it? Just to make sure it wokrs for you (it does for me).

**Comment by franglais125** [comment]
Good news, this is now in master! [93c5a7a9462f03b9c9e825ced056ddacf3d8c350]

Thanks Michele.

**Comment by ItamarShDev** [comment]
Thanks!!!
