### ISSUE TITLE
dock doesn't show up in secondary monitor

### ISSUE THREAD

**Issue by jpmolinamatute** [micheleg/dash-to-dock#525]
I'm Using ArchLinux, gnome shell 3.24.2 and dash-to-dock 59
these are some outputs

[dconf-dump.txt](https://github.com/micheleg/dash-to-dock/files/1081159/dconf-dump.txt)

[journalctl-gnome-shell.txt](https://github.com/micheleg/dash-to-dock/files/1081186/journalctl-gnome-shell.txt)
please let me know if you need anything else from me

thanks for this awesome extension :-)

**Comment by franglais125** [comment]
Hi, the log seems to indicate that you upgraded to v59 not too long ago. Sorry for the simple question, but could you try restarting the Shell? Otherwise I don't see any errors on the log.

**Comment by jpmolinamatute** [comment]
I did, I guess there is not error on the log you can see the '-- Reboot --' on line 14 when I restarted the shell. let me logout/login too see if I can get new output

**Comment by jpmolinamatute** [comment]
before I did `gnome-shell --replace` I thought this was enough to update gnome shell and see the dash-to-dock on both of my screens, but I was wrong, I logout/login, and I can see dash-to-dock in both of my screen now :-)

this is my latest output in case you can use it

[journalctl-gnome-shell.txt](https://github.com/micheleg/dash-to-dock/files/1081263/journalctl-gnome-shell.txt)

**Comment by franglais125** [comment]
I'm glad it's working for you! :)

Cheers!

Regarding the first log you posted:
- It says "Reboot" just before 10:43:56
- Dash-to-dock was upgraded at 10:50:38

This is why I thought you hadn't restarted the session.
