### ISSUE TITLE
Wrong localisation for menu command opening settings dialog

### ISSUE THREAD

**Issue by psokol** [micheleg/dash-to-dock#527]
There is a command in right-click menu which shows preferences dialog for your extension. Translation of its label in Polish language (and I suppose in more languages) looks really weird because of wrong words order. Now there is "Dash to Dock Ustawienia" and should be "Ustawienia Dash to Dock". I noticed only "Settings" string is translatable in po file so making all sentence translatable should fix the problem.

**Comment by micheleg** [comment]
The reason I split the string was to inherit the translation of "Settings" from the shell for those languages (most) we don't have a translation. I was anticipating this sort of problem but I thought it would have been better than no translation at all for most languages. I might need to rethink this. 

One option as you suggest is to let translator translate the full sentence. 

As an alternative, would something like "Dash to Dock - Settings"  -> "Dash to Dock - Ustawienia" sound better in Polish?

Otherwise, another option would be to have two lines  menu with the extension name as a sort of header:

<pre>
   ________________
 | Dash to Dock      |
  - - - - - - - - -
 | Settings          |
<--------------------
</pre>

**Comment by psokol** [comment]
I understand your reasons now. "Dash to Dock - Ustawienia" looks much better for sure. But if you want to know my opinion, having only one string translated don't change a thing. And you don't know if this single string is properly used in all languages - there could be even different translations guidances. Always is better to pass this kind of decisions to translators. Having translated interface in other languages could be also done by using some automated translation tools.

**Comment by psokol** [comment]
Another win-win idea is to make whole string translatable using variable. For example it could looks like this: "Dash to Dock %s", where %s will pass translation of "Settings" string. Translator can change strings order to get "%s Dash to Dock".

**Comment by micheleg** [comment]
I have been thinking about programmatically generating translations based on the shell ones, but I never manage to try it. I'm quite interested in your last suggestion:. Would you mind elaborating on how that would work?

**Comment by psokol** [comment]
Unfortunately I only have experience as a translator, not developer. [Here](https://www.gnu.org/software/gettext/manual/html_node/c_002dformat-Flag.html#c_002dformat-Flag) I found some C code example that could help.

**Comment by franglais125** [comment]
@psokol Nice suggestion!

I implemented this here: https://github.com/franglais125/dash-to-dock/commit/8dea55d907074b238df05b80b82c80fcaba9f7df, in this branch: https://github.com/franglais125/dash-to-dock/tree/string_format

I couldn't test it yet though.

Here is the idea:
```
let name = __('Dash to Dock %s').format(_('Settings'))
```

And for a po file:
```
#: appIcons.js:1167
#, javascript-format
msgid "Dash to Dock %s"
msgstr "%s Dash to Dock"
```

**Comment by franglais125** [comment]
I just tested this for Spanish, with the following po modification:
```
#: appIcons.js:1167
#, javascript-format
msgid "Dash to Dock %s"
msgstr "%s de Dash to Dock"
```
![captura de pantalla de 2017-06-21 15-38-27](https://user-images.githubusercontent.com/19195975/27403264-d178aa34-5697-11e7-927d-d58067b8f955.png)

**Comment by micheleg** [comment]
@psokol thanks for the suggestion, @franglais125 thanks for the implementation. My understanding is that  the "Settings" alone translation will come from the shell translations, but it won't be used in the case the full translation is provided. That would be great. 

This should be a way to add a translation comment:
```
/* Translators:  ...*/
let name = __('Dash to Dock %s').format(_('Settings'))
```
by adding in the makefle to the getttext lines the option ``` --add-comments='Translators:'```

**Comment by franglais125** [comment]
Ah! That's a great suggestion. I was thinking of manually adding a comment to every .po file, but that's way better. Let me try it and see how it goes.

**Comment by franglais125** [comment]
Here is a patch with comments added: https://github.com/franglais125/dash-to-dock/commit/51968c89412da497d80b89bc10e82d4b6646d09e

**Comment by micheleg** [comment]
The string should now be properly translatable after #535.
