### ISSUE TITLE
Undefined properties and variables in JavaScript code

### ISSUE THREAD

**Issue by Edenhofer** [micheleg/dash-to-dock#528]
Some variables are not properly declared in JavaScript and GNOME therefore logs some undesirable warnings.
Excerpt from `journalctl`:
```
DATE MachineName gnome-shell[6715]: JS WARNING: [/home/username/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js 762]: reference to undefined property oldApps[oldIndex]
DATE MachineName gnome-shell[6715]: JS WARNING: [/home/username/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js 637]: assignment to undeclared variable minWidth
DATE MachineName gnome-shell[6715]: JS WARNING: [/home/username/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js 104]: reference to undefined property this._focusAppId
```
I am using gnome-shell version 3.24.2, Linux version 4.11.5 and X as window system. The extension version is the one which is currently available at http://extensions.gnome.org.

**Comment by franglais125** [comment]
Fortunately the three warnings are already fixed in master, so next version won't show these errors.

Fixes: [865a3d8a7f37900a398095385ebe5f032c3aa6dd], [f37606d80e821ff4aae52e00f222b753fdcf0919] and [d7d53fc8195791503cb05bd79b1b93b8d12eb268].

**Comment by franglais125** [comment]
Actually, I just realized these fixes were already shipped in v59. Are you sure you don't have updates available?

https://extensions.gnome.org/local/

**Comment by Edenhofer** [comment]
Apparently I fetched all of my extensions from the store, excerpt for yours. Sorry, for the noise :see_no_evil:
