### ISSUE TITLE
Cannot add certain non-native apps to Favorites

### ISSUE THREAD

**Issue by Naatan** [micheleg/dash-to-dock#533]
They only show "All Windows" and "Quit". Thing is this definitely worked when I was on Arch linux. Can't tell if that was a difference with the distro or with the version of Dash to Dock.

So far I've experienced this issue with:

 * Wavebox
 * Komodo IDE / Edit

**Comment by cryptoneep** [comment]
I have the more or less the same problem. I'm on Gnome3 on Ubuntu 17. I can't add certain apps such as Konsole.

**Comment by micheleg** [comment]
Can you add it to the default dash, i.e disabling the extension?  I suspect this might be a duplicate of #396.

**Comment by cryptoneep** [comment]
Ah. I've actually managed to do it. First by just doing super, typing the name of the app. Then dragging it from there. Instead of trying to add it as a favorite from the icon when it is already opened.

**Comment by Naatan** [comment]
It does not work in default dash either, so I guess it is indeed a problem in gnome-shell itself. Strange, never had this issue on Arch.

**Comment by franglais125** [comment]
@Naatan it could be a problem with the .desktop file of the application. I sometimes need to modify for 3rd party applications, e.g. usually the ones that you download from some random website instead of the distro's repositories.

**Comment by Naatan** [comment]
I'm the lead developer of one of the apps that have the problem. I'm fairly certain it's just because we get a bit creative with how the app is started up. But since it worked on Arch I figured there was something going on with Ubuntu.

Perhaps it's just cause Arch is more bleeding edge and as such has a fix of some sort that is not yet available on Ubuntu.
