### ISSUE TITLE
Change "minimize or overview" to only show application windows

### ISSUE THREAD

**Issue by andersgb1** [micheleg/dash-to-dock#540]
First, thanks for the completely awesome extension!

I was happy to see the addition of the "minimize or overview" feature, but it behaved a bit differently than I had expected. I was hoping that "overview" in this case meant an overview only of the windows for the clicked application, not all applications (like when clicking Super).

Would this be possible to implement?

**Comment by micheleg** [comment]
It is indeed being developerd:  have a look at this pull request: https://github.com/micheleg/dash-to-dock/pull/519.

**Comment by andersgb1** [comment]
Ah, sorry, I didn't see that PR. Sounds good!
