### ISSUE TITLE
Right-clicking on Dash-to-Dock icons doesn't show me optirun gnome extension options

### ISSUE THREAD

**Issue by Hexcz** [micheleg/dash-to-dock#544]
First of all i'd like to thank you for such great extension, i love it and imo it's a must-have ^^. As title said, when i right-click any app icon, the options from optirun extension (optirun, primusrun and optiprime) are not given, but in 'Show all Apps' it works very well. This issue happened after latest update, before this update the options were being showed normally. Tried to: install the alternate extension optiprime, reinstall Dash-to-Dock, reinstall optirun, restart Dash-to-Dock while optirun was running, restart optirun while Dash-to-Dock was running. None of those solved the issue. Thanks for support in advance!
![captura de tela de 2017-07-11 16-46-30](https://user-images.githubusercontent.com/17841940/28087369-9258eb2c-6658-11e7-901a-40156f369e52.png)
![captura de tela de 2017-07-11 16-46-39](https://user-images.githubusercontent.com/17841940/28087370-925a0f3e-6658-11e7-80eb-678e3c165fbd.png)

**Comment by micheleg** [comment]
Can you plese provide details of which versoin you were updating from and which version you updated to? And what Gnome Shell version are you running?

**Comment by Hexcz** [comment]
Thanks for your response.
Updated from v57 to v60;
Gnome Shell version: 3.24.2
Also if it helps, i'm using Apricity OS x64.

**Comment by micheleg** [comment]
I can't see an obvious candidate for a regression related to this. Do you have the option launches/"show open windows previews" enabled? Does that affect this issue?

**Comment by Hexcz** [comment]
SOLVED: unchecking "show open windows previews" box brought me back the options i wanted. Thanks!!
