### ISSUE TITLE
Typo in description for Intelligent Autohide

### ISSUE THREAD

**Issue by AdamKane41** [micheleg/dash-to-dock#545]
Duplicated "the" in the Intelligent Autohide description. It reads: "...window of the **the** current..."

![screenshot from 2017-07-11 17-50-29](https://user-images.githubusercontent.com/30092603/28092893-0f1eecba-6663-11e7-9bc7-9175b77500cb.png)

**Comment by micheleg** [comment]
Thanks,  I've fixed this in e8ce05f5dd5873204974bb39a270ca548d49c3c4.
