### ISSUE TITLE
Blur on dock please!

### ISSUE THREAD

**Issue by Cookie74** [micheleg/dash-to-dock#546]
I want request the blur effect on dock ,like OS X ,when the bar is half transparent.
![image](https://user-images.githubusercontent.com/30097589/28247857-ce16b580-6a0f-11e7-9291-68a5999cbcbc.png)
![image](https://user-images.githubusercontent.com/30097589/28247862-db897cd4-6a0f-11e7-87d1-36a7c2c9e5e7.png)

**Comment by xbonio** [comment]
+1 from me. It would improve readability, especially while overlapping with filenames (what happens really often).

**Comment by micheleg** [comment]
Closing as duplicate of  #224.
