### ISSUE TITLE
Groups or folders in dash

### ISSUE THREAD

**Issue by Taskkill** [micheleg/dash-to-dock#549]
Hello,
I would like to ask about possible feature. It's folders/groups of icons on dash.
It could look something like android icon folders on homescreen, or it could look something like: single choosen icon on dash and when hover this icon, some other icons would popup, maybe in column verticaly, or in rectangle.
I would use it for saving space and grouping similar application in my dash. It would be extra usefull as I am currently using dash as my application launcher. (Everything I use is on dash)

Thanks for your amazing job.

**Comment by micheleg** [comment]
Thanks for the suggestion. Honestly, I don't think I have the time to prioritize invesitgating the development of such feature for the time being.  It would not be a trivial effort due to al the drag and drop machinery to handle to create and manage the folders.

**Comment by Taskkill** [comment]
I see. Thanks for response.

**Comment by dvorapa** [comment]
Possible duplicate #332

**Comment by micheleg** [comment]
Closing as duplicate of #332.
