### ISSUE TITLE
Show minimised windows in the dock

### ISSUE THREAD

**Issue by kprinssu** [micheleg/dash-to-dock#551]
In my opinion a good macOS dock feature is the displaying minimised windows in the dock. 
An example of the feature I am requesting is shown in this screenshot:  https://i.stack.imgur.com/vyTSu.jpg

In the above screenshot, you can see a preview of the minimised "Safari" window in the dock. 

Is this possible to do in dash-to-dock? If not, can this feature be added to dash-to-dock?

**Comment by Cookie74** [comment]
It would be nice.

**Comment by micheleg** [comment]
I have mixed feeling about this feature. Anyhow, this is a duplicate of #201.
