### ISSUE TITLE
Update-notifier keeps pinging about update available while on current master

### ISSUE THREAD

**Issue by xbonio** [micheleg/dash-to-dock#552]
I had the extension installed via https://extensions.gnome.org/ but then pulled master from git and installed the extension manually (as described in README.md). Since that time update-notifier keeps pinging me about extension update available and while I go to https://extensions.gnome.org/local/ it turns out that... no update is available.

Is this something that can be fixed here or it's update-notifier issue?
![screenshot from 2017-07-20 08-49-47](https://user-images.githubusercontent.com/14818302/28404172-8ffe2d16-6d28-11e7-9d1a-1d57ed6ec69b.png)

**Comment by franglais125** [comment]
Are you referring to the update notification? This probably comes from the Firefox/Chrome extension to integrate to Gnome Shell.

![screenshot from 2017-07-20 03-07-53](https://user-images.githubusercontent.com/19195975/28404778-b011e38e-6cf8-11e7-8a43-3045ef7e521b.png)

If so, the problem is caused by the fact that the `make install` method writes the git hash as the version in the metadata. You can manually change that in `.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json`, the "version" field.

**Comment by xbonio** [comment]
I use Opera but that's it!

As I get why I see the notifications, I still find manually changing the version a workaround, not a solution. I shouldn't be pinged while on other version than known by extensions.gnome.org. Imagine having multiple extensions installed from source that need their version to be changed manually...

**Comment by franglais125** [comment]
I know, this was my pain too. I deactivate notifications from the browser.

I wrote an extension to work around it: https://extensions.gnome.org/extension/1166/extension-update-notifier/. What is does is to check if the version field for each extension is a number at all. If it isn't, then it won't emit a notification.

Perhaps you can open an issue here: https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues ?

**Comment by micheleg** [comment]
I decided to use version "-1" as that seemed to be considered somehow more recent the the ones available on the extension website (https://github.com/micheleg/dash-to-dock/commit/f1657fa30d1a63d677c96bf092e60b0c6fb2aee3), but  I have been annoied by the update popup too recently. I should probably start saving the extension version in the code. Let me think about it.

**Comment by micheleg** [comment]
I have since started committing the current version (since v63), so this problem should not occur any more.
