### ISSUE TITLE
Dock shows on lock screen with GNOME 3.25.90

### ISSUE THREAD

**Issue by jbicha** [micheleg/dash-to-dock#569]
GNOME Shell 3.25.90 from GNOME3 Staging PPA
Ubuntu 17.10 Alpha
Ubuntu Dock 0.2

The Ubuntu Dock shows on the lock screen with GNOME 3.25.90. I was using the 'Ubuntu on Wayland' session.

I can't duplicate this issue with GNOME Shell 3.24.3 (the version currently in Ubuntu 17.10).

**Comment by micheleg** [comment]
Closing this as it was solved by [44ed947e87692935fbfe934acc0e9faca4ec5af3].

**Comment by 1989gironimo** [comment]
Nope it's there again. Using Ubuntu 17.10 and it's shown on the lockscreen again.

**Comment by jbicha** [comment]
@1989gironimo I think you need to file a new bug since this bug was already fixed.

But please check to see what other extensions you have installed since one of them might be interfering.
