### ISSUE TITLE
[REQUEST] Icons colored background

### ISSUE THREAD

**Issue by seugeneus** [micheleg/dash-to-dock#572]
Please add an option to enable adaptive colored background. It help to quickly identify launcher icons.
Something like a icon-only task manager plasmoid in KDE4.
![colored_panel](https://user-images.githubusercontent.com/31179535/29493892-45c26e18-85a8-11e7-943a-069630e8b2b7.png)
In Unity are colored when the application is launched, but I prefer a constant coloring.

**Comment by micheleg** [comment]
I'm working on it right now :) See #512.
