### ISSUE TITLE
It is bad to work together with "put windows"

### ISSUE THREAD

**Issue by lunarjoll** [micheleg/dash-to-dock#575]
I install gnome extensions "put windows" to move window with number board. But it is usually open the app with "dash-to-dock" by "super +num".  Can't you ignore the right number board then they can work together.  
This bug appear sometimes and some num-key. Just "1 3 7 " belong to "put windows" and "9"belong to "dash to dock"

**Comment by micheleg** [comment]
I'm not sure I understand (please correct me).
1. Both dash to dock and put windows  use <super>+number as shortcuts
2. You would like dash to dock to unly use the top row numbers, and so the numpad ones can we used bu put-windows

I'm not sure if it is possible to isolate only the two sets of keypad ( "KP_1 ... KP_9" seems to be the code for the keypad only, any ideas for the keyboard ones only?). I would be keen on considering it if it is possible as it seems to makes sense to me.

You are aware that you can disable the sortcuts in dash to dock?

**Comment by lunarjoll** [comment]
Yes, you have understood. "put window" used numpad to replace windows. So I wish dash to dock can ignore the numpad.  
When I use ubuntu 14.04 by unity. They can do it perectly . So I wish that can achieve in gnome.

**Comment by franglais125** [comment]
This is something that I have been thinking about as well, in particular due to the quarter tiling work on Gnome-Shell. The reason is that I don't know what keybindings they will use. I think Unity was using the 4 corner numbers in the keypad (`Sup + [1, 3, 7, 9]`) to put a window in each of the four corners.

I have to test it to be sure, but I think it suffices to remove this line: https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L1435

Just for more info, it connect to each of the numbers from the schema: https://github.com/micheleg/dash-to-dock/blob/master/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml#L492

@micheleg As it often happens... Should we make this an option?

**Comment by lunarjoll** [comment]
Yes. Thank you. I know the function which replaced window is offered by compiz in ubuntu.  I wish this can achieved

**Comment by franglais125** [comment]
@lunarjoll do you mind testing this branch? I don't have a large keyboard at the moment.

https://github.com/franglais125/dash-to-dock/tree/hotkeys_keypad

**Comment by lunarjoll** [comment]
@franglais125 yes,it is work. numpad is worked for "put window".  I will test recently, and report to you.

**Comment by micheleg** [comment]
I'm even temped to just make this the default, with the option to re-enable the numpad keys. What do you think?

**Comment by franglais125** [comment]
@micheleg Absolutely, that's what I did in the branch: https://github.com/franglais125/dash-to-dock/commit/229fa76de7b96883afd121be77b8045d60643904#diff-e675f16de90b0bab07a05416a7d84814R258

**Comment by micheleg** [comment]
A negation got lost in my typing ... i was thinking of just changing the behaviour, **without** any option at all.

**Comment by franglais125** [comment]
*Personally* I don't mind, as I actually don't use the keypad. I'm just afraid that this will be seen as a regression by some users (although I don't know how many).

After having the hotkeys exposed for ~6 months (with the keypads), this is only the first report we get of a conflict of shortcuts, so my guess is the situation wasn't so bad (I would actually expect more bug reports wrt this). Now, if the built-in quarter tiling in gnome-shell ends up using `Sup+keypad`, then yes, we should definitely remove the keypad hotkeys.

Having the option allows the (seemingly?) low number of users having a problem to avoid it. I know that I perhaps propose too many options, so if you see this as a hindrance to maintainability/development, then I think the way forward is to *remove* the keypad hotkeys.

If we want to remove the keypad hotkeys, then the patch is of course much simpler: https://github.com/franglais125/dash-to-dock/tree/hotkeys_remove_keypad

Up to you in the end, of course.

**Comment by lunarjoll** [comment]
It is more simple to press "super + top row number ". and old ubuntu users will easy  to allow it. Is it  also nobody propose keypad is necessary?

**Comment by lunarjoll** [comment]
And reload tweak-tool command alt-F2 r enter is unable in wayland.

**Comment by micheleg** [comment]
I have decided to disable te keypad shortcuts for now [979b443fca66bf9].
