### ISSUE TITLE
Gnome 3.26 no work

### ISSUE THREAD

**Issue by Alexandr1322** [micheleg/dash-to-dock#583]
Hi!
Antergos 17 updated
Gnome 3.25.91
Not working, when you install the extension crashes gnome

**Comment by micheleg** [comment]
Thanks for the early testing and feedback. Please, can you confirm which version of the extension you are using? Current master should run on 3.26, but I haven't made a realease yet supporting it.

**Comment by psyhlo** [comment]
i can confirm that with master works as it should

**Comment by dimitrov-adrian** [comment]
With latest from master works, but in activities view and applications, the builtin in GNOME appears, so ends with 2 docks

**Comment by micheleg** [comment]
@dimitrov-adrian: please confirm if you have the problem even after restarting the shell.

**Comment by bharanikrishna7** [comment]
I can confirm that double dock problem persists with gnome-shell 3.25.91

To be more specific there is default dock along with dash-to-dock dock.

**Comment by micheleg** [comment]
@bharanikrishna7: can you copy and paste your settings (```dconf dump /org/gnome/shell/extensions/dash-to-dock/```) and check for relevant errors with: 

```journalctl -f  /usr/bin/gnome-shell```

Try enabling disabling the extensoin and see if some error appears. Thank you.

**Comment by bharanikrishna7** [comment]
@micheleg **dconf dump /org/gnome/shell/extensions/dash-to-dock/ results are** -
dock-fixed=true
force-straight-corner=true
show-show-apps-button=false
multi-monitor=false
show-favorites=true
apply-custom-theme=false
custom-theme-running-dots=true
dock-position='BOTTOM'
custom-theme-shrink=true
background-opacity=0.73999999999999999
dash-max-icon-size=40
opaque-background=false
icon-size-fixed=true

**journalctl -f /usr/bin/gnome-shell results are** -
Sep 03 10:54:52 MSI gnome-shell[1626]: WARNING: addSignalMethods is replacing existing [0xc8b0a02350 Gjs_ShowAppsIcon.dash-item-container] emit method
Sep 03 10:54:52 MSI gnome-shell[1626]: Some code accessed the property 'InjectionsHandler' on the module 'utils'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Sep 03 10:54:52 MSI gnome-shell[1626]: Some code accessed the property 'ThemeManager' on the module 'theming'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Sep 03 10:54:52 MSI gnome-shell[1626]: JS WARNING: [/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js 1122]: reference to undefined property "legacyTray"
Sep 03 10:54:52 MSI gnome-shell[1626]: Extension "dash-to-dock@micxgx.gmail.com" had error: TypeError: Main.legacyTray is undefined
Sep 03 10:54:52 MSI gnome-shell[1626]: Some code accessed the property 'MyAppIcon' on the module 'appIcons'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Sep 03 10:54:52 MSI gnome-shell[1626]: JS ERROR: TypeError: Main.legacyTray is undefined
                                       DockedDash<._adjustLegacyTray@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1122:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       DockedDash<._resetPosition@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1102:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Sep 03 10:54:52 MSI gnome-shell[1626]: JS ERROR: TypeError: Main.legacyTray is undefined
                                       DockedDash<._adjustLegacyTray@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1122:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       DockedDash<._resetPosition@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1102:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Sep 03 10:54:52 MSI gnome-shell[1626]: JS ERROR: TypeError: Main.legacyTray is undefined
                                       DockedDash<._adjustLegacyTray@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1122:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       DockedDash<._resetPosition@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1102:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Sep 03 10:54:52 MSI gnome-shell[1626]: JS ERROR: TypeError: Main.legacyTray is undefined
                                       DockedDash<._adjustLegacyTray@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1122:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                       DockedDash<._resetPosition@/home/anaiken/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1102:9
                                       wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22

**and a screenshot** - 
![screenshot from 2017-09-03 10-55-08](https://user-images.githubusercontent.com/8712418/30004092-d3ff6c3c-9096-11e7-9d8f-8819d7286753.png)


Sorry for late reply.

**Comment by micheleg** [comment]
@bharanikrishna7: are you running current master? It doesn't seems so from the log.

**Comment by bharanikrishna7** [comment]
@micheleg Sorry for misunderstanding. I'll run current master. While reinstalling I might have installed from firefox.

**Comment by bharanikrishna7** [comment]
It's working perfectly now. Thank you for all your work !

**Comment by micheleg** [comment]
Good. Unfortunately when you install from source  the system will prompt you to update to the extensions.gnome.org version (my trick to avoid it is not working anymore). A new release for 3.26  should come within next week.

**Comment by micheleg** [comment]
I would be glad if you could test the branch:  https://github.com/micheleg/dash-to-dock/tree/gnome-3.26

I'm fixing the remaining minor issues *mainly warnings) before making a new official release, and it would be nice to have some feedback to ensure I'm not introducing any regression.

**Comment by franglais125** [comment]
@micheleg Perhaps not exactly what you are looking for, but I'm testing the branch on 3.22, with no regressions so far (no new warnings either). Will let you know if I find anything.

**Comment by bharanikrishna7** [comment]
@micheleg I tested [Branch gnome-3.26](https://github.com/micheleg/dash-to-dock/tree/gnome-3.26) branch. Everything seems to be working as expected. I didnot encounter any errors associated with this extension.

**Comment by micheleg** [comment]
All the fixes are now in master,  and a new release (v61) was made.
