### ISSUE TITLE
Autohide mode: Dock interferes when using super+N shortcut

### ISSUE THREAD

**Issue by owais** [micheleg/dash-to-dock#585]
In autohide/intelligent mode, the dock shows up every time a launch icon is activated using the super+numeric-key shortcut. This makes the dock obtrusive and often interferes with content on screen.  Unity launcher solved this pretty well. IIRC, they made the specific launch icon pop out for just under a second when activating the shortcut. Until something like this can be implemented in dash-to-dock, I'd like to suggest not reveal the dock at all when super+num shortcut is used under autohide mode.

**Comment by franglais125** [comment]
If I didn't misunderstand the issue, this is an option in the settings. (I'm trying to upload a screenshot, hopefully it will work, spotty connection)

![screenshot from 2017-09-03 09-29-45](https://user-images.githubusercontent.com/19195975/30003415-912da29a-908a-11e7-8e18-de52f3ddeeb2.png)

**Comment by owais** [comment]
Awesome! I'm using Ubuntu Dock and tried to look for this in Dconf but didn't find it. This solves the problem. Perhaps would make sense to default to this. People who use super+N do so consciously and I don't think the visual confirmation using dock adds value that overweight the downsides of the distraction.

**Comment by franglais125** [comment]
To fix it, you can try this:

```
dconf write /org/gnome/shell/extensions/dash-to-dock/hotkeys-show-dock false
```

**Comment by micheleg** [comment]
Changing the defaults might be something more crucial for the Ubuntu folks (@didrocks), as they are not exposing this setting I geuss.

As far as we are concern, my argument for having the option on by defualt is that it's better to be explicit in showing that the shortcut comes from the dock, and then let the user digs into the extension settings if she wants to customize the behaviour. Alternatively, we should disable the hotkeys by defualt alltogether I think.

**Comment by owais** [comment]
I don't know if it is worth it but if it was up to me, I'd by default show it for the first 20 activations and then stop showing it. An explicit setting would override this behaviors.

**Comment by didrocks** [comment]
I think we want for discoverability purposes to have the dock shown when triggering this hotkey (I'm even considering having it shown when you press <super> in intellihide mode, so that you can see the list of applications enabled).

Something to refine over time, as we did with unity :)

**Comment by franglais125** [comment]
> I'm even considering having it shown when you press in intellihide mode

@didrocks This is already the behavior, isn't it?

**Comment by didrocks** [comment]
pressing <Super> in intellihide alone (without any shortcut) doesn't do anything for me, should it?

**Comment by franglais125** [comment]
@didrocks I misunderstood what you said... Never mind!

**Comment by micheleg** [comment]
I'm closing this as we have addressed the main problem for the moment.
