### ISSUE TITLE
Super key calls duplicate dock

### ISSUE THREAD

**Issue by Yahoe001** [micheleg/dash-to-dock#587]
On Ubuntu 17.10, fully updated, hitting the Super key displays a second dock (default settings) under the user configured dock (see screenshot below).

https://snag.gy/yNgMzZ.jpg

**Comment by franglais125** [comment]
Possible duplicate: https://github.com/micheleg/dash-to-dock/issues/564, https://github.com/micheleg/dash-to-dock/issues/568

It looks like you might be using dash-to-dock straight from extensions.gnome.org

You might need to install from git, as a version with Gnome 3.26 support hasn't been released yet.

**Comment by Yahoe001** [comment]
Thanks.
Indeed, the latest git version (installed 2017-09-05) fixes the issue.
