### ISSUE TITLE
Provide Unity Launcher API

### ISSUE THREAD

**Issue by paroj** [micheleg/dash-to-dock#591]
provide a DBus service for the Unity launcher API:
https://wiki.ubuntu.com/Unity/LauncherAPI

and implement display the count, progress, ugrency properties.
This way Unity applications relying on these APIs continue to work with Gnome3 as expected.

copy of: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1713712

**Comment by azzar1** [comment]
As part of Ubuntu Desktop Team I started addressing this issue. You can find the first PR [here](https://github.com/micheleg/dash-to-dock/pull/590). I started with counters. In the next few days I'll try to cover all the APIs.

**Comment by 3v1n0** [comment]
This has been fixed long time ago.

**Comment by archisman-panigrahi** [comment]
How to use this API?

In unity, you could do stuff like (source:https://wiki.ubuntu.com/Unity/LauncherAPI)
```
launcher = Unity.LauncherEntry.get_for_desktop_id ("evolution.desktop")
launcher.set_property("count", 124)
launcher.set_property("count_visible", True)
```

What is the alternative here?
