### ISSUE TITLE
Add keyboard shortcuts to dock

### ISSUE THREAD

**Issue by Samsagax** [micheleg/dash-to-dock#6]
This is just a feature request on this awesome extension.
Could you add some keyboard shortcuts to access the dock and start applications in it easily? Something like holding SUPER/SYSTEM key to bring up the dock and then a number/letter to launch an application? Each one should launch a new instance of the application. This upgrade plus window navigation extension just rock the GNOME-Shell.

Thanks!

**Comment by micheleg** [comment]
I'm closing this issue as it is implemented and being refined in #360.
