### ISSUE TITLE
Mouse scrollwheel switches workspaces when mouse against the left edge of screen

### ISSUE THREAD

**Issue by nathanhaines** [micheleg/dash-to-dock#605]
In artful when logged in with the 'ubuntu' GNOME session with the mouse pointer on the leftmost edge of the screen, the scrollwheel scrolls through the available workspaces. The Desktop team says this is not the desired behavior.

Also filed against Ubuntu Dock as https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1719706

**Comment by franglais125** [comment]
Perhaps the setting is set to `'switch-workspace'`

Can you try this to see if it's fixed?

```
dconf write /org/gnome/shell/extensions/dash-to-dock/scroll-action "'cycle-windows'"
```

**Comment by franglais125** [comment]
It seems that ubuntu-dock is being packaged that way:

https://github.com/micheleg/dash-to-dock/blob/ubuntu-dock/schemas/10_ubuntu-dock.gschema.override#L12

**Comment by franglais125** [comment]
@nathanhaines I think I misunderstood the problem. You can the workspace-switch action, just not on the edge of the screen?

Here is a patch for that: https://github.com/franglais125/dash-to-dock/commit/1598b2b6eea545abf4b969c5f465b643abe7a3a6, branch based on ubuntu-dock: https://github.com/franglais125/dash-to-dock/tree/mouse_scroll

**Comment by nathanhaines** [comment]
@franglais125 I'm over at the Ubuntu Rally and everyone here is very impressed.  Thanks so much for that!  I'll ping the right people over here.  :)

**Comment by franglais125** [comment]
@nathanhaines Awesome, let me know if it needs some tweaks!

**Comment by micheleg** [comment]
@franglais125: I'm not sure I understand what you are trying to achieve with that patch. The reason the border is reactive to the scroll events is that, due to margin/padding (depending on the theme)  the event is not captured by the appicon actors

**Comment by micheleg** [comment]
I do like it as well, but I undertand it might feel a bit unpredictable.

**Comment by micheleg** [comment]
I stand corrected: the behaviour is not dependent on margin/padding (depending on the theme), but relieably intercepted here:

https://github.com/micheleg/dash-to-dock/blob/fd81051ee0ae8320ef52eeeca3091d6f8f4860be/dash.js#L328-L332

It is restricted to 1px in the case of fixed-icons, while the whole dock is sensitive when it gets resized and threre's no other reason for scrolling. The easiest way to disable (as desired by the ubuntu team) is therefore to delete those lines. I'm tempted to do that indeed.

**Comment by micheleg** [comment]
This [8cbfa9836efff3c] would make i.

**Comment by didrocks** [comment]
let's close the issue btw as it's in master :)
