### ISSUE TITLE
Opacity of currently running application background is too big

### ISSUE THREAD

**Issue by 0matgal0** [micheleg/dash-to-dock#612]
It's really hard to tell which application is currently focused. Tweaking value to 0.3 opacity helps a lot and doesn't distract too much imho.

**Comment by 0matgal0** [comment]
below example of what i'm talking. maybe it's just my old ass lcd but it's hard as hell to tell which one is running on the second screen

![image](https://user-images.githubusercontent.com/18264503/31056560-d95c4404-a6d3-11e7-8654-02f146ca2bc6.png) ![image](https://user-images.githubusercontent.com/18264503/31056573-0aa265f2-a6d4-11e7-9526-7424ed61ffc6.png)

**Comment by micheleg** [comment]
Agreed. Thanks for pingin me on this. I made it a bit more prominent [68a6ede76dee8f3f9387f5a2b4fced313da4330b]. What do you think?

**Comment by 0matgal0** [comment]
Sorry for the delay in reply. The change seems good to me, thanks.
