### ISSUE TITLE
[Gnome 3.26] After unlocking shell becomes unusable

### ISSUE THREAD

**Issue by Pryx** [micheleg/dash-to-dock#620]
Hi, I've been encountering problem that when I unlock, shell becomes unresponsive and behaves as if Activities overview was open (see screenshot). Unfortunately this makes the extension unusable, without it everything seems fine. Would be glad if you looked into it, will provide more info if needed. 

![screenshot from 2017-10-16 23-10-13](https://user-images.githubusercontent.com/5222912/31635701-fc37b22e-b2c7-11e7-8a9c-671aa65244cd.png)

System is ArchLinux - Gnome 3.26.1, enabled extensions :
* openweather-extension
* caffeine
* workspaces-to-dock
* impatience
* alternate-tab
* audio-output-switcher
* user-theme
* native-window-placement
* dash-to-dock
* sound-output-device-chooser

Thanks :)

**Comment by sebastien-bugzilla** [comment]
Hello
Same behaviour here but I didn't realized that it was the locking of the session that trigger the bug. I've just check and everything is fine until I lock my session. I'm on Ubuntu 17.10 (with the gnome-session) with Gnome 3.26.1.
enabled extensions : 
- dash-to-dock
- appfolders-manager
- mediaplayer
- openweather-extension
- panel-osd
- user-theme
- workspaces-to-dock

I would be happy to help too if I can provide additional information. At the moment I stay under Xorg. I notice that gnome-shell reinitialization with Alt+F2 + r reset the bug. Alt + F2 is not possible under wayland.

**Comment by sebastien-bugzilla** [comment]
`journalctl /usr/bin/gnome-shell` 
give me this : 
https://framabin.org/?ccff43c1f920e43d#qcjx/PTw8cNa0YGiqnsy+AtC7crVU/wYuTTt785JZoc=

**Comment by franglais125** [comment]
@sebastien-bugzilla You seem to have a bunch of errors related to the workspaces-to-dock extension.

```
oct. 17 19:44:34 artful gnome-shell[2250]: Extension "workspaces-to-dock@passingthru67.gmail.com" had error: TypeError: DashToDock.dockManager._allDocks[0] is undefined oct. 17 19:44:34 artful gnome-shell[2250]: JS WARNING: [/home/sebastien/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js 2169]: reference to undefined property "_struts" oct. 17 19:44:34 artful gnome-shell[2250]: JS ERROR: TypeError: this._struts is undefined DockedWorkspaces<._updateSize@/home/sebastien/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:2169:9 wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22 DockedWorkspaces<._resetPosition@/home/sebastien/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:2263:9 wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22 DockedWorkspaces<._refreshThumbnails@/home/sebastien/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:2290:9 wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22 DockedWorkspaces<._overrideGnomeShellFunctions/Layout.LayoutManager.prototype._updateRegions@/home/sebastien/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:674:17
```

And so on... Could you try disabling this extension to see if the problem goes away?

@Pryx I see you also have the workspaces-to-dock extension. Could you try that as well? If it doesn't work, can you provide the output of  `sudo journalctl /usr/bin/gnome-shell?

**Comment by sebastien-bugzilla** [comment]
@franglais125 Yes that's what I've understood. I confirm that I don't have the bug under wayland when I disable workspace-to-dock

**Comment by franglais125** [comment]
I guess the best person to address this is @passingthru67

**Comment by Pryx** [comment]
@franglais125 Seems to work after disabling workspaces to dock extension. Seems to be related to https://github.com/passingthru67/workspaces-to-dock/issues/119 Didn't realize that might be workspaces to dock causing it, because disabling dash to dock worked :) Anyway it seems like they have fix ready, just waiting to be reviewed by Gnome ppl. No reason to keep this open then.
