### ISSUE TITLE
Nautilus icon with option to unmount and eject removable drive?

### ISSUE THREAD

**Issue by orschiro** [micheleg/dash-to-dock#625]
Hey all, 

Coming from this [1] discussion.

Would it be possible to add a context menu entry for Nautilus Dash to Dock icon to unmount and eject a removable drive?

[1] https://community.ubuntu.com/t/why-removable-device-menu-not-default/938/5

**Comment by orschiro** [comment]
@philipl this is brilliant. Thanks so much for your work!

Hope it's going to be merged. :-)

**Comment by 3v1n0** [comment]
Done for some time now :)
