### ISSUE TITLE
Icon list isnt being refreshed after I open a new application or close?

### ISSUE THREAD

**Issue by davidv171** [micheleg/dash-to-dock#626]
This is my current settings page:

https://i.imgur.com/Qzw7LiI.png

If I turn the Show running applications off then back on the Icon list refreshes. 

Any idea? 

16.04 Ubuntu. Downloaded from Gnome Extension Lists using my browser.

**Comment by micheleg** [comment]
Hi,

sorry for the late reply. Are you still experiencing this issue? Does it happen with a specific application?

**Comment by dvorapa** [comment]
Maybe a duplicate of #293?

**Comment by cunidev** [comment]
Also experiencing this issue on Solus 3 GNOME

**Comment by micheleg** [comment]
Closing as duplicated of #293
