### ISSUE TITLE
Dash to Dock causes GNOME 3.26 desktop session to logout when turning of monitor

### ISSUE THREAD

**Issue by yookoala** [micheleg/dash-to-dock#627]
Tested on Ubuntu 17.10 with GNOME 3.26.1 (Gnome session with Xorg). Enabling the extension would cause the desktop session to logoff when I turn off my computer screen. Disabling it can remove the issue from my system.

Similar things seems to happen on other extensions.

You may see detail reports in these tickets:
1. https://bugs.launchpad.net/gnome-shell/+bug/1721428
2. https://bugzilla.gnome.org/show_bug.cgi?id=789166

From [this comment](https://bugzilla.gnome.org/show_bug.cgi?id=789166#c6) the issue can be caused by extensions accessing non-existent GSettings key, which is a fatal error.

**Comment by MaxSchambach** [comment]
I'm experiencing frequent crashes of the gnome-shell too, most likely caused by dash-to-dock, though not only when I turn off the screen, but also sometimes randomly mid-session, and, reproducibly, after a lock of the screen and trying to log back in. There seem to be more tickets regarding this:

1. https://bugzilla.gnome.org/show_bug.cgi?id=788737
2. https://bugzilla.gnome.org/show_bug.cgi?id=788931

though some users state that their problems arise even without the dash-to-dock extension.
For me, however, disabling dash-to-dock got rid of all gnome-shell crashes that I experienced. I'm willing to help/debug the problem, unfortunately for me the core dump information was not very helpful.

**Comment by micheleg** [comment]
Could you check in the logs if before the crash there's some error message related to dash to dock or the shell?

```sudo journalctl  /usr/bin/gnome-shell```

**Comment by MaxSchambach** [comment]
Updated to gnome shell 3.26.2 today and re-enabled dash-to-dock today. So far, the observed core dumps and crashes did not reappear. 
If a crash occurs, I will let you know and post the log here.
I don't know if this closes the issue or if the crashes still occur for OP, though.

**Comment by yookoala** [comment]
This gist contains log right before the stated incident:
https://gist.github.com/yookoala/92f423effda699feac8fad2f2cefb22e

Note: There are logs about other extensions but I think they don't matter. As stated before, as long as I disable Dash to Dock and it alone, the problem is stopped.

**Comment by micheleg** [comment]
@yookoala : do you have more than one monitor? Can't find anything interesting from the logs unfortunately. Some additional info might be useful: wayland or X? Which GPU (intel/nvidia/amd)?

**Comment by yookoala** [comment]
@micheleg: I only have 1 monitor.

I think I'm using plain Xorg session (because wayland session is not available for me to choose)

**Comment by Zeka13** [comment]
Guys, you should uninstall gnome-shell-extension-ubuntu-dock from system, after that - no bugs

**Comment by yookoala** [comment]
Just tried removing gnome-shell-extension-ubuntu-dock. Don't seems to fix the issue for me.

**Comment by Brandl** [comment]
Can confirm this bug.

Dash to dock 62
Ubuntu 17.10
GNOME Shell 3.26.2
Nvidia 1060

**Comment by flega68** [comment]
Same problem here.
Locking the screen before turning off the screen helps.
Automatically lock the screen when turning off the screen doesn't work.
Turning off Dash to dock does help ;)

Dash to dock 62
Fedora 27
Gnome-Shell 3.26.2, xorg session
Intel i915 Driver

**Comment by micheleg** [comment]
@flega68 Are you able to provide some logs?

**Comment by flega68** [comment]
@micheleg 
I reproduced the problem and found out that it only crashes when dash to dock auto-hides. If i turn this of, everything seems to work.

Here the log I found so far (is there a better way):
journalctl /usr/bin/gnome-shell | grep dash
[dash.log](https://github.com/micheleg/dash-to-dock/files/1870981/dash.log)

**Comment by micheleg** [comment]
@flega68 Thanks for the additional log. I'm wondering if could be related to #493.

Could you confitm your configuration: Screen resolutions and relative positions(i.e. same resolution, or if not, how they are aligned).  Can you deterministically reproduce the bug?

**Comment by yookoala** [comment]
Hello. Update here. I'm testing on Ubuntu 18.04 beta 2. Same problem.
Stably reproducible on both Xorg and Wayland session.

* Ubuntu 18.04 beta 2
* Gnome 3.28
* Single HDMI output to a TV set.
* Nvidia Geforce GTX 1050 Ti with Open source Nvidia driver

**Comment by flega68** [comment]
@micheleg 
I have only one screen in this configuration. (1680x1050)
And yes, I can reproduce the Bug.
Dodge Windows on: Gnome crashes every time I unplug the monitor. Sometimes it is "just" a crash and the session stays on and sometimes Gnome crashes and the session closes.
Dodge Windows off: Normal behavior

**Comment by kll** [comment]
I have a single 4k monitor connected over DisplayPort using integrated Intel graphics. I'm running Arch Linux with Gnome 3.28, but the problem also happened back on Gnome 3.26. In my testing so far it only seems to kick in when I'm running a Wayland session. In that case just turning off my monitor causes a crash and when I turn the monitor back on I'm sitting at the login screen. If I run the exact same setup but launch the Xorg session instead the problem does not happen.

**Comment by kll** [comment]
I take that back, I've now gotten a crash while running an Xorg session as well. It just took a lot longer to happen. Often times, but not always, I can reproduce the crash under Wayland by simply turning my monitor off and right back on. I've never had that happen under Xorg, but I left an Xorg session logged on last night and turned my monitor off and then when I came back this morning it had crashed. Looking at the logs and it seems it was about 2 hours after I had turned the monitor off.

[logs](https://gist.github.com/kll/b2fae8443f95f0bd869c5a1b4c66180f)

**Comment by ctrl-f5** [comment]
also confirming this bug on 17.10, gnome 3.26.2

**Comment by perikitodestino** [comment]
Version: Git 09/05/2018
GNOME 3.28.1
Fedora 28 with Wayland
No multi-monitor
4K monitor
GTX 1050 with 396.24 propietary driver

Dash To Dock on: gnome-shell crash after turning off the monitor
Dash To Dock off: no errors, no crash

**Comment by perikitodestino** [comment]
I've noticed that the same thing happens when the screen lock is disabled in the privacy option of the configuration. When turning on the monitor it reloads GNOME (Windows-style with its explorer.exe hehe). The bug seems that it does not close the session by itself, it is GNOME that does it with the screen lock activated. When it is disabled it simply reloads the interface.

To me it concretely does to me when turning off the monitor, not when I turn it on.

I hope the information is useful, as you already know. There are many logs, if you tell me which look could put it without problems.

@micheleg

**Comment by micheleg** [comment]
@perikitodestino thanks for the additional information. @franglais125 thanks for pointing out those changes! 

I'm wondering if it is indeed enough to just skip the dock repositioning if there's not monitor attached. We are referring to monitors in various part of the code. My understanding is that the values stored in the monitor objects might be temporary meanigless but still valid given that they were previous monitor configuration. 

Given that at each monitor change we are destroying and recreating the docks, should we just stop the recreation process if no monitor is present? This is a tentative fix: e6dab2574f5063a1f1282fd3684d7657c5b41f21.

**Comment by franglais125** [comment]
@micheleg I'm running the branch with the fix, but all I can say is the dock still works... I can't confirm if the issue is fixed as I was not affected by it!

**Comment by micheleg** [comment]
yeah, not easy for me as well to test. Hoping on people that can more easily try to reproduce the bug to test if it works @perikitodestino @kll @ctrl-f5 @yookoala

**Comment by kll** [comment]
So far so good after 24 hours of use including the monitor being off overnight without a crash.

**Comment by ctrl-f5** [comment]
a quick test seems to be positive. Will report back if I still experience a crash.

**Comment by flega68** [comment]
Fix [e6dab2](https://github.com/micheleg/dash-to-dock/commit/e6dab2574f5063a1f1282fd3684d7657c5b41f21) seems to have solved the issue for me. 
Thx

**Comment by franglais125** [comment]
@ctrl-f5 or anyone else *still* having crashes:

Could you please attach a log if you have a new crash? That way we can verify that the cause is still the same, and if it's not we can be sure that the fix worked (or not).

**Comment by kll** [comment]
I've also had two more overnight crashes, but I've also had several more times where it didn't crash. I don't think it is related to dash-to-dock though, or at least I can't find any sign of it in the logs. Here they are for completeness sake in case I'm missing something.  For now I'm assuming it is unrelated.
[logs](https://gist.github.com/kll/635911f69bc050af80a78a0782c9dda3)

**Comment by xiatianyu** [comment]
Same here with Fedora 28 and GNOME Shell 3.28.2

**Comment by yookoala** [comment]
Thanks. Confirm the problem fixed on my computer that I talked about.

**Comment by Culted** [comment]
hi, i still have issues with dash-to-dock causing gnome to log out or crash when i turn of my monitor or when gnome turn it of, i did some testing and it only happens when dash-to-dock is active

i am using opensuse tumbleweed gnome is version Version 3.28.2
i have a geforce 960 with the proprietary nvidia driver version 396.24 and my monitor is connected via displayport

in "journalctl /usr/bin/gnome-shell" some errors appear that have to do with dash-to-dock, its a lot of text so i put it on [pastebin](https://pastebin.com/9qG3HUtY)

**Comment by micheleg** [comment]
@Culted are you running master? I habent release a version with the fix yet (I'll try to do it this week)
