### ISSUE TITLE
optional flat hover theme

### ISSUE THREAD

**Issue by Zeromatiker** [micheleg/dash-to-dock#632]
Add an option to make the highlighting of the background (when the mouse is over the item) fill the whole panel at the position of the icon. That would result in a cleaner look. (Setting could be located next to unity7-glossy-icons).

preview:
![dock change](https://user-images.githubusercontent.com/16196920/32252352-49e72e04-be95-11e7-9660-fe08aa5cd5ee.png)

**Comment by micheleg** [comment]
Correct me if I'm wrong, but the style on mouse over is the same in dash to dock and in the default dash (disabling the extension). If so, I believe this should be provided by the theme, not by the extension.

**Comment by imyxh** [comment]
Micheleg is right, it's provided by theme. The [theme I'm using](https://github.com/godlyranchdressing/United-GNOME) does this.

**Comment by Zeromatiker** [comment]
Ok, thanks for the info.
