### ISSUE TITLE
Dock shows on lockscreen on Ubuntu 17.10

### ISSUE THREAD

**Issue by 1989gironimo** [micheleg/dash-to-dock#641]
Referring to this bugreport: https://github.com/micheleg/dash-to-dock/issues/569#issuecomment-343710348 - It's pretty much the same but in August that was already fixed.

It's not always the case but most of the time the dock is visible on the left bottom side if the lockscreen is active.

**Comment by franglais125** [comment]
Could you check `sudo journalctl /usr/bin/gnome-shell` and post the output whenever this happens?

**Comment by ernstp** [comment]
Could it be a conflict with ubuntu-dock? They're using the same variable name?
I have both extensions installed but Ubuntu Dock disabled. Or supposed to be disabled.

nov 15 13:30:03 semall0566 gnome-shell[5623]: JS WARNING: [/home/ernsjo/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js 34]: reference to undefined property Symbol.toPrimitive
nov 15 13:30:03 semall0566 gnome-shell[5623]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1361]: unreachable code after return statement
nov 15 13:30:03 semall0566 gnome-shell[5623]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js 44]: assignment to undeclared variable runningExtensions
nov 15 13:30:28 semall0566 gnome-shell[5623]: Extension "ubuntu-dock@ubuntu.com" had error: TypeError: dockManager is null

**Comment by ernstp** [comment]
Yeah, uninstalling gnome-shell-extension-ubuntu-dock solved the issue for me.

**Comment by 1989gironimo** [comment]
Have done that (like the posts before) unintentionally and cannot reproduce that error anymore.
If it's coming back, I'll report.

**Comment by 1989gironimo** [comment]
Ok - had it now.
Had to copy the command from thunderbird, so there may be unnecessary stuff related to that:

`Nov 19 11:27:51 robot gnome-shell[2245]: Failed to apply DRM plane transform 0: Keine Berechtigung
Nov 19 11:27:51 robot org.gnome.Shell.desktop[2245]: Window manager warning: Failed to set power save mode for output LVDS-1: Keine Berechtigung
Nov 19 11:27:51 robot gnome-shell[2766]: WARNING: addSignalMethods is replacing existing [0x55b29fc65440 Gjs_ShowAppsIcon.dash-item-container] conn
Nov 19 11:27:51 robot gnome-shell[2766]: WARNING: addSignalMethods is replacing existing [0x55b29fc65440 Gjs_ShowAppsIcon.dash-item-container] disc
Nov 19 11:27:51 robot gnome-shell[2766]: WARNING: addSignalMethods is replacing existing [0x55b29fc65440 Gjs_ShowAppsIcon.dash-item-container] emit
Nov 19 11:27:53 robot gnome-shell[2245]: nma_mobile_providers_database_lookup_cdma_sid: assertion 'sid > 0' failed
Nov 19 11:27:53 robot gnome-shell[2766]: nma_mobile_providers_database_lookup_cdma_sid: assertion 'sid > 0' failed
Nov 19 11:29:50 robot gnome-shell[2766]: Max Id:12
Nov 19 11:29:50 robot gnome-shell[2766]: HDMI / DisplayPort 3
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 1:HDMI / DisplayPort 3:hdmi-output-2
Nov 19 11:29:50 robot gnome-shell[2766]: Removed: 1
Nov 19 11:29:50 robot gnome-shell[2766]: HDMI / DisplayPort 2
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 2:HDMI / DisplayPort 2:hdmi-output-1
Nov 19 11:29:50 robot gnome-shell[2766]: Removed: 2
Nov 19 11:29:50 robot gnome-shell[2766]: HDMI / DisplayPort
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 3:HDMI / DisplayPort:hdmi-output-0
Nov 19 11:29:50 robot gnome-shell[2766]: Removed: 3
Nov 19 11:29:50 robot gnome-shell[2766]: Kopfhörer
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 4:Kopfhörer:analog-output-headphones
Nov 19 11:29:50 robot gnome-shell[2766]: Removed: 4
Nov 19 11:29:50 robot gnome-shell[2766]: Lautsprecher
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 5:Lautsprecher:analog-output-speaker
Nov 19 11:29:50 robot gnome-shell[2766]: Activated: 5
Nov 19 11:29:50 robot gnome-shell[2766]: Line-Ausgang
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 6:Line-Ausgang:analog-output-lineout
Nov 19 11:29:50 robot gnome-shell[2766]: Removed: 6
Nov 19 11:29:50 robot gnome-shell[2766]: Max Id:13
Nov 19 11:29:50 robot gnome-shell[2766]: Eingang
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 7:Eingang:analog-input-linein
Nov 19 11:29:50 robot gnome-shell[2766]: Removed: 7
Nov 19 11:29:50 robot gnome-shell[2766]: Mikrofon
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 8:Mikrofon:analog-input-mic
Nov 19 11:29:50 robot gnome-shell[2766]: Removed: 8
Nov 19 11:29:50 robot gnome-shell[2766]: Internes Mikrofon
                                         (Eingebautes Tongerät)
Nov 19 11:29:50 robot gnome-shell[2766]: Added: 9:Internes Mikrofon:analog-input-internal-mic
Nov 19 11:29:50 robot gnome-shell[2766]: Activated: 9
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-1".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-2".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-3".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-4".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-5".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-6".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-7".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-8".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-9".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-hotkey-10".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-1".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-2".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-3".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-4".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-5".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-6".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-7".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-8".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-9".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-shift-hotkey-10".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-1".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-2".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-3".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-4".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-5".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-6".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-7".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-8".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-9".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-10".
Nov 19 11:29:50 robot org.gnome.Shell.desktop[2766]: Window manager warning: Trying to re-add keybinding "shortcut".
Nov 19 11:29:50 robot gnome-shell[2766]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.110/org/ayatana/NotificationItem/software_up
Nov 19 11:29:50 robot gnome-shell[2766]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.72/org/ayatana/NotificationItem/_modules_kde
Nov 19 11:29:51 robot org.gnome.Shell.desktop[2766]: libinput error: libinput bug: timer: offset negative (-276593)
Nov 19 11:29:55 robot gnome-shell[2766]: [pixel-saver]: Can't find original state for Mozilla Thunderbird with id 0x2200010
Nov 19 11:29:55 robot gnome-shell[2766]: [pixel-saver]: Can't find original state for Sicherheits-Ausnahmeregel hinzufügen with id 0x220003c
Nov 19 11:29:56 robot gnome-shell[2766]: [pixel-saver]: Can't find original state for Sicherheits-Ausnahmeregel hinzufügen with id 0x220004a
Nov 19 11:29:56 robot gnome-shell[2766]: [pixel-saver]: Can't find original state for Sicherheits-Ausnahmeregel hinzufügen with id 0x220005f
Nov 19 11:29:57 robot gnome-shell[2766]: [pixel-saver]: Can't find original state for Sicherheits-Ausnahmeregel hinzufügen with id 0x220006e
Nov 19 11:30:15 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title Terminal
Nov 19 11:30:15 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title t42h6@robot: ~
Nov 19 11:30:15 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title t42h6@robot: ~
Nov 19 11:30:15 robot gnome-shell[2766]: [pixel-saver]: Finding XID for window t42h6@robot: ~ failed
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title null
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title null
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title null
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title null
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title null
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Finding XID for window null failed
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Could not find XID for window with title null
Nov 19 11:30:16 robot gnome-shell[2766]: [pixel-saver]: Finding XID for window null failed
`

**Comment by tprasadtp** [comment]
@1989gironimo  I also had the same issue, but when I switched to "Stock Gnome" session and disabled ubuntu dock there, the issue vanished. I think its because of conflicts with ubuntu dock extension. 
When error occurs, Looking glass says that extension ubuntu-dock has some errors
and ` sudo journalctl /usr/bin/gnome-shell | grep ubuntu-dock` gives following 
```
gnome-shell[3063]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1361]: unreachable code after return statement
gnome-shell[3063]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js 44]: assignment to undeclared variable runningExtensions
```
Ubuntu devs have modified it not to display right click option and it somehow errors out
the lines  from appIcon.js  [source tarball](http://archive.ubuntu.com/ubuntu/pool/main/g/gnome-shell-extension-ubuntu-dock/gnome-shell-extension-ubuntu-dock_0.7.tar.xz) seems to be causing the error. 
```
showAppsIcon.popupMenu = function() {
    /* disable settings on right-click as only Dash to Dock will display extended settings */
        return;
      showAppsIcon._removeMenuTimeout();
      showAppsIcon.actor.fake_release();
```
I think the problem lies with Ubuntu dock extension not this one.  I am no expert in this so excuse me if anything I have said is not correct.

**Comment by GijsVermarien** [comment]
I also have this error, such a shame as this dash to dock looks amazing.

**Comment by Nebrit** [comment]
please @micheleg solve this problem in the next version please.

**Comment by naisanza** [comment]
Seeing the same thing as well on a fresh install

![dock to dash](https://user-images.githubusercontent.com/1614425/36013932-0f2d13c0-0d35-11e8-979c-0af0a42a8fa8.png)

**Comment by Zeka13** [comment]
Guys, you should uninstall gnome-shell-extension-ubuntu-dock from system, after that - no bugs

**Comment by oy495649630** [comment]
I came across such a problem when customizing my dock with 'dash to dock'. Before that I installed gnome tweaks and in extension column I found switches for several managing extensions including 'dash to dock'. Just switching it off solved my problem. Wish that could help for someone!

**Comment by Ads20000** [comment]
Anyone still affected by this issue with the Ubuntu Dock please [mark yourself as affected by the Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1769383)! :) Also, [here's the `journalctl -f` output](https://paste.ubuntu.com/p/Y3MxnXzqXq/) on my system when I lock the screen and reproduce the bug!

**Comment by galgalesh** [comment]
For me it happens every time after I wake my computer from sleep mode. It did not happen in 18.04 for me.

**Comment by robzon** [comment]
I experience the same issue on Ubuntu 18.10.

**Comment by micheleg** [comment]
This #848 could fix this issue.

**Comment by rocky7x** [comment]
Maybe it will fix it for Ubuntu dock, but not for other distros, that suffer the same problems, but do not have Ubuntu dock installed, just normal dash to dock.

**Comment by shutchinson** [comment]
I also experience this. Is there any info I can provide to help solve?

**Comment by Ads20000** [comment]
@shutchinson If you're using the default Ubuntu dock rather than Dash to Dock then yes, please run `ubuntu-bug gnome-shell-extension-ubuntu-dock` and it will provide all the information the Ubuntu developers need to fix the issue (also briefly describe the issue)
