### ISSUE TITLE
Inconsistent corner roundness when maximized

### ISSUE THREAD

**Issue by seandjones92** [micheleg/dash-to-dock#645]
I've noticed that when I disable dock autohiding the corners of maximized windows are inconsistent. The pictures attached demonstrate what I'm seeing:

When the window is not maximized:
![non-max](https://user-images.githubusercontent.com/17571045/32858776-c9bec662-ca09-11e7-81bf-bc7f76cbd869.png)

When the window is maximized:
![max](https://user-images.githubusercontent.com/17571045/32858813-e34defcc-ca09-11e7-9687-4fc53e784c10.png)
![max-right](https://user-images.githubusercontent.com/17571045/32858818-e5ea6706-ca09-11e7-90dd-6c9ed55594fd.png)

We can see that the top left corner is squared, but the top right corner is rounded. Is there something that could be done to keep both rounded? I like having the dock visible all the time and this is one of the only weird things I've found using this extension.

**Comment by micheleg** [comment]
The right round corner is the result of a superimposed element, it is not drawn by the window and in that case it would be something we can't interfere from the extension. So as far as I know there's no easy solution to this. You can use a theme that hide both round corners for symmetry (we actually do this from the extension if you enable the panel mode)

**Comment by seandjones92** [comment]
Thanks for the quick answer on that. I'll play around with some themes!
