### ISSUE TITLE
Dash to dock shows on lockscreen

### ISSUE THREAD

**Issue by shrihari007** [micheleg/dash-to-dock#649]
The dash to dock isnt disabled when the screen is locked. All the icons are clickable on lockscreen. Gnome 3.26.2 
Ubuntu 17.10

**Comment by pavelhritonenko** [comment]
This effect appears after first locking (first attempt goes without any issues), and after first locking there is additional dock on the left side, see screnshots:

![screenshot from 2017-12-01 11-17-40](https://user-images.githubusercontent.com/2510026/33473927-7c84f254-d689-11e7-8685-38cc93ba394e.png)

![image](https://user-images.githubusercontent.com/2510026/33473994-b7d2f3e2-d689-11e7-85bc-0ff5475903a1.png)

**Comment by pavelhritonenko** [comment]
Ok, resolved the issue by removing default `ubuntu-dock@ubuntu.com`:

```
$ sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com ~/
```

**Comment by virtualviolet** [comment]
this fixed it for me

**Comment by yushin59** [comment]
Thank you very much for your input pavelhritonenko !

**Comment by dylanmtaylor** [comment]
Same issue, same solution

**Comment by izhakjakov** [comment]
I think this issue is back in Ubuntu 18.04

**Comment by berkson** [comment]
I'm using gnome-software 3.28.1 and GNOME Shell 3.28.1 and everything works fine after using the command.

**Comment by izhakjakov** [comment]
The comment I posted 3 days ago is not longer valid I reinstall the gnome-session and everything is working as it should now.

**Comment by yoshegg** [comment]
Is there a reason for moving it to the home directory? Or did you actually want to type `rm` instead of `mv`?

**Comment by pavel-khritonenko** [comment]
To prevent losing the original file, obviously. You can just remove that extension using rm

**Comment by rathboma** [comment]
Should this really be a closed issue? It is a problem for all default installs of Ubuntu 18.04

**Comment by landsman** [comment]
@rathboma Working for me

**Comment by KABreaker** [comment]
Same error here, for me, unfortunately the rm dint help.

**Comment by sabbirsr** [comment]
Thanks, @pavel-khritonenko after executing your move command and reboot I see everything is fine Thanks man :+1: 
I am using Ubuntu 18.04.1 LTS

**Comment by Yazan111** [comment]
Worked for me Ubuntu 18.04 LTS.
Can someone explain the solution?

**Comment by sarki** [comment]
Most probably because the ubuntu-dock is a system extension while your dash-to-dock is a local one (/usr/share/gnome-shell/extensions as opposed to /home/$USER/.local/share/gnome-shell/extensions)
This means you can't possibly disable it with gnome-tweaks, so as soon as you lock your session these seem to come in conflict.


IMHO you're better off with doing a slightly modified version (in order to keep ubuntu-dock):
`sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com ~/.local/share/gnome-shell/extensions
sudo chown -R $USER:$USER ~/.local/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com`

Once there disabling the ubuntu-dock via gnome-tweaks might work without displaying a warning sign.

**Comment by aacassandra** [comment]
@pavel-khritonenko Thank you, i'm using Ubuntu 18.04.1 LTS and everything works fine after using the command and second step is reboot my ubuntu.

**Comment by nsrosenqvist** [comment]
On a system upgrade the ubuntu-dock reappears. Ubuntu have messed up big time here. Anyway an Ubuntu developer can actually look at fixing this?

**Comment by nimne** [comment]
Uninstalling the ubuntu-dock extension with `sudo apt-get remove gnome-shell-extension-ubuntu-dock` also appears to fix this.

**Comment by didrocks** [comment]
The best way to get it fixed is to be able to disable mod extensions, which is something I'm working on, and you can follow it on https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/2. This will probably be for dingo.

**Comment by joyal618** [comment]
Thank you so much. It works fine

**Comment by dbrsseau** [comment]
I've also notice that active apps aren't showing in the dock. This extension package has some weird habits. The workaround solution propose by @pavel-khritonenko seem to fix everything. Is their any way to propose a permanent fix for future fresh install? Thanks for the solution! :+1:

**Comment by Ads20000** [comment]
@dbrsseau The dash to dock showing on the lockscreen issue is a bug, the active apps not showing is another bug, please run `ubuntu-bug gnome-shell-extension-ubuntu-dock` to report it and wait for it to be fixed. We just have to wait for the Ubuntu developers to get round to fixing the issues, unless you are able to code and fix the issue yourself. Once they have the time, if they have the time, it will be resolved for future fresh installs.

I've realized, though, that when I install Dash to Dock from GNOME Extensions and mess with the settings that then messes with (hidden) Ubuntu Dock settings, effectively, and causes a broken experience. Basically, if you're planning to revert to the default Ubuntu Dock at some point, _do not install Dash to Dock_. I don't think it's right to expect Ubuntu Dock to behave correctly in my use-case, by installing Extensions you're accepting some instability to GNOME and deviation from how the developers intended the shell to run.

**Comment by farhadazimi** [comment]
> Ok, resolved the issue by removing default `ubuntu-dock@ubuntu.com`:
> 
> ```
> $ sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com ~/
> ```

that's true but 
but another way, we can download dash to dock from extention.ubuntu.com 
and customize it,
sincerely yours

**Comment by lsansco** [comment]
For the first time ever I have encountered this problem in Fedora 29. The dock was showing on the lockscreen like it did on my old Ubuntu install and it made parts of the shell blurry. 

My attempts at taking a screenshot failed so here is a photo.  I installed Dash to Dock from the Software Centre less than 24 hours ago. 

![photo_2019-01-28_09-08-08](https://user-images.githubusercontent.com/36652517/51808187-4195da00-22dc-11e9-8f90-efed6cbc3394.jpg)

**Comment by pwd-github** [comment]
@lsansco this should be solved when @micheleg publishes a new build.

**Comment by laichiaheng** [comment]
Ubuntu Dock has fixed it, but it happens in Manjaro now.

**Comment by pwd-github** [comment]
@laichiaheng Yeah, it's still waiting on @micheleg to release a new build as to fundamentally fix the problems. Ubuntu have contributed a few pertinent performance improvements.

**Comment by micheleg** [comment]
I have just submitted an updated version to the extensions website. It will be available following the review process (https://extensions.gnome.org/review/). It might take a while as there is a long queue.

**Comment by laichiaheng** [comment]
Oh My God! It is still at the bottom of the list

**Comment by laichiaheng** [comment]
@micheleg When will they review it? It has been a long while.

**Comment by Ads20000** [comment]
@laichiaheng I tried asking in the [gnome-shell IRC](https://wiki.gnome.org/Community/GettingInTouch/IRC) what we, as ordinary users, could do to help work on that review queue, but I got no responses in the first few hours of asking that question then I logged out of IRC (GNOME's IRC is unlogged (unlike, e.g., Ubuntu's) so communication there is very difficult in my opinion). I don't think they'd appreciate an 'ETA' question because presumably it's volunteers working through that queue, so the answer will be indefinite/never unless someone steps in to help speed it up. You could try asking the question also on the [GNOME Reddit](https://www.reddit.com/r/gnome/) (as the devs do look at that, so [until the Discourse is made](https://gitlab.gnome.org/Infrastructure/Infrastructure/issues/99) (please +1 (hit the thumbs up button) for that one!!), that's the way to go for a forum equivalent to, e.g., the Ubuntu Community Hub). Alternatively file an Issue [here](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/issues)!

**Comment by natan64** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

gnome-shell --version
GNOME Shell 3.28.3

gnome-core                                    1:3.22+9                    amd64                       GNOME Desktop Environment -- essential components
ii  gnome-desktop3-data                           3.28.2-0ubuntu1.2           all   

I remove gnome-shell-extension-ubuntu-dock and gnome-shell-extension-dashtodock
I install latest ver "Dash to Dock" for my gnome-shell

Problem exists. The dock was showing on the lockscreen .....

Any real sollutions or alternative ?

**Comment by stratigos** [comment]
FYI you may not need to reboot your system after moving the `ubuntu-dock` dir. After moving it to a location in my home dir, I just restarted Gnome Shell with `Alt + F2` and then the command: `r`, and the problem went away (repeated screen locks no longer display the dock).

**Comment by dbrsseau** [comment]
> @dbrsseau The dash to dock showing on the lockscreen issue is a bug, the active apps not showing is another bug, please run `ubuntu-bug gnome-shell-extension-ubuntu-dock` to report it and wait for it to be fixed. We just have to wait for the Ubuntu developers to get round to fixing the issues, unless you are able to code and fix the issue yourself. Once they have the time, if they have the time, it will be resolved for future fresh installs.

Sorry for late respond, but it seem to me to be related somehow but anyway, I'm not into reporting bug since I've stopped using gnome and it dock. I've use the quick fix proposed by @pavel-khritonenko and it was suffisant for me back then! Thanks again!

**Comment by ywang146** [comment]
> explain

yes he just removed the original system dock ( actually move because he want to backup the file )

**Comment by EJTH** [comment]
Reported AND closed in 2017, but its still a problem...

**Comment by mantlecurve** [comment]
This problem still exists

Distributor ID:	Ubuntu
Description: Ubuntu 20.04 LTS
Release: 20.04
Codename: focal

GNOME Shell 3.36.1

**Comment by Ads20000** [comment]
If anyone still has the problem on Ubuntu using Ubuntu's default dock, please run `ubuntu-bug gnome-shell-extension-ubuntu-dock` so that Ubuntu developers can fix the bug, thanks! :)

**Comment by rogerpolvr** [comment]
> Ok, resolved the issue by removing default `ubuntu-dock@ubuntu.com`:
> 
> ```
> $ sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com ~/
> ```

Thank you! This fixed for me

**Comment by bobeymcool** [comment]
> Ok, resolved the issue by removing default `ubuntu-dock@ubuntu.com`:
> 
> ```
> $ sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com ~/
> ```

Thank You. This fixed the issue for me.

**Comment by menobleknight** [comment]
I had the same issues (dock on lock screen and overlapping dock on the home screen). 
- I removed `dash-to-dock` extension and then disable ubuntu-dock from extensions as well as from gnome-tweaks (you can use `super` key to switch between applications after removing dock). 
- Then install `dash-to-dock` again and select proper version of gnome-shell while installing dash-to-dock (you can run `gnome-shell --version` to check version of your gnome-shell).  
This process resolved above issues for me.

**Comment by audoh** [comment]
I didn't want to start moving folders around, so I ran this command:
`gnome-extensions disable ubuntu-dock@ubuntu.com`

Which added this line to dconf:
```
[org/gnome/shell]
disabled-extensions=['ubuntu-dock@ubuntu.com']
```

**Comment by WRangers** [comment]
If you also install `dash to dock animator` with `dash to dock`, you can try:

1. `sudo apt purge gnome-shell-extension-ubuntu-dock`
2. remove `dash to dock animator`
3. logout
4. install `dash to dock animator`

It works for me!
