### ISSUE TITLE
Tapping application icon launches two instances

### ISSUE THREAD

**Issue by flipflop97** [micheleg/dash-to-dock#652]
When tapping an application icon using a touch screen the application launches twice, creating two instances at once. This happens every time.

Sometimes when doing this the application icon also fades to a low opacity and stays so until reboot, however I'm not able to reproduce this at will, it seems to happen randomly.

*Arch Linux  
Gnome 3.26.2  
Dash to Dock 61*

-----

EDIT  
Dragging an application icon using the touch screen bugs out the whole dock and even the shell, making some items unclickable and/or untappable across whole Gnome shell.

**Comment by micheleg** [comment]
Possibly the same as #128

**Comment by flipflop97** [comment]
Yep that's indeed the same issue. My bad.
