### ISSUE TITLE
Gnome 3.26.2 hangs off

### ISSUE THREAD

**Issue by IgnisAvis** [micheleg/dash-to-dock#654]
I use gnome-shell 3.26.2 on Arch Linux.
When I try to drag & drop items on panel my system is hangs off.
```
$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
opaque-background=true
preferred-monitor=0
show-apps-at-top=true
show-windows-preview=true
extend-height=true
dock-fixed=true
force-straight-corner=true
show-running=true
hot-keys=false
multi-monitor=false
custom-background-color=true
apply-custom-theme=false
custom-theme-running-dots=false
isolate-monitors=false
height-fraction=1.0
custom-theme-shrink=true
background-opacity=0.14999999999999999
dash-max-icon-size=36
background-color='#000000'
icon-size-fixed=true
isolate-workspaces=false
journalctl -f /usr/bin/gnome-shell
```
![2017-12-09 14-36-42](https://user-images.githubusercontent.com/30938103/33795662-6b2f40fc-dcee-11e7-9488-1e01b8db7f9b.png)
What I need to do to fix it??

**Comment by FirstZero** [comment]
I can replicate this issue

**Comment by franglais125** [comment]
Everyone, FYI: https://gitlab.gnome.org/GNOME/gjs/issues/21

**Comment by IgnisAvis** [comment]
Guys, downgrading to gjs-1.50.2-1 helps me:
`sudo pacman -U /var/cache/pacman/pkg/gjs-1.50.2-1-x86_64.pkg.tar.xz`
