### ISSUE TITLE
Dash to Dock not run in Gnome 3.26.2

### ISSUE THREAD

**Issue by peinadoso** [micheleg/dash-to-dock#655]
Hi, I tried to run Dash-To-Dock in my new Fedora 27 Version but it showed me a message error:

"There was an error trying to launch the settings dialog box to Dash-To-Dock" ------------------

Error: Expected type utf8 for Argument 'domain' but got type 'undefined' ------------------

Stack trace:
  bindtextdomain@resource:///org/gnome/gjs/modules/gettext.js:48:12
  initTranslations@/home/rpeina01/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/convenience.js:32:9
  init@/home/rpeina01/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:702:5
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:76:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43
  
System descriptions:
* Linux localhost.localdomain 4.13.16-302.fc27.x86_64 #1 SMP Thu Nov 30 15:33:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* GNOME Shell 3.26.2
* GNOME Tweak Tool 3.26.3
* Dash To Dock for GNOME 3.26 V61

Thanks in advance for the help.

**Comment by arisskz6** [comment]
I met the same problem:(
Also the fedora 27
Gnome 3.26

**Comment by ALEXRAFAO** [comment]
ok
________________________________
发件人: arisskz6 <notifications@github.com>
发送时间: 2018年1月21日 17:18
收件人: micheleg/dash-to-dock
抄送: Subscribed
主题: Re: [micheleg/dash-to-dock] Dash to Dock not run in Gnome 3.26.2 (#655)


I met the same problem:(
Also the fedora 27
Gnome 3.26

―

**Comment by mrwulf** [comment]
:+1:

**Comment by dvorapa** [comment]
Does `dconf reset /org/gnome/shell/extensions/dash-to-dock/` help?

**Comment by AndreT81** [comment]
Thanks dvorapa. This solved the issue for me
