### ISSUE TITLE
Dock disappears, prevents dash from showing

### ISSUE THREAD

**Issue by jikamens** [micheleg/dash-to-dock#66]
(Moving this issue from #59, since I've now figured out more about it and it seems clear that it's a different issue from that one.)

If I turn on the "Dock is fixed and always visible" option and then log out and log back in, not only does the dock disappear, but the dash is also missing when I move my mouse to the hot corner of my screen.

If I then open the extension preferences and turn off the "Dock is fixed and always visible" option, the dash reappears when I activate the hot corner. If I then turn "Dock is fixed and always visible" back on, the dock appears as well and everything works fine.

I'm using Fedora 19.

**Comment by micheleg** [comment]
Closing this issue as probably after so much time  - I hope - not relevant anymore. Feel free to reopen it if similar problems persist.
