### ISSUE TITLE
Adaptive and Dynamic opacity style issue

### ISSUE THREAD

**Issue by FOOTCLAN** [micheleg/dash-to-dock#666]
When using the default shell theme and the position of the dock is set to bottom and the opacity is set to either Adaptive or Dynamic the very bottom right corner of the dock is rounded when it should be squared to meet the edge of the screen. 
![dock](https://user-images.githubusercontent.com/8490161/34550484-4d88747e-f0df-11e7-84d4-21f8ea191933.png)
EDIT: After posting the screenshot I noticed the top left corner is squared when should be rounded.

**Comment by jacopo1395** [comment]
Same problem but also when using custom theme

**Comment by bugm3n0t** [comment]
@micheleg Could you please have a look at this? Is this something tricky to solve?

**Comment by bugm3n0t** [comment]
I tested the code locally and for what concerns the results it seems o fix the issue.
