### ISSUE TITLE
Windows on the second monitor are not isolated in the overview

### ISSUE THREAD

**Issue by mitar** [micheleg/dash-to-dock#669]
I am using "isolated workspace" feature and it works great on my primary monitor. No dots are shown in the app icon if there are no windows by that app in the workspace I am currently in (which is what I expect). And if I go into overview mode I see only windows in the workspace (which is what I expect).

But this is not true for the second monitor. When I go into overview mode with second monitor attached, I see all windows from all workspaces in that monitor. Dots in the app icon work correctly. But the overview does not.

cc @franglais125

**Comment by franglais125** [comment]
Thanks for reporting this. I took some time to respond as I didn't have my second monitor. However, I can't reproduce the issue.

Could you provide some more info:
1. Gnome Shell and d-t-d versions?
2. Perhaps a screenshot?

Just to clarify, is this related to the "Gnome Tweaks" setting for secondary monitors ("Workspaces span displays")? See screenshot below!

![screenshot from 2018-01-08 17-51-33](https://user-images.githubusercontent.com/19195975/34696385-9ef89e86-f49c-11e7-9ed7-a6067e371673.png)

Cheers!

**Comment by mitar** [comment]
Ah, yes, I have `Workspaces span displays` enabled. So to me each workspace contains two monitors. The main monitor works well, but the extra monitor has all windows from all workspaces on the extra monitor shown. So only windows which are on the extra monitor are shown there, but for all workspaces.

I am using Ubuntu 17.10 and d-t-d provided with it.

GNOME Shell 3.26.2

**Comment by franglais125** [comment]
Would you mind sharing a screenshot? I have certainly never seen that (yet!)

**Comment by mitar** [comment]
Huh, let me figure out how to make a screen shot across two monitors. Do you know?

**Comment by franglais125** [comment]
Same as usual actually, just press "PrntScr".

![screenshot from 2018-01-08 18-05-33](https://user-images.githubusercontent.com/19195975/34696921-9c764b66-f49e-11e7-84dd-5ff46d34444b.png)

**Comment by mitar** [comment]
It worked. Thanks.

So this is a workspace with one window on each monitor.

![screenshot from 2018-01-08 15-09-57](https://user-images.githubusercontent.com/585279/34697098-6516b308-f486-11e7-9c3b-237c7698ebd5.png)

When I go into overview mode, it pulls another window on second monitor in, from other workspace.

![screenshot from 2018-01-08 15-10-32](https://user-images.githubusercontent.com/585279/34697110-71c81bf0-f486-11e7-8151-6b250d371194.png)

**Comment by mitar** [comment]
Reproduction:

* enable `Workspaces span displays`
* create a window on monitor 2 on workspace 2
* create a window on monitor 1 on workspace 1
* create a window on monitor 2 on workspace 1
* on workspace 1, go into overview mode

**Comment by franglais125** [comment]
As far as I remember, the extension doesn't really touch the overview, so not something that can be fixed here.

i.e. can you reproduce the issue with d-t-d disabled?

**Comment by mitar** [comment]
I think that this is a consequence of #325. When I enabled it, also overview gets limited. But on the primary monitor only. If I remember correctly.

**Comment by micheleg** [comment]
As @franglais125  said, I don't think we are touching at all the overview behaviour. Can you please confirm  that the bug doesn't occur with dash-to-dock disabled?

**Comment by mitar** [comment]
Oh, you are right. It seems this is not this extension. I am now very confused.

Sorry for the noise.
