### ISSUE TITLE
Duplicate docks

### ISSUE THREAD

**Issue by chuymax** [micheleg/dash-to-dock#673]
In ubuntu 17.10, sometimes the dock is duplicated. See screenshot. Restarting my system usually fixes the problem.

![screenshot from 2018-01-15 21-35-45](https://user-images.githubusercontent.com/1208947/34969302-3151342e-fa3c-11e7-8a44-e4addbd353bc.png)

**Comment by micheleg** [comment]
Pretty strange! Would you be able to provide some logs when the issue occurs? You can monitor the logs with:
```journalctl -f /usr/bin/gnome-shell```

**Comment by chuymax** [comment]
Yeah, sure. I'm attaching the logs.

[out.txt](https://github.com/micheleg/dash-to-dock/files/1650668/out.txt)

**Comment by pdimh** [comment]
I'm also having the same problem. Restart works for me too, it always comes back.

**Comment by chuymax** [comment]
Ubuntu 17.10 ships with a fork of dash to dock. On one of my system updates, dash to dock was uninstalled and no longer installable. The duplicate docks seem to have been a problem caused by both dock applications running at the same time, the dock with the icons on the left should be ubuntu dock, and the centered icons should be dash to dock.

Closing.

**Comment by chuymax** [comment]
I uninstalled Ubuntu Dock, and installed Dash to Dock. I haven't had problems anymore.
