### ISSUE TITLE
Add to favorites programmatically

### ISSUE THREAD

**Issue by sethen** [micheleg/dash-to-dock#674]
I am looking for a way to add icons to dash to dock in an automated way.  I would use this sort of behavior for an initial set up of my system.  I can't seem to find anything on this topic by searching Google.  I also dug through dconf to see if there is anything in there.

The question is, where does dash to dock keep these settings?  Are these editable through terminal so I can set icons on my dock?

**Comment by micheleg** [comment]
Hi,

I think that the favorite apps are saved by the shell itself in
```gsettings get org.gnome.shell favorite-apps```
so you should be able to add programmatically application via ```gsetting set```.

**Comment by franglais125** [comment]
I was about to answer as well... Here is an example:

```
dconf write /org/gnome/shell/favorite-apps "['org.gnome.Nautilus.desktop', 'firefox.desktop', 'rhythmbox.desktop']"
```

To simply get the string:
```
dconf read /org/gnome/shell/favorite-apps
```

**Comment by sethen** [comment]
@franglais125 Ah yes, that was it.  Thank you so much!

**Comment by viniciusbds** [comment]
works here, thanks @franglais125

**Comment by compumatter** [comment]
Worked.  Thanks
