### ISSUE TITLE
A quick access to recent files AND app's ( as in Unity dash ) ?

### ISSUE THREAD

**Issue by Coeur-Noir** [micheleg/dash-to-dock#678]
Hi,

There are many features I miss from Unity when trying to get accustomed to 17.10. One of them is a one single click ability to find my recent app's AND files - yes both of them, as Unity dash used to show at first click.

Coming from there https://bugzilla.gnome.org/show_bug.cgi?id=792484 here are some ugly mockups, maybe they could inspire something…
- icon in dock / no opened window
![sur_bureau_recents_apps_et_fichiers](https://user-images.githubusercontent.com/1895947/35189932-f432f9f6-fe55-11e7-990e-4b8c2c56df42.jpg)
- icon in dock / above opened window(s)
![par_dessus_avec_recents_apps_et_fichiers](https://user-images.githubusercontent.com/1895947/35189936-ffd7398e-fe55-11e7-8b5d-35a099837cef.jpg)
- an optional mode : persistent on desktop view ( but not dependent on any nautilus-desktop planned-to-death feature )
![par_dessous_avec_recents_apps_et_fichiers](https://user-images.githubusercontent.com/1895947/35189937-076bd178-fe56-11e7-8165-2811e50c512c.jpg)

It's kind of related to https://github.com/micheleg/dash-to-dock/issues/671 regarding quick access to nautilus bookmarks, and therefore files, recent ones included.

Why so ? Whereas app's pinned in the dock are your daily favorites, while working on a topic / project you may use intensively some app's and files only for the duration of this project… And many files ( images, videos, raw texts ) can be used through differents app's ( simple viewers, editors, word processor, DTP… ) so having both recent app's and files at the same place, with the same hierarchy, saves much time.

**Comment by vanvugt** [comment]
I'm going to close this issue because:
* It describes two separate feature requests (recent files and apps).
* It prescribes a solution that's almost certainly not going to be implemented that way.
* https://github.com/micheleg/dash-to-dock/issues/2283 is a shorter description of the main feature really lacking.
