### ISSUE TITLE
Dash to Dock version 62 is not available via the extensions site on Debian Sid (GNOME 3.26)

### ISSUE THREAD

**Issue by furquan-lp** [micheleg/dash-to-dock#679]
The latest version of dash-to-dock has been [released](https://micheleg.github.io/dash-to-dock/release/2017/12/25/new-relsease-v62.html) a month ago but the update still hasn't popped up on the extensions site (as shown in this [screenshot](https://user-images.githubusercontent.com/22724578/35446211-ff57af42-02d9-11e8-9a91-23a46fe8b43d.png)).

I'm using GNOME 3.26 on Debian Sid (aka unstable). Manual installs of the extension don't work (the extension simply doesn't show up in the Tweak Tool and the dconf entry has already has it added).

**Comment by micheleg** [comment]
Hi, version 62 is still awaiting review (https://extensions.gnome.org/review/). You should be able to download the zip file (https://extensions.gnome.org/review/download/7799.shell-extension.zip) and install it via gnome-tweak-tool.

**Comment by furquan-lp** [comment]
Thanks for the response. Manually adding the extension still doesn't work. I've copied the extension in the relevant directory ([screenshot](https://user-images.githubusercontent.com/22724578/35607165-d33e5580-0678-11e8-9382-78e2b058c5c3.png) but the extension doesn't appear in the [tweak-tool](https://user-images.githubusercontent.com/22724578/35607179-e10c1472-0678-11e8-8f29-dc611a2b2739.png).

I suspect this is a problem on my end and I think it would be better to wait for the version to be reviewed.

**Comment by franglais125** [comment]
@furquan-lp the folder name should really be `dash-to-dock@micxgx.gmail.com` **exactly** (which you don't have in the screenshot).

Alternatively, you can install from the Debian repos directly: `sudo apt install gnome-shell-extension-dashtodock`.

Remember to restart the session!

**Comment by furquan-lp** [comment]
> Alternatively, you can install from the Debian repos directly: sudo apt install gnome-shell-extension-dashtodock.

That worked. Thanks.
