### ISSUE TITLE
pop-up gnome setting window

### ISSUE THREAD

**Issue by max95100** [micheleg/dash-to-dock#683]
I've been having a gnome problem for some time now that prevents me from using this environment. after starting the system, most often when running any application using the Internet, I get a gnome settings window. closing this window results in its reopening. when I close all applications for some time I have peace. after I open the gnome settings window, I can not write in any program because for some reason the cursor is positioned in the search box gnome shell.
I have the same problems on both ubuntu and manjaro, but I do not have this problem on opensuse leap 42.3, but gnome settings is replaced by yast. 
other environments (kde, xfce, deepin) work properly for me, only with gnome I have a problem.

**Comment by micheleg** [comment]
I'm not sure this relates this extension. If you think so, please reopen the issue and explain the problem further.
