### ISSUE TITLE
Show dock on holding Super, hide on release

### ISSUE THREAD

**Issue by Lesik** [micheleg/dash-to-dock#684]
Dash to Dock has a great feature which lets you switch between applications using the `Super + Num` keyboard shortcut (with Num = {1..9, 0}), where `Super + 1` is the topmost application in the dock, `Super + 2` is the one below it, etc.

As most people have set the dock to autohide, you don't see which positions the applications are in. With docked applications, you can try to remember the positions manually, but with dynamically opened ones it's impossible.

Luckily, Dash to Dock provides the `Super + q` shortcut, which temporarily shows and hides the dock, so that you can glance at the numbers (displayed next to the applications for extra convenience) and afterwards press the number corresponding to the application you want to show. When the shortcut is pressed, it shows the dock for just three seconds, if you need more time you can simply hold the shortcut instead.

My issue is simply that this shortcut is a mandatory extra step to opening an application from the dock, which slows down productivity, as switching between applications is something people usually do a _lot_. If you only have two applications that you switch between, this is even slower than alt-tabbing. I often find myself alt-tabbing through my applications instead of using this great Dash to Dock feature.

I think a more elegant a solution would be to simply show the dock on holding Super, which is a key you need to press anyway to switch between applications. Then, without releasing Super, you can hit a number key and thus you needed to press just two keys to switch between applications.

What I suspect is that maybe the GNOME Shell API for extensions doesn't allow hijacking the Super key on its own (without an additional key)? Or it doesn't support shortcuts for just _holding_ the Super key? I'd be glad if someone more knowledgeable could shed some light onto this question.

As a workaround, I noticed that Dash to Dock also allows the use of `Super + q + Num` to switch between applications while at the same time showing the dock. So you can start holding `Super + q` for as much time as you need to find your application in the dock, then, without releasing `Super + q`, press the number next to the application. This makes you press only one keyboard shortcut (instead of two), but one which consists of three keys.

**Comment by micheleg** [comment]
Sorry for the late reply and thank for your considerations with which I agree. Yes, there are some limitations with the super buttons (have a look at #469, of which I believe this is a duplicate), although it's not clear if they can somehow workaround it (as per some upstream comment https://bugzilla.gnome.org/show_bug.cgi?id=788159#c1).
