### ISSUE TITLE
Stacking order of window preview shifts

### ISSUE THREAD

**Issue by 8none1** [micheleg/dash-to-dock#686]
I find that when using dock to switch between two windows of the same application, Terminal for example, that the most recent window used is always at the top.

While this makes perfect sense, I find it terribly confusing.  Sometimes the window I want to access is the top one, sometimes it's the bottom one.

I think it would help to keep the windows in the preview stack in the same order at all times.  However, I can see that this is not going to be to everyone's liking, so I'd be delighted with a setting to switch between the two modes.

**Comment by d2a-raudenaerde** [comment]
I agree, I always have issues with this. First I click the second, then decide that is not the 'correct' one. Then open the top one, whick is accidentally replaced by my first action.

So please have a mode where the order will be the order of window creation, so the top window is always the oldest.

**Comment by 8none1** [comment]
I think this is a dupe of: https://github.com/micheleg/dash-to-dock/issues/639

**Comment by micheleg** [comment]
Yes, closing as duplicate.
