### ISSUE TITLE
Make mounted drives be pinnable or automatically show in dock

### ISSUE THREAD

**Issue by dvorapa** [micheleg/dash-to-dock#699]
Repoted downstream: https://github.com/Apricity-OS/apricity-build/issues/76

----
Extension version: 62
Gnome Shell version: 3.26.2
Linux distribution and version: Arch Linux latest/fully updated (build 20180201)
Whether you have a multi-monitor configuration: nope
Your settings:
```$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
preferred-monitor=0
shift-click-action='minimize'
shift-middle-click-action='launch'
extend-height=true
dock-fixed=true
force-straight-corner=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
show-windows-preview=false
show-show-apps-button=false
hot-keys=false
custom-background-color=false
custom-theme-customize-running-dots=true
apply-custom-theme=false
custom-theme-running-dots=true
unity-backlit-items=false
dock-position='LEFT'
custom-theme-shrink=true
icon-size-fixed=true
middle-click-action='launch'
background-color='#ffffff'
isolate-workspaces=true
```

**Comment by uncertainquark** [comment]
Unity had this and is very useful. It'd be great for Dash to Dock to have it as well.

**Comment by adatum** [comment]
Yes, please! 

I was wondering whether I had simply not configured something properly, or if showing mounted volumes on the dock simply isn't implemented. It seems it's the latter. If not, please let me know!

**Comment by dvorapa** [comment]
Solved in the last release!
