### ISSUE TITLE
when open Spotify show 2 icons

### ISSUE THREAD

**Issue by JMGama** [micheleg/dash-to-dock#700]
I have Spotify in my favorites so, it shows in dash to dock bar, but when i open Spotify it show me 2 icons, one that is the application window and the other that if i click on it, it opens an other application window.

**Comment by dvorapa** [comment]
Please include https://micheleg.github.io/dash-to-dock/development.html#bug-reporting some information needed

**Comment by dvorapa** [comment]
Possibly similar to #215 and #602.

**Comment by JMGama** [comment]
Now i see it was a Spotify Problem sorry
