### ISSUE TITLE
Dock doesn't show badge count, if new notifications arrived when screen locked

### ISSUE THREAD

**Issue by eugene-rom** [micheleg/dash-to-dock#708]
Gnome Shell disables extensions on screen lock.
If, for example, new mail will arrived in Thunderbird during screen locked, no badges will be shown on unlock.
Also, lock/unlock screen while badges displayed will clear them.

So, in current implementation, badges looks very unreliable to rely on them, and looks more a mess than a feature.

Solution may be adding a user space daemon, which interact with applications even when dock extension is disabled, and provide badges information for dock.

**Comment by micheleg** [comment]
I believe we should be able to maintain the sync even without having to write an additional daemon, as the info is coming via dbus from the system. I'm normally not running an Ubuntu system so I'm not well aware of the behavior of this feature which was implemented by the Ubuntu people (@azzar1). Did you report the bug to Ubuntu?

**Comment by eugene-rom** [comment]
Yes, reported.
