### ISSUE TITLE
Dash to dock loses styles

### ISSUE THREAD

**Issue by ipergenitsa** [micheleg/dash-to-dock#709]
Panel mode (extend to the screen edge) is enabled. When I unlock screen after it's gone to sleep, dash becomes bigger (height). It becomes normal if I point a mouse over it (height is decreased).
Switching off and on Appearance/Use built-in theme fixes the issue until the next screen sleep.

**Comment by micheleg** [comment]
Hi Igor, sorry for the late reply. 

Could you please provide some additional information. 
* Gnome Shell and extension version.
* Xorg or Wayaland? 
* Basic settings (intellihide, dock position)

When you say bigger, does it means that the icon size is wrong or what? A screenshot might help.

If the bug is easily reproducible, would you mind checking if there's some errors in the logs?
``` journalctl -f /usr/bin/gnome-shell```?

**Comment by AdamKane41** [comment]
After sleep/unlock event, dash-to-dock appears "over" another dash with default settings (Ubuntu's own internal dock?). What @ipergenitsa sees is both  "layers" at the same time. always did that after sleep/unlock...
![peek 2018-04-02 22-57](https://user-images.githubusercontent.com/30092603/38226859-94f4ec9a-36c9-11e8-93c6-0a76d4d0bb22.gif)

**Comment by micheleg** [comment]
@AdamKane41 this is probably a different bug. That's happen if the extension fail to load somehow. I recommend you try to look in the logs for error, and either try to update to the latest version (v63) or as a last resource try to uninstall ubuntu-dock.

**Comment by AdamKane41** [comment]
-updated to v63
-same thing happen after lock screen
-ubuntu-dock is funky when disabled, ... , will try uninstalling it later

my workaround atm is to ALT+F2 r after each lock screen wake events.
peace!

**Comment by micheleg** [comment]
Yes, restarting the shell will reset the the status but it's a bad workaround... Could you have a look at the logs
```journalctl -f /usr/bin/gnome-shell```?

**Comment by AdamKane41** [comment]
Alt. Workaround:
-Ubuntu Dock Shell extension=> [ON]
-Dash to Dock extension=> [OFF]
-No shell reset required anymore.

Now it no longer "duplicate" after lock screen, AND changing the settings of Dash to Dock (while at OFF) will apply live and keep it. No need to re-enable it again. weird!
![peek 2018-04-05 20-49](https://user-images.githubusercontent.com/30092603/38398858-a4d735b2-3914-11e8-857a-2bcbbf88799f.gif)

**Comment by ipergenitsa** [comment]
I used:
`gnome-shell --version`
`GNOME Shell 3.26.2`

extension version: 62.
Sorry but other information is missed. I've just reinstalled the extension and it works fine. Will report if something goes wrong. Thanks

**Comment by AdamKane41** [comment]
gnome 3.26 and dash to dock 62 are 0ld... ubuntu 18.04 uses gnome 3.28 and dash to dock 63...

**Comment by ipergenitsa** [comment]
@AdamKane41, I'm using Ubuntu 17.10

**Comment by micheleg** [comment]
@ipergenitsa closing as I assume the issue didn't re-occurs.

**Comment by jcolares** [comment]
I have the same issue. It's real and very frustrating.
