### ISSUE TITLE
Cannot activate/see thumbnail popup 

### ISSUE THREAD

**Issue by rugk** [micheleg/dash-to-dock#714]
In https://micheleg.github.io/dash-to-dock/release/2017/07/08/new-release-v60.html you introduce this feature:

![](https://micheleg.github.io/dash-to-dock/media/v60-windows-thumbnails-popup-menu.jpg)

I am using v62 and I do not see that behaviour. I see the right-click menu and the previews there, but not the one when hovering the icon.

I have this setting enabled (which i assume might refer to this feature):
![grafik](https://user-images.githubusercontent.com/11966684/37928736-30297b36-313e-11e8-8827-01e9426879c6.png)

GNOME 3.26
Fedora 27

**Comment by micheleg** [comment]
The option to show the previews on hover is not yet available (In version 60 it was made available as one of the click options). The features is till work in progress (see #574).
