### ISSUE TITLE
galician (gl) translation file

### ISSUE THREAD

**Issue by xmgz** [micheleg/dash-to-dock#716]
Dash-to-dock into galician (gl)
[dash2dock_gl.po.zip](https://github.com/micheleg/dash-to-dock/files/1863864/dash2dock_gl.po.zip)

attached is .po file translated for dash-to-dock

I hope it contains no errors and could be added to this extension. Thanks for your work and dont hesitate to contact me if needed

**Comment by micheleg** [comment]
Thanks! Merged [faafac2ebf44].
