### ISSUE TITLE
When adding an app to favourites, two icons are created

### ISSUE THREAD

**Issue by frenchy82** [micheleg/dash-to-dock#718]
on a fresh install of ubuntu 18.04 , When adding an app to favorites, there were two items of the application created in the ubuntu dock 

 I have this bug when adding terminal or totem or cheese with right click on the icon from the applications menu or with a drag and drop

**Comment by micheleg** [comment]
Closing as it is an upstream issue then.

**Comment by julian-alarcon** [comment]
Hey @micheleg this is obviously an upstream (gnome-shell) bug, but, do anybody has the bug number against gnome-shell?
