### ISSUE TITLE
New styles are drawn over default style

### ISSUE THREAD

**Issue by dialvarezs** [micheleg/dash-to-dock#720]
- OS: OpenSUSE Tumbleweed
- Gnome: 3.28
- Themes: Adapta-Nokto (Shell & GTK), Flat Remix Dark (Icons)

The new styles in v63 are great, but for me the default style is always behind, ruining the aesthetic. I tried with all options, but I can't make it work like it's supposed to be.

Screenshot:
![captura de pantalla de 2018-04-05 15-47-23](https://user-images.githubusercontent.com/13831919/38386046-f55737a6-38e9-11e8-91fe-318aded8a5b0.png)

Thanks,

**Comment by micheleg** [comment]
Can you confirm if this is a regression introduced in version 63? I believe those styles are provided by the theme you are using. Unfortunately, I cannot support individually all third parties themes.

**Comment by dialvarezs** [comment]
I didn't mean this was a regression, it's just the same as #727. And you're right, it works as spected with Adwaita, so it's an incompatibility issue.
