### ISSUE TITLE
Rather unfortunate typo

### ISSUE THREAD

**Issue by eboyblue3** [micheleg/dash-to-dock#723]
![image](https://user-images.githubusercontent.com/28734874/38598611-af6ea444-3d22-11e8-938d-74ee59ee2560.png)
Unless you are targeting users who frequently compute from the toilet, this line in org.gnome.shell.extensions.dash-to-dock.gschema.xml should be fixed.

**Comment by micheleg** [comment]
Oh shit! Thank you! Fixed now (7cd5897).
