### ISSUE TITLE
Detaching secondary monitors and dash to dock isolation

### ISSUE THREAD

**Issue by jelovac** [micheleg/dash-to-dock#729]
Hello,

I use dash to dock on Ubuntu 17.10 with the following setup: laptop + 2 monitors connected via the docking station.

The dash on the two secondary monitors is isolated via dash to dock 'isolate monitors + isolate workspaces option'.

The annoyance I noticed is when I detach the laptop from the docking station is that active dash items don't fall back from the isolated docks to the dash to dock on the primary monitor. The apps are still active however I cannot reach them.

Regards,
Vladimir

**Comment by micheleg** [comment]
Thank you for your bug report. I tried reproducing it on my system (with only one secondary monitor attached) but to me launchers seems to be moving back to the main dock as expected. Could you confirm your extension and gnome-shell version? Would you be able to confirm if it also occurs in the simpler case of  a single secondary monitor?

**Comment by jelovac** [comment]
Hello,

The dash to dock extension version is: 62
Gnome shell version: 3.26.2

Couldn't reproduce it again, but it happens from time to time. I am thinking it has something to do when waking up from hibernation on Ubuntu 17.10.

Closing this ticket, If I found out how to reproduce it I will reopen it.

Regards,
Vladimir
