### ISSUE TITLE
Show applications text is to the right in every dock orientation.

### ISSUE THREAD

**Issue by DEA7H-INC** [micheleg/dash-to-dock#732]
![](https://i.imgur.com/TszFlAg.png)

Text for all other applications is normal I.E when dock is on bottom text is on top / dock on right text on left but Show applications is always to the right. Occurs for me in both ubuntu 16.04 and ubuntu 18.04 using vanilla gnome.

in 16.04 tried using dconf reset -f /org/gnome/shell/extensions/dash-to-dock/ with no luck. installing version 60 of dash-to-dock fixes it. Version 61 and 62 for gnome shell 3.18 seem to have the issue for me and whatever version gets pulled in for ubuntu 18.04.

**Comment by DEA7H-INC** [comment]
so in 16.04 using dconf reset -f /org/gnome/shell/extensions/dash-to-dock/ and installing Version 60 of dash-to-dock fixes it. I'm not sure what changed in 61+ but that might help.

**Comment by micheleg** [comment]
Thanks for reporting the bug. I think it is fixed now by 5e38a58.
