### ISSUE TITLE
Ubuntu dock still showing in activities overview

### ISSUE THREAD

**Issue by rayfun** [micheleg/dash-to-dock#739]
Hi,
I'm on a Ubuntu 18.04 release with the default Ubuntu Gnome.
I've installed Dash-to-Dock from git source.
It works great but the default Ubuntu dock is still showing in the activities overview.
Are there any other extensions, tricks, tweaks that can fix this?
Please see attached screenshot.

Best regards,
Ray

![screenshot from 2018-05-15 14-00-17](https://user-images.githubusercontent.com/15213735/40055884-c9da00f2-5849-11e8-9ca1-36733726b452.png)

**Comment by fcastilloec** [comment]
I had the same issue, I fixed it by uninstalling Ubuntu Dock.
Just run `sudo apt purge gnome-shell-extension-ubuntu-dock` and after restarting gnome-shell you're good to go. Since there's no point in having both installed/enabled, this is a safe approach.

**Comment by rayfun** [comment]
This would also uninstall the Ubuntu desktop meta package.
Not sure if this is a good thing to do :-/

```
~$ sudo apt purge gnome-shell-extension-ubuntu-dock
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  gnome-shell-extension-ubuntu-dock* ubuntu-desktop*
```

**Comment by fcastilloec** [comment]
It's safe to remove the `ubuntu-desktop` package. Like you mentioned, it's just a meta package that holds a lot of dependencies when installing Ubuntu. It's only useful if you're planning on upgrading from 18.04 to 18.10 or any future version when they are released. I never update Ubuntu this way, always a fresh install, so the package is irrelevant.

**Comment by sebanderson** [comment]
I took @fcastilloec's advice; it required a restart but I think the dock is finally gone in Activities Overview. :D

**Comment by SazhnevDI** [comment]
@fcastilloec  thx! It's work for me.

**Comment by vsimitsis** [comment]
@fcastilloec Thanks! It works for me too

**Comment by micheleg** [comment]
Closing this then.

**Comment by na21** [comment]
@fcastilloec Is there a way to reinstall the `ubuntu-desktop` meta package if you would want to?

**Comment by fcastilloec** [comment]
@na21 yes, just type `sudo apt install ubuntu-desktop` on a command line and you're good to go. But this will install all of its dependencies, including `gnome-shell-extension-ubuntu-dock` which is what was causing this bug.
