### ISSUE TITLE
Ubuntu 18.04 ubuntu-dock notifications and progress bar.

### ISSUE THREAD

**Issue by k0rbendallas** [micheleg/dash-to-dock#741]
In ubuntu 18.04 there are no working notifications badges (the number per app icon in the dock) and the progress bar in the ubuntu-dock application for Thunderbird, Firefox and other applications.

It is possible to activate this notification, as on the page at https://micheleg.github.io/dash-to-dock/release/2017/12/25/new-relsease-v62.html?

![screen_008](https://user-images.githubusercontent.com/12039251/40238845-0e8a86fc-5abd-11e8-9e6b-bb77297e56eb.png)

**Comment by iLynux8888** [comment]
They work? Really? I am also having a problem with this on 18.04. Vanilla install doesn't even have them.

Also tried manually installing dash-to-dock v63, which should have this feature, and it doesn't. Xorg or Wayland, same problem.

**Comment by Feichtmeier** [comment]
I think the problem is that not every app suports it.

So far badges are only supported by Geary and Telegram :man_shrugging: 
I believe thunderbird used to support them a while back but I think they maybe miss something now

**Comment by micheleg** [comment]
To clarify, the support is typically only on Ubuntu (and it should work out of the box) and from those applications that have been patched to support the specific dbus protocola developed by the Ubuntu people.

**Comment by Austcool-Walker** [comment]
Thats sucks fuck you canonical for not explaining there source code and help contribute to upstream GNU/Linux

**Comment by azzar1** [comment]
> Thats sucks fuck you canonical for not explaining there source code and help contribute to upstream GNU/Linux

The API are documented here: https://wiki.ubuntu.com/Unity/LauncherAPI. To use the API there is no need to use libunity, you can use directly dbus and it should work.

It would be nice to have a generic API (something under the freedesktop domain) but to my knowledge there is nothing like that atm.
