### ISSUE TITLE
Mouse gets stuck on secondary monitor after making a window full screen on primary monitor

### ISSUE THREAD

**Issue by logix2** [micheleg/dash-to-dock#743]
The mouse cursor gets stuck on secondary monitor after making a window full screen on primary monitor (positioned on the left of the secondary monitor) when using Dash to Dock or Ubuntu Dock, with the following conditions:

1. Multi-monitor setups (obviously)
2. Ubuntu Dock / Dash to Dock with the auto-hide option enabled
3. Ubuntu Dock / Dash to Dock set to show on all displays
4. Ubuntu Dock / Dash to Dock position set to left (this is the default setting)
5. No window covering the Ubuntu Dock / Dash to Dock on the second monitor (so dock is visible on the second monitor)

The bug continues to occur after exiting full screen.

Changing any of this and the issue stops occurring.

I explained this with more details on my blog: [https://www.linuxuprising.com/2018/05/dual-monitor-fix-mouse-getting-stuck-on.html](https://www.linuxuprising.com/2018/05/dual-monitor-fix-mouse-getting-stuck-on.html)

I tested this in Ubuntu 18.04 with gnome-shell-extension-ubuntu-dock 0.9.1 / Dash to Dock v62 installed from the Gnome extensions website.

**Comment by TheBishopOfSoho** [comment]
This same issue happens with me, on 18.04.1, version 64 of Dash to Dock. When I have the mouse cursor on secondary monitor, positioned above my laptop monitor, if I hit super to start searching for an app in the Activities pane, once I start typing, if i try to bring the mouse down onto the primary monitor it gets stck at bottom of secondary. Disabling the dock on all monitors fixes this but is not ideal

**Comment by mariorodriguespt** [comment]
I've a variation of this bug but without the docker on both monitors. I suspect this could be, partially, due to Nvidia drivers. Once I wake my computer, I've some glitches in some applications, specially electron apps. Right now, I can move my cursor to my second monitor (monitor above my laptop, top position) but sometimes when I try to move down to the primary monitor: There's a wall and my cursor gets stuck, it's like a very specify invisible line at some Y position, because above that line I can move my cursor freely.

If I try to move several times, eventually my mouse will be set free and I can go back to the primary monitor.

**Comment by Lukypie** [comment]
I am experiencing the same, I workarounded this by just pressing the super key

**Comment by luispabon** [comment]
Here for a variation https://github.com/micheleg/dash-to-dock/issues/930

Basically it's not primary / secondary display related, but positioning of the displays and direction of travel of the pointer

**Comment by micheleg** [comment]
Can you have a look at #936? I believe this should at least fix @luispabon problem, maybe the others mentioned here too (and hopefully it doesn't break anything else).

**Comment by DmitryShuba** [comment]
Try this out, it helped me:
1. Open the GNOME Extensions(https://extensions.gnome.org/local/) and find the "Dash to dock" extension.
2. Open its settings and click on the "Intelligent autohide" settings icon.
3. Uncheck "Push to show: require pressure to show the dock".

**Comment by sdlins** [comment]
This bugs also happens if you:

1. Open app indicator menu (top right);
2. Move your cursor to the right monitor;

Now you can't go back. The only way is pressing `ESC` to close app indicator menu so that you can go back.

This only happens when dock autohide is on.

**Comment by kyrrr** [comment]
Not a dash to dock issue for me, but posting it here for future googlers. For me the issue is the extension Custom Hot Corners - Extended. Haven't fiddled with the settings to see what can be changed to have both dual monitors and hot corners, but disabling it worked for me.
