### ISSUE TITLE
New window location doesn't play well with dash intelligent autohide

### ISSUE THREAD

**Issue by memeplex** [micheleg/dash-to-dock#759]
I've reported this at https://gitlab.gnome.org/GNOME/gnome-shell/issues/370 but maybe is relevant here:

> New windows open in cascade starting at the right side of the dock. When the dash extension is configured to intelligently autohide new windows open at the left of the screen, over the dock, and consequently the dash hides itself. This is inconvenient since there is place in the screen to keep both the dash and the window visible. Intelligent autohide is useful for big/maximized windows, otherwise it's not as intelligent as announced :)

**Comment by micheleg** [comment]
Known limitation #105. I don't know if the settings ` /org/gnome/mutter/center-new-windows` woud help you . Closing as duplicate.
