### ISSUE TITLE
Legacy tray is missing

### ISSUE THREAD

**Issue by maciej-lech** [micheleg/dash-to-dock#766]
Hi Guys,

I've encountered an issue while using dash-to-dock 63 installed from the Gnome webpage.
When dash-to-dock is installed, legacy tray is missing after Gnome Shell restart. Even if I have plugins like TopIconsPlus installed. Any tips how to make legacy tray visible again?

I'm using Ubuntu 18.04 and Gnome Shell 3.28

Thanks in advance!
Maciek

**Comment by panjandrum** [comment]
Setting dump shown below, however changing configuration has no impact what so ever.
```
$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
animate-show-apps=false
show-apps-at-top=false
customize-alphas=true
extend-height=true
dock-fixed=true
max-alpha=1.0
click-action='minimize'
hot-keys=false
multi-monitor=true
scroll-action='switch-workspace'
apply-custom-theme=false
isolate-monitors=true
dock-position='LEFT'
custom-theme-shrink=true
icon-size-fixed=true
min-alpha=0.0
dash-max-icon-size=32
transparency-mode='ADAPTIVE'
```

**Comment by typekpb** [comment]
@panjandrum not sure, but sounds like legacy tray is no more present in the gnome version you use: https://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray

**Comment by panjandrum** [comment]
@typekpb yes it's removed by default. But can be restored with extensions like TopIcons Plus or kStatus/Appindicator. And those extension work just fine when dash-to-dock in not installed. Once I install dash-to-dock they stop working.

**Comment by micheleg** [comment]
We should not be doing anything related to the legacy try in revent version https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L1124 but wer might mess up with its positioning. Does the tray appear if you change the dock position for instance on the right?

**Comment by treba123** [comment]
I have both, dash-to-dock and kStatus/Appindicator installed and they work together. TopIcons Plus is badly broken on new releases and people should stop using it (or somebody has to update it :/ )

**Comment by panjandrum** [comment]
@micheleg change the position doesn't work for me.
