### ISSUE TITLE
"Use keyboard shortcuts to activate apps" disabled after screen lock

### ISSUE THREAD

**Issue by ultraUser76** [micheleg/dash-to-dock#773]
"Use keyboard shortcuts to activate apps" is disabled after screen lock.

To get it to work again I have to go and disable/enable button. 
For a period of time works as normal and again... the keyboard shortcuts breaks.

Ubuntu 18.04 
Gnome 3.28.2 
Extension installed: Dash To Dock.

Thanks.

**Comment by micheleg** [comment]
Maybe related to #648

**Comment by ultraUser76** [comment]
Fixed on Ubuntu 18.10 following instructions by Sarki on #649 .

$ sudo mv /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com ~/.local/share/gnome-shell/extensions
# reboot system. 

In fact the solution proposed by Sarki fix two things for me:
1- Keyboard shortcuts disabled after screen lock
2- Dash to dock shows on lock screen.

:smile:
