### ISSUE TITLE
Gnome Shell 3.28 hangs when using dash to dock with dual monitors in overview screen

### ISSUE THREAD

**Issue by ghost** [micheleg/dash-to-dock#774]
Hi,
First of all, fantastic work and excellent extension. Thank you for your efforts!

now, for the bug, 

After installing Ubuntu 18.04, if I am connected to an external monitor, and enter the overview mode with super key, dash to dock makes gnome shell hang. It doesn't exit the overview mode after this. Although panel indicators and menus ( and alt + f2) work. 

I have tested this by disabling dash to dock and gnome runs perfectly with dual monitors.

Gnome version : 3.28 ( extension version : 63 )

**Comment by micheleg** [comment]
Could you give some more details of your configurations: Wayland/Xorg? Intel/Nvidia? Monitor configuration (resolutions and relative position)

Also, could you check the logs `journalctl  -f /usr/bin/gnome-shell` when this happen?

**Comment by vanvugt** [comment]
Closing due to no response for almost 5 years. A similar issue is still open in #2000.
