### ISSUE TITLE
Ubuntu Dock is interfering with dash-to-dock functionality 

### ISSUE THREAD

**Issue by thedonquixotic** [micheleg/dash-to-dock#778]
I have disabled Ubuntu Dock in my Gnome Tweaks settings, and I use dash to dock instead but upon restarting my computer I see this:

![image](https://user-images.githubusercontent.com/9451726/43476298-e369fc42-94bd-11e8-8adf-4dcbb444410e.png)

These are both interactive. They also auto hide, though only the dash to dock will properly pop out when I push my mouse up top while a windows is maximized. 

This is really more of an Ubuntu Dock bug as far as I can see but I'm still looking for their git and I figured someone here might have some advice.

**Comment by micheleg** [comment]
try to force reset the settings with `dconf reset  /org/gnome/shell/extensions/dash-to-dock/`. This is somethin in line with these bug  (#762, #649).

**Comment by thedonquixotic** [comment]
Excellent, thank you @micheleg
