### ISSUE TITLE
Dock not hidden/disabled in lock screen

### ISSUE THREAD

**Issue by idovitz** [micheleg/dash-to-dock#78]
Dont know if its an gnome issue.. In gnome 3.10 in ArchLinux the dock is not hidden and can be clicked in the gnome lock screen. Programs can be started but are only visible after unlock. With additional extension "launch new instance" it is possible for any person with physical access to pc to start many programs as possible.

**Comment by alexmurray** [comment]
I've been seeing this periodically lately - usually I notice it when I resume from suspend. Running Ubuntu 16.04 with latest dash to dock installed from extensions.gnome.org
```
$ tail -n 2 .local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json 
  "version": 61
```

**Comment by micheleg** [comment]
Please have a look at your logs when this happen. 
```journalctl -f /usr/bin/gnome-shell```

This usually happens when there's an error, and the function supposed to hide the dock does not get run.

**Comment by chiranshu14** [comment]
I have the same problem: 
my logs after your given command are : 

chiranshu@chiranshu:~$ journalctl -f /usr/bin/gnome-shell
-- Logs begin at Wed 2017-11-08 21:56:50 IST. --
Nov 09 07:37:20 chiranshu org.gnome.Shell.desktop[2549]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-6".
Nov 09 07:37:20 chiranshu org.gnome.Shell.desktop[2549]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-7".
Nov 09 07:37:20 chiranshu org.gnome.Shell.desktop[2549]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-8".
Nov 09 07:37:20 chiranshu org.gnome.Shell.desktop[2549]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-9".
Nov 09 07:37:20 chiranshu org.gnome.Shell.desktop[2549]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-10".
Nov 09 07:37:20 chiranshu org.gnome.Shell.desktop[2549]: Window manager warning: Trying to re-add keybinding "shortcut".
Nov 09 07:37:20 chiranshu gnome-shell[2549]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.266/org/ayatana/NotificationItem/deluge
Nov 09 07:37:20 chiranshu gnome-shell[2549]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.72/org/ayatana/NotificationItem/indicator_sound_switcher
Nov 09 07:37:20 chiranshu gnome-shell[2549]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.96/org/ayatana/NotificationItem/software_update_available
Nov 09 07:37:20 chiranshu gnome-shell[2549]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.71/org/ayatana/NotificationItem/blueman

**Comment by stfnppv** [comment]
Yeah, I have the same problem in Aartful Ardvark.

**Comment by leandrolanzieri** [comment]
I'm having the same problem on Ubuntu 18.04. Flat remix theme. My log is:

```
leandro@Asus:/usr/local$ journalctl -f /usr/bin/gnome-shell
-- Logs begin at Wed 2018-05-09 08:30:43 -03. --
may 31 19:15:47 Asus org.gnome.Shell.desktop[2769]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-7".
may 31 19:15:47 Asus org.gnome.Shell.desktop[2769]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-8".
may 31 19:15:47 Asus org.gnome.Shell.desktop[2769]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-9".
may 31 19:15:47 Asus org.gnome.Shell.desktop[2769]: Window manager warning: Trying to re-add keybinding "app-ctrl-hotkey-10".
may 31 19:15:47 Asus org.gnome.Shell.desktop[2769]: Window manager warning: Trying to re-add keybinding "shortcut".
may 31 19:15:47 Asus gnome-shell[2769]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.67/org/ayatana/NotificationItem/software_update_available
may 31 19:15:47 Asus gnome-shell[2769]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.65/org/ayatana/NotificationItem/chrome_app_indicator_1
may 31 19:15:48 Asus gnome-shell[2769]: [Dynamic Panel Transparency] Using theme data for: Adwaita
may 31 19:15:48 Asus gnome-shell[2769]: [Dynamic Panel Transparency] Failed to find shell theme settings. Ignore this if you are not using a custom theme.
may 31 19:15:48 Asus gnome-shell[2769]: percentage lengths not currently supported
```
Here is what happens:
![capture](https://user-images.githubusercontent.com/5381296/40811407-7a207030-6507-11e8-9a0e-b8e549152a1b.jpg)

Thank you!

**Comment by TiredMir** [comment]
Uhm, bump on the Ubuntu 18.04?

**Comment by sanketnadkarni** [comment]
having same problem
