### ISSUE TITLE
Please pull ubuntu-dock-bionic branch

### ISSUE THREAD

**Issue by 3v1n0** [micheleg/dash-to-dock#780]
Pull with tags from https://github.com/3v1n0/dash-to-dock/tree/ubuntu-dock-bionic

@didrocks build is ready for being published in https://bileto.ubuntu.com/#/ticket/3338

Thanks :)

**Comment by didrocks** [comment]
Answered on the PR, please redo it with quilt patches as you proposed. Then, we can pull with tags ;)

**Comment by 3v1n0** [comment]
This should be fixed, not using quilt at this point as we keep the fork.
