### ISSUE TITLE
Dock size limit always showing

### ISSUE THREAD

**Issue by fisken** [micheleg/dash-to-dock#784]
Installed on a fresh ubuntu 18.04.

The dock size limit is always showing, can't seem to hide it in anyway. See the attached photo.

![dash-to-dock](https://user-images.githubusercontent.com/3316950/43673728-034be9dc-97c8-11e8-9e78-219553694fc6.png)

**Comment by fisken** [comment]
Had to disable the dock in "tweaks" now it working correct.

**Comment by Racle** [comment]
If anyone else is having this issue, I fixed this with removing the ubuntu dock and rebooting
```
sudo apt remove gnome-shell-extension-ubuntu-dock
```
Ubuntu dock was already disabled on my system (18.04), so that wasn't a choice.
