### ISSUE TITLE
Request gnome-shell 3.30 support

### ISSUE THREAD

**Issue by dino99** [micheleg/dash-to-dock#786]
Ubuntu cosmic (18.10) has loaded gnome-shell and mutter 3.29.90+ , and that breaks this useful extension.
Please add the required support to get it compatible.

**Comment by jbicha** [comment]
This might already be fixed in git master with commit 8398d41c6c

**Comment by treba123** [comment]
I can confirm that current git master works against mutter 3.29.91 / gnome-shell 3.29.90

**Comment by micheleg** [comment]
Support for 3.30 explicitely enabled [0ceb6043]. New release prepared (v64).
