### ISSUE TITLE
The dash is not respecting my local settings for Gtk Themes (on .desktop files )

### ISSUE THREAD

**Issue by ErickTucto** [micheleg/dash-to-dock#787]
I created a .desktop file and then added it to my favorites to use a different theme than the default one(For example `Exec= env GTK_THEME= Numix firefox %u`), but the Dash ignores this configuration. @eevleevs have the same problem. [See Comment](https://github.com/micheleg/dash-to-dock/issues/462#issuecomment-326899848) (#462)

**Comment by micheleg** [comment]
Closing as duplicated. Follow the discussion in #462.
