### ISSUE TITLE
Dash appears on lock screen and after this appears second dash in activity area

### ISSUE THREAD

**Issue by Dimarei** [micheleg/dash-to-dock#788]
![image](https://user-images.githubusercontent.com/40320374/44262016-5fc9bb00-a211-11e8-83ca-b0a752219389.png)
Basically, when system show the lock screen appears a dash on it, and after this at activity menu and app menu appears second dash.

**Comment by qingju32** [comment]
just trun off the dash to dock, and you can still use the sets of dash to dock, maybe you need set once more.

**Comment by qingju32** [comment]
Actually, what I'm trying to say is "turn off", It works for me. Don't turn on dash to dock. The settings are still useful when the dash to dock shuts down.

**Comment by micheleg** [comment]
Closing as duplicate  of #641.
