### ISSUE TITLE
Implement rounded corners when dock is persistent.

### ISSUE THREAD

**Issue by gmlshadi** [micheleg/dash-to-dock#792]
![image](https://user-images.githubusercontent.com/11833878/44468083-158b7400-a62d-11e8-9be9-dc7453c792ac.png)  ![image](https://user-images.githubusercontent.com/11833878/44468136-35bb3300-a62d-11e8-80c7-8be22cf7e8e1.png) the extension would fit in better with the desktop if the corners were round. also windows would look nicer.

**Comment by micheleg** [comment]
This can't be controlled from the extension.

**Comment by gmlshadi** [comment]
There is no way to change the shape of the dock?
