### ISSUE TITLE
Duplicated count indicators when changing visualization

### ISSUE THREAD

**Issue by tflori** [micheleg/dash-to-dock#795]
When I change the count indicators it shows them twice. Also I'm not able to disable them - the dot's are always shown.

Here is a screenshot with metro style enabled:
![bildschirmfoto von 2018-08-24 12-34-21](https://user-images.githubusercontent.com/4855611/44580492-65d41480-a79a-11e8-8320-c237b20216aa.png)

I'm running ubuntu 18.04 with gnome-shell 3.28.2 on X11 and the installed dash-to-dock extension has version 63.

**Comment by micheleg** [comment]
Are maybe the dots provided by the theme?

**Comment by tflori** [comment]
you mean the gtk theme, or the gnome shell theme? yes, maybe. I can't disable them somewhere else - or is there a way to disable them in gnome tweak or somewhere else?

**Comment by tflori** [comment]
This is solved by the theme maintainer, thanks!
