### ISSUE TITLE
Dock will appear in the Gnome lock screen after a user has locked their session

### ISSUE THREAD

**Issue by osilkin98** [micheleg/dash-to-dock#796]
# Dash will appear at the lock screen during a locked user session
#### Swipe to enter screen:
![](https://user-images.githubusercontent.com/16809287/44615492-cbf38280-a800-11e8-894b-f42f543b812b.jpg)

#### Password input screen:
![](https://user-images.githubusercontent.com/16809287/44615513-386e8180-a801-11e8-81e0-82c5dafc6994.jpg)

**Comment by micheleg** [comment]
Closing this as duplicate (#726).

**Comment by osilkin98** [comment]
This isn't a duplicate of #726 because this issue persists in version 63 which you claimed to have fixed in that thread
