### ISSUE TITLE
Counter indicatior not showing anymore

### ISSUE THREAD

**Issue by zer09** [micheleg/dash-to-dock#798]
the highlight on which app is open and the counter indicator is not showing anymore, here is my screenshot. 
![screenshot from 2018-08-30 07-51-36](https://user-images.githubusercontent.com/780780/44821794-05295980-ac2a-11e8-8acc-75ad7d9c7076.png)

Dash-to-Dock ver: 61
OS: Fedora 28
GNOME Shell ver: 3.28.3

Thanks

**Comment by hmarthinsen** [comment]
The same thing happened to me, but I managed to get the indicators back by turning extensions off and on again in GNOME Tweaks.
![untitled](https://user-images.githubusercontent.com/6989581/44840817-331a9800-ac42-11e8-9110-82473e671bfd.png)

**Comment by dvorapa** [comment]
@zer09 Does the suggested solved your issue?

**Comment by zer09** [comment]
@dvorapa If I recall it correctly, I think it was.
