### ISSUE TITLE
Deprecation warning: GenericContainer to be removed

### ISSUE THREAD

**Issue by treba123** [micheleg/dash-to-dock#799]
There is a upcoming [big MR](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/153) for gnome-shell removing GenericContainer. It's not going to land for gnome 3.30, but it's maybe good to know in advance.
I'm not sure but it should be already possible to adapt the code accordingly without breaking backward compatibility

With the patches of the branch applied, dash-to-dock fails with the following error:
```
Sep 03 13:36:19 robert.thinkpad-x230 gnome-shell[7886]: JS WARNING: [/home/robert/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js 71]: reference to undefined property "GenericContainer"
Sep 03 13:36:19 robert.thinkpad-x230 gnome-shell[7886]: Extension "dash-to-dock@micxgx.gmail.com" had error: TypeError: Shell.GenericContainer is not a constructor
```

**Comment by micheleg** [comment]
Thanks for the information, I was actually reading through the merge request. I'm quite concern this migt be problematic because of [41a315cd5].

**Comment by jonian** [comment]
It is merged now and will be available in GNOME 3.30.2

https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/153
https://www.reddit.com/r/gnome/comments/9n0h7v/call_for_action_big_work_landed_in_gnome_shell

**Comment by treba123** [comment]
Well, it should be noted that in 3.30.2 GenericContainer won't be used any more by gnome-shell itself, but it's still available for extensions. The actual removal was split out to https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/257 and will land in 3.32

**Comment by micheleg** [comment]
#825

**Comment by micheleg** [comment]
Closing as #825 was merged in master.
