### ISSUE TITLE
[Question] Is there any option in order to lock the dock?

### ISSUE THREAD

**Issue by ceyhunnabiyev** [micheleg/dash-to-dock#802]

**Comment by micheleg** [comment]
I assume you are asking for something linke this #771, which is a feature not available yet.

**Comment by ceyhunnabiyev** [comment]
Hi @micheleg ,
I mean, to lock the  dock - to be in fixed position, can't move icons to anywhere , changing position of dock icons  can't be possible.

**Comment by micheleg** [comment]
The position is fixed as you need to go into the settings to change that. Instead there's no option to fully lock the icons.
