### ISSUE TITLE
Fights with workspaces to dock and messes lock screen

### ISSUE THREAD

**Issue by horga83** [micheleg/dash-to-dock#810]
When I have Workspace to dock installed as well as Dash to Dock the screen lock fails when initiated.  Basically the background disappears, Dash to Dock disappears, workspaces to Dock stays on the screen and there is no way to recover except Control-Alt-Backspace.

**Comment by horga83** [comment]
This issue seems to have resolved itself.

**Comment by micheleg** [comment]
Closing then.
