### ISSUE TITLE
Dash to Dock crashes on an error. 

### ISSUE THREAD

**Issue by prashanthglen** [micheleg/dash-to-dock#813]
Dash to Dock crashes on startup with a prompt on gnome tweak tool saying error loading extension.

version: 64
Gnome version: 3.30.0
Linux distribution: Arch Linux
Linux version: 4.18.9-arch1-1-ARCH x86_64

**error in Looking Glass**:
TypeError: object is undefined

**settings**:
[prat@prat-arch ~]$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
apply-custom-theme=false
multi-monitor=false
dock-fixed=false
preferred-monitor=0

**Journalctl output while re-installing Dash to Dock**:

Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]: Archive:  /tmp/5FKXPZ.shell-extension.zip
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/nb/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/cs/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/tr/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/cs/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/fr/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/de/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/el/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/id/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sk/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/fr/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/it/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/ru/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sr@latin/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/uk_UA/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/pt/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/pt_BR/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/gl/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/id/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/ru/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/hu/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/ja/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sr/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/ar/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sv/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/fr/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/de/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/es/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/hu/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/gl/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/pt/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sv/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/README.md
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/highlight_stacked_bg.svg
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/COPYING
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/zh_CN/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/logo.svg
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/glossy.svg
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sk/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/intellihide.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/pl/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sr@latin/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/pl/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/pl/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/extension.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/nl/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/nl/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sr@latin/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/nl/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/launcherAPI.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/zh_CN/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/sr/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/convenience.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/zh_CN/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/utils.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/zh_TW/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/Settings.ui
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/cs/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/pt_BR/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/media/highlight_stacked_bg_h.svg
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/windowPreview.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:    creating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/es/LC_MESSAGES/
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/locale/es/LC_MESSAGES/dashtodock.mo
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:   inflating: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js
Sep 22 04:22:16 prat-arch org.gnome.Shell.desktop[2886]:  extracting: /home/prat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json
Sep 22 04:22:17 prat-arch gnome-shell[2886]: Extension "dash-to-dock@micxgx.gmail.com" had error: TypeError: object is undefined

**Comment by ShinZ6** [comment]
same problem here

**Comment by micheleg** [comment]
Could you run gnome-shell --replace in a terminal and see the logs there when it crash? Sometimes they are more informative. Also, are you on wayland? I can't reproduce the issue on Ubuntu 18.10.

**Comment by skalarproduktraum** [comment]
@micheleg @prashanthglen's approach actually also fixed it for me. I am very confused now -.-

**Comment by prashanthglen** [comment]
I have had no problems with the Dash to Dock since my last comment. Moving to close this issue.

**Comment by Ansh-me2** [comment]
GNOME Shell-Message: 20:08:17.902: Extension "dash-to-dock@micxgx.gmail.com" had error: TypeError: Me is null

**Comment by bitsofmymind** [comment]
Reinstalling the extension and doing gnome-shell --replace also seemed to have done the trick. It also fixed a bunch of other extensions that were giving off the same error.
