### ISSUE TITLE
cannot use run the make file

### ISSUE THREAD

**Issue by thymargo13** [micheleg/dash-to-dock#822]
after I git clone the repo, and I type make, I got the following error:

glib-compile-schemas ./schemas/
msgfmt -c po/de.po -o po/de.mo
make: msgfmt: Command not found
make: *** [Makefile:54: po/de.mo] Error 127

**Comment by micheleg** [comment]
You are missing some package. On ubuntu/debian installing `gettext` should fix the problem. On other distributions you need to look for the package containing that executable.
