### ISSUE TITLE
`Scroll action -> switch workspace` doesn't work

### ISSUE THREAD

**Issue by wotmshuaisi** [micheleg/dash-to-dock#827]
after i upgrade my dash to dock plugin, i try to use mouse wheel scrolling any icon on the favourite panel, it not work anymore, except `applications icon`

**Comment by danielbitesdog** [comment]
Same issue on gnome 3.30

**Comment by micheleg** [comment]
The settings are not very clean. The behaviour also depends on the "fixed icon size" option  being activated or not (See #710). Is this what you are experiencing? If not, is it something limited to a wayland session?

**Comment by wotmshuaisi** [comment]
> The settings are not very clean. The behaviour also depends on the "fixed icon size" option being activated or not (See #710). Is this what you are experiencing? If not, is it something limited to a wayland session?

oh thanks it works now
