### ISSUE TITLE
Feature: switch windows with Forward/Backward mouse buttons

### ISSUE THREAD

**Issue by usbkey9** [micheleg/dash-to-dock#830]
Hi guys,
Please allow user to switch windows with Forward/Backward mouse buttons
Eg:

Focus on Window A, whatever workspace
Focus on Window B, whatever workspace
Mouse/keyboard backward button pressed
Go and focus on window A
Mouse/keyboard forward button pressed
Go and focus on window B

I think it's kind of usefull in heavy using workspace
Best

**Comment by micheleg** [comment]
This is outside the scope of the project, as it relate to the overall gnome windows management rather than the dock itself.
