### ISSUE TITLE
Customized windows counter  indicators show over default

### ISSUE THREAD

**Issue by yar0d** [micheleg/dash-to-dock#832]
Hello,

Dash-to-doc version 64 display Ciliora courters (and other kinds too) over the default counter indicators.

Here is a screenshot of what that look like:
![capture d ecran du 2018-11-09 10-20-45](https://user-images.githubusercontent.com/190219/48254346-1b158080-e40a-11e8-8d4e-818718aa02cf.png)

OS: Arch Linux 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
GPU: Intel® HD Graphics 620 (Kaby Lake GT2)  and  Xorg server.
Desktop: Gnome 3.30.2

**Comment by Koriban** [comment]
same issue here. Occurs with ANY of the non default options

System:  
Ubuntu 18.10
Ubuntu's Dock removed, installed from gnome's site

**Comment by micheleg** [comment]
Is that with the default theme or with a custom one? What happen if you set the indicator style to Default?

**Comment by yar0d** [comment]
It occurs with the default theme. Setting indication to default display correctly the default indicators.

**Comment by yar0d** [comment]
I misanderstood what you ask me. With Gnome default theme it's ok, indicators are corrects. I apologize!
