### ISSUE TITLE
[ubuntu-dock] minimize/preview behavior

### ISSUE THREAD

**Issue by ghost** [micheleg/dash-to-dock#833]
Hello,

I understand that ubuntu-dock doesn't have a lot of settings to keep it beginner-friendly, however it's kinda sad to see that when we click on an opened app it does absolutely nothing. It would be natural and useful if clicking on something would minimize and restore (show previews if several windows), like one of the default behaviors available in dash-to-dock.

**Comment by vanvugt** [comment]
Duplicate of #594

**Comment by vanvugt** [comment]
Duplicate of #365
