### ISSUE TITLE
Anyone maintaining this issue tracker?

### ISSUE THREAD

**Issue by rugk** [micheleg/dash-to-dock#835]
Can someone please maintain it?

There are many, many (open) duplicates and it is really awkward to find the one that may be valid/has the most users now. I'd also say it does not make tracking/fixing/developing these issues easier to have 500 duplicates of each topic.

One example is e.g. the "lock screen issue". We have 5 issues of the likely the same or very similar issue now, 4 of them are still open, see https://github.com/micheleg/dash-to-dock/issues/829#issuecomment-438458966.

This is just not really productive and it could help very much to "tidy up" here.

**Comment by micheleg** [comment]
Hi,

yes been busy and haven't had much time to take care of this . That issue is a mess because I keep closing them and people keep reopening as it is just a synthon of any possible problems.

Thank for pointing out the duplicates. Will try to tidy up a bit.

**Comment by rugk** [comment]
> people keep reopening

When you close an issue as a maintainer, the original reporter actually cannot re-open it. They could only create a new issue…

But that's why I've pointed out the duplicates. When they are all closed with "Duplicate of #…" to point to a single issue, people will hopefully get there and keep it in the one issue. To have a single topic (issue) scattered in multiple issues is not really helpful…
