### ISSUE TITLE
Official extensions badge

### ISSUE THREAD

**Issue by andyholmes** [micheleg/dash-to-dock#842]
Hi, about a week ago I asked for "Get it on..." badge for extensions like Google Play has, so GNOME had their marketing designer Caroline Henriksen make an official badge for us. They asked if I'd contact a few extension developers to get the word out.

[<img src="https://raw.githubusercontent.com/andyholmes/gnome-shell-extensions-badge/master/get-it-on-ego.svg?sanitize=true" height="100">](https://extensions.gnome.org/extension/307/dash-to-dock)

There is a PNG and SVG available that you can host yourself, possibly link from the [GitLab issue](https://gitlab.gnome.org/Teams/Engagement/marketing-design/issues/3), or I have a [repository on Github](https://github.com/andyholmes/gnome-shell-extensions-badge) you can link from (see the raw markdown from this comment for using SVG on Github).

Or just feel free to close the issue if you're not interested! Thanks for the great extension, who doesn't use this one? ;)

**Comment by micheleg** [comment]
Thanks,

I have added the badge to the README [f4870c2e41878bf64244] and will consider using the badge elsewhere too.
