### ISSUE TITLE
Previews shuffle on hover

### ISSUE THREAD

**Issue by dnut** [micheleg/dash-to-dock#858]
gnome-shell v3.30.2
Dash to Dock v64

### Description
When I have multiple windows open of the same type, and I click on the icon on the dock, the windows are arranged one way. As soon as I move my cursor to hover over any preview, they rearrange. This is infuriating because the window I'm trying to click on always disappears and I end up clicking the wrong one.

### Reproduce
1. Enable "Minimize or show previews" option for the Click action behavior.
2. Open two windows of the same type so they share the same dock icon.
3. Use the dock preview to switch focus back and forth between the windows a few times.

It may require switching focus a few times after opening the windows, but eventually you will see that every time, the previews start out one way and then swap once you hover over either.

### Cause
It appears the cause of this is that the preview order is sorted from most to least recently focused window, but this sort does not happen when the previews open. It only happens once the mouse is hovering over the previews.

### Solution
There are two possible solutions to this issue:
1. Sort the previews in the same manner, but do so before displaying them, such as when the dash icon is clicked. Do not wait until the mouse hovers over a preview to re-order them
   - Sorting like this is preferred if you have over three windows open, and you usually only want to access the most recent one.
2. Sort the previews according to when the windows were opened, not when the windows were last in focus. This way, the preview order never has to change.
   - This implementation may be simpler and less bug prone.
   - If the order is static, you can remember where the windows are, rather than having to always review all of the previews to figure out where the window you want is. This is ideal if you have:
     - only 2-3 windows of a certain type open at a time
     - many open, but you are not usually just looking for the most recent.

Originally I thought option 2 would be best, but I see that option 1 can be advantageous in some cases when you have many windows open. It leads me to consider making this configurable, or having different behavior depending on the number of windows (or some combination of dynamic behavior and configurability). Though these are increasingly complex solutions which is not ideal.

**Comment by micheleg** [comment]
I think this was fixed in 86f4404dffce054fbb3943b1faf6610306988eb8, where I implemented option 2. I honestly do not understand how option 1 would be any different than the old behaviour.

The fix is not released yet, you need to get current master an install from source.

**Comment by dnut** [comment]
> I honestly do not understand how option 1 would be any different than the old behaviour.

The behavior I see is that when I click on the icon and get a list of previews, they are in an outdated order. The preview to the far left isn't actually the most recently active window. It's the second most recently active window. But as soon as I simply move the mouse cursor to hover over any of the previews (without clicking), then the list of previews shuffles before my eyes, resorting them such that the preview on the far left is actually now the most recently active window.

With option 1, I was proposing that the previews should be correctly sorted immediately when you click on the icon, rather than waiting for you to hover over the previews and then re-sorting them.

**Comment by micheleg** [comment]
I've never seen such behaviour with previews rearranging when hovering the popup. Is it something reproducible?
