### ISSUE TITLE
Display workspace switcher arrow when scrolling workspaces

### ISSUE THREAD

**Issue by bulletmark** [micheleg/dash-to-dock#86]
This is a feature request. When you change workspaces using the keyboard (ctrl+alt+up/down) gnome-shell briefly displays a popup showing the position/context of the current workspace and the direction of workspace movement. It would be very handy if this same popup appeared when using mouse-scroll over the dash-to-dock. I find it difficult to remember which desktop I am on without that frame of reference.

**Comment by micheleg** [comment]
This was introduced time ago by 5d8b8290802362acfcc502fa25f9ffaa49d66fa7.

**Comment by fropeter** [comment]
You need Gnome Shell 3.12 or later to get this to work. Fedora 20 has 3.10, and won't be e.o.l. for about another 6 months (just in case someone tries and fails).
