### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by y2kbadbug** [micheleg/dash-to-dock#860]
In the README file, you specify GPLv2+ but the license file COPYING specifies specifically GPLv2.

Can you update one or the other to clarify which license is valid?

Thank you!

**Comment by micheleg** [comment]
I'm not sure how this can be improved.  I cannot include a license "version 2 or later" in the copying file, as t such legal document (the license) does not exist. 

I'm currently doing exactly the same thing as gnome-shell itself: https://gitlab.gnome.org/GNOME/gnome-shell. Any idea?

**Comment by y2kbadbug** [comment]
I see what you mean about the no LICENSE file available for that license.
Someone made a point to call out the COPYING file compared to the README.md file when I wrote a port for FreeBSD.  So I wanted to verify.  Thanks for the response!
