### ISSUE TITLE
Add option to disable active window indicator

### ISSUE THREAD

**Issue by joshuah345** [micheleg/dash-to-dock#864]
i would like to disable the dot above the icon that shows the window is active. in my opinion it runs the look of the dock a bit.

**Comment by clobrano** [comment]
It is not an active window indicator, it shows that there is one or more application instances opened

**Comment by joshuah345** [comment]
thats not what i mean, the dot above the icon, it appears when that window is active

**Comment by micheleg** [comment]
That dot is provided by yout theme I believe. It's not in my control.

**Comment by dvorapa** [comment]
This should be closed, right?
