### ISSUE TITLE
Dominant color doesn't work with Slack

### ISSUE THREAD

**Issue by lumnn** [micheleg/dash-to-dock#875]
Just as in title.
Slack installed as flatpak app. It happens since recent slack logo/icon update
Gnome: 3.30.2
Extension version: 64
btw i use arch

Default:
![image](https://user-images.githubusercontent.com/2505114/51599691-29971280-1ef8-11e9-8f9e-8d1b67dc3767.png)

When using dominant color indicator:
![image](https://user-images.githubusercontent.com/2505114/51599650-12582500-1ef8-11e9-8b98-f1699176b991.png)

**Comment by micheleg** [comment]
Thanks. It should be fixed in master now (b8ce54f9a1476).
