### ISSUE TITLE
Dock has extended beyond what is should

### ISSUE THREAD

**Issue by Rishabh-Lohia** [micheleg/dash-to-dock#879]
- 
![screenshot from 2019-01-31 12-31-49](https://user-images.githubusercontent.com/12861180/52037313-aa878700-2554-11e9-8c3f-f0d2b078ba67.png)

The dock has been behaving wrongly, as can be seen from the screenshot. 
I don't know if  it's related, but gnome-shell-extension-ubuntu-dock got updated yesterday to v0.9.1ubuntu18.04.3 . This system extension was disabled before and is still disabled.
Dash to dock version is 64. GNOME version is 3.28.2 . Ubuntu 18.04.1. Happening for both single and two monitors. 
Settings dump:
extend-height=false
force-straight-corner=false
click-action='minimize-or-overview'
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
max-alpha=0.80000000000000004
multi-monitor=true
apply-custom-theme=false
custom-theme-running-dots=true
unity-backlit-items=false
dock-position='BOTTOM'
custom-theme-shrink=true
preferred-monitor=0
height-fraction=0.90000000000000002
dash-max-icon-size=28
transparency-mode='ADAPTIVE'

No errors emitted in looking glass.

**Comment by jcdepth** [comment]
I was having the same issue. It's possible that you have Ubuntu dock settings somehow still creating an empty Ubuntu dock.

If you follow the steps here: https://github.com/micheleg/dash-to-dock/issues/851#issuecomment-445077469, it should fix your issue. It did for me!

**Comment by Rishabh-Lohia** [comment]
> I was having the same issue. It's possible that you have Ubuntu dock settings somehow still creating an empty Ubuntu dock.
> 
> If you follow the steps here: [#851 (comment)](https://github.com/micheleg/dash-to-dock/issues/851#issuecomment-445077469), it should fix your issue. It did for me!

Thanks. It works fine now.
