### ISSUE TITLE
support badge icons and progress bars in arch linux based distros

### ISSUE THREAD

**Issue by Austcool-Walker** [micheleg/dash-to-dock#884]
Is there a possibility of supporting the dash-to-dock badge icons and progress bars on arch linux?

**Comment by micheleg** [comment]
That depends on the underlying system to provide that information via DB. I believe Ubuntu is patching a number of applications for this purpose, so i guess (but I'm not sure) it is not possible (or at least it would be something the arch distribution should support, not us).

**Comment by Austcool-Walker** [comment]
badge icons are working on manjaro with the https://aur.archlinux.org/pkgbase/yaru/ desktop yaru-session but progress bars I'm not sure about.
