### ISSUE TITLE
v65 not available via the extensions site, no tag on github

### ISSUE THREAD

**Issue by drakkan** [micheleg/dash-to-dock#887]
v65 is available to download here:

https://micheleg.github.io/dash-to-dock/releases.html

but not here:

https://extensions.gnome.org/extension/307/dash-to-dock/

and no tag exists in github. 

Could you please add a tag? thanks

**Comment by micheleg** [comment]
Hi, the extenson is still under review on the extension site (https://extensions.gnome.org/review/9189). As for the tag, I indeed forgot to push the commit and tags to github but it is now here (https://github.com/micheleg/dash-to-dock/releases/tag/extensions.gnome.org-v65).

**Comment by drakkan** [comment]
I need the git tag to update Arch Linux package

https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock/

thanks for adding it
