### ISSUE TITLE
Ubuntu 18.10 error

### ISSUE THREAD

**Issue by duxingzhe** [micheleg/dash-to-dock#889]
details:

TypeError: ExtensionUtils.initTranslations is not a function

Stack trace:
  init@/home/luxuan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:856:5
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:68:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43

**Comment by micheleg** [comment]
Hi,

it seems like you are running current master, in which we dropped support for gnome shell < 3.31 (26feddbd568), thus this is an expected error in ubuntu 18.10.

There's a gnome-3.30 branch on which I will backports fixes and hopefully additional functionalities.
