### ISSUE TITLE
version 65 not released in master branch

### ISSUE THREAD

**Issue by azzar1** [micheleg/dash-to-dock#896]
https://github.com/micheleg/dash-to-dock/releases lists extensions.gnome.org-v65  as released but https://github.com/micheleg/dash-to-dock/blob/2c90645180d7a61d8e411263d972cd95261367e5/metadata.json#L12 still uses 64.

**Comment by micheleg** [comment]
Yes, I forgot to push the commit with the version bump to master and then started mergin additional PR, so it ended up only into the gnome-3.30 branch, where the tag is.

Versioning is a bit messy and confusing. My main distribution channel used to be (and it is still nowadays  believe) the extension website, thus I'm following their version scheme. This means there could be a version 67 in the future which is a backported version for  gnome 3.30, while version 66 is the most updated version!

So we can fix this time the version but we will alwasy have this kind of mismatch. I considered following a different internal version scheme but never found it really necessary. I would happiliy adopt one if that can help the release workflow.
