### ISSUE TITLE
GS 3.31.90 +v65 not displaying icons

### ISSUE THREAD

**Issue by dino99** [micheleg/dash-to-dock#897]
Ubuntu 19.04
Upgraded dashtodock v65 from the archive, and upgraded GS to 3.31.90 from 3.30.2, then restarted the session:
- upgade without error / warning
- but all icons are missed but the 'show applications' one, and is not clickable.

Downgraded to GS 3.30.2, and dashtodock v65 works as expected.
So still need some work to support GS 3.32.

**Comment by Haxk20** [comment]
Can confirm that this is issue here too. After upgrading to master it doesnt even load the extension.
SyntaxError: Bad method definition

**Comment by micheleg** [comment]
v65 is not  meant to support GS 3.32 yet. There are some breaking upstream changes. You need current master for that. A new release will be done soon.
