### ISSUE TITLE
Allow scrollable icons when too many are present on dash

### ISSUE THREAD

**Issue by padraic7a** [micheleg/dash-to-dock#90]
At the moment as the number of icons increases the sixe decreases. I would rather they remain at the same size, or at a set minimum and that further icons are available by scrolling up or down.

[Great extension by the way, well done on the work!]

**Comment by micheleg** [comment]
This is being developed in the scrollview branch (3.14 for the moment), which now allows to set a minimum icon size as well, after which the dash becomes scrollable. Not finalized yet, there are still things to fix.

**Comment by micheleg** [comment]
This has been merged into master now (450741fa1038c210b09f180ad2ba08b06e1784fa..a898d55ca07a0c59fe3ee5dc8f1c75644a897f20), and in the gnome-3.14 branch too.
