### ISSUE TITLE
Gnome Shell 3.31.92 overview mode dock is black

### ISSUE THREAD

**Issue by yuiiio** [micheleg/dash-to-dock#904]
![screenshot from 2019-03-07 16-48-04](https://user-images.githubusercontent.com/36093713/53940433-09629200-40f9-11e9-82a9-bb1029a112d3.png)

**Comment by clobrano** [comment]
I was just about to open the same, thanks @yuiiio

**Comment by PavelSmokorovskiy** [comment]
Please give somebody the fix for dock transparency

**Comment by clobrano** [comment]
Gnome shell translucency feature used transparency as default mode, adding then a special class `.solid` to handle opaque mode.
Now that this feature has been removed the default mode have alpha value 0 and the `.solid` class has been removed. I believe this might affect how dash-to-dock handle transparency.
I'll try to look into that

**Comment by clobrano** [comment]
Short update, the dock works properly if "customize opacity" is dynamic

**Comment by PavelSmokorovskiy** [comment]
How I can change "customize opacity" to dynamic?

**Comment by clobrano** [comment]
gnome-tweaks -> extensions -> dash-to-dock options -> appearance tab

**Comment by Stele77** [comment]
I dont know if this is related, but on 3.31.92 i can not install it.
Just switched from Antergos+KDE to Fedora Rawhide GNOME said shell version. When trying to install it does not work and show the red "error" button.
I am sorry, i am still new to Linux. Is this issue realted to mine or should i open a seperate issue?
Thanks

**Comment by micheleg** [comment]
Is this still a bug on my side?

**Comment by clobrano** [comment]
As far as I know, ubuntu customization used to override transparency-mode using ADAPTIVE value, which is not available anymore. However, from my tests, using DYNAMIC instead in the override file, I was not able to set this value anyway.
I was able to make it work only using gsettings command. Does this make sense to you?

**Comment by micheleg** [comment]
kind of make sense given adaptive does not exist anymore in master. However, the ubuntu branch did not pick that change yet (and probably wont for ths release cycle), although that seemed their plan https://github.com/micheleg/dash-to-dock/pull/890#issuecomment-466781592.

 However I would expect you can fix the problem by setting the opacity to dynamic or static in the UI settings too?

**Comment by clobrano** [comment]
> However, the ubuntu branch did not pick that change yet

Interesting, I do remember an error message similar to "wrong mode" or something.
Correct, if the UI settings are available the one can use it to fix it

**Comment by micheleg** [comment]
There's a bug in the settings UI, so the dynamic mode match to an unexistent enum entry (that's where that "wrong mode" is coming from)

**Comment by clobrano** [comment]
Great!
