### ISSUE TITLE
Toggle On/Off Extensions Page

### ISSUE THREAD

**Issue by lamofgod** [micheleg/dash-to-dock#913]
I'm actually not sure if this is a bug, but the directions on the Downloads page say that there should be a switch for turning the extension on.
![dash-to-dock-bug](https://user-images.githubusercontent.com/8324776/54506643-b3f96280-48fa-11e9-874a-1e7f17b774e8.png)

**Comment by dvorapa** [comment]
Read the blue box. You'll need to install the browser extension and small additional package first. Then you'll see the switch.

I would close this as invalid.
