### ISSUE TITLE
Dock is missing after antergos update

### ISSUE THREAD

**Issue by Bauja** [micheleg/dash-to-dock#917]
I'm relatively new to gnome (antergos in this case) or to linux in general. I'm not quite sure how to help but my dock disappeared after the  last arch linux update. The gnome website shows an error icon and the mouse-over description says 'undefined'.

![image](https://user-images.githubusercontent.com/48857384/54865716-2c807900-4d6a-11e9-9117-89b0397fc894.png)

EDIT:
```
[jaba@jaba-x260 ~]$ uname -r
5.0.3-arch1-1-ARCH
```

**Comment by G710** [comment]
Hi,
I had the same problem. When running ```pacman -Suy``` you probably got this error message or something similar.
```
warning: dash-to-dock: local (1:64-4) is newer than core (66)
```
This prevents the system from updating your package.
Solution: Try running ```pacman -Suu```. This will "downgrade" your package and after a reboot you should have the newest version running and everything should work again. I suspect the version numbers are confusing pacman.

**Comment by Bauja** [comment]
Thanks a lot. Got fixed after updating my system.
