### ISSUE TITLE
Dash to Dock isn't completely transparent (opacity is set correctly)

### ISSUE THREAD

**Issue by josh1dev** [micheleg/dash-to-dock#918]
Opacity and everything is all configured correctly. It happened suddenly, tried several fixes, even disabled the plugin and reconfigured, no luck yet though. Borders are still visible, somehow. 

I don't have this problem on Fedora btw. 

### Versions: 

- Dash To Dock 3.32
- GNOME 3.30.1
- Ubuntu 18.10  

Screenshot: `https://imgur.com/s0g1QUt`

Thanks, let me know if I can help out!

**Comment by micheleg** [comment]
Which theme are you using? Can you check with the default theme? Looks like some sort of box-shadow is applied?

**Comment by Josh1Dev** [comment]
I use Flat Remix. I tried with default theme and other themes, but it's still there unfortunately.

**Comment by Josh1Dev** [comment]
**Settings Log**

org.gnome.shell.extensions.dash-to-dock transparency-mode 'FIXED'
org.gnome.shell.extensions.dash-to-dock shortcut-text '<Super>q'
org.gnome.shell.extensions.dash-to-dock apply-custom-theme false
org.gnome.shell.extensions.dash-to-dock show-favorites true
org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
org.gnome.shell.extensions.dash-to-dock app-hotkey-9 ['<Super>9']
org.gnome.shell.extensions.dash-to-dock custom-background-color false
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-1 ['<Shift><Super>1']
org.gnome.shell.extensions.dash-to-dock multi-monitor true
org.gnome.shell.extensions.dash-to-dock height-fraction 1.0
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-1 ['<Ctrl><Super>1']
org.gnome.shell.extensions.dash-to-dock isolate-workspaces false
org.gnome.shell.extensions.dash-to-dock shift-click-action 'minimize'
org.gnome.shell.extensions.dash-to-dock shortcut-timeout 2.0
org.gnome.shell.extensions.dash-to-dock show-delay 0.25
org.gnome.shell.extensions.dash-to-dock custom-theme-shrink true
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-2 ['<Shift><Super>2']
org.gnome.shell.extensions.dash-to-dock show-windows-preview true
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-2 ['<Ctrl><Super>2']
org.gnome.shell.extensions.dash-to-dock autohide-in-fullscreen false
org.gnome.shell.extensions.dash-to-dock icon-size-fixed false
org.gnome.shell.extensions.dash-to-dock scroll-action 'do-nothing'
org.gnome.shell.extensions.dash-to-dock shift-middle-click-action 'launch'
org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-border-color '#ffffff'
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-3 ['<Shift><Super>3']
org.gnome.shell.extensions.dash-to-dock pressure-threshold 100.0
org.gnome.shell.extensions.dash-to-dock hide-delay 0.20000000000000001
org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-3 ['<Ctrl><Super>3']
org.gnome.shell.extensions.dash-to-dock show-show-apps-button true
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-4 ['<Shift><Super>4']
org.gnome.shell.extensions.dash-to-dock show-running true
org.gnome.shell.extensions.dash-to-dock force-straight-corner false
org.gnome.shell.extensions.dash-to-dock app-hotkey-1 ['<Super>1']
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-4 ['<Ctrl><Super>4']
org.gnome.shell.extensions.dash-to-dock running-indicator-style 'DOTS'
org.gnome.shell.extensions.dash-to-dock hotkeys-overlay true
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-5 ['<Shift><Super>5']
org.gnome.shell.extensions.dash-to-dock animation-time 0.20000000000000001
org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-color '#ffffff'
org.gnome.shell.extensions.dash-to-dock running-indicator-dominant-color true
org.gnome.shell.extensions.dash-to-dock hotkeys-show-dock true
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-5 ['<Ctrl><Super>5']
org.gnome.shell.extensions.dash-to-dock unity-backlit-items false
org.gnome.shell.extensions.dash-to-dock animate-show-apps true
org.gnome.shell.extensions.dash-to-dock app-hotkey-2 ['<Super>2']
org.gnome.shell.extensions.dash-to-dock custom-theme-running-dots-border-width 0
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-6 ['<Shift><Super>6']
org.gnome.shell.extensions.dash-to-dock shortcut ['<Super>q']
org.gnome.shell.extensions.dash-to-dock customize-alphas false
org.gnome.shell.extensions.dash-to-dock app-hotkey-3 ['<Super>3']
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-6 ['<Ctrl><Super>6']
org.gnome.shell.extensions.dash-to-dock autohide true
org.gnome.shell.extensions.dash-to-dock minimize-shift true
org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-7 ['<Shift><Super>7']
org.gnome.shell.extensions.dash-to-dock app-hotkey-10 ['<Super>0']
org.gnome.shell.extensions.dash-to-dock custom-theme-customize-running-dots false
org.gnome.shell.extensions.dash-to-dock app-hotkey-4 ['<Super>4']
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-7 ['<Ctrl><Super>7']
org.gnome.shell.extensions.dash-to-dock background-opacity 0.0
org.gnome.shell.extensions.dash-to-dock middle-click-action 'launch'
org.gnome.shell.extensions.dash-to-dock extend-height false
org.gnome.shell.extensions.dash-to-dock dock-fixed false
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-8 ['<Shift><Super>8']
org.gnome.shell.extensions.dash-to-dock max-alpha 0.80000000000000004
org.gnome.shell.extensions.dash-to-dock app-hotkey-5 ['<Super>5']
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-8 ['<Ctrl><Super>8']
org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 40
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-9 ['<Shift><Super>9']
org.gnome.shell.extensions.dash-to-dock intellihide true
org.gnome.shell.extensions.dash-to-dock require-pressure-to-show true
org.gnome.shell.extensions.dash-to-dock app-hotkey-6 ['<Super>6']
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-9 ['<Ctrl><Super>9']
org.gnome.shell.extensions.dash-to-dock bolt-support true
org.gnome.shell.extensions.dash-to-dock scroll-switch-workspace true
org.gnome.shell.extensions.dash-to-dock preferred-monitor -1
org.gnome.shell.extensions.dash-to-dock min-alpha 0.20000000000000001
org.gnome.shell.extensions.dash-to-dock app-hotkey-7 ['<Super>7']
org.gnome.shell.extensions.dash-to-dock app-ctrl-hotkey-10 ['<Ctrl><Super>0']
org.gnome.shell.extensions.dash-to-dock activate-single-window true
org.gnome.shell.extensions.dash-to-dock intellihide-mode 'FOCUS_APPLICATION_WINDOWS'
org.gnome.shell.extensions.dash-to-dock isolate-monitors false
org.gnome.shell.extensions.dash-to-dock background-color '#ffffff'
org.gnome.shell.extensions.dash-to-dock app-hotkey-8 ['<Super>8']
org.gnome.shell.extensions.dash-to-dock app-shift-hotkey-10 ['<Shift><Super>0']
org.gnome.shell.extensions.dash-to-dock hot-keys true

**Comment by micheleg** [comment]
I cannot reproduce ths with the default gnome theme. I can make the dock fully transparent.

**Comment by vhladiienko** [comment]
Why was this issue closed? Did you find out what was the culprit exactly, @J0XX0?
I can reproduce this behaviour on Pop!_OS 19.10 and Gnome 3.34.1 with Adwaita, Ant Dracula (slim) and default Pop theme.

Screenshot - [https://imgur.com/OZzUtme](https://imgur.com/OZzUtme)

**Comment by J0XX0** [comment]
> Why was this issue closed? Did you find out what was the culprit exactly, @J0XX0?
> I can reproduce this behaviour on Pop!_OS 19.10 and Gnome 3.34.1 with Adwaita, Ant Dracula (slim) and default Pop theme.
> 
> Screenshot - https://imgur.com/OZzUtme

I figured I let it rest because someone couldn't reproduce; I've switched to KDE anyway. I couldn't fix it, and, quite frankly, am better of on KDE anyway. 

Good luck @vhladiienko

**Comment by noahdigesu** [comment]
## Issue solved
The 1px border is due to the option `shrink the dash` under the `appearance` tab.


### Easy fix
Don't shrink the dash
### More complex (but still super easy) fix
Edit the **4th line** in `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css` from `border:1px;` to `border:0px`.
That way you **can both shrink the dash and remove the border**
(It was really triggering me too so I searched a bit ahah)

Hope this helped @LoopsGod @vhladiienko ^^
