### ISSUE TITLE
Missing gschemas.compiled

### ISSUE THREAD

**Issue by fizermire** [micheleg/dash-to-dock#922]
After the latest update, the sidebar is missing. The system reminds me there 's something went wrong in dash to dock and suggest me to report this issue. 

The original message is: "the settings for this extension can't be displayed."
And the detail is:
The settings of extension dash-to-dock@micxgx.gmail.com had an error:
```
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/gschemas.compiled”: open() failed: No such file or directory
```

Stack trace:
```
getSettings@resource:///org/gnome/shell/misc/extensionUtils.js:114:24
DashToDock_Settings@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:87:26
buildPrefsWidget@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/prefs.js:857:20
_selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
_onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
@<main>:1:43
```
In "/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/" directory, there is only one file called "10_dash-to-dock.gschema.override".

### Version:
Gnome V3.32.0 
Manjaro 18.0.4 Linux 64-bit
Dash to dock 66.1 from archlinuxcn explicitly installed

**Comment by micheleg** [comment]
Ig you are installing th extension via a distribution package you probably want to report the bug to the package mantainer. You can probably remove the distribution package and manually install the extension as a workaround in the meantime.
