### ISSUE TITLE
Automaticly switch windows while DnD-ing a file

### ISSUE THREAD

**Issue by gigglylo** [micheleg/dash-to-dock#948]
Hi, i have a feature request that hopefully makes the extension more useful.

Well it's easier explain it with a real case. So here it is. I'm currently working with gimp, and there's a image file displayed on a file manager i want to edit. The way im doing it now is to left click on the file, click open with, and i choose gimp. It would be simpler if i can just drag that file on the gimp icon on dock and gimp windows automatically open and i drop my file there to open it

**Comment by stokito** [comment]
I just had a the problem and wondered why this is not implemented

**Comment by the-mentor** [comment]
+1

**Comment by ghabit** [comment]
Me too please.

**Comment by vanvugt** [comment]
Duplicate of #49
