### ISSUE TITLE
Icon overlapping and missing running processes

### ISSUE THREAD

**Issue by Gryzor** [micheleg/dash-to-dock#952]
### Context
* Pop!_OS 19.04 "up-2-date" 
* Dash-to-dock v66

### Behavior
More often than not, the dock appears to overlap running apps/processes, as seen here:

<details>
<summary>Postman + Settings</summary>

![Screenshot from 2019-05-29 13-17-11](https://user-images.githubusercontent.com/15253/58553132-66f80d80-8214-11e9-92cb-a3522d6925c3.png)

</details>

In some other cases, running apps don't show at all, but they do show when you "control-tab"; I haven't found which windows (if there's a pattern) cause this; I've seen it happen with Postman ("native"), Android Studio, Android Studio Emulator, and Gnome Settings. These windows are then ones I remember got overlapped or disappeared, but I cannot say for sure these are exclusive. 

<details>
<summary>Missing postman</summary>

![IMG_1569](https://user-images.githubusercontent.com/15253/58553308-e84fa000-8214-11e9-8053-4d25b36b1028.JPG)

</details>

### Workaround
In all cases, accessing "dash-to-dock" settings and changing the position (from left to bottom, and back), fixes the issue, but it tends to happen relatively fast again. 

Here's my settings:

<details>
<summary>All settings</summary>

![Screenshot from 2019-05-29 13-26-25](https://user-images.githubusercontent.com/15253/58553573-8479a700-8215-11e9-9bda-3707ece7fe53.png)
![Screenshot from 2019-05-29 13-26-34](https://user-images.githubusercontent.com/15253/58553576-86dc0100-8215-11e9-8887-17d62866035b.png)
![Screenshot from 2019-05-29 13-26-41](https://user-images.githubusercontent.com/15253/58553578-880d2e00-8215-11e9-9199-34edfd8e974e.png)
![Screenshot from 2019-05-29 13-26-47](https://user-images.githubusercontent.com/15253/58553581-8a6f8800-8215-11e9-8bf0-c35d9c85c93f.png)
![Screenshot from 2019-05-29 13-26-53](https://user-images.githubusercontent.com/15253/58553589-8d6a7880-8215-11e9-8775-ba0d0e487aba.png)

</details>

**Comment by vanvugt** [comment]
Ubuntu 19.04 is no longer supported and v66 is no longer used in any supported releases. So closing.
