### ISSUE TITLE
Does Dash to Dock support preview on hover?  

### ISSUE THREAD

**Issue by dln949** [micheleg/dash-to-dock#956]
When I look at the settings for Dash to Dock, it is not clear to me if preview on hover - that is, without having to click on the icon - should work.  

Does it?  

If it does, what settings make that happen?  I cannot see how to do that.  

Thanks.

**Comment by laichiaheng** [comment]
You need to open two windows of the same app.

**Comment by dln949** [comment]
> You need to open two windows of the same app.
> I thought it worked that way, too.

Oh.  Ok.  Thanks.  I did not realize that.  

However......  I see that I still need to click on he icon in order to see the previews, instead of simply hovering over the icon.  Am I still missing a setting, or is that the way it is meant to work?

**Comment by laichiaheng** [comment]
Yes, it is.
I hope I can see the preview by hovering over the icon, too.

**Comment by dln949** [comment]
I see.  

It is currently a very nice extension.  

I wish I could see a preview by merely hovering over the icon.  Also, I wish I could see the preview even if only one window is currently open.
