### ISSUE TITLE
Does not work in GNOME 3.33

### ISSUE THREAD

**Issue by Haxk20** [micheleg/dash-to-dock#966]
As expected with every new GNOME version extensions break. And DTD is no exception this time.
I know there was a way to debug GNOME extensions but i dont remember now know.
So please tell me how to debug it and i will post logs tomorrow.

**Comment by rmader** [comment]
Keep in mind that most likely more breaking changes will land in in 3.33 (e.g. https://gitlab.gnome.org/GNOME/mutter/merge_requests/409). So this will be a catch-up game until the feature freeze.

**Comment by vatula** [comment]
With today's update of rawhide dash to dock was not loaded
![image](https://user-images.githubusercontent.com/450851/60262442-840e2200-9921-11e9-8d9f-a1ecc1dc032a.png)

![image](https://user-images.githubusercontent.com/450851/60262508-a607a480-9921-11e9-8b6c-8813c3298868.png)

**Comment by Haxk20** [comment]
Well GNOME beta was released few days ago so i guess we can start making it 3.34 compatible ?

**Comment by octoquad** [comment]
> Well GNOME beta was released few days ago so i guess we can start making it 3.34 compatible ?

There is an open PR to get this working in 3.34. See #975. Works ok for me:

```shell
$ gnome-shell --version
GNOME Shell 3.33.91
```

**Comment by Haxk20** [comment]
Will check

**Comment by Haxk20** [comment]
Ohhhh how glad im to see dash-to-dock back again. So yeah works for me too.

**Comment by octoquad** [comment]
@Haxk20 So, it worked great for a while, but I started getting bad gnome-shell crashes. I hope it's working better for you :)

**Comment by Haxk20** [comment]
@octoquad  ohhhh so DTD does those crashes ? ahhh yes i sadly have them too.

**Comment by octoquad** [comment]
@Haxk20 A workaround is to disable autohide. See https://github.com/micheleg/dash-to-dock/issues/978#issuecomment-525823128
