### ISSUE TITLE
Does not work on Gnome 3.33.91

### ISSUE THREAD

**Issue by silviobierman** [micheleg/dash-to-dock#978]
The Gnome version on the Ubuntu 19.10 development version was bumped to 3.33.91 and now Dash-to-Dock no longer works. Working with plain vanilla Gnome now :-((

**Comment by shemgp** [comment]
Fix is on the way via: #975 
Tested and it works. Had to reset settings of intelligent auto-hide to make it work again.

**Comment by octoquad** [comment]
> Fix is on the way via: #975
> Tested and it works. Had to reset settings of intelligent auto-hide to make it work again.

Thanks, for figuring this out. I had a hard gnome-shell crash after compiling from the 3.34 branch. Just curious, did you reset via dconf or the DTD settings?

**Comment by shemgp** [comment]
It does crash with auto-hide and with scroll action even if I reset the
dconf settings.

**Comment by silviobierman** [comment]
Sorry for opening a new issue when there already was one on the same subject. I missed that.

Good to hear a fix is coming. Is that in the current master? I would be happy to test.

**Comment by octoquad** [comment]
@silviobierman It's still being worked on [here](https://github.com/3v1n0/dash-to-dock/tree/gnome-3-34), so it hasn't landed in master yet.

**Comment by silviobierman** [comment]
Fair enough. I have installed that and at first sight everything looks fine. If I encounter any oddities I will report them. But I do not use auto-hide so if the issues lie there then I may be of little use.
