### ISSUE TITLE
Super+[0-9] shortcuts cannot be disabled!

### ISSUE THREAD

**Issue by eduncan911** [micheleg/dash-to-dock#985]
OS: Pop_OS! 19.04 (aka, Ubuntu 19.04 LTS - but with custom keyboard bindings and skin)
Kernel: 5.0.0-25-generic #826 
DE: Gnome 3.32.2

Similar to issue #974 , I can't disable the shortcuts (I don't want them).  The option is disabled in the control panel as I use these keys for other things.  They seem to be disabled on first boot; but, after using the keys once or twice, Dash to Dock launches apps.

My binding usage still works for my other apps; however, it's extremely annoying when a whole nother app launches right in front of me.

**Comment by dvorapa** [comment]
Have you tried Dash-to-dock preferences? (or which control panel are you referring to)

**Comment by eduncan911** [comment]
Closing as the original issue was a system config.

However, it shouldn't be part of this extension any longer as it could cause more confusion in the future.

**Comment by dvorapa** [comment]
> So, I guess this feature can be removed from DashToDock since it is now part of the system?

Dash to dock is not only a Ubuntu extension

**Comment by eduncan911** [comment]
> > So, I guess this feature can be removed from DashToDock since it is now part of the system?
> 
> Dash to dock is not only a Ubuntu extension

Very good point!

Humm.  Would an OS check for Ubuntu >= 18.04 work here?  if it's 18.04 or higher, disable the hotkey feature and direct people to their system settings?

**Comment by dvorapa** [comment]
Seems reasonable to me, but from my point of view (not a dev of any part discussed), perhaps this is something Ubuntu devs should handle instead?

**Comment by eduncan911** [comment]
Well, my point for Ubuntu 18.04+ is that if they are doing Super+Num keys, and this extension is doing Super+Num keys...

What if they disable the Ubuntu keys, but Super+Num still are bound? It would confuse users, until they realize it's this extension that was double binding.

Or, people like me who thought I "did" disable it, but didn't because yet there was a 2nd level of bindings.

**Comment by dvorapa** [comment]
This is similar issue like emoji support in Gnome vs. libinput. Both implemented the same thing, but both in a different way, so the final result was a mess :D

This seems like UbuntuDock and Dash-to-dock still fighting on Ubuntu, instead one of these disabled properly (also some other similar issues suggest this, like the issue of showing both D2D and UD at once - duplicated panel)

**Comment by eduncan911** [comment]
Would you like me to reopen? :)
