### ISSUE TITLE
Appearance animation

### ISSUE THREAD

**Issue by Amathadius** [micheleg/dash-to-dock#989]
If the mouse cursor moves before the appearance or disappearance animation is finished gnome crashes and, of course, I lost everything.

Archlinux
Kernel : 5.3.0-arch1-1-ARCH
GNOME Shell 3.34.0
Ubuntu dock branch 66-2

**Comment by drakkan** [comment]
I confirm this bug. 66-2 is the Arch Linux package's version, the installed version is `ubuntu-dock-66ubuntu19.10.2`

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gnome-shell-extension-dash-to-dock#n17

**Comment by Jhackler** [comment]
same issue

**Comment by drakkan** [comment]
This issue seems fixed by this commit:

https://github.com/micheleg/dash-to-dock/commit/881de7e59160cdd7bf227504d59e3145957bc817

For Arch users I updated the PKGBUILD to the current master
