### ISSUE TITLE
Stay active in a virtual machine

### ISSUE THREAD

**Issue by dmarrazzo** [micheleg/dash-to-dock#99]
I loved this extension because the dash was accessible even in the VM (in full screen mode): it's very useful to quickly switch between VM and host apps.
Some update removed this capability, is it possible to get it back?

Thank you

**Comment by dmarrazzo** [comment]
After some time, I cannot give this up as lost! Any idea/news? Thank you

**Comment by micheleg** [comment]
Hi @dmarrazzo, thanks for pointing out this old question. I honestly don't remember why I didn't merge the proposed workaround.  I can't test it right now. I do think however it's not totally obvious  that it is a good idea. In principle one might want to be able to use that edge from inside the vm too. I'll check when I'm back to my computer, I should at least be able to provide a simple temporary patch for you, unless something is really blocked at the gnome-shell level. I've seen your email in the gnome-shell mailing-list too

**Comment by micheleg** [comment]
@dmarrazzo, a couple of questions: which shell version are you running? What are you looking for: being able to show the dock or just the ability to scroll desktop?

**Comment by dmarrazzo** [comment]
Hello Michele, thank you.
I'm using Gnome 3.16 but soon I will migrate on 3.18.
I'd like to get both. Consider that I'm even a Mac user, where the logic is exactly the same and especially for vmware is really useful because it make you switch seamlessly between the host OS and the guest VM. I understand even that in some other cases it could be confusing, because you could have an overlap where the same action produce two effects! So if you want to reach the Nirvana: you should implement it on optional base or even better distinguishing the application that is in fullscreen (checking window title against a white list).

**Comment by micheleg** [comment]
Check the branch enable_in_fullscreen_316. As a proof of principle this should do the job of allowing the dock to be shown by autohide  even with fullscreen apps. Just a quick and dirty hack, didn't take care of the case intellihide is disabled.

**Comment by dmarrazzo** [comment]
Fantastic! It works like a charm! Please merge to master!

**Comment by zapashcanon** [comment]
@micheleg, seems like it's been merged in master, right ? So, I think this can be closed. :)

**Comment by micheleg** [comment]
Yes, was merged in master [916185190, 63c6f9f170b].
