### ISSUE TITLE
Dash to Dock autohide doesn't work as usual in Gnome3.34

### ISSUE THREAD

**Issue by laichiaheng** [micheleg/dash-to-dock#990]
I doesn't appear when I move my cursor to the left of my screen.

**Comment by laichiaheng** [comment]
And it works now again, why??

**Comment by laichiaheng** [comment]
And it doesn't work again after my Gnome crashes.

**Comment by x80486** [comment]
There was a Pull Request to make it work under GNOME `3.34`; there should be a release any time soon...hopefully.

**Comment by micheleg** [comment]
I believe this was before support was introduced.
