### ISSUE TITLE
Shortcut for display the dock don't work

### ISSUE THREAD

**Issue by Nooguat** [micheleg/dash-to-dock#991]
On Arch Linux 5.3.0 Gnome 3.34, got this error message in logs when trying to use the shortcut :
`` JS ERROR: TypeError: dock._settings is undefined
                                            _showOverlay@/home/nooguat/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:1429:1 ``

**Comment by kebeda** [comment]
The keyboard shortcut doesn't work on Fedora 31, Gnome 3.34.1, Wayland. I changed it to "<alt>d".
Used to work on Fedora 30/Gnome 3.32/Wayland. Don't know where I would go to see error messages, but as far as I can tell it doesn't even get the keypress.

**Comment by hackel** [comment]
Same on Ubuntu 19.10.  The PR fixed it for me.

**Comment by kebeda** [comment]
I applied franglais125's PR Fix_showOverlay #1019, and it did NOT fix it for me on Fedora 31.

**Comment by clownchrys** [comment]
On Ubuntu18.04, it occurs when system turned on or rebooted. To use hotkeys, i make the dash-to-dock's hotkey option(i dont know what i can call it, cuz i dont use eng version linux) unavailable and available again. It can hotkeys work properly.

**Comment by micheleg** [comment]
The fix is now in master a71861a05f02660877f6d9a81b25cc06faecdb00.

**Comment by clownchrys** [comment]
I am really sorry to say that, but is there any solutions for dash-to-dock v.65?
fix in master a71861a is not working in v.65 version....
