### ISSUE TITLE
Alt+F2+r make gnome crash

### ISSUE THREAD

**Issue by Amathadius** [micheleg/dash-to-dock#992]
alt + F2 and r make gnome crash. Try to open firefox, for instance, which closed from crash and gnome crash again (and corrupt firefox config).

You need to disable and enable the extension until next alt+f2 r.

Archlinux
Kernel : 5.3.1-arch1-1-ARCH
GNOME Shell 3.34.0
Ubuntu dock branch 66+141+g908a050-1

**Comment by akiirui** [comment]
`Alt + F2 + r` crash not this extensions make.
Gnome upstream (or Arch Linux package patches) issues

**Comment by mason1920** [comment]
@akiirui he's saying it only crashes with this extension enabled. It seems like the issue would be originating from this extension.

**Comment by akiirui** [comment]
> @akiirui he's saying it only crashes with this extension enabled. It seems like the issue would be originating from this extension.

I'm Arch Linux user too.
I'm sure this is gnome-shell 3.34 with community patches issue. And it was fixed in new Arch Linux package.

**Comment by Amathadius** [comment]
Dash to dock forgot random settings after Alt-F2 + r
Icons size
Intelligent behavior

I can't make it appears  over maximized windows.

**Comment by Amathadius** [comment]
Gnome doesn't crash anymore.
