### ISSUE TITLE
Icon tooltips remain on screen

### ISSUE THREAD

**Issue by forairan** [micheleg/dash-to-dock#995]
Faint/visible icon tooltips sometimes remain on the screen, becoming more visible over time until they are fully opaque. Hovering over each icon again resets the tooltip, but they slowly become more visible again over time.

Using the latest Gnome Shell 3.34 version from the Arch AUR ([908a050](https://github.com/micheleg/dash-to-dock/commit/908a05022a1ce2565d56af4c762fe95c5fb6b39c)).
![](https://i.imgur.com/v61w1JS.png)

**Comment by proalexa** [comment]
+1

**Comment by rudrab** [comment]
I have seen this, but after applying #975 its no longer the case.
I am in Wayland.

**Comment by Inglebard** [comment]
Hi,
I am on Archlinux with Xorg.

For me, this issue disappear after upgrading gnome shell to version 3.34.0+152+g0fdbde910-1 and upgrade dash-to-dock from git.

**Comment by kaipee** [comment]
+1

I'm also experiencing the same issue.

![image](https://user-images.githubusercontent.com/5189160/65632891-aa9c3180-dfd2-11e9-9c5d-3e19cf11ec6c.png)

**Comment by youtous** [comment]
+1, same issue

**Comment by micheleg** [comment]
Can you confirm if this is still an issue?

**Comment by youtous** [comment]
> Can you confirm if this is still an issue?

It's solved on my side. Thank you :)
