### ISSUE TITLE
Default theme window indicators are shown even though a custom theme is used

### ISSUE THREAD

**Issue by Mrtenz** [micheleg/dash-to-dock#999]
I'm using [matcha](https://github.com/vinceliuice/matcha) as `gnome-shell` theme, but even though `Use built-in theme` is disabled on the `dash-to-dock` settings, the default window indicators are shown.

![](https://i.morten.dev/8604b965a27f4d49.png)

With the custom theme disabled:

![](https://i.morten.dev/6a03b03de9487881.png)

My appearance settings:

![](https://i.morten.dev/83acbc2973879b24.png)

![](https://i.morten.dev/65e5b7e472caeea8.png)

I'm not sure if this is an issue with `dash-to-dock` or the custom theme...

**Comment by micheleg** [comment]
You should choose "Default" as the option for "Customize windows counter indicators".

**Comment by Mrtenz** [comment]
Sorry for the late reply. The point is that I want to use the custom indicators (dots), instead of the default _ indicators. This doesn't seem possible right now, because the default ones are shown regardless.
